<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-BR" xml:lang="pt-BR"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Marcos M. Raimundo — Instituto de Computação, UNICAMP">

<title>Aula 3: Topografia de Densidade e Grafos — Clustering Hierárquico e HDBSCAN – Marcos M. Raimundo</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../more.png" rel="icon" type="image/png">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-de6b2afc8591517e0c1f78da07193c80.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Marcos M. Raimundo</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Procurar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Alternar de navegação" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../teaching/index.html"> 
<span class="menu-text">Teaching</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../projects/index.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../publications/index.html"> 
<span class="menu-text">Publications</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../people/index.html"> 
<span class="menu-text">People</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../contact.html"> 
<span class="menu-text">Contact</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/marcosmrai"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://scholar.google.com.br/citations?user=ibe0jfQAAAAJ&amp;hl=pt-BR"> <i class="bi bi-mortarboard-fill" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Nesta página</h2>
   
  <ul>
  <li><a href="#abertura-o-que-cluster-deveria-significar" id="toc-abertura-o-que-cluster-deveria-significar" class="nav-link active" data-scroll-target="#abertura-o-que-cluster-deveria-significar"><span class="header-section-number">1</span> Abertura — O Que “Cluster” Deveria Significar</a>
  <ul class="collapse">
  <li><a href="#roteiro-desta-aula" id="toc-roteiro-desta-aula" class="nav-link" data-scroll-target="#roteiro-desta-aula"><span class="header-section-number">1.1</span> Roteiro desta aula</a></li>
  <li><a href="#pergunta" id="toc-pergunta" class="nav-link" data-scroll-target="#pergunta"><span class="header-section-number">1.2</span> Pergunta</a></li>
  </ul></li>
  <li><a href="#intuição-vales-e-montanhas-não-bolas" id="toc-intuição-vales-e-montanhas-não-bolas" class="nav-link" data-scroll-target="#intuição-vales-e-montanhas-não-bolas"><span class="header-section-number">2</span> Intuição — Vales e Montanhas, Não Bolas</a>
  <ul class="collapse">
  <li><a href="#pergunta-1" id="toc-pergunta-1" class="nav-link" data-scroll-target="#pergunta-1"><span class="header-section-number">2.1</span> Pergunta</a></li>
  </ul></li>
  <li><a href="#conjuntos-de-nível-de-densidade" id="toc-conjuntos-de-nível-de-densidade" class="nav-link" data-scroll-target="#conjuntos-de-nível-de-densidade"><span class="header-section-number">3</span> Conjuntos de Nível de Densidade</a>
  <ul class="collapse">
  <li><a href="#pergunta-2" id="toc-pergunta-2" class="nav-link" data-scroll-target="#pergunta-2"><span class="header-section-number">3.1</span> Pergunta</a></li>
  </ul></li>
  <li><a href="#da-densidade-ao-grafo-distância-de-alcançabilidade-mútua" id="toc-da-densidade-ao-grafo-distância-de-alcançabilidade-mútua" class="nav-link" data-scroll-target="#da-densidade-ao-grafo-distância-de-alcançabilidade-mútua"><span class="header-section-number">4</span> Da Densidade ao Grafo: Distância de Alcançabilidade Mútua</a>
  <ul class="collapse">
  <li><a href="#pergunta-3" id="toc-pergunta-3" class="nav-link" data-scroll-target="#pergunta-3"><span class="header-section-number">4.1</span> Pergunta</a></li>
  </ul></li>
  <li><a href="#a-árvore-geradora-mínima-e-o-clustering-hierárquico-clássico" id="toc-a-árvore-geradora-mínima-e-o-clustering-hierárquico-clássico" class="nav-link" data-scroll-target="#a-árvore-geradora-mínima-e-o-clustering-hierárquico-clássico"><span class="header-section-number">5</span> A Árvore Geradora Mínima e o Clustering Hierárquico Clássico</a>
  <ul class="collapse">
  <li><a href="#pergunta-4" id="toc-pergunta-4" class="nav-link" data-scroll-target="#pergunta-4"><span class="header-section-number">5.1</span> Pergunta</a></li>
  </ul></li>
  <li><a href="#condensando-a-árvore-e-medindo-persistência" id="toc-condensando-a-árvore-e-medindo-persistência" class="nav-link" data-scroll-target="#condensando-a-árvore-e-medindo-persistência"><span class="header-section-number">6</span> Condensando a Árvore e Medindo Persistência</a>
  <ul class="collapse">
  <li><a href="#aplicando-ao-breast-cancer-wisconsin-sem-rótulos" id="toc-aplicando-ao-breast-cancer-wisconsin-sem-rótulos" class="nav-link" data-scroll-target="#aplicando-ao-breast-cancer-wisconsin-sem-rótulos"><span class="header-section-number">6.1</span> Aplicando ao Breast Cancer Wisconsin, Sem Rótulos</a></li>
  <li><a href="#pergunta-5" id="toc-pergunta-5" class="nav-link" data-scroll-target="#pergunta-5"><span class="header-section-number">6.2</span> Pergunta</a></li>
  </ul></li>
  <li><a href="#síntese-o-que-o-hdbscan-compra-e-o-que-ainda-custa" id="toc-síntese-o-que-o-hdbscan-compra-e-o-que-ainda-custa" class="nav-link" data-scroll-target="#síntese-o-que-o-hdbscan-compra-e-o-que-ainda-custa"><span class="header-section-number">7</span> Síntese: o Que o HDBSCAN Compra, e o Que Ainda Custa</a>
  <ul class="collapse">
  <li><a href="#pergunta-6" id="toc-pergunta-6" class="nav-link" data-scroll-target="#pergunta-6"><span class="header-section-number">7.1</span> Pergunta</a></li>
  </ul></li>
  <li><a href="#fechamento-e-ponte-para-a-aula-4" id="toc-fechamento-e-ponte-para-a-aula-4" class="nav-link" data-scroll-target="#fechamento-e-ponte-para-a-aula-4"><span class="header-section-number">8</span> Fechamento e Ponte para a Aula 4</a>
  <ul class="collapse">
  <li><a href="#pergunta-7" id="toc-pergunta-7" class="nav-link" data-scroll-target="#pergunta-7"><span class="header-section-number">8.1</span> Pergunta</a></li>
  </ul></li>
  <li><a href="#exercícios" id="toc-exercícios" class="nav-link" data-scroll-target="#exercícios"><span class="header-section-number">9</span> Exercícios</a>
  <ul class="collapse">
  <li><a href="#questões-discursivas" id="toc-questões-discursivas" class="nav-link" data-scroll-target="#questões-discursivas"><span class="header-section-number">9.1</span> Questões discursivas</a></li>
  <li><a href="#questões-de-verdadeirofalso" id="toc-questões-de-verdadeirofalso" class="nav-link" data-scroll-target="#questões-de-verdadeirofalso"><span class="header-section-number">9.2</span> Questões de Verdadeiro/Falso</a></li>
  <li><a href="#aviso" id="toc-aviso" class="nav-link" data-scroll-target="#aviso"><span class="header-section-number">9.3</span> Aviso</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Outros formatos</h2><ul><li><a href="slides.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Aula 3: Topografia de Densidade e Grafos — Clustering Hierárquico e HDBSCAN</h1>
<p class="subtitle lead">Aprendizado Não Supervisionado</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor</div>
    <div class="quarto-title-meta-contents">
             <p>Marcos M. Raimundo — Instituto de Computação, UNICAMP </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Data de Publicação</div>
    <div class="quarto-title-meta-contents">
      <p class="date">30 de agosto de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><a href="slides.html" class="see-all" aria-label="Ver slides" title="Ver slides">Slides</a> <a href="../../../teaching/unsupervised-learning/index.html" class="see-all lesson-list-link" aria-label="Lista de aulas" title="Lista de aulas">Lista de aulas</a></p>
<section id="abertura-o-que-cluster-deveria-significar" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Abertura — O Que “Cluster” Deveria Significar</h1>
<p>A Aula 2 respondeu “esse valor de <span class="math inline">\(\mathbf{x}\)</span> é comum ou raro?” para cada ponto do espaço, isoladamente — <span class="math inline">\(d_K(\mathbf{x})\)</span> pequeno = região densa; grande = região rara. Mas um paciente individual raramente interessa isolado: o que se quer, quase sempre, é agrupar pacientes parecidos entre si, sem saber de antemão quantos grupos existem, nem que forma cada grupo tem. Isso é <strong>clustering</strong> — e é o objeto desta aula.</p>
<p>A resposta mais imediata, e a que a maioria dos cursos ensina primeiro, é K-means: escolha <span class="math inline">\(K\)</span> centros <span class="math inline">\(\boldsymbol\mu_1,\dots,\boldsymbol\mu_K\)</span> e atribua cada ponto ao centro mais próximo. Bishop (PRML, 2006, p.&nbsp;424) coloca a meta do método nestes termos — tradução livre:</p>
<blockquote class="blockquote">
<p>“Nosso objetivo é encontrar uma atribuição de pontos a clusters, bem como um conjunto de vetores <span class="math inline">\(\{\boldsymbol\mu_k\}\)</span>, tais que a soma dos quadrados das distâncias de cada ponto ao seu vetor mais próximo <span class="math inline">\(\boldsymbol\mu_k\)</span> seja mínima.”</p>
</blockquote>
<p>Formalmente, cada ponto <span class="math inline">\(\mathbf{x}_n\)</span> recebe o rótulo do centro mais próximo — “simplesmente atribuímos o <span class="math inline">\(n\)</span>-ésimo ponto ao centro de cluster mais próximo” (PRML, p.&nbsp;425, tradução livre), <span class="math inline">\(r_{nk}=1\)</span> se <span class="math inline">\(k=\arg\min_j \lVert\mathbf{x}_n-\boldsymbol\mu_j\rVert^2\)</span>. Hastie, Tibshirani &amp; Friedman (ESL, 2009, p.&nbsp;510) descrevem o resultado geométrico dessa regra com um nome preciso — tradução livre:</p>
<blockquote class="blockquote">
<p>“As linhas retas mostram o particionamento dos pontos, sendo cada setor o conjunto de pontos mais próximos de cada centróide. Esse particionamento é chamado de <em>tesselação de Voronoi</em>.”</p>
</blockquote>
<p>Guarde esse nome — <strong>tesselação de Voronoi</strong> — porque ele é a raiz matemática exata do problema que abre esta aula. Toda célula de uma tesselação de Voronoi é um conjunto <strong>convexo</strong> (a interseção de semi-planos, cada um definido por “estou mais perto do centro <span class="math inline">\(k\)</span> do que do centro <span class="math inline">\(j\)</span>”). Isso não é um detalhe técnico: significa que <strong>nenhuma atribuição por centróide, para nenhum <span class="math inline">\(K\)</span>, pode produzir um cluster com forma de lua crescente ou de anel</strong> — qualquer fronteira reta que tente separar duas luas entrelaçadas vai cortar pelo menos uma delas ao meio.</p>
<section id="roteiro-desta-aula" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="roteiro-desta-aula"><span class="header-section-number">1.1</span> Roteiro desta aula</h2>
<p>Quatro perguntas guiam os próximos ~100 minutos:</p>
<ol type="1">
<li>Se “distância ao centróide mais próximo” falha para formas arbitrárias, <strong>o que exatamente deveria significar “cluster”</strong>?</li>
<li>Dado essa definição melhor, <strong>como construir um cluster computacionalmente</strong>, sem escolher <span class="math inline">\(K\)</span> (nem nenhum outro parâmetro de forma) de antemão?</li>
<li>Isso pode ser reduzido a um problema de <strong>grafos</strong> — e, se sim, qual estrutura de grafo captura <em>toda</em> a hierarquia de clusters possível de uma só vez?</li>
<li>Uma vez com essa estrutura, <strong>como decidir quais clusters encontrados são estrutura real dos dados</strong>, e quais são só flutuação amostral?</li>
</ol>
<p><strong>Problema motivador.</strong> Antes de resolver nada, olhe o problema de frente: a figura abaixo aplica K-means (<span class="math inline">\(K=2\)</span>) a um conjunto de pontos sintético em forma de duas luas entrelaçadas — um exemplo controlado, não o Breast Cancer Wisconsin, escolhido especificamente porque exibe uma forma que nenhuma fronteira reta consegue respeitar.</p>
<div class="fig-resize" style="width: 65%; margin: 0 auto;">
<div id="9cd22a7c" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/cell-3-output-1.png" class="quarto-figure quarto-figure-center figure-img" width="633" height="503"></p>
</figure>
</div>
</div>
</div>
</div>
<p>Os dois centróides (X preta) caem, cada um, aproximadamente no meio de cada lua — e a fronteira reta entre eles (perpendicular ao segmento que os une, embora não desenhada aqui) corta as duas luas em pedaços errados: parte da lua azul vira “laranja”, parte da laranja vira “azul”. Numericamente, comparando o rótulo do K-means com o rótulo verdadeiro de cada lua (o rótulo que gerou os dados, nunca visto pelo K-means), a acurácia da melhor correspondência possível entre os dois é de apenas <span class="math inline">\(\approx 75{,}7\%\)</span> — bem abaixo do que se esperaria de um “bom” clustering em um problema desenhado para ter exatamente dois grupos óbvios a olho nu. Isso não é uma falha de implementação nem de escolha de <span class="math inline">\(K\)</span>: é a convexidade da tesselação de Voronoi, o resultado matemático citado acima, aparecendo na prática. O resto da aula constrói uma alternativa que resolve exatamente isso.</p>
</section>
<section id="pergunta" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="pergunta"><span class="header-section-number">1.2</span> Pergunta</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Se a tesselação de Voronoi do K-means é sempre convexa, o que exatamente precisa mudar na <em>definição</em> de cluster para permitir grupos como as duas luas?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: pense no que “convexo” está implicitamente assumindo sobre onde os pontos de um mesmo cluster podem estar, e o que teria que ser verdade para dispensar essa suposição.</p>
<ul>
<li>□ Bastaria aumentar <span class="math inline">\(K\)</span> (por exemplo, usar <span class="math inline">\(K=10\)</span> em vez de <span class="math inline">\(K=2\)</span>) para que o K-means eventualmente capture a forma de lua com pequenos fragmentos convexos suficientes.</li>
<li>□ Uma definição de cluster baseada em “estar conectado por uma trilha de alta densidade”, em vez de “estar perto de um centro fixo”, não impõe convexidade — uma lua inteira pode ser uma única trilha densa, sem que a forma do seu contorno importe.</li>
<li>□ O problema das duas luas seria resolvido só trocando distância euclidiana por distância de Manhattan (<span class="math inline">\(L_1\)</span>) no K-means, sem mudar a lógica de atribuição ao centro mais próximo.</li>
<li>□ Se um cluster é definido como uma componente conexa de uma região de alta densidade, dois pontos podem estar geometricamente distantes um do outro (medindo em linha reta) e ainda pertencerem ao mesmo cluster, desde que exista um caminho de densidade alta conectando-os.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="intuição-vales-e-montanhas-não-bolas" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Intuição — Vales e Montanhas, Não Bolas</h1>
<p>Antes de qualquer formalismo, veja o resultado inteiro primeiro — só vai faltar nomear os passos. Pense na densidade <span class="math inline">\(p(\mathbf{x})\)</span> dos dados como uma <strong>paisagem</strong>: regiões densas são montanhas, regiões raras são vales. A aposta desta aula é que <strong>um cluster é uma montanha inteira</strong> — não importa o formato do contorno da montanha na base, só importa que ela seja um bloco conectado de terreno alto, separado das outras montanhas por um vale (uma região de baixa densidade).</p>
<p>Um algoritmo que respeita essa definição não precisa de centróide nenhum: em vez de “para qual centro fixo eu estou mais perto”, ele pergunta “caminhando sempre por terreno alto, até onde eu consigo chegar sem descer a um vale?”. Cada lua inteira, mesmo curva, é terreno alto conectado de ponta a ponta — não importa que as duas pontas da lua estejam geometricamente longe uma da outra em linha reta, porque a trilha entre elas nunca desce a um vale.</p>
<div id="8cfc2f95" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/cell-4-output-1.png" class="quarto-figure quarto-figure-center figure-img" width="1153" height="476"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Duas luas   — K-means: 0.757   HDBSCAN: 1.000
Dois anéis  — K-means: 0.507   HDBSCAN: 1.000</code></pre>
</div>
</div>
<p>O painel direito usa exatamente o algoritmo que esta aula vai construir — HDBSCAN, cujo nome ainda não foi justificado — e acerta as duas luas por completo: acurácia <span class="math inline">\(100\%\)</span> contra o rótulo verdadeiro (a mesma comparação que deu <span class="math inline">\(\approx 75{,}7\%\)</span> para o K-means). O mesmo teste, repetido com dois anéis concêntricos (uma forma ainda mais hostil à convexidade: o anel externo <em>envolve</em> o interno por todos os lados), é ainda mais dramático — K-means cai para <span class="math inline">\(\approx 50{,}7\%\)</span>, que é essencialmente o mesmo que adivinhar aleatoriamente entre dois rótulos, enquanto o algoritmo baseado em densidade continua em <span class="math inline">\(100\%\)</span>. Nenhum desses dois números é coincidência: é a convexidade de Voronoi (K-means) contra a ausência de qualquer suposição de forma (densidade-conectividade).</p>
<p>Falta nomear os passos: como, exatamente, “caminhar por terreno alto” se transforma em um algoritmo executável? A resposta atravessa três ideias, uma por bloco: (i) formalizar “montanha” como um conjunto de nível de densidade (Bloco 3); (ii) transformar isso em um grafo, usando uma distância que “sabe” onde é vale e onde é montanha (Bloco 4); (iii) extrair, desse grafo, uma única estrutura que contém toda a hierarquia de clusters possível ao mesmo tempo (Bloco 5).</p>
<section id="pergunta-1" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="pergunta-1"><span class="header-section-number">2.1</span> Pergunta</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Duas montanhas separadas por um vale raso (densidade baixa, mas não zero) — “andar por terreno alto” as trata como um cluster só, ou dois?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: pense no que muda se o vale for rebaixado ainda mais, até chegar a densidade zero, comparado ao vale raso original.</p>
<ul>
<li>□ Se o vale entre as duas montanhas nunca é totalmente seco (densidade sempre estritamente positiva em todo o caminho), então, para qualquer limiar de altura <span class="math inline">\(\lambda\)</span> suficientemente baixo, existe um caminho de terreno “alto o bastante” ligando as duas montanhas — então, nesse limiar, elas formam um cluster só.</li>
<li>□ A pergunta “cluster só ou dois clusters” tem uma resposta fixa, independente de qual altura <span class="math inline">\(\lambda\)</span> se usa para definir “terreno alto”.</li>
<li>□ Se o vale for rebaixado até ter densidade exatamente zero em algum ponto do caminho, nenhum limiar <span class="math inline">\(\lambda&gt;0\)</span> jamais conecta as duas montanhas por cima desse ponto.</li>
<li>□ Um vale raso entre duas montanhas altas é evidência de que, na verdade, os dados vieram de uma única população, e a divisão em duas montanhas é sempre um artefato de estimação.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="conjuntos-de-nível-de-densidade" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Conjuntos de Nível de Densidade</h1>
<p>Antes do formalismo, veja o esqueleto abstrato da metáfora da paisagem (Bloco 2) num corte transversal simples: um eixo <span class="math inline">\(\mathbf{x}\)</span> (aqui em 1D, só para poder desenhar) e a densidade <span class="math inline">\(p(\mathbf{x})\)</span> no eixo vertical, com duas “montanhas” separadas por um “vale”.</p>
<div class="fig-resize" style="width: 62%; margin: 0 auto;">
<img src="index_files/mediabag/71b07682cee4fe5a127da898a387c2acd2eacb17.svg" class="img-fluid">
</div>
<p>Fixando um limiar <span class="math inline">\(\lambda\)</span> (linha vermelha tracejada), o conjunto de nível <span class="math inline">\(L_\lambda=\{\mathbf{x}:p(\mathbf{x})\ge\lambda\}\)</span> é exatamente o trecho do eixo <span class="math inline">\(\mathbf{x}\)</span> em que a curva azul-acinzentada está acima da linha — aqui, <strong>duas componentes conexas disjuntas</strong> (destacadas em azul), uma por montanha, porque o vale entre elas fica abaixo de <span class="math inline">\(\lambda\)</span>. Baixando <span class="math inline">\(\lambda\)</span> até abaixo da altura do vale, as duas componentes se tocariam e passariam a contar como uma componente só — exatamente o mecanismo que a figura seguinte (com densidade estimada de verdade, via KDE, sobre os dados reais de duas luas) verifica numericamente, variando <span class="math inline">\(\lambda\)</span> de fato.</p>
<p>Formalize a metáfora da paisagem. Para um limiar <span class="math inline">\(\lambda \ge 0\)</span>, defina o <strong>conjunto de nível</strong> de densidade</p>
<p><span class="math display">\[L_\lambda = \{\mathbf{x} : p(\mathbf{x}) \ge \lambda\}.\]</span></p>
<p><span class="math inline">\(L_\lambda\)</span> é o “terreno acima da altura <span class="math inline">\(\lambda\)</span>” — o conjunto de todos os pontos do espaço onde a densidade é pelo menos <span class="math inline">\(\lambda\)</span>. A tese central desta aula, anunciada na Abertura, agora tem uma fórmula:</p>
<blockquote class="blockquote">
<p><strong>Um cluster, num nível <span class="math inline">\(\lambda\)</span> fixo, é uma componente conexa de <span class="math inline">\(L_\lambda\)</span>.</strong></p>
</blockquote>
<p>Essa definição já responde ao Bloco 2: uma componente conexa não precisa ser convexa, nem ter contorno regular — só precisa ser um bloco de terreno alto que se pode percorrer inteiro sem descer abaixo de <span class="math inline">\(\lambda\)</span>. Hastie, Tibshirani &amp; Friedman (ESL, 2009, p.&nbsp;507) descrevem essa família de método como um dos três paradigmas fundamentais de clustering, ao lado do combinatório (K-means, que abriu a aula) e da modelagem por mistura (que a Aula 4 vai cobrir) — tradução livre:</p>
<blockquote class="blockquote">
<p>“Buscadores de moda (‘caçadores de irregularidades’) adotam uma perspectiva não-paramétrica, tentando estimar diretamente as modas distintas da função de densidade de probabilidade. As observações ‘mais próximas’ de cada respectiva moda definem então os clusters individuais.”</p>
</blockquote>
<p><strong>O que acontece variando <span class="math inline">\(\lambda\)</span>.</strong> Para <span class="math inline">\(\lambda\)</span> muito alto, só os picos mais extremos de densidade sobrevivem — poucas regiões, pequenas, bem separadas (cada montanha isolada pelo próprio topo). Conforme <span class="math inline">\(\lambda\)</span> cai, cada região de <span class="math inline">\(L_\lambda\)</span> cresce (o “terreno acima de <span class="math inline">\(\lambda\)</span>” se expande encosta abaixo) e, em algum ponto crítico, duas regiões que eram separadas se tocam e se fundem numa só — exatamente o fenômeno da Pergunta do Bloco 2. Em <span class="math inline">\(\lambda=0\)</span>, <span class="math inline">\(L_0\)</span> é o suporte inteiro da densidade: uma única componente (supondo suporte conexo).</p>
<p>Isso já é, em germe, uma <strong>hierarquia de clusters indexada por <span class="math inline">\(\lambda\)</span></strong>: decrescer <span class="math inline">\(\lambda\)</span> de <span class="math inline">\(\infty\)</span> até <span class="math inline">\(0\)</span> nunca separa componentes que já estavam unidas (só pode fundir, nunca dividir) — a mesma estrutura de árvore, de baixo para cima, que o dendrograma da Aula de hierárquico clássico (Bloco 5) vai produzir. A figura abaixo mostra <span class="math inline">\(L_\lambda\)</span> estimado por KDE nos dados de duas luas, para limiares decrescentes: repare como as duas luas — cada uma uma componente sozinha nos limiares mais altos — permanecem separadas até <span class="math inline">\(\lambda\)</span> ficar baixo o bastante para o “vale” entre elas ser absorvido.</p>
<div class="fig-resize" style="width: 90%; margin: 0 auto;">
<div id="177c1269" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/cell-5-output-1.png" class="quarto-figure quarto-figure-center figure-img" width="1348" height="451"></p>
</figure>
</div>
</div>
</div>
</div>
<p>Da esquerda para a direita, <span class="math inline">\(\lambda\)</span> cai de <span class="math inline">\(0{,}20\)</span> para <span class="math inline">\(0{,}04\)</span>: no painel esquerdo, as duas luas ainda são regiões nitidamente separadas de <span class="math inline">\(L_\lambda\)</span> (a área azul); no painel direito, <span class="math inline">\(\lambda\)</span> já é baixo o bastante para que o vale entre as luas seja absorvido em <span class="math inline">\(L_\lambda\)</span> — as duas regiões se tocam e, para esse <span class="math inline">\(\lambda\)</span>, seriam contadas como uma componente conexa só. Nenhum <span class="math inline">\(\lambda\)</span> único é “o certo” — é exatamente esse problema (qual <span class="math inline">\(\lambda\)</span> escolher?) que o Bloco 6 vai resolver, não escolhendo um único <span class="math inline">\(\lambda\)</span>, mas medindo quanto tempo cada cluster “sobrevive” ao longo de toda a faixa de <span class="math inline">\(\lambda\)</span>.</p>
<section id="pergunta-2" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="pergunta-2"><span class="header-section-number">3.1</span> Pergunta</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>No limite <span class="math inline">\(\lambda \to \infty\)</span>, quantas componentes conexas tem <span class="math inline">\(L_\lambda\)</span>, em geral?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: pense no que sobra de “terreno acima de <span class="math inline">\(\lambda\)</span>” quando <span class="math inline">\(\lambda\)</span> é maior que a densidade máxima de qualquer região dos dados.</p>
<ul>
<li>□ No limite <span class="math inline">\(\lambda\to\infty\)</span>, <span class="math inline">\(L_\lambda\)</span> é, em geral, o conjunto vazio — nenhum ponto do espaço tem densidade infinita, então nenhum ponto sobrevive ao limiar.</li>
<li>□ O número de componentes conexas de <span class="math inline">\(L_\lambda\)</span> é uma função monótona não-crescente de <span class="math inline">\(\lambda\)</span> — nunca aumenta conforme <span class="math inline">\(\lambda\)</span> sobe (pode diminuir ou ficar igual, indo a zero no limite).</li>
<li>□ Existe sempre um <span class="math inline">\(\lambda\)</span> finito tal que <span class="math inline">\(L_\lambda\)</span> tem exatamente uma componente conexa por moda (pico local) da densidade — desde que os picos tenham alturas suficientemente diferentes entre si e o <span class="math inline">\(\lambda\)</span> seja escolhido logo abaixo do menor pico relevante.</li>
<li>□ Se a densidade <span class="math inline">\(p(\mathbf{x})\)</span> é estritamente positiva em todo o espaço <span class="math inline">\(\mathbb{R}^d\)</span> (nunca toca zero, mesmo longe dos dados), então <span class="math inline">\(L_\lambda\)</span> para <span class="math inline">\(\lambda\)</span> pequeno mas positivo pode ainda ter mais de uma componente conexa, dependendo de como <span class="math inline">\(p\)</span> varia.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="da-densidade-ao-grafo-distância-de-alcançabilidade-mútua" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Da Densidade ao Grafo: Distância de Alcançabilidade Mútua</h1>
<p>O Bloco 3 definiu cluster em termos de <span class="math inline">\(p(\mathbf{x})\)</span> — mas <span class="math inline">\(p\)</span> nunca é conhecido de verdade, só estimado. A Aula 2 já resolveu exatamente esse problema: <span class="math inline">\(d_K(\mathbf{x})\)</span>, a distância ao <span class="math inline">\(K\)</span>-ésimo vizinho mais próximo, é <strong>inversamente relacionado à densidade local</strong> (<span class="math inline">\(d_K(\mathbf{x})\)</span> pequeno = região densa; grande = região rara), sem exigir nenhuma forma paramétrica para <span class="math inline">\(p\)</span>. Hoje esse mesmo número recebe um nome novo — <strong>core distance</strong>, ou distância ao núcleo, <span class="math inline">\(\mathrm{core}_K(\mathbf{x}) = d_K(\mathbf{x})\)</span> — e um uso novo: virar peso de aresta num grafo.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Premissas desta derivação
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><span class="math inline">\(\mathrm{core}_K(\mathbf{x})\)</span> pequeno <span class="math inline">\(\Leftrightarrow\)</span> <span class="math inline">\(\mathbf{x}\)</span> está numa região densa (herdado direto da Aula 2).</li>
<li>A distância bruta <span class="math inline">\(d(a,b)\)</span> entre dois pontos, por si só, <strong>não</strong> diz nada sobre a densidade da vizinhança de nenhum dos dois — dois pontos podem estar geometricamente próximos mesmo que um deles more numa região densa e o outro numa região quase vazia.</li>
<li>Um cluster (Bloco 3) é definido por conectividade <em>dentro de terreno alto</em> — então a “distância” usada para conectar dois pontos no grafo precisa penalizar caminhos que passam por regiões raras, não só medir o comprimento geométrico do caminho.</li>
</ol>
</div>
</div>
<p><strong>Por que a distância bruta não basta.</strong> Imagine dois pacientes <span class="math inline">\(a\)</span> e <span class="math inline">\(b\)</span> com valores de atributos geometricamente próximos — <span class="math inline">\(d(a,b)\)</span> pequeno. Se <span class="math inline">\(a\)</span> mora no meio de uma região densa (muitos pacientes parecidos por perto, <span class="math inline">\(\mathrm{core}_K(a)\)</span> pequeno) e <span class="math inline">\(b\)</span> mora sozinho, longe de qualquer vizinho (região rara, <span class="math inline">\(\mathrm{core}_K(b)\)</span> grande), conectar <span class="math inline">\(a\)</span> e <span class="math inline">\(b\)</span> diretamente pelo valor bruto <span class="math inline">\(d(a,b)\)</span> ignoraria que <span class="math inline">\(b\)</span> está, na prática, isolado — <span class="math inline">\(b\)</span> só “parece” perto de <span class="math inline">\(a\)</span> porque a distância entre os dois é pequena, não porque existe uma trilha densa de pacientes ligando os dois.</p>
<p><strong>A construção, passo a passo.</strong> Defina a <strong>distância de alcançabilidade mútua</strong></p>
<p><span class="math display">\[d_{\mathrm{mreach}}(a,b) = \max\bigl(\mathrm{core}_K(a),\ \mathrm{core}_K(b),\ d(a,b)\bigr).\]</span></p>
<p>Ela “acalma” pontos em regiões raras: se <span class="math inline">\(b\)</span> está isolado (<span class="math inline">\(\mathrm{core}_K(b)\)</span> grande), então <span class="math inline">\(d_{\mathrm{mreach}}(a,b) \ge
\mathrm{core}_K(b)\)</span> para <strong>qualquer</strong> <span class="math inline">\(a\)</span> — <span class="math inline">\(b\)</span> nunca parece mais próximo de ninguém do que sua própria distância ao vale mais próximo permite. Ao mesmo tempo, se <span class="math inline">\(a\)</span> e <span class="math inline">\(b\)</span> moram na mesma região densa (ambos os <em>core distances</em> pequenos e <span class="math inline">\(d(a,b)\)</span> também pequeno), <span class="math inline">\(d_{\mathrm{mreach}}(a,b)\)</span> continua pequeno — a distância bruta domina o máximo, e a conexão é barata, exatamente o que se espera de dois pontos dentro da mesma “montanha”.</p>
<div class="fig-resize" style="width: 55%; margin: 0 auto;">
<img src="index_files/mediabag/7ea24b6c6c7778898f956c422dd8f9ec4e445c78.svg" class="img-fluid">
</div>
<p>O diagrama resume a construção: três quantidades entram, uma sai. Note que <span class="math inline">\(d_{\mathrm{mreach}}\)</span> é sempre <strong>maior ou igual</strong> à distância bruta <span class="math inline">\(d(a,b)\)</span> — a alcançabilidade mútua nunca aproxima pontos, só os afasta quando algum dos dois mora numa região rara. Essa assimetria (só afastar, nunca aproximar) é o mecanismo exato de “acalmar” pontos isolados sem alterar em nada as distâncias dentro de uma região já densa.</p>
<div id="39e4ac5d" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Núcleo pequeno (K=5) sobre os dois atributos reais que vão sustentar</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co"># o Bloco 6 -- ilustra a "calma" da alcançabilidade mútua em 5 pacientes</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># escolhidos deliberadamente: 4 numa vizinhança densa, 1 isolado.</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>_tree_2d <span class="op">=</span> cKDTree(X_2d)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>_core_2d <span class="op">=</span> core_distance(X_2d, K<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>_isolado <span class="op">=</span> np.argmax(_core_2d)          <span class="co"># paciente com o maior core distance</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>_denso <span class="op">=</span> np.argsort(_core_2d)[:<span class="dv">4</span>]        <span class="co"># 4 pacientes na região mais densa</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>_a, _b <span class="op">=</span> _denso[<span class="dv">0</span>], _isolado</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>_d_raw <span class="op">=</span> np.linalg.norm(X_2d[_a] <span class="op">-</span> X_2d[_b])</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>_d_mreach <span class="op">=</span> <span class="bu">max</span>(_core_2d[_a], _core_2d[_b], _d_raw)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"core(</span><span class="sc">{</span>_a<span class="sc">}</span><span class="ss">)=</span><span class="sc">{</span>_core_2d[_a]<span class="sc">:.3f}</span><span class="ss">  core(</span><span class="sc">{</span>_b<span class="sc">}</span><span class="ss">)=</span><span class="sc">{</span>_core_2d[_b]<span class="sc">:.3f}</span><span class="ss">  "</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"d_bruta=</span><span class="sc">{</span>_d_raw<span class="sc">:.3f}</span><span class="ss">  d_mreach=</span><span class="sc">{</span>_d_mreach<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>core(418)=0.033  core(461)=1.288  d_bruta=5.388  d_mreach=5.388</code></pre>
</div>
</div>
<p>Neste exemplo com os dados reais do Breast Cancer Wisconsin (usando apenas os dois atributos de visualização deste bloco em diante, <code>radius_worst</code> e <code>concave points_worst</code>, padronizados), o paciente mais isolado tem <span class="math inline">\(\mathrm{core}_5\)</span> visivelmente maior que a distância bruta até um paciente da região densa — então <span class="math inline">\(d_{\mathrm{mreach}}\)</span> é dominado pelo <em>core distance</em> do isolado, não pela distância bruta: exatamente o comportamento “acalmante” descrito acima, agora visto num número real, não só na fórmula.</p>
<section id="pergunta-3" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="pergunta-3"><span class="header-section-number">4.1</span> Pergunta</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Se <span class="math inline">\(\mathrm{core}_K(a) = \mathrm{core}_K(b) = 0\)</span> (dois pontos coincidentes com pelo menos <span class="math inline">\(K\)</span> outros pontos na mesma posição exata), o que <span class="math inline">\(d_{\mathrm{mreach}}(a,b)\)</span> vale?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: releia a fórmula — o que o <span class="math inline">\(\max\)</span> faz quando dois dos três termos são zero?</p>
<ul>
<li>□ Se <span class="math inline">\(\mathrm{core}_K(a)=\mathrm{core}_K(b)=0\)</span>, então <span class="math inline">\(d_{\mathrm{mreach}}(a,b) = d(a,b)\)</span> — a distância bruta passa a decidir sozinha, porque os dois termos de núcleo não competem com ela no máximo.</li>
<li>□ <span class="math inline">\(d_{\mathrm{mreach}}(a,b)\)</span> sempre vale zero quando pelo menos um dos dois <em>core distances</em> é zero, independente do valor de <span class="math inline">\(d(a,b)\)</span>.</li>
<li>□ Num caso extremo em que <span class="math inline">\(d(a,b)=0\)</span> também (os próprios <span class="math inline">\(a\)</span> e <span class="math inline">\(b\)</span> coincidem exatamente), <span class="math inline">\(d_{\mathrm{mreach}}(a,b)=0\)</span>.</li>
<li>□ Esse caso extremo (core distance zero) é impossível de ocorrer na prática com dados reais, então não precisa ser considerado ao implementar a fórmula.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="a-árvore-geradora-mínima-e-o-clustering-hierárquico-clássico" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> A Árvore Geradora Mínima e o Clustering Hierárquico Clássico</h1>
<p>Com <span class="math inline">\(d_{\mathrm{mreach}}\)</span> definida para todo par de pontos, construa o <strong>grafo completo</strong> cujos vértices são os <span class="math inline">\(N\)</span> pontos e cujo peso de aresta <span class="math inline">\((i,j)\)</span> é <span class="math inline">\(d_{\mathrm{mreach}}(i,j)\)</span>. Esse grafo tem <span class="math inline">\(N(N-1)/2\)</span> arestas — computacionalmente pesado, mas ele contém, escondida dentro de si, uma estrutura muito mais compacta: a <strong>Árvore Geradora Mínima</strong> (<em>Minimum Spanning Tree</em>, MST), a árvore de <span class="math inline">\(N-1\)</span> arestas que conecta todos os <span class="math inline">\(N\)</span> vértices com a menor soma de pesos possível.</p>
<p><strong>O resultado citado.</strong> Um fato clássico de teoria de grafos e clustering conecta a MST a um método de clustering hierárquico que Hastie, Tibshirani &amp; Friedman (ESL, 2009, §14.3.12) descrevem em detalhe: <strong>ligação simples</strong> (<em>single linkage</em>), tradução livre —</p>
<blockquote class="blockquote">
<p>“<em>Ligação simples</em> (SL) toma a dissimilaridade intergrupo como a do par mais próximo (menos dissimilar): <span class="math inline">\(d_{SL}(G,H) = \min_{i\in G,
i'\in H} d_{ii'}\)</span>. Isso também é chamado, com frequência, de técnica do <em>vizinho mais próximo</em>.” (p.&nbsp;523)</p>
</blockquote>
<p>O algoritmo hierárquico aglomerativo por ligação simples começa com <span class="math inline">\(N\)</span> clusters (um por ponto) e, a cada passo, funde os dois clusters cuja menor distância entre um par de membros é a menor de todas — produzindo uma sequência de <span class="math inline">\(N-1\)</span> fusões, cada uma em um nível de dissimilaridade maior que a anterior (ESL, p.&nbsp;520-521, tradução livre): <em>“cada nível da hierarquia representa um agrupamento particular […] a árvore binária […] tem <span class="math inline">\(N-1\)</span> níveis”</em>.</p>
<p><strong>A conexão com a MST, verificada num exemplo pequeno.</strong> O fato central desta seção — que <strong>cortar as <span class="math inline">\(k-1\)</span> arestas mais pesadas da MST reproduz exatamente as <span class="math inline">\(k\)</span> componentes do clustering por ligação simples com <span class="math inline">\(k\)</span> clusters</strong> — não é intuitivo à primeira vista. Antes de aceitá-lo, verifique com um exemplo pequeno, um <em>worked example</em> no espírito da técnica de “exemplo resolvido antes do resultado geral”:</p>
<div id="d3b0f00b" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exemplo pequeno e concreto: 7 pontos 2D em 3 grupos visuais --------</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>pts <span class="op">=</span> np.array([</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    [<span class="fl">0.0</span>, <span class="fl">0.0</span>], [<span class="fl">0.5</span>, <span class="fl">0.3</span>], [<span class="fl">0.2</span>, <span class="fl">0.9</span>],      <span class="co"># grupo A (perto da origem)</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    [<span class="fl">5.0</span>, <span class="fl">5.0</span>], [<span class="fl">5.4</span>, <span class="fl">5.3</span>], [<span class="fl">5.1</span>, <span class="fl">4.6</span>],      <span class="co"># grupo B</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    [<span class="fl">9.5</span>, <span class="fl">0.2</span>],                               <span class="co"># ponto C, isolado</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>n_pts <span class="op">=</span> <span class="bu">len</span>(pts)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>D_pts <span class="op">=</span> squareform(pdist(pts))</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>edges_pts <span class="op">=</span> mst_edges_sorted(D_pts)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Arestas da MST (i, j, peso), ordem crescente:"</span>)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, j, w <span class="kw">in</span> edges_pts:</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  (</span><span class="sc">{</span>i<span class="sc">}</span><span class="ss">,</span><span class="sc">{</span>j<span class="sc">}</span><span class="ss">) peso=</span><span class="sc">{</span>w<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.cluster.hierarchy <span class="im">import</span> linkage, fcluster</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> adjusted_rand_score</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>Z_pts <span class="op">=</span> linkage(pts, method<span class="op">=</span><span class="st">'single'</span>)</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> k <span class="kw">in</span> [<span class="dv">2</span>, <span class="dv">3</span>]:</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>    labels_mst <span class="op">=</span> clusters_from_mst_cut(edges_pts, n_pts, k)</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>    labels_sl <span class="op">=</span> fcluster(Z_pts, k, criterion<span class="op">=</span><span class="st">'maxclust'</span>)</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>    ari <span class="op">=</span> adjusted_rand_score(labels_mst, labels_sl)</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"k=</span><span class="sc">{</span>k<span class="sc">}</span><span class="ss">:  MST-corte = </span><span class="sc">{</span>labels_mst<span class="sc">}</span><span class="ss">   ligação-simples = </span><span class="sc">{</span>labels_sl<span class="sc">}</span><span class="ss">   ARI = </span><span class="sc">{</span>ari<span class="sc">:.2f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Arestas da MST (i, j, peso), ordem crescente:
  (3,5) peso=0.412
  (3,4) peso=0.500
  (0,1) peso=0.583
  (1,2) peso=0.671
  (2,5) peso=6.140
  (5,6) peso=6.223
k=2:  MST-corte = [0 0 0 0 0 0 1]   ligação-simples = [1 1 1 1 1 1 2]   ARI = 1.00
k=3:  MST-corte = [0 0 0 1 1 1 2]   ligação-simples = [2 2 2 1 1 1 3]   ARI = 1.00</code></pre>
</div>
</div>
<div class="fig-resize" style="width: 55%; margin: 0 auto;">
<div id="15b7f033" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/cell-8-output-1.png" class="quarto-figure quarto-figure-center figure-img" width="633" height="529"></p>
</figure>
</div>
</div>
</div>
</div>
<p>Os 7 pontos formam visualmente três grupos: A (<span class="math inline">\(0,1,2\)</span>, perto da origem), B (<span class="math inline">\(3,4,5\)</span>, perto de <span class="math inline">\((5,5)\)</span>) e o ponto isolado <span class="math inline">\(6\)</span> (<span class="math inline">\((9{,}5,
0{,}2)\)</span>). A MST tem, como esperado, <span class="math inline">\(6\)</span> arestas (<span class="math inline">\(N-1=6\)</span>): quatro arestas curtas dentro de A e B (pesos entre <span class="math inline">\(0{,}41\)</span> e <span class="math inline">\(0{,}67\)</span>) e duas arestas longas ligando os grupos entre si e ao ponto isolado (pesos <span class="math inline">\(6{,}14\)</span> e <span class="math inline">\(6{,}22\)</span>) — exatamente as duas arestas mais pesadas.</p>
<p>Cortando a aresta mais pesada (<span class="math inline">\(k=2\)</span>): sobra <span class="math inline">\(\{0,1,2,3,4,5\}\)</span> de um lado e <span class="math inline">\(\{6\}\)</span> isolado do outro — e o clustering por ligação simples com <span class="math inline">\(k=2\)</span> produz <strong>exatamente a mesma partição</strong> (ARI <span class="math inline">\(=1{,}00\)</span>, concordância perfeita). Cortando também a segunda mais pesada (<span class="math inline">\(k=3\)</span>): sobra <span class="math inline">\(\{0,1,2\}\)</span>, <span class="math inline">\(\{3,4,5\}\)</span> e <span class="math inline">\(\{6\}\)</span> — os três grupos visuais, de novo idênticos à ligação simples (ARI <span class="math inline">\(=1{,}00\)</span>). Note que em <span class="math inline">\(k=2\)</span> os grupos A e B se fundem antes de <span class="math inline">\(6\)</span> se juntar a qualquer um deles — porque a menor distância entre A e B (<span class="math inline">\(6{,}14\)</span>) é, por pouco, menor que a menor distância de <span class="math inline">\(6\)</span> a qualquer dos dois grupos (<span class="math inline">\(6{,}22\)</span>); um exemplo de que “vizinho mais próximo” pode produzir fusões que não são as mais “intuitivas” à primeira vista, mas são as matematicamente corretas pela definição de ligação simples.</p>
<p><strong>O que isso compra.</strong> A MST, uma única estrutura com <span class="math inline">\(N-1\)</span> arestas, contém a hierarquia completa: para obter o clustering de ligação simples em <strong>qualquer</strong> número de clusters <span class="math inline">\(k\)</span>, basta ordenar as arestas da MST por peso e cortar as <span class="math inline">\(k-1\)</span> mais pesadas — sem refazer nenhum cálculo de distância. É a compressão exata da paisagem inteira de <span class="math inline">\(\lambda\)</span>s do Bloco 3 numa única árvore.</p>
<p>Um aviso honesto, também do ESL (p.&nbsp;524, tradução livre), sobre a ligação simples especificamente: <em>“Como a ligação simples exige apenas que uma única dissimilaridade seja pequena para que dois grupos sejam considerados próximos, […] ela terá tendência a combinar, em limiares relativamente baixos, observações ligadas por uma série de observações intermediárias próximas. Esse fenômeno, chamado de <em>encadeamento</em> (<em>chaining</em>), é frequentemente considerado um defeito do método.”</em> — uma fileira de pontos, cada um perto do próximo, pode encadear dois grupos que “deveriam” ser distintos. É esse defeito, mais o problema de “que <span class="math inline">\(k\)</span>/<span class="math inline">\(\lambda\)</span> escolher” do Bloco 3, que o Bloco 6 ataca.</p>
<section id="pergunta-4" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="pergunta-4"><span class="header-section-number">5.1</span> Pergunta</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Se um único ponto de ruído for inserido exatamente no meio do “vale” entre dois clusters genuinamente distintos, o que acontece com a MST e com o clustering por ligação simples resultante?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: pense no “encadeamento” citado do ESL — o que uma única observação intermediária bem posicionada consegue fazer.</p>
<ul>
<li>□ Esse único ponto de ruído pode, por si só, criar uma aresta curta ligando os dois clusters através dele, fazendo a ligação simples fundir os dois clusters num nível de dissimilaridade bem mais baixo do que fundiria sem esse ponto.</li>
<li>□ Um único ponto no meio do vale nunca afeta a MST global, porque a MST é definida pela soma total de pesos, e um único ponto tem peso desprezível relativo ao total.</li>
<li>□ Esse cenário é exatamente o que o ESL chama de <em>chaining</em> (encadeamento) — um defeito citado explicitamente do método de ligação simples.</li>
<li>□ O problema desapareceria completamente ao usar <span class="math inline">\(d_{\mathrm{mreach}}\)</span> em vez da distância bruta, porque a alcançabilidade mútua nunca permite encadeamento em nenhuma circunstância.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="condensando-a-árvore-e-medindo-persistência" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Condensando a Árvore e Medindo Persistência</h1>
<p>O Bloco 5 deixou dois problemas em aberto: (i) um único <span class="math inline">\(k\)</span> (ou <span class="math inline">\(\lambda\)</span>) fixo não serve para um dataset com clusters de densidades muito diferentes entre si — um <span class="math inline">\(\lambda\)</span> que revela um cluster raro e denso pode já ter apagado outro, mais espalhado; (ii) encadeamento pode ligar, por um fio fino de pontos, dois grupos que “deveriam” ser distintos. O HDBSCAN ataca os dois de uma vez, com uma ideia que não está em nenhum dos livros-texto desta disciplina (Campello, Moulavi &amp; Sander, 2013) — <strong>persistência</strong>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Ponte conceitual
</div>
</div>
<div class="callout-body-container callout-body">
<p>Pense na hierarquia inteira (a MST cortada em toda altura possível, não só um <span class="math inline">\(k\)</span>) como um filme: em cada quadro (cada valor de <span class="math inline">\(d_{\mathrm{mreach}}\)</span> de corte), alguns clusters existem, outros não. Um cluster que aparece por muitos quadros seguidos, sobrevivendo como componente distinta por uma longa faixa de cortes, é mais “real” do que um que aparece e desaparece rapidamente.</p>
</div>
</div>
<p><strong>Passo 1 — árvore condensada.</strong> Construa a hierarquia completa (o dendrograma de ligação simples equivalente à MST, Bloco 5) e <strong>condense-a</strong>: sempre que um ramo se divide em dois, mas um dos dois lados tem menos que <code>min_cluster_size</code> pontos, trate esse lado como “pontos que se perderam do cluster pai” (não como um novo cluster) em vez de um novo ramo — só ramos com pelo menos <code>min_cluster_size</code> pontos contam como clusters candidatos. Isso já elimina boa parte do encadeamento do Bloco 5: uma cadeia fina de pontos raramente atinge o tamanho mínimo para ser um ramo próprio.</p>
<p><strong>Passo 2 — persistência por excesso de massa.</strong> Para cada ramo (cluster candidato) da árvore condensada, meça por quanto tempo ele “sobrevive” como componente distinta ao longo da faixa de valores de <span class="math inline">\(\lambda\)</span> (equivalentemente, de <span class="math inline">\(1/d_{\mathrm{mreach}}\)</span>) — a soma, para cada ponto do ramo, do intervalo de <span class="math inline">\(\lambda\)</span> em que aquele ponto pertenceu a esse cluster específico antes de ser absorvido por um cluster-pai ou virar ruído. Essa soma é a <strong>persistência</strong> (excesso de massa) do cluster. Clusters de alta persistência sobreviveram como blocos coerentes por uma faixa longa de limiares — evidência de estrutura real, não um artefato de onde exatamente <span class="math inline">\(\lambda\)</span> foi cortado.</p>
<p><strong>Passo 3 — extração.</strong> Percorrendo a árvore condensada de baixo para cima, escolha, em cada ramificação, o cluster de maior persistência total entre “manter o cluster-pai inteiro” ou “dividir nos dois filhos” — o algoritmo original (Campello, Moulavi &amp; Sander, 2013, descrito também na documentação do scikit-learn, fonte não-livro, sinalizada como tal) resolve essa escolha por programação dinâmica, maximizando a persistência total da partição final. O resultado: uma partição em clusters que <strong>não</strong> precisa vir de um único corte horizontal em <span class="math inline">\(\lambda\)</span> — clusters diferentes podem ser extraídos de alturas diferentes da árvore, cada um no seu próprio “melhor” <span class="math inline">\(\lambda\)</span>.</p>
<div class="fig-resize" style="width: 60%; margin: 0 auto;">
<img src="index_files/mediabag/7e4457b316cb414935beaca6c041c84e643d7b56.svg" class="img-fluid">
</div>
<p>O pipeline resume os três passos: da MST (já construída no Bloco 5) para a hierarquia completa (o dendrograma equivalente), dessa para a árvore condensada (Passo 1) e, por fim, a extração por persistência (Passos 2-3). Cada seta é um passo computável, sem nenhum <span class="math inline">\(\lambda\)</span> escolhido à mão — só o parâmetro de escala <code>min_cluster_size</code> (e, tipicamente, <code>min_samples</code>, o análogo de <span class="math inline">\(K\)</span> do <em>core distance</em>).</p>
<section id="aplicando-ao-breast-cancer-wisconsin-sem-rótulos" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="aplicando-ao-breast-cancer-wisconsin-sem-rótulos"><span class="header-section-number">6.1</span> Aplicando ao Breast Cancer Wisconsin, Sem Rótulos</h2>
<p>Hora de aplicar tudo isso ao problema-fio real, ainda sem usar o diagnóstico. Usando os dois atributos reais de visualização já apresentados (<code>radius_worst</code>, padronizado, e <code>concave points_worst</code>, padronizado) e <code>min_cluster_size=15</code>, o HDBSCAN (via <code>sklearn.cluster.HDBSCAN</code>, confirmado disponível na versão 1.8.0 do scikit-learn instalada no kernel desta disciplina — não o pacote <code>hdbscan</code> externo, que não está instalado) encontra a seguinte partição:</p>
<div id="b8e05acd" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>hdb_bc <span class="op">=</span> HDBSCAN(min_cluster_size<span class="op">=</span><span class="dv">15</span>).fit(X_2d)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>labels_bc <span class="op">=</span> hdb_bc.labels_</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>uniq, counts <span class="op">=</span> np.unique(labels_bc, return_counts<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Clusters encontrados (rótulo: nº de pacientes):"</span>, <span class="bu">dict</span>(<span class="bu">zip</span>(uniq, counts)))</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Fração marcada como ruído (-1): </span><span class="sc">{</span>(labels_bc <span class="op">==</span> <span class="op">-</span><span class="dv">1</span>)<span class="sc">.</span>mean()<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Clusters encontrados (rótulo: nº de pacientes): {np.int64(-1): np.int64(168), np.int64(0): np.int64(54), np.int64(1): np.int64(347)}
Fração marcada como ruído (-1): 0.295</code></pre>
</div>
</div>
<div class="fig-resize" style="width: 100%; margin: 0 auto;">
<div id="5c57c3be" class="cell" data-execution_count="9">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/cell-10-output-1.png" class="quarto-figure quarto-figure-center figure-img" width="1218" height="530"></p>
</figure>
</div>
</div>
</div>
</div>
<p><strong>Só agora, olhando o painel direito, o diagnóstico entra na conversa</strong> — nenhum passo anterior usou a coluna <code>diagnosis</code>. A correspondência:</p>
<div id="79fa0bff" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> adjusted_rand_score</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(pd.crosstab(labels_bc, diagnosis, margins<span class="op">=</span><span class="va">True</span>))</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>mask <span class="op">=</span> labels_bc <span class="op">!=</span> <span class="op">-</span><span class="dv">1</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">ARI (excluindo ruído, n=</span><span class="sc">{</span>mask<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">}</span><span class="ss">): </span><span class="sc">{</span>adjusted_rand_score(diagnosis[mask], labels_bc[mask])<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"ARI (todos, ruído como rótulo próprio): </span><span class="sc">{</span>adjusted_rand_score(diagnosis, labels_bc)<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>col_0    B    M  All
row_0               
-1      42  126  168
0        0   54   54
1      315   32  347
All    357  212  569

ARI (excluindo ruído, n=401): 0.644
ARI (todos, ruído como rótulo próprio): 0.493</code></pre>
</div>
</div>
<p>O HDBSCAN encontrou dois clusters e marcou <span class="math inline">\(168\)</span> dos <span class="math inline">\(569\)</span> pacientes (<span class="math inline">\(\approx 29{,}5\%\)</span>) como ruído. O <strong>Cluster 0</strong> (<span class="math inline">\(54\)</span> pacientes) é <strong>puro</strong>: os <span class="math inline">\(54\)</span> são malignos, zero benignos — uma “montanha” densa e homogênea de tumores malignos, exatamente o tipo de estrutura que a definição do Bloco 3 promete encontrar sem nunca ter visto o rótulo. O <strong>Cluster 1</strong> (<span class="math inline">\(347\)</span> pacientes) é majoritariamente benigno (<span class="math inline">\(315\)</span> benignos, <span class="math inline">\(32\)</span> malignos — <span class="math inline">\(\approx 90{,}8\%\)</span> de pureza benigna), mas com contaminação real. Dos <span class="math inline">\(212\)</span> pacientes malignos no total, a maioria (<span class="math inline">\(126\)</span>, <span class="math inline">\(\approx 59{,}4\%\)</span>) cai no ruído — não em nenhum dos dois clusters — o que é, honestamente, o resultado esperado: tumores malignos variam muito mais em apresentação do que tumores benignos (a doença tem múltiplos subtipos e estágios), então só uma fração forma uma “montanha” densa o bastante para sobreviver como cluster de alta persistência nesses dois atributos; boa parte fica dispersa no “vale” entre o núcleo maligno denso e a grande massa benigna.</p>
<p>O ARI (índice de Rand ajustado, que mede concordância entre duas partições corrigindo por acaso) é <span class="math inline">\(0{,}644\)</span> olhando só os pacientes que o HDBSCAN classificou com confiança (excluindo ruído) — uma concordância forte — e <span class="math inline">\(0{,}493\)</span> olhando todos os pacientes, tratando o ruído como uma terceira categoria. Nenhum dos dois número é <span class="math inline">\(1{,}0\)</span>: o HDBSCAN não é um classificador, e não teve acesso ao rótulo — o fato de encontrar <em>qualquer</em> estrutura que se alinha tão bem ao diagnóstico real, começando de dois atributos e nenhuma supervisão, é o resultado central deste bloco.</p>
</section>
<section id="pergunta-5" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="pergunta-5"><span class="header-section-number">6.2</span> Pergunta</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Se <code>min_cluster_size</code> fosse reduzido de 15 para 2 no exemplo do Breast Cancer Wisconsin, o que aconteceria com a fração de pacientes marcados como ruído, e por quê?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: pense no que <code>min_cluster_size</code> está, na prática, impedindo de virar cluster.</p>
<ul>
<li>□ Reduzir <code>min_cluster_size</code> para 2 tende a diminuir a fração de ruído, porque ramos muito pequenos da árvore condensada (antes descartados como “perda” do cluster-pai) passam a contar como clusters válidos por si mesmos.</li>
<li>□ <code>min_cluster_size=2</code> reintroduz, na prática, uma versão do problema de encadeamento (<em>chaining</em>) da ligação simples pura — uma cadeia fina de 2-3 pontos já basta para ser aceita como cluster próprio.</li>
<li>□ O valor de <code>min_cluster_size</code> não afeta a fração de ruído — ele só afeta quantos clusters distintos são extraídos, mantendo o total de pontos “ruidosos” constante.</li>
<li>□ Escolher <code>min_cluster_size</code> continua sendo, mesmo no HDBSCAN, uma decisão de escala imposta pelo usuário — a persistência decide <em>quais</em> ramos sobrevivem, mas não decide, por si só, o tamanho mínimo que conta como ramo.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="síntese-o-que-o-hdbscan-compra-e-o-que-ainda-custa" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Síntese: o Que o HDBSCAN Compra, e o Que Ainda Custa</h1>
<p>Recapitulando de ponta a ponta: (1) <span class="math inline">\(\mathrm{core}_K(\mathbf{x})\)</span>, o mesmo <span class="math inline">\(d_K(\mathbf{x})\)</span> da Aula 2, mede densidade local sem forma paramétrica; (2) <span class="math inline">\(d_{\mathrm{mreach}}\)</span> transforma isso numa distância de grafo que “acalma” pontos isolados; (3) a MST desse grafo comprime toda a hierarquia de clustering por ligação simples numa única árvore; (4) condensar essa árvore e medir persistência por excesso de massa extrai os clusters mais estáveis, em alturas possivelmente diferentes, sem exigir um único corte global.</p>
<p><strong>O que isso compra</strong>, em relação ao K-means da Abertura: nenhuma suposição de convexidade (as duas luas, os dois anéis, resolvidos de ponta a ponta); nenhuma escolha obrigatória do número de clusters <span class="math inline">\(K\)</span>; pontos genuinamente atípicos podem ser marcados como ruído em vez de forçados a pertencer a algum cluster.</p>
<p><strong>O que ainda custa.</strong> Dois preços, nenhum deles anunciado como “gratuito” antes: primeiro, <code>min_cluster_size</code> (e, em geral, <code>min_samples</code>, que desempenha o papel de <span class="math inline">\(K\)</span> no <em>core distance</em>) ainda é uma escolha de escala — o Bloco 6 mostrou, na Pergunta, que reduzir esse parâmetro reintroduz uma versão do encadeamento. Segundo — e este é o fio que conecta diretamente de volta à Aula 2 — o HDBSCAN herda a mesma maldição da dimensionalidade que <span class="math inline">\(d_K(\mathbf{x})\)</span> já sofria como estimador de densidade, porque <span class="math inline">\(\mathrm{core}_K\)</span> é literalmente o mesmo número. Um teste direto, nos <span class="math inline">\(30\)</span> atributos originais (todos padronizados) do Breast Cancer Wisconsin, torna isso concreto:</p>
<div id="a6b6e2e1" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> mcs <span class="kw">in</span> [<span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">15</span>, <span class="dv">20</span>, <span class="dv">30</span>]:</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    hdb_full <span class="op">=</span> HDBSCAN(min_cluster_size<span class="op">=</span>mcs).fit(X_std)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    frac_ruido <span class="op">=</span> (hdb_full.labels_ <span class="op">==</span> <span class="op">-</span><span class="dv">1</span>).mean()</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    n_clusters <span class="op">=</span> <span class="bu">len</span>(<span class="bu">set</span>(hdb_full.labels_) <span class="op">-</span> {<span class="op">-</span><span class="dv">1</span>})</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"min_cluster_size=</span><span class="sc">{</span>mcs<span class="sc">:3d}</span><span class="ss">  →  </span><span class="sc">{</span>n_clusters<span class="sc">}</span><span class="ss"> cluster(s), "</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"</span><span class="sc">{</span>frac_ruido<span class="sc">:.1%}</span><span class="ss"> dos pacientes como ruído"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>min_cluster_size=  5  →  2 cluster(s), 59.2% dos pacientes como ruído
min_cluster_size= 10  →  0 cluster(s), 100.0% dos pacientes como ruído
min_cluster_size= 15  →  0 cluster(s), 100.0% dos pacientes como ruído
min_cluster_size= 20  →  0 cluster(s), 100.0% dos pacientes como ruído
min_cluster_size= 30  →  0 cluster(s), 100.0% dos pacientes como ruído</code></pre>
</div>
</div>
<p>Nos <span class="math inline">\(30\)</span> atributos originais, padronizados, sem nenhuma redução de dimensionalidade: com <code>min_cluster_size=5</code> (já um valor agressivo, pequeno), <span class="math inline">\(\approx 59{,}2\%\)</span> dos pacientes já viram ruído; a partir de <code>min_cluster_size=10</code>, <strong><span class="math inline">\(100\%\)</span></strong> dos <span class="math inline">\(569\)</span> pacientes são marcados como ruído — nenhum cluster sobrevive. Comparado aos dois atributos do Bloco 6, onde <span class="math inline">\(70{,}5\%\)</span> dos pacientes ficaram em algum cluster, essa é uma queda drástica de estrutura encontrada, só por aumentar de <span class="math inline">\(2\)</span> para <span class="math inline">\(30\)</span> dimensões (mesmos pacientes, mesmos dados). O mecanismo é exatamente o da Aula 2: em alta dimensão, distâncias perdem poder de discriminação, <span class="math inline">\(d_K(\mathbf{x})\)</span> deixa de refletir bem “densidade local” no sentido intuitivo, <span class="math inline">\(d_{\mathrm{mreach}}\)</span> (que depende de <span class="math inline">\(d_K\)</span> e de <span class="math inline">\(d\)</span> bruta) herda o problema, e a árvore condensada não encontra ramo nenhum estável o bastante para sobreviver como cluster — tudo vira “ruído” porque, em alta dimensão, quase tudo parece igualmente distante de quase tudo.</p>
<section id="pergunta-6" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="pergunta-6"><span class="header-section-number">7.1</span> Pergunta</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Um colega sugere “resolver” a queda de estrutura em 30 dimensões aumentando <code>min_cluster_size</code> até encontrar pelo menos um cluster de novo. Isso resolveria o problema de fundo?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: pense se <code>min_cluster_size</code> grande está atacando a causa (distâncias perdendo poder discriminativo) ou só mudando o limiar de quantos pontos “contam”.</p>
<ul>
<li>□ Aumentar <code>min_cluster_size</code> pode, sim, eventualmente produzir algum cluster de novo — mas isso resolve o sintoma (nenhum cluster aparecia) sem resolver a causa (as distâncias em 30D perderam poder discriminativo).</li>
<li>□ Se um cluster aparecer com <code>min_cluster_size</code> bem alto em 30D, ele é necessariamente tão confiável estatisticamente quanto o cluster puro de <span class="math inline">\(54\)</span> pacientes encontrado com <span class="math inline">\(2\)</span> atributos no Bloco 6.</li>
<li>□ A solução mais direta para a maldição, sugerida já na Aula 2 e reaproveitável aqui, é reduzir a dimensionalidade (ex.: escolher um subconjunto de atributos informativos, ou usar componentes principais) antes de rodar HDBSCAN, não só ajustar <code>min_cluster_size</code>.</li>
<li>□ Esse problema é exclusivo do HDBSCAN — um K-means aplicado aos mesmos 30 atributos padronizados não sofreria de nenhuma versão análoga da maldição da dimensionalidade.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="fechamento-e-ponte-para-a-aula-4" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Fechamento e Ponte para a Aula 4</h1>
<p>Retomando as quatro perguntas da Abertura, uma frase cada:</p>
<ol type="1">
<li><strong>O que deveria significar “cluster”?</strong> Uma componente conexa de uma região de alta densidade — não uma bola em torno de um centróide.</li>
<li><strong>Como construir isso sem escolher <span class="math inline">\(K\)</span> a priori?</strong> Via <span class="math inline">\(d_{\mathrm{mreach}}\)</span> e a MST, sem nenhum parâmetro de forma, só uma escala local (<span class="math inline">\(K\)</span> do <em>core distance</em>).</li>
<li><strong>Que estrutura de grafo captura toda a hierarquia de uma vez?</strong> A MST — cortar suas <span class="math inline">\(k-1\)</span> arestas mais pesadas reproduz ligação simples para qualquer <span class="math inline">\(k\)</span>, verificado no exemplo do Bloco 5.</li>
<li><strong>Como decidir quais clusters são reais?</strong> Persistência por excesso de massa na árvore condensada, não um único <span class="math inline">\(\lambda\)</span> escolhido à mão.</li>
</ol>
<p><strong>O que fica em aberto.</strong> O HDBSCAN entrega uma partição <strong>rígida</strong>: cada paciente pertence a exatamente um cluster, ou é ruído — uma decisão binária, sem meio-termo. Isso é honesto quando os clusters são genuinamente bem separados (como as duas luas), mas força uma escolha artificial quando dois clusters genuinamente se sobrepõem — um paciente na fronteira entre o núcleo maligno denso e a massa benigna do Bloco 6 não é “um pouco maligno, um pouco benigno”: ele é forçado a ruído ou a um dos dois lados.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Ponte para a Aula 4
</div>
</div>
<div class="callout-body-container callout-body">
<p>A Aula 4 introduz <strong>Modelos de Mistura Gaussiana</strong> (<em>Gaussian Mixture Models</em>) e o algoritmo <strong>EM</strong> (<em>Expectation-Maximization</em>) — a mesma pergunta de agrupar pontos, mas relaxando a atribuição rígida para uma atribuição <strong>probabilística</strong>: cada paciente recebe uma probabilidade de pertencer a cada cluster, não um rótulo único. Útil exatamente onde o HDBSCAN força uma escolha: fronteiras genuinamente ambíguas entre populações que se sobrepõem.</p>
</div>
</div>
<p>O ESL (p.&nbsp;507) já havia citado essa rota como um dos três paradigmas — “modelagem por mistura” — ao lado do combinatório (K-means, Bloco 1) e do “mode seeking” (esta aula inteira). A Aula 4 fecha o trio.</p>
<section id="pergunta-7" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="pergunta-7"><span class="header-section-number">8.1</span> Pergunta</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Um hospital precisa decidir se atribuição rígida (HDBSCAN) ou probabilística (GMM/EM, Aula 4) se ajusta melhor a uma triagem entre dois subtipos de tumor cujos biomarcadores parecem se sobrepor. O que deveria pesar mais nessa escolha?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: pense se a “ambiguidade” observada nos dados é evidência de um vale de densidade genuíno entre os subtipos, ou de uma sobreposição real e contínua entre eles.</p>
<ul>
<li>□ Se os dois subtipos realmente se sobrepõem numa faixa contínua de biomarcadores, sem um vale de densidade genuíno entre eles, uma atribuição probabilística tende a refletir melhor essa ambiguidade do que forçar cada paciente a um rótulo único.</li>
<li>□ Como o HDBSCAN já produz uma força de pertencimento por ponto dentro do cluster ao qual foi atribuído, ele já é, na prática, equivalente a uma atribuição probabilística completa como a do GMM/EM, que distribui probabilidade entre <em>todos</em> os clusters.</li>
<li>□ No limite em que os dois subtipos verdadeiros são separados por um vale de densidade exatamente zero, a atribuição probabilística do GMM/EM converge para probabilidades próximas de <span class="math inline">\(0\)</span> ou <span class="math inline">\(1\)</span> — coincidindo, na prática, com a atribuição rígida do HDBSCAN.</li>
<li>□ Se a escolha entre partição rígida e probabilística fosse só uma questão de conveniência computacional, sem nenhuma relação com a estrutura real dos dados, então HDBSCAN e GMM deveriam sempre produzir partições idênticas quando aplicados ao mesmo dataset.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="exercícios" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Exercícios</h1>
<section id="questões-discursivas" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="questões-discursivas"><span class="header-section-number">9.1</span> Questões discursivas</h2>
<ol type="1">
<li><p>O Bloco 1 mostrou que a tesselação de Voronoi do K-means é sempre convexa, e por isso falha nas duas luas e nos dois anéis. Explique, em termos da definição de cluster como componente conexa de um conjunto de nível <span class="math inline">\(L_\lambda\)</span> (Bloco 3), por que essa definição <strong>não</strong> herda a mesma limitação — e dê um exemplo (pode ser diferente dos vistos na aula) de uma forma de cluster que nenhum método baseado em centróide conseguiria capturar, mas que uma componente conexa de densidade capturaria sem dificuldade.</p></li>
<li><p>O Bloco 4 definiu <span class="math inline">\(d_{\mathrm{mreach}}(a,b) = \max(\mathrm{core}_K(a),
\mathrm{core}_K(b), d(a,b))\)</span>. Explique por que essa distância nunca é menor que a distância bruta <span class="math inline">\(d(a,b)\)</span>, e construa um argumento (sem precisar de números) de por que essa propriedade é exatamente o que se quer para “acalmar” um ponto isolado sem alterar as distâncias dentro de uma região já densa.</p></li>
<li><p>O Bloco 6 encontrou, no Breast Cancer Wisconsin, um cluster de <span class="math inline">\(54\)</span> pacientes <span class="math inline">\(100\%\)</span> malignos e um cluster de <span class="math inline">\(347\)</span> pacientes <span class="math inline">\(\approx 90{,}8\%\)</span> benignos, com <span class="math inline">\(168\)</span> pacientes (<span class="math inline">\(\approx 29{,}5\%\)</span>) marcados como ruído — e, dos <span class="math inline">\(212\)</span> pacientes malignos totais, <span class="math inline">\(126\)</span> (<span class="math inline">\(\approx 59{,}4\%\)</span>) caíram nesse ruído. Usando o resultado do Bloco 7 (a queda de estrutura ao ir de <span class="math inline">\(2\)</span> para <span class="math inline">\(30\)</span> atributos), discuta se aumentar o número de atributos usados na visualização do Bloco 6 (por exemplo, de <span class="math inline">\(2\)</span> para <span class="math inline">\(10\)</span>) tenderia a diminuir ou aumentar a fração de pacientes malignos capturados no cluster puro — e por quê.</p></li>
</ol>
</section>
<section id="questões-de-verdadeirofalso" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="questões-de-verdadeirofalso"><span class="header-section-number">9.2</span> Questões de Verdadeiro/Falso</h2>
<p>Cada bloco de 4 itens trata do mesmo tema. A questão só é considerada correta se todos os 4 itens forem julgados corretamente (deixar em branco tem penalidade de 20% da nota da questão).</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Cluster como componente conexa vs.&nbsp;distância a centróide
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>□ Se um cluster verdadeiro tem formato de “U” (uma curva fechada quase se tocando nas duas pontas), um K-means com <span class="math inline">\(K\)</span> grande o bastante eventualmente recupera esse formato exato como um único cluster, só fragmentando-o internamente em pequenas células convexas que, somadas, aproximam bem o “U”.</li>
<li>□ A convexidade de cada célula de Voronoi é uma consequência necessária de usar distância euclidiana ao centro mais próximo como regra de atribuição — não uma escolha adicional independente do K-means.</li>
<li>□ Um cluster definido como componente conexa de um conjunto de nível <span class="math inline">\(L_\lambda\)</span> pode, em princípio, ter qualquer formato geométrico, inclusive não-convexo, desde que exista um caminho contínuo dentro de <span class="math inline">\(L_\lambda\)</span> ligando quaisquer dois de seus pontos.</li>
<li>□ Se dois pontos pertencem à mesma componente conexa de <span class="math inline">\(L_\lambda\)</span>, isso implica que a distância euclidiana direta entre eles é menor do que a distância de qualquer um dos dois a pontos fora dessa componente.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Conjuntos de nível e a hierarquia indexada por <span class="math inline">\(\lambda\)</span>
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>□ Decrescer <span class="math inline">\(\lambda\)</span> de um valor alto para um valor baixo pode dividir uma componente conexa de <span class="math inline">\(L_\lambda\)</span> em duas, além de poder fundir componentes existentes.</li>
<li>□ Se duas regiões de alta densidade são separadas por um vale de densidade exatamente zero em pelo menos um ponto do caminho entre elas, então, para qualquer <span class="math inline">\(\lambda&gt;0\)</span>, elas nunca aparecem como uma única componente conexa de <span class="math inline">\(L_\lambda\)</span>.</li>
<li>□ A definição de cluster via <span class="math inline">\(L_\lambda\)</span> dispensa completamente a necessidade de qualquer parâmetro de escala, ao contrário do K-means (que exige <span class="math inline">\(K\)</span>).</li>
<li>□ ESL (p.&nbsp;507) descreve “buscadores de moda” (<em>mode seekers</em>) como um paradigma que estima diretamente as modas da densidade e atribui cada observação à moda mais próxima — um paradigma distinto tanto do combinatório quanto da modelagem por mistura.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Core distance: o mesmo <span class="math inline">\(d_K\)</span> da Aula 2, novo uso
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>□ <span class="math inline">\(\mathrm{core}_K(\mathbf{x})\)</span> pequeno continua significando região densa, exatamente como <span class="math inline">\(d_K(\mathbf{x})\)</span> significava na Aula 2 — a fórmula não mudou, só o papel que a quantidade desempenha (estimador de densidade vs.&nbsp;peso de aresta).</li>
<li>□ Se <span class="math inline">\(K\)</span> for aumentado (por exemplo, de <span class="math inline">\(5\)</span> para <span class="math inline">\(50\)</span>), o valor de <span class="math inline">\(\mathrm{core}_K(\mathbf{x})\)</span> para um ponto numa região densa tende a variar relativamente menos do que o mesmo aumento de <span class="math inline">\(K\)</span> produziria para um ponto numa região rara — a mesma propriedade discutida na Aula 2 para <span class="math inline">\(d_K\)</span>.</li>
<li>□ Dois pontos com o mesmo valor de <span class="math inline">\(\mathrm{core}_K\)</span>, para o mesmo <span class="math inline">\(K\)</span>, necessariamente moram na mesma região do espaço de atributos.</li>
<li>□ <span class="math inline">\(\mathrm{core}_K(\mathbf{x})\)</span>, como usado nesta aula, não depende em nada da escolha de <span class="math inline">\(K\)</span> — é uma propriedade fixa de cada ponto, independente de qualquer parâmetro.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Distância de alcançabilidade mútua
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>□ <span class="math inline">\(d_{\mathrm{mreach}}(a,b) \ge d(a,b)\)</span> vale sempre, para quaisquer <span class="math inline">\(a,b\)</span> e qualquer <span class="math inline">\(K\)</span> — a alcançabilidade mútua nunca aproxima dois pontos além de sua distância bruta.</li>
<li>□ Se <span class="math inline">\(a\)</span> e <span class="math inline">\(b\)</span> estão ambos em regiões muito densas (ambos os <em>core distances</em> pequenos), <span class="math inline">\(d_{\mathrm{mreach}}(a,b)\)</span> é, em geral, determinado pela distância bruta <span class="math inline">\(d(a,b)\)</span>, não pelos núcleos.</li>
<li>□ Num cenário em que <span class="math inline">\(a\)</span> está numa região densa e <span class="math inline">\(b\)</span> está isolado bem longe de qualquer vizinho, <span class="math inline">\(d_{\mathrm{mreach}}(a,b)\)</span> é necessariamente igual a <span class="math inline">\(d(a,b)\)</span>, porque o núcleo de <span class="math inline">\(a\)</span> (pequeno) domina o máximo.</li>
<li>□ Trocar a distância bruta <span class="math inline">\(d\)</span> por <span class="math inline">\(d_{\mathrm{mreach}}\)</span> em todo o grafo pode mudar quais arestas pertencem à MST, comparado à MST construída sobre a distância bruta original.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>MST e a equivalência com ligação simples
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>□ Para um conjunto de <span class="math inline">\(N\)</span> pontos, a MST sobre a matriz de distâncias brutas tem sempre exatamente <span class="math inline">\(N-1\)</span> arestas, independente de quantos clusters “verdadeiros” existam nos dados.</li>
<li>□ Cortar as <span class="math inline">\(k-1\)</span> arestas mais pesadas da MST produz sempre uma partição em exatamente <span class="math inline">\(k\)</span> componentes conexas, para qualquer <span class="math inline">\(1\le k\le N\)</span>.</li>
<li>□ Se a MST inteira for reconstruída usando <span class="math inline">\(d_{\mathrm{mreach}}\)</span> em vez da distância bruta, o resultado de “cortar as <span class="math inline">\(k-1\)</span> arestas mais pesadas” ainda corresponde ao clustering de ligação simples — mas agora sobre as distâncias de alcançabilidade mútua, não sobre as distâncias brutas originais.</li>
<li>□ No exemplo numérico do Bloco 5 (7 pontos, grupos A, B e o ponto isolado 6), o fato de A e B se fundirem antes de 6 se juntar a qualquer um deles (no corte <span class="math inline">\(k=2\)</span>) é uma inconsistência do algoritmo de ligação simples, não uma consequência esperada da definição <span class="math inline">\(d_{SL}(G,H)=\min_{i\in G,i'\in H}d_{ii'}\)</span>.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>O defeito do encadeamento (<em>chaining</em>)
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>□ O encadeamento citado do ESL ocorre porque a ligação simples define a proximidade entre dois grupos pelo par mais próximo entre eles, ignorando todos os outros pares — uma única cadeia de pontos intermediários basta para acionar uma fusão.</li>
<li>□ Ligação completa (<em>complete linkage</em>, que usa a distância máxima entre pares, não a mínima) sofreria exatamente do mesmo defeito de encadeamento que a ligação simples, pela mesma razão matemática.</li>
<li>□ Um único ponto de ruído inserido bem no meio do vale entre dois clusters genuinamente distintos pode, por si só, fazer a ligação simples fundir os dois num nível de dissimilaridade artificialmente baixo.</li>
<li>□ <span class="math inline">\(d_{\mathrm{mreach}}\)</span> reduz a chance de encadeamento causado por pontos isolados de baixa densidade, mas não elimina, por si só, todo encadeamento possível — daí a necessidade adicional de <code>min_cluster_size</code> no HDBSCAN.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Árvore condensada
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>□ Na árvore condensada, um ramo com menos que <code>min_cluster_size</code> pontos, ao se separar do seu ramo-pai, é tratado como “pontos perdidos” do pai, não como um cluster novo — mesmo que, na hierarquia completa (não condensada), esse ramo aparecesse como uma divisão legítima.</li>
<li>□ Condensar a árvore usando <code>min_cluster_size</code> elimina completamente a necessidade de qualquer outro parâmetro de escala no HDBSCAN, já que a persistência decide tudo o mais automaticamente.</li>
<li>□ Aumentar <code>min_cluster_size</code> tende a reduzir o número de ramos que sobrevivem como clusters candidatos na árvore condensada, comparado a um <code>min_cluster_size</code> menor sobre a mesma hierarquia completa.</li>
<li>□ A árvore condensada de um conjunto de dados sem nenhuma estrutura de cluster real (por exemplo, uma única Gaussiana multivariada bem comportada) pode, ainda assim, ter ramos que sobrevivem ao condensamento, dependendo de <code>min_cluster_size</code> escolhido.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Persistência por excesso de massa
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>□ A persistência de um cluster candidato é definida somando, para cada ponto do ramo, o intervalo de <span class="math inline">\(\lambda\)</span> (ou de <span class="math inline">\(1/d_{\mathrm{mreach}}\)</span>) em que esse ponto pertenceu a esse cluster específico antes de ser absorvido pelo pai ou virar ruído.</li>
<li>□ Um cluster que aparece por uma faixa muito curta de <span class="math inline">\(\lambda\)</span> antes de se fundir com outro tem, em geral, persistência mais baixa do que um cluster de tamanho comparável que sobrevive por uma faixa longa de <span class="math inline">\(\lambda\)</span>.</li>
<li>□ A extração final por persistência, em cada ramificação da árvore condensada, escolhe sempre “dividir nos dois filhos” em vez de “manter o pai inteiro”, porque dois clusters específicos têm, por definição, mais persistência somada do que um cluster genérico.</li>
<li>□ Se dois clusters candidatos tivessem exatamente o mesmo tamanho (mesmo número de pontos), eles teriam, necessariamente, a mesma persistência, independente de quanto tempo cada um sobreviveu na hierarquia.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>O resultado no Breast Cancer Wisconsin
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>□ O cluster de <span class="math inline">\(54\)</span> pacientes encontrado no Bloco 6, sendo <span class="math inline">\(100\%\)</span> malignos, é uma evidência de que HDBSCAN funcionou como um classificador treinado no rótulo <code>diagnosis</code> — o rótulo foi usado apenas para conferir o resultado depois, não durante o clustering.</li>
<li>□ O fato de <span class="math inline">\(126\)</span> dos <span class="math inline">\(212\)</span> pacientes malignos totais caírem em ruído (não em nenhum dos dois clusters) é consistente com a ideia de que tumores malignos variam mais em apresentação clínica do que tumores benignos, formando uma “montanha” de densidade menos coesa nesses dois atributos.</li>
<li>□ O ARI de <span class="math inline">\(0{,}644\)</span> (excluindo ruído) sendo maior que o ARI de <span class="math inline">\(0{,}493\)</span> (incluindo ruído como rótulo) é esperado, porque excluir os pontos mais ambíguos (o ruído) da comparação tende a aumentar a concordância medida nos pontos restantes.</li>
<li>□ Se o HDBSCAN tivesse encontrado só ruído (nenhum cluster) nesses dois atributos, o ARI (incluindo ruído como rótulo) seria necessariamente próximo de <span class="math inline">\(1\)</span>, já que todos os pontos receberiam o mesmo tratamento.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Hiperparâmetros: <code>min_cluster_size</code> e <code>min_samples</code>
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>□ Trocar a escolha de um valor de <span class="math inline">\(\lambda\)</span> global (nos métodos de corte único do Bloco 3) por uma escolha de <code>min_cluster_size</code> no HDBSCAN elimina, por completo, qualquer decisão de escala que o usuário precise tomar.</li>
<li>□ Reduzir <code>min_cluster_size</code> para um valor muito pequeno (como <span class="math inline">\(2\)</span>) tende a reintroduzir uma versão do problema de encadeamento discutido para a ligação simples pura.</li>
<li>□ <code>min_samples</code> desempenha, no HDBSCAN, um papel análogo ao de <span class="math inline">\(K\)</span> no <em>core distance</em> <span class="math inline">\(\mathrm{core}_K(\mathbf{x})\)</span> — ambos controlam quantos vizinhos definem a escala local de densidade.</li>
<li>□ Um cluster que só aparece ao forçar <code>min_cluster_size</code> bem mais alto do que o valor originalmente usado é, por esse único motivo, necessariamente tão confiável estatisticamente quanto um cluster que aparece de forma estável numa faixa ampla de valores testados.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Maldição da dimensionalidade herdada da Aula 2
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>□ A queda de <span class="math inline">\(70{,}5\%\)</span> dos pacientes em algum cluster (com <span class="math inline">\(2\)</span> atributos) para <span class="math inline">\(100\%\)</span> de ruído (com <span class="math inline">\(30\)</span> atributos, <code>min_cluster_size\ge 10</code>) ocorre porque <span class="math inline">\(\mathrm{core}_K\)</span> é literalmente o mesmo <span class="math inline">\(d_K(\mathbf{x})\)</span> da Aula 2 — herda o mesmo mecanismo pelo qual distâncias perdem poder discriminativo em alta dimensão.</li>
<li>□ Aumentar <code>min_cluster_size</code> até encontrar algum cluster de novo em 30 dimensões resolve a causa raiz da maldição da dimensionalidade para esse dataset, não só o sintoma de “nenhum cluster apareceu”.</li>
<li>□ Um K-means aplicado aos mesmos <span class="math inline">\(30\)</span> atributos padronizados está, em algum grau, imune à maldição da dimensionalidade, porque não usa nenhum estimador de densidade baseado em vizinhos como <span class="math inline">\(\mathrm{core}_K\)</span>.</li>
<li>□ Reduzir a dimensionalidade (por exemplo, escolher um subconjunto pequeno de atributos informativos, como feito no Bloco 6) antes de rodar HDBSCAN ataca a causa do problema, não só o sintoma.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Partição rígida vs.&nbsp;probabilística — ponte para a Aula 4
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>□ A saída do HDBSCAN atribui cada ponto a exatamente um cluster, ou a ruído — nunca uma probabilidade de pertencimento a mais de um cluster ao mesmo tempo.</li>
<li>□ Um paciente exatamente na fronteira entre o núcleo maligno denso e a massa benigna do Bloco 6, sob uma atribuição probabilística (Aula 4), receberia tipicamente uma probabilidade bem definida e próxima de <span class="math inline">\(1\)</span> para um único cluster, e próxima de <span class="math inline">\(0\)</span> para o outro — igual ao HDBSCAN, sem diferença prática nesse caso.</li>
<li>□ O ESL (p.&nbsp;507) cita “modelagem por mistura” como um paradigma de clustering distinto tanto do combinatório (K-means) quanto do “mode seeking” (HDBSCAN) — os três paradigmas citados ao longo desta aula.</li>
<li>□ A escolha entre uma partição rígida (HDBSCAN) e uma probabilística (Aula 4) é, em essência, uma escolha sobre o quanto se acredita que os clusters verdadeiros se sobrepõem genuinamente, não uma escolha puramente de conveniência computacional.</li>
</ul>
</div>
</div>
</section>
<section id="aviso" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="aviso"><span class="header-section-number">9.3</span> Aviso</h2>
<p>As questões de Verdadeiro/Falso e discursivas ficam sem solução neste arquivo — são para resolução autônoma do aluno, fora do horário de aula.</p>


</section>
</section>

</main> <!-- /main -->
<!-- Parcial estático, igual em toda aula (não é mais gerado por script —
     ver histórico do teaching/generate_lesson_nav.py, removido). Só
     carrega o script que transforma o sumário nativo do Quarto (#TOC,
     "Nesta página") no painel de acordeão "Nesta aula". -->
<script src="../../toc-accordion.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© 2026 Marcos M. Raimundo</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>