<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-BR" xml:lang="pt-BR"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Prof.&nbsp;Marcos Medeiros Raimundo">

<title>Aula 3: Projeções Ortogonais e Subespaços – Marcos M. Raimundo</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../more.png" rel="icon" type="image/png">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-de6b2afc8591517e0c1f78da07193c80.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Marcos M. Raimundo</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Procurar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Alternar de navegação" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../teaching/index.html"> 
<span class="menu-text">Teaching</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../projects/index.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../publications/index.html"> 
<span class="menu-text">Publications</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../people/index.html"> 
<span class="menu-text">People</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../contact.html"> 
<span class="menu-text">Contact</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/marcosmrai"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://scholar.google.com.br/citations?user=ibe0jfQAAAAJ&amp;hl=pt-BR"> <i class="bi bi-mortarboard-fill" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Nesta página</h2>
   
  <ul>
  <li><a href="#o-problema-que-a-aula-2-deixou-em-aberto" id="toc-o-problema-que-a-aula-2-deixou-em-aberto" class="nav-link active" data-scroll-target="#o-problema-que-a-aula-2-deixou-em-aberto"><span class="header-section-number">1</span> O Problema Que a Aula 2 Deixou em Aberto</a>
  <ul class="collapse">
  <li><a href="#revisão-rápida-onde-a-aula-2-parou" id="toc-revisão-rápida-onde-a-aula-2-parou" class="nav-link" data-scroll-target="#revisão-rápida-onde-a-aula-2-parou"><span class="header-section-number">1.1</span> Revisão Rápida: Onde a Aula 2 Parou</a></li>
  <li><a href="#organizador-prévio-de-sem-solução-para-melhor-aproximação" id="toc-organizador-prévio-de-sem-solução-para-melhor-aproximação" class="nav-link" data-scroll-target="#organizador-prévio-de-sem-solução-para-melhor-aproximação"><span class="header-section-number">1.2</span> Organizador Prévio: De “Sem Solução” Para “Melhor Aproximação”</a></li>
  <li><a href="#roteiro-da-aula" id="toc-roteiro-da-aula" class="nav-link" data-scroll-target="#roteiro-da-aula"><span class="header-section-number">1.3</span> Roteiro da Aula</a></li>
  <li><a href="#problema-motivador" id="toc-problema-motivador" class="nav-link" data-scroll-target="#problema-motivador"><span class="header-section-number">1.4</span> Problema Motivador</a></li>
  </ul></li>
  <li><a href="#intuição-a-sombra-no-chão-não-no-ar" id="toc-intuição-a-sombra-no-chão-não-no-ar" class="nav-link" data-scroll-target="#intuição-a-sombra-no-chão-não-no-ar"><span class="header-section-number">2</span> Intuição: A Sombra no Chão, Não no Ar</a>
  <ul class="collapse">
  <li><a href="#a-ideia-antes-da-álgebra" id="toc-a-ideia-antes-da-álgebra" class="nav-link" data-scroll-target="#a-ideia-antes-da-álgebra"><span class="header-section-number">2.1</span> A Ideia Antes da Álgebra</a></li>
  </ul></li>
  <li><a href="#subespaços-e-complemento-ortogonal" id="toc-subespaços-e-complemento-ortogonal" class="nav-link" data-scroll-target="#subespaços-e-complemento-ortogonal"><span class="header-section-number">3</span> Subespaços e Complemento Ortogonal</a>
  <ul class="collapse">
  <li><a href="#recapitulando-subespaço-e-espaço-coluna" id="toc-recapitulando-subespaço-e-espaço-coluna" class="nav-link" data-scroll-target="#recapitulando-subespaço-e-espaço-coluna"><span class="header-section-number">3.1</span> Recapitulando: Subespaço e Espaço-Coluna</a></li>
  <li><a href="#o-complemento-ortogonal" id="toc-o-complemento-ortogonal" class="nav-link" data-scroll-target="#o-complemento-ortogonal"><span class="header-section-number">3.2</span> O Complemento Ortogonal</a></li>
  </ul></li>
  <li><a href="#o-teorema-da-projeção-premissas-e-passo-a-passo" id="toc-o-teorema-da-projeção-premissas-e-passo-a-passo" class="nav-link" data-scroll-target="#o-teorema-da-projeção-premissas-e-passo-a-passo"><span class="header-section-number">4</span> O Teorema da Projeção: Premissas e Passo a Passo</a>
  <ul class="collapse">
  <li><a href="#enunciando-o-problema-com-precisão" id="toc-enunciando-o-problema-com-precisão" class="nav-link" data-scroll-target="#enunciando-o-problema-com-precisão"><span class="header-section-number">4.1</span> Enunciando o Problema com Precisão</a></li>
  <li><a href="#passo-i-mais-próximo-equivale-a-ortogonal" id="toc-passo-i-mais-próximo-equivale-a-ortogonal" class="nav-link" data-scroll-target="#passo-i-mais-próximo-equivale-a-ortogonal"><span class="header-section-number">4.2</span> Passo (i): “Mais Próximo” Equivale a “Ortogonal”</a></li>
  <li><a href="#passo-ii-escrevendo-hatmathbfy-em-termos-de-x" id="toc-passo-ii-escrevendo-hatmathbfy-em-termos-de-x" class="nav-link" data-scroll-target="#passo-ii-escrevendo-hatmathbfy-em-termos-de-x"><span class="header-section-number">4.3</span> Passo (ii): Escrevendo <span class="math inline">\(\hat{\mathbf{y}}\)</span> em Termos de <span class="math inline">\(X\)</span></a></li>
  <li><a href="#passo-iii-ortogonal-a-cada-coluna-de-x" id="toc-passo-iii-ortogonal-a-cada-coluna-de-x" class="nav-link" data-scroll-target="#passo-iii-ortogonal-a-cada-coluna-de-x"><span class="header-section-number">4.4</span> Passo (iii): Ortogonal a <em>Cada Coluna</em> de <span class="math inline">\(X\)</span></a></li>
  <li><a href="#passo-iv-isolando-hatmathbfw-as-equações-normais" id="toc-passo-iv-isolando-hatmathbfw-as-equações-normais" class="nav-link" data-scroll-target="#passo-iv-isolando-hatmathbfw-as-equações-normais"><span class="header-section-number">4.5</span> Passo (iv): Isolando <span class="math inline">\(\hat{\mathbf{w}}\)</span> — as Equações Normais</a></li>
  </ul></li>
  <li><a href="#aplicação-e-verificação-no-dado-real" id="toc-aplicação-e-verificação-no-dado-real" class="nav-link" data-scroll-target="#aplicação-e-verificação-no-dado-real"><span class="header-section-number">5</span> Aplicação e Verificação no Dado Real</a>
  <ul class="collapse">
  <li><a href="#calculando-hatmathbfw-de-verdade" id="toc-calculando-hatmathbfw-de-verdade" class="nav-link" data-scroll-target="#calculando-hatmathbfw-de-verdade"><span class="header-section-number">5.1</span> Calculando <span class="math inline">\(\hat{\mathbf{w}}\)</span> de Verdade</a></li>
  <li><a href="#conferência-independente-numpy.linalg.lstsq" id="toc-conferência-independente-numpy.linalg.lstsq" class="nav-link" data-scroll-target="#conferência-independente-numpy.linalg.lstsq"><span class="header-section-number">5.2</span> Conferência Independente: <code>numpy.linalg.lstsq</code></a></li>
  <li><a href="#verificando-a-ortogonalidade-do-resíduo" id="toc-verificando-a-ortogonalidade-do-resíduo" class="nav-link" data-scroll-target="#verificando-a-ortogonalidade-do-resíduo"><span class="header-section-number">5.3</span> Verificando a Ortogonalidade do Resíduo</a></li>
  <li><a href="#o-tamanho-do-resíduo-o-que-a-ortogonalidade-não-diz" id="toc-o-tamanho-do-resíduo-o-que-a-ortogonalidade-não-diz" class="nav-link" data-scroll-target="#o-tamanho-do-resíduo-o-que-a-ortogonalidade-não-diz"><span class="header-section-number">5.4</span> O Tamanho do Resíduo — o Que a Ortogonalidade <em>Não</em> Diz</a></li>
  <li><a href="#vendo-o-ajuste-numa-amostra-concreta" id="toc-vendo-o-ajuste-numa-amostra-concreta" class="nav-link" data-scroll-target="#vendo-o-ajuste-numa-amostra-concreta"><span class="header-section-number">5.5</span> Vendo o Ajuste numa Amostra Concreta</a></li>
  </ul></li>
  <li><a href="#quando-a-fórmula-falha-ou-fica-frágil" id="toc-quando-a-fórmula-falha-ou-fica-frágil" class="nav-link" data-scroll-target="#quando-a-fórmula-falha-ou-fica-frágil"><span class="header-section-number">6</span> Quando a Fórmula Falha, ou Fica Frágil</a>
  <ul class="collapse">
  <li><a href="#reconectando-com-a-aula-2-posto-completo" id="toc-reconectando-com-a-aula-2-posto-completo" class="nav-link" data-scroll-target="#reconectando-com-a-aula-2-posto-completo"><span class="header-section-number">6.1</span> Reconectando com a Aula 2: Posto Completo</a></li>
  <li><a href="#caso-1-multicolinearidade-exata-hatmathbfy-único-hatmathbfw-não" id="toc-caso-1-multicolinearidade-exata-hatmathbfy-único-hatmathbfw-não" class="nav-link" data-scroll-target="#caso-1-multicolinearidade-exata-hatmathbfy-único-hatmathbfw-não"><span class="header-section-number">6.2</span> Caso 1: Multicolinearidade Exata — <span class="math inline">\(\hat{\mathbf{y}}\)</span> Único, <span class="math inline">\(\hat{\mathbf{w}}\)</span> Não</a></li>
  <li><a href="#caso-2-quase-multicolinearidade-xtx-mal-condicionada" id="toc-caso-2-quase-multicolinearidade-xtx-mal-condicionada" class="nav-link" data-scroll-target="#caso-2-quase-multicolinearidade-xtx-mal-condicionada"><span class="header-section-number">6.3</span> Caso 2: Quase-Multicolinearidade — <span class="math inline">\(X^TX\)</span> Mal-Condicionada</a></li>
  </ul></li>
  <li><a href="#fechamento-e-ponte-para-a-aula-4" id="toc-fechamento-e-ponte-para-a-aula-4" class="nav-link" data-scroll-target="#fechamento-e-ponte-para-a-aula-4"><span class="header-section-number">7</span> Fechamento e Ponte para a Aula 4</a>
  <ul class="collapse">
  <li><a href="#retomando-as-perguntas-de-abertura" id="toc-retomando-as-perguntas-de-abertura" class="nav-link" data-scroll-target="#retomando-as-perguntas-de-abertura">Retomando as perguntas de abertura</a></li>
  <li><a href="#o-que-fica-em-aberto" id="toc-o-que-fica-em-aberto" class="nav-link" data-scroll-target="#o-que-fica-em-aberto">O Que Fica em Aberto</a></li>
  </ul></li>
  <li><a href="#exercícios" id="toc-exercícios" class="nav-link" data-scroll-target="#exercícios"><span class="header-section-number">8</span> Exercícios</a>
  <ul class="collapse">
  <li><a href="#questões-discursivas" id="toc-questões-discursivas" class="nav-link" data-scroll-target="#questões-discursivas"><span class="header-section-number">8.1</span> Questões discursivas</a></li>
  <li><a href="#questões-de-verdadeirofalso" id="toc-questões-de-verdadeirofalso" class="nav-link" data-scroll-target="#questões-de-verdadeirofalso"><span class="header-section-number">8.2</span> Questões de Verdadeiro/Falso</a></li>
  <li><a href="#aviso" id="toc-aviso" class="nav-link" data-scroll-target="#aviso"><span class="header-section-number">8.3</span> Aviso</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Outros formatos</h2><ul><li><a href="slides.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Aula 3: Projeções Ortogonais e Subespaços</h1>
<p class="subtitle lead">Álgebra Linear e Otimização para Aprendizado de Máquina</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor</div>
    <div class="quarto-title-meta-contents">
             <p>Prof.&nbsp;Marcos Medeiros Raimundo </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Data de Publicação</div>
    <div class="quarto-title-meta-contents">
      <p class="date">30 de agosto de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><a href="slides.html" class="see-all" aria-label="Ver slides" title="Ver slides">Slides</a> <a href="../../../teaching/optimization-linear-algebra/index.html" class="see-all lesson-list-link" aria-label="Lista de aulas" title="Lista de aulas">Lista de aulas</a></p>
<section id="o-problema-que-a-aula-2-deixou-em-aberto" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> O Problema Que a Aula 2 Deixou em Aberto</h1>
<hr>
<section id="revisão-rápida-onde-a-aula-2-parou" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="revisão-rápida-onde-a-aula-2-parou"><span class="header-section-number">1.1</span> Revisão Rápida: Onde a Aula 2 Parou</h2>
<p>A Aula 2 generalizou “um vetor” para “um dataset inteiro” via a matriz de design <span class="math inline">\(X\in\mathbb{R}^{N\times d}\)</span>, deu duas leituras ao produto <span class="math inline">\(A\mathbf{x}\)</span> (por linha: previsão; por coluna: combinação linear), e terminou classificando os sistemas lineares <span class="math inline">\(A\mathbf{x}=\mathbf{b}\)</span> em três casos — nenhuma, exatamente uma, ou infinitas soluções — via o critério do posto, <span class="math inline">\(\text{rk}(A)=\text{rk}(A|\mathbf{b})\)</span>. A peça central que fica: em Regressão Linear Múltipla, o sistema <span class="math inline">\(X\mathbf{w}=\mathbf{y}\)</span> tem <span class="math inline">\(N\)</span> equações e <span class="math inline">\(d\)</span> incógnitas, e como <span class="math inline">\(N\gg d\)</span> em praticamente todo problema real, o sistema é <strong>sobredeterminado</strong> — genericamente, <strong>nenhuma solução exata</strong>.</p>
</section>
<section id="organizador-prévio-de-sem-solução-para-melhor-aproximação" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="organizador-prévio-de-sem-solução-para-melhor-aproximação"><span class="header-section-number">1.2</span> Organizador Prévio: De “Sem Solução” Para “Melhor Aproximação”</h2>
<p>A Aula 2 fechou com essa constatação como um beco aparentemente sem saída: exigir que <span class="math inline">\(X\mathbf{w}\)</span> alcance <span class="math inline">\(\mathbf{y}\)</span> exatamente é pedir demais quando há milhares de observações reais e ruidosas. Mas “sem solução exata” não é “sem solução nenhuma que preste”. O próprio livro que citamos nas Aulas 1-2 (MathML) já aponta a saída, no capítulo sobre projeções: quando um sistema <span class="math inline">\(A\mathbf{x}=\mathbf{b}\)</span> não pode ser resolvido exatamente, ainda é possível perguntar qual é a melhor aproximação — “a ideia é encontrar o vetor no subespaço gerado pelas colunas de <span class="math inline">\(A\)</span> que está mais próximo de <span class="math inline">\(\mathbf{b}\)</span>” (tradução nossa, MathML, §3.8.2, p.&nbsp;88). Essa pergunta — “mais próximo, mas dentro de onde?” — é geométrica antes de ser algébrica, e é exatamente o fio que esta aula segue.</p>
</section>
<section id="roteiro-da-aula" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="roteiro-da-aula"><span class="header-section-number">1.3</span> Roteiro da Aula</h2>
<p>Quatro perguntas guiam esta aula:</p>
<ol type="1">
<li>O que significa, geometricamente, “a melhor aproximação possível” de <span class="math inline">\(\mathbf{y}\)</span> por um <span class="math inline">\(X\mathbf{w}\)</span> alcançável?</li>
<li>O que é projetar um vetor sobre um subespaço, e por que essa operação resolve exatamente o problema da pergunta 1?</li>
<li>Como essa ideia geométrica vira uma fórmula calculável — as <strong>Equações Normais</strong>?</li>
<li>Quando essa fórmula falha, ou fica numericamente frágil, e por quê?</li>
</ol>
</section>
<section id="problema-motivador" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="problema-motivador"><span class="header-section-number">1.4</span> Problema Motivador</h2>
<p>Volte ao <em>California Housing Dataset</em> das Aulas 1-2: <span class="math inline">\(N=16\,640\)</span> bairros (a partição de treino), 4 atributos (<code>MedInc</code>, <code>HouseAge</code>, <code>AveRooms</code>, <code>AveBedrms</code>), e o alvo <code>MedHouseVal</code>. O sistema <span class="math inline">\(X\mathbf{w}=\mathbf{y}\)</span> tem <span class="math inline">\(16\,640\)</span> equações e <span class="math inline">\(4\)</span> incógnitas — sobredeterminado por uma margem enorme. Sem resolver nada ainda, pense por um instante: se <span class="math inline">\(X\mathbf{w}\)</span> nunca alcança <span class="math inline">\(\mathbf{y}\)</span> exatamente, <strong>qual</strong> <span class="math inline">\(X\mathbf{w}\)</span> alcançável está mais perto? E “mais perto” — medido como, exatamente?</p>
<div class="fig-resize" style="width: 90%; margin: 0 auto;">
<img src="index_files/mediabag/cf778620246cb426b33fa7ea626111e4046a5173.svg" class="img-fluid">
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Se <span class="math inline">\(X\mathbf{w}=\mathbf{y}\)</span> nunca é alcançado exatamente, existe sempre exatamente uma “melhor” aproximação, ou pode haver várias igualmente boas?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: pense em como a Aula 2 já classificou o <strong>número</strong> de soluções de um sistema exato — nenhuma, uma, ou infinitas. A pergunta agora troca “solução exata” por “solução aproximada”. O número de “melhores aproximações” muda de natureza?</p>
<ul>
<li>□ Se o sistema <span class="math inline">\(X\mathbf{w}=\mathbf{y}\)</span> fosse subdeterminado (<span class="math inline">\(N&lt;d\)</span>) em vez de sobredeterminado, ainda faria sentido perguntar qual <span class="math inline">\(X\mathbf{w}\)</span> é “mais próximo” de <span class="math inline">\(\mathbf{y}\)</span>, mas a pergunta mudaria de natureza: deixaria de ser sobre um erro irredutível e passaria a ser sobre escolher entre infinitas soluções exatas.</li>
<li>□ No caso-limite <span class="math inline">\(N=d\)</span> com <span class="math inline">\(X\)</span> de posto completo, a “melhor aproximação” <span class="math inline">\(X\hat{\mathbf{w}}\)</span> coincide exatamente com <span class="math inline">\(\mathbf{y}\)</span> (erro zero).</li>
<li>□ Num sistema de posicionamento por GPS, com mais satélites (equações) do que coordenadas a estimar (incógnitas), a mesma lógica de “melhor aproximação por projeção” se aplica, ainda que o contexto seja localização geográfica, não preço de imóvel.</li>
<li>□ Como nenhum <span class="math inline">\(X\mathbf{w}\)</span> alcança <span class="math inline">\(\mathbf{y}\)</span> exatamente num sistema sobredeterminado, a Regressão Linear Múltipla deixa de fornecer qualquer informação útil sobre a relação entre atributos e alvo.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="intuição-a-sombra-no-chão-não-no-ar" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Intuição: A Sombra no Chão, Não no Ar</h1>
<hr>
<section id="a-ideia-antes-da-álgebra" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="a-ideia-antes-da-álgebra"><span class="header-section-number">2.1</span> A Ideia Antes da Álgebra</h2>
<p>Antes de qualquer fórmula, uma imagem concreta. Imagine um ponto <span class="math inline">\(\mathbf{y}\)</span> flutuando no espaço, e um subespaço <span class="math inline">\(U\)</span> — uma reta ou um plano passando pela origem — como se fosse o chão. Se uma fonte de luz vier exatamente <strong>perpendicular</strong> ao chão, a sombra de <span class="math inline">\(\mathbf{y}\)</span> sobre <span class="math inline">\(U\)</span> é um ponto específico: chame-o <span class="math inline">\(\hat{\mathbf{y}}\)</span>. Essa sombra tem duas propriedades que, juntas, definem tudo o que este bloco precisa:</p>
<ol type="1">
<li><strong>É o ponto de <span class="math inline">\(U\)</span> mais próximo de <span class="math inline">\(\mathbf{y}\)</span></strong> — nenhum outro ponto do chão está a uma distância menor de <span class="math inline">\(\mathbf{y}\)</span> do que a própria sombra.</li>
<li><strong>O segmento (ponto → sombra) é perpendicular a <span class="math inline">\(U\)</span></strong> — a “haste” que liga <span class="math inline">\(\mathbf{y}\)</span> à sua sombra <span class="math inline">\(\hat{\mathbf{y}}\)</span> faz ângulo reto com o chão inteiro, não só com a direção da luz.</li>
</ol>
<p>Essas duas propriedades não são independentes — a segunda é a razão pela qual a primeira é verdade, algo que o Bloco 4 vai provar formalmente. Por ora, olhe para o desenho: projetar sobre uma reta (subespaço de dimensão 1) e projetar sobre um plano (subespaço de dimensão 2) são a mesma operação, só que o “chão” tem mais dimensões.</p>
<div class="fig-resize" style="width: 100%; margin: 0 auto;">
<div id="90873ccc" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-3-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
<p>No painel esquerdo, <span class="math inline">\(U\)</span> é a reta gerada pela direção <span class="math inline">\((2,1)\)</span>, e <span class="math inline">\(\mathbf{y}=(1{,}0,\,3{,}2)\)</span> está fora dela. A sombra <span class="math inline">\(\hat{\mathbf{y}}\)</span> (quadrado laranja) é o ponto da reta mais próximo de <span class="math inline">\(\mathbf{y}\)</span>, e o segmento tracejado (o “resíduo”) encontra a reta em ângulo reto — não em qualquer ângulo. No painel direito, o “chão” já é um plano bidimensional (o plano <span class="math inline">\(x_3=0\)</span>) dentro de um espaço tridimensional: <span class="math inline">\(\mathbf{y}=(1{,}5,\,1{,}8,\,2{,}3)\)</span> tem sombra <span class="math inline">\(\hat{\mathbf{y}}=(1{,}5,\,1{,}8,\,0)\)</span> — a projeção simplesmente “zera” a componente perpendicular ao chão, e o segmento tracejado (puramente na direção <span class="math inline">\(x_3\)</span>) é, de novo, perpendicular a todo o plano, não só a uma direção dentro dele. É essa segunda observação — perpendicular a <strong>todo</strong> o subespaço — que vai generalizar para o espaço-coluna de <span class="math inline">\(X\)</span>, que tem <span class="math inline">\(d=4\)</span> dimensões, não <span class="math inline">\(1\)</span> ou <span class="math inline">\(2\)</span>: a “álgebra” muda, a geometria não.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Se a “luz” da projeção não viesse perpendicular ao chão, mas num ângulo oblíquo fixo, o ponto resultante ainda seria o mais próximo de <span class="math inline">\(\mathbf{y}\)</span>?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: pense no desenho da reta acima. Se você inclinasse a direção da “luz” (a direção da haste que liga <span class="math inline">\(\mathbf{y}\)</span> à sua sombra), o ponto de chegada na reta mudaria — ele continuaria sendo o ponto mais próximo?</p>
<ul>
<li>□ Se a luz não viesse perpendicular ao chão, mas em um ângulo oblíquo fixo, o ponto resultante ainda seria o ponto do subespaço mais próximo de <span class="math inline">\(\mathbf{y}\)</span>.</li>
<li>□ Se o ponto <span class="math inline">\(\mathbf{y}\)</span> já pertencesse ao subespaço <span class="math inline">\(U\)</span>, a “sombra” de <span class="math inline">\(\mathbf{y}\)</span> sobre <span class="math inline">\(U\)</span> coincidiria com o próprio <span class="math inline">\(\mathbf{y}\)</span>, e o resíduo teria norma zero.</li>
<li>□ Comprimir uma imagem mantendo só suas componentes principais é, geometricamente, projetar cada vetor-pixel sobre um subespaço de menor dimensão — a mesma lógica da sombra perpendicular discutida aqui, aplicada a outro tipo de dado.</li>
<li>□ Como a sombra perpendicular minimiza a distância até <span class="math inline">\(\mathbf{y}\)</span>, ela também é, necessariamente, o ponto do subespaço com a <strong>maior</strong> norma possível entre os candidatos considerados.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="subespaços-e-complemento-ortogonal" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Subespaços e Complemento Ortogonal</h1>
<hr>
<section id="recapitulando-subespaço-e-espaço-coluna" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="recapitulando-subespaço-e-espaço-coluna"><span class="header-section-number">3.1</span> Recapitulando: Subespaço e Espaço-Coluna</h2>
<p>A Aula 1 definiu <strong>subespaço</strong> como um subconjunto fechado sob soma e multiplicação por escalar; a Aula 2 deu um exemplo concreto e central para este curso — o <strong>espaço-coluna</strong> <span class="math inline">\(\text{col}(X)\)</span>, o conjunto de tudo que <span class="math inline">\(X\mathbf{w}\)</span> alcança quando <span class="math inline">\(\mathbf{w}\)</span> varia livremente por <span class="math inline">\(\mathbb{R}^d\)</span>. Com <span class="math inline">\(X\in\mathbb{R}^{16640\times 4}\)</span> de posto completo (verificado na Aula 2), <span class="math inline">\(\text{col}(X)\)</span> é um subespaço de dimensão <span class="math inline">\(4\)</span> dentro de um espaço ambiente de dimensão <span class="math inline">\(16\,640\)</span> — geometricamente, como um plano finíssimo boiando dentro de um espaço gigantesco, e <span class="math inline">\(\mathbf{y}\)</span> (o vetor com as <span class="math inline">\(16\,640\)</span> observações de <code>MedHouseVal</code>) quase certamente não está dentro dele.</p>
</section>
<section id="o-complemento-ortogonal" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="o-complemento-ortogonal"><span class="header-section-number">3.2</span> O Complemento Ortogonal</h2>
<p>A pergunta natural — “o que dizer sobre a parte de <span class="math inline">\(\mathbf{y}\)</span> que <strong>não</strong> está em <span class="math inline">\(\text{col}(X)\)</span>?” — tem uma resposta com nome: o <strong>complemento ortogonal</strong>. Dado um subespaço <span class="math inline">\(U\)</span> de um espaço <span class="math inline">\(V\)</span> de dimensão <span class="math inline">\(D\)</span>, com <span class="math inline">\(U\)</span> de dimensão <span class="math inline">\(M\)</span>, o MathML define (tradução nossa, §3.6, p.&nbsp;79):</p>
<blockquote class="blockquote">
<p>“seu complemento ortogonal <span class="math inline">\(U^\perp\)</span> é um subespaço de <span class="math inline">\(V\)</span> de dimensão <span class="math inline">\((D-M)\)</span> e contém todos os vetores em <span class="math inline">\(V\)</span> que são ortogonais a todo vetor em <span class="math inline">\(U\)</span>. Além disso, <span class="math inline">\(U\cap U^\perp=\{\mathbf{0}\}\)</span>, de modo que qualquer vetor <span class="math inline">\(\mathbf{x}\in V\)</span> pode ser decomposto de forma única” <span class="math display">\[
\mathbf{x} = \sum_{m=1}^{M}\lambda_m\mathbf{b}_m + \sum_{j=1}^{D-M}\psi_j\mathbf{b}_j^\perp,
\qquad \lambda_m,\psi_j\in\mathbb{R} \qquad \text{(MathML, eq. 3.36)},
\]</span> onde <span class="math inline">\((\mathbf{b}_1,\dots,\mathbf{b}_M)\)</span> é uma base de <span class="math inline">\(U\)</span> e <span class="math inline">\((\mathbf{b}_1^\perp,\dots,\mathbf{b}_{D-M}^\perp)\)</span> é uma base de <span class="math inline">\(U^\perp\)</span>. Em notação compacta, isso se escreve <span class="math inline">\(V = U \oplus U^\perp\)</span>: todo vetor de <span class="math inline">\(V\)</span> é a soma de <strong>uma única</strong> parte dentro de <span class="math inline">\(U\)</span> com <strong>uma única</strong> parte dentro de <span class="math inline">\(U^\perp\)</span> — nunca duas formas diferentes de fazer essa soma, nunca nenhuma parte sobrando de fora.</p>
</blockquote>
<div class="fig-resize" style="width: 70%; margin: 0 auto;">
<div id="1a0f4ded" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-4-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
<p>Em <span class="math inline">\(\mathbb{R}^2\)</span> (<span class="math inline">\(D=2\)</span>), com <span class="math inline">\(U\)</span> a reta de dimensão <span class="math inline">\(M=1\)</span>, o complemento ortogonal <span class="math inline">\(U^\perp\)</span> também tem dimensão <span class="math inline">\(D-M=1\)</span> — a reta perpendicular. O vetor <span class="math inline">\(\mathbf{x}=(1,3)\)</span> se decompõe de forma única em uma parte sobre <span class="math inline">\(U\)</span> e uma parte sobre <span class="math inline">\(U^\perp\)</span> (linhas pontilhadas): some as duas setas azul/laranja e você recupera exatamente <span class="math inline">\(\mathbf{x}\)</span>, sem sobra e sem ambiguidade — não existe uma segunda forma de fazer essa soma. Em <span class="math inline">\(\mathbb{R}^3\)</span>, se <span class="math inline">\(U\)</span> fosse um plano (<span class="math inline">\(M=2\)</span>), <span class="math inline">\(U^\perp\)</span> teria dimensão <span class="math inline">\(D-M=1\)</span> — é exatamente o “vetor normal” do MathML: “o vetor <span class="math inline">\(\mathbf{w}\)</span> com <span class="math inline">\(\|\mathbf{w}\|=1\)</span>, ortogonal ao plano <span class="math inline">\(U\)</span>, é o vetor de base de <span class="math inline">\(U^\perp\)</span>” (tradução nossa, §3.6, p.&nbsp;80). No caso da regressão que fecha esta aula, <span class="math inline">\(D=16\,640\)</span> e <span class="math inline">\(M=4\)</span>: <span class="math inline">\(U^\perp=\text{col}(X)^\perp\)</span> tem a dimensão gigantesca <span class="math inline">\(16\,636\)</span>, mas isso não importa para o que vamos usar dele — só importa que o resíduo <span class="math inline">\(\mathbf{y}-\hat{\mathbf{y}}\)</span> vai viver exatamente ali dentro.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Se <span class="math inline">\(U\)</span> fosse o subespaço trivial <span class="math inline">\(\{\mathbf{0}\}\)</span>, o que seria <span class="math inline">\(U^\perp\)</span>?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: releia a definição — <span class="math inline">\(U^\perp\)</span> contém todo vetor ortogonal a <strong>todo</strong> vetor de <span class="math inline">\(U\)</span>. Se o único vetor de <span class="math inline">\(U\)</span> for <span class="math inline">\(\mathbf{0}\)</span>, quantos vetores de <span class="math inline">\(V\)</span> são ortogonais a ele?</p>
<ul>
<li>□ Se <span class="math inline">\(U\)</span> fosse o subespaço trivial <span class="math inline">\(\{\mathbf{0}\}\)</span>, seu complemento ortogonal <span class="math inline">\(U^\perp\)</span> seria igual ao espaço <span class="math inline">\(V\)</span> inteiro.</li>
<li>□ Se <span class="math inline">\(U=V\)</span> (o subespaço é o espaço inteiro), então <span class="math inline">\(U^\perp=\{\mathbf{0}\}\)</span>.</li>
<li>□ Num modelo de regressão em que o resíduo <span class="math inline">\(\mathbf{y}-\hat{\mathbf{y}}\)</span> é ortogonal a todo vetor do espaço-coluna de <span class="math inline">\(X\)</span>, esse resíduo não é apenas “ortogonal a ele” informalmente — ele satisfaz a própria definição formal de pertencer a <span class="math inline">\(\text{col}(X)^\perp\)</span>.</li>
<li>□ Como todo vetor de <span class="math inline">\(V\)</span> se decompõe de forma única numa parte de <span class="math inline">\(U\)</span> e uma parte de <span class="math inline">\(U^\perp\)</span>, isso implica que <span class="math inline">\(U\)</span> e <span class="math inline">\(U^\perp\)</span> têm, necessariamente, a mesma dimensão.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="o-teorema-da-projeção-premissas-e-passo-a-passo" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> O Teorema da Projeção: Premissas e Passo a Passo</h1>
<hr>
<section id="enunciando-o-problema-com-precisão" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="enunciando-o-problema-com-precisão"><span class="header-section-number">4.1</span> Enunciando o Problema com Precisão</h2>
<p>Antes de derivar qualquer fórmula, vamos deixar explícitas as premissas — seguindo a diretriz deste curso de nunca saltar direto para o resultado final.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Premissas
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Temos um subespaço <span class="math inline">\(U=\text{col}(X)\subseteq\mathbb{R}^N\)</span>, o espaço-coluna da matriz de design (Aula 2).</li>
<li>Temos um vetor <span class="math inline">\(\mathbf{y}\in\mathbb{R}^N\)</span> que, em geral, <strong>não</strong> pertence a <span class="math inline">\(U\)</span> (o caso sobredeterminado da Aula 2 e do Bloco 1 desta aula).</li>
<li>Definimos <span class="math inline">\(\hat{\mathbf{y}}\in U\)</span> como o ponto de <span class="math inline">\(U\)</span> <strong>mais próximo</strong> de <span class="math inline">\(\mathbf{y}\)</span> — o que minimiza <span class="math inline">\(\|\mathbf{y}-\hat{\mathbf{y}}\|\)</span> (a formalização da “sombra” do Bloco 2).</li>
</ol>
</div>
</div>
<p>O objetivo dos quatro passos seguintes é ir de “<span class="math inline">\(\hat{\mathbf{y}}\)</span> minimiza a distância” até uma fórmula fechada e calculável para <span class="math inline">\(\hat{\mathbf{w}}\)</span> tal que <span class="math inline">\(\hat{\mathbf{y}}=X\hat{\mathbf{w}}\)</span>.</p>
</section>
<section id="passo-i-mais-próximo-equivale-a-ortogonal" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="passo-i-mais-próximo-equivale-a-ortogonal"><span class="header-section-number">4.2</span> Passo (i): “Mais Próximo” Equivale a “Ortogonal”</h2>
<p>O MathML caracteriza exatamente essa condição de mínimo, primeiro no caso de uma reta e depois generalizando (tradução nossa, §3.8.1, p.&nbsp;82, adaptando a notação para <span class="math inline">\(\hat{\mathbf{y}}\)</span> em vez de <span class="math inline">\(\pi_U(x)\)</span>):</p>
<blockquote class="blockquote">
<p>“A projeção <span class="math inline">\(\hat{\mathbf{y}}\)</span> é a mais próxima de <span class="math inline">\(\mathbf{y}\)</span>, onde ‘mais próxima’ implica que a distância <span class="math inline">\(\|\mathbf{y}-\hat{\mathbf{y}}\|\)</span> é mínima. Disso segue que o segmento <span class="math inline">\(\hat{\mathbf{y}}-\mathbf{y}\)</span> […] é ortogonal a <span class="math inline">\(U\)</span>.”</p>
</blockquote>
<p>Ou seja: minimizar a distância <strong>não é uma condição separada</strong> de “ortogonal a <span class="math inline">\(U\)</span>” — são a mesma condição, vista de dois ângulos. Por quê? Intuitivamente (o argumento completo usa cálculo, fora do escopo desta aula): se o resíduo <span class="math inline">\(\mathbf{y}-\hat{\mathbf{y}}\)</span> tivesse qualquer componente <strong>não</strong> ortogonal a <span class="math inline">\(U\)</span> — ou seja, alguma componente dentro de <span class="math inline">\(U\)</span> —, seria possível mover <span class="math inline">\(\hat{\mathbf{y}}\)</span> um pouco dentro de <span class="math inline">\(U\)</span>, na direção dessa componente, e diminuir ainda mais a distância. Isso contradiz <span class="math inline">\(\hat{\mathbf{y}}\)</span> já ser o ponto mais próximo. Logo, no mínimo, não pode sobrar componente alguma do resíduo dentro de <span class="math inline">\(U\)</span> — o resíduo inteiro tem que estar em <span class="math inline">\(U^\perp\)</span> (Bloco 3): <span class="math display">\[
\mathbf{y}-\hat{\mathbf{y}} \;\perp\; U \qquad\Longleftrightarrow\qquad
\mathbf{y}-\hat{\mathbf{y}} \in U^\perp .
\]</span></p>
</section>
<section id="passo-ii-escrevendo-hatmathbfy-em-termos-de-x" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="passo-ii-escrevendo-hatmathbfy-em-termos-de-x"><span class="header-section-number">4.3</span> Passo (ii): Escrevendo <span class="math inline">\(\hat{\mathbf{y}}\)</span> em Termos de <span class="math inline">\(X\)</span></h2>
<p><span class="math inline">\(\hat{\mathbf{y}}\)</span> é um elemento de <span class="math inline">\(U=\text{col}(X)\)</span> — e a Leitura 2 do produto matriz-vetor (Aula 2, Bloco 2) já disse exatamente o que isso significa: todo elemento do espaço-coluna de <span class="math inline">\(X\)</span> é uma combinação linear das colunas de <span class="math inline">\(X\)</span>, ou seja, é <span class="math inline">\(X\mathbf{w}\)</span> para algum vetor de pesos <span class="math inline">\(\mathbf{w}\in\mathbb{R}^d\)</span>. Chame esse vetor <span class="math inline">\(\hat{\mathbf{w}}\)</span>: <span class="math display">\[
\hat{\mathbf{y}} = X\hat{\mathbf{w}}, \qquad \hat{\mathbf{w}}\in\mathbb{R}^d.
\]</span> Substituindo no resultado do Passo (i): <span class="math display">\[
\mathbf{y}-X\hat{\mathbf{w}} \;\perp\; \text{col}(X).
\]</span></p>
</section>
<section id="passo-iii-ortogonal-a-cada-coluna-de-x" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="passo-iii-ortogonal-a-cada-coluna-de-x"><span class="header-section-number">4.4</span> Passo (iii): Ortogonal a <em>Cada Coluna</em> de <span class="math inline">\(X\)</span></h2>
<p>“Ortogonal a <span class="math inline">\(\text{col}(X)\)</span> inteiro” parece, à primeira vista, uma condição gigantesca — <span class="math inline">\(\text{col}(X)\)</span> tem infinitos vetores. Mas o MathML mostra que basta checar a ortogonalidade <strong>coluna a coluna</strong> (tradução nossa, §3.8.2, p.&nbsp;85-86, adaptando <span class="math inline">\(B\to X\)</span>, <span class="math inline">\(\mathbf{b}_i\to\)</span> coluna <span class="math inline">\(i\)</span> de <span class="math inline">\(X\)</span>):</p>
<blockquote class="blockquote">
<p>“Como ‘mais próxima’ significa ‘distância mínima’, isso implica que o vetor ligando <span class="math inline">\(\hat{\mathbf{y}}\in U\)</span> e <span class="math inline">\(\mathbf{y}\)</span> deve ser ortogonal a todos os vetores de base de <span class="math inline">\(U\)</span>. Portanto, obtemos <span class="math inline">\(m\)</span> condições simultâneas […] o que, […] pode ser escrito como um sistema linear homogêneo […] <span class="math inline">\(B^T(\mathbf{x}-B\lambda)=\mathbf{0}\)</span>”</p>
</blockquote>
<p>Por que basta checar as <strong>colunas</strong> de <span class="math inline">\(X\)</span> (uma base de <span class="math inline">\(\text{col}(X)\)</span>), em vez de todo vetor de <span class="math inline">\(\text{col}(X)\)</span>? Porque qualquer vetor de <span class="math inline">\(\text{col}(X)\)</span> é uma combinação linear das colunas (de novo, a Leitura 2); se o resíduo é ortogonal a cada coluna individualmente, ele é ortogonal a <strong>qualquer</strong> combinação linear delas — a ortogonalidade “passa” pela combinação linear sem se perder. Aplicando isso ao nosso caso (<span class="math inline">\(X\)</span> no lugar de <span class="math inline">\(B\)</span>, <span class="math inline">\(\hat{\mathbf{w}}\)</span> no lugar de <span class="math inline">\(\lambda\)</span>): <span class="math display">\[
X^T\big(\mathbf{y}-X\hat{\mathbf{w}}\big) = \mathbf{0}.
\]</span></p>
</section>
<section id="passo-iv-isolando-hatmathbfw-as-equações-normais" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="passo-iv-isolando-hatmathbfw-as-equações-normais"><span class="header-section-number">4.5</span> Passo (iv): Isolando <span class="math inline">\(\hat{\mathbf{w}}\)</span> — as Equações Normais</h2>
<p>Distribuindo o produto do Passo (iii): <span class="math display">\[
X^T\mathbf{y} - X^TX\hat{\mathbf{w}} = \mathbf{0}
\qquad\Longleftrightarrow\qquad
X^TX\hat{\mathbf{w}} = X^T\mathbf{y}.
\]</span> O MathML batiza essa equação (tradução nossa, §3.8.2, p.&nbsp;86, eq. 3.56): “a última expressão é chamada <strong>equação normal</strong>”. Isso ainda não é a fórmula fechada de <span class="math inline">\(\hat{\mathbf{w}}\)</span> — é um sistema linear em <span class="math inline">\(\hat{\mathbf{w}}\)</span>, com <span class="math inline">\(X^TX\in\mathbb{R}^{d\times d}\)</span> no papel de “<span class="math inline">\(A\)</span>” e <span class="math inline">\(X^T\mathbf{y}\in\mathbb{R}^d\)</span> no papel de “<span class="math inline">\(\mathbf{b}\)</span>” (a mesma estrutura <span class="math inline">\(A\mathbf{x}=\mathbf{b}\)</span> da Aula 2, agora numa matriz derivada de <span class="math inline">\(X\)</span>, não em <span class="math inline">\(X\)</span> diretamente).</p>
<p><strong>Quando esse sistema tem solução única.</strong> O MathML completa a derivação notando exatamente a condição que faz <span class="math inline">\(X^TX\)</span> invertível (tradução nossa, §3.8.2, p.&nbsp;86): “como <span class="math inline">\(b_1,\dots,b_m\)</span> são uma base de <span class="math inline">\(U\)</span> e, portanto, linearmente independentes, <span class="math inline">\(B^TB\in\mathbb{R}^{m\times m}\)</span> é regular e pode ser invertida.” Traduzido para o nosso caso: as colunas de <span class="math inline">\(X\)</span> são linearmente independentes exatamente quando <span class="math inline">\(X\)</span> tem <strong>posto completo</strong> (<span class="math inline">\(\text{rk}(X)=d\)</span>) — o mesmo critério provado na Aula 2, Bloco 5. Quando isso vale, <span class="math inline">\(X^TX\)</span> é invertível, e podemos isolar <span class="math inline">\(\hat{\mathbf{w}}\)</span>: <span class="math display">\[
\hat{\mathbf{w}} = (X^TX)^{-1}X^T\mathbf{y}.
\]</span> O MathML chama a matriz <span class="math inline">\((X^TX)^{-1}X^T\)</span> de <strong>pseudo-inversa</strong> de <span class="math inline">\(X\)</span> (tradução nossa, §3.8.2, p.&nbsp;86) — um nome que vai voltar quando o curso tratar de decomposições matriciais (SVD), mais adiante. Por ora, a peça que fecha o ciclo aberto na Aula 2: o sistema <span class="math inline">\(X\mathbf{w}=\mathbf{y}\)</span> sobredeterminado não tem solução exata, mas <strong>tem</strong>, sob posto completo, uma única melhor aproximação — e ela tem fórmula fechada.</p>
<div class="fig-resize" style="width: 65%; margin: 0 auto;">
<img src="index_files/mediabag/396cf257be985a28527a0b7f9176b77380327c4a.svg" class="img-fluid">
</div>
<p>O esquema resume os quatro passos: <span class="math inline">\(\text{col}(X)\)</span> é a “reta” azul (uma representação necessariamente simplificada de um subespaço de dimensão <span class="math inline">\(4\)</span>), <span class="math inline">\(\mathbf{y}\)</span> está fora dele, <span class="math inline">\(\hat{\mathbf{y}}=X\hat{\mathbf{w}}\)</span> é o ponto mais próximo dentro de <span class="math inline">\(\text{col}(X)\)</span>, e o resíduo (tracejado) encontra o subespaço em ângulo reto — a mesma “sombra” do Bloco 2, agora com nome de variável de regressão.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>A condição <span class="math inline">\((\mathbf{y}-X\hat{\mathbf{w}})\perp\text{col}(X)\)</span> garante que o resíduo seja zero?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: releia o Passo (i) — “mais próximo” e “ortogonal” são a mesma condição. Isso é o mesmo que dizer “o erro desaparece”?</p>
<ul>
<li>□ Se, em vez de minimizar <span class="math inline">\(\|\mathbf{y}-X\mathbf{w}\|\)</span> (norma <span class="math inline">\(L_2\)</span>), o critério de “melhor” fosse minimizar <span class="math inline">\(\|\mathbf{y}-X\mathbf{w}\|_1\)</span> (norma <span class="math inline">\(L_1\)</span>), a condição de ortogonalidade <span class="math inline">\((\mathbf{y}-X\hat{\mathbf{w}})\perp\text{col}(X)\)</span> ainda garantiria a solução.</li>
<li>□ No caso em que <span class="math inline">\(\mathbf{y}\)</span> já pertence ao espaço-coluna de <span class="math inline">\(X\)</span>, as Equações Normais <span class="math inline">\(X^TX\hat{\mathbf{w}}=X^T\mathbf{y}\)</span> têm como solução um <span class="math inline">\(\hat{\mathbf{w}}\)</span> tal que <span class="math inline">\(X\hat{\mathbf{w}}=\mathbf{y}\)</span> exatamente (erro zero).</li>
<li>□ Num problema de calibração de sensores, em que <span class="math inline">\(\mathbf{y}\)</span> são leituras redundantes de <span class="math inline">\(N\)</span> sensores e <span class="math inline">\(X\)</span> mapeia <span class="math inline">\(d&lt;N\)</span> parâmetros físicos verdadeiros para essas leituras, a mesma derivação das Equações Normais forneceria a melhor estimativa desses parâmetros por mínimos quadrados.</li>
<li>□ Como a condição <span class="math inline">\((\mathbf{y}-X\hat{\mathbf{w}})\perp\text{col}(X)\)</span> equivale a <span class="math inline">\(X^T(\mathbf{y}-X\hat{\mathbf{w}})=\mathbf{0}\)</span>, isso significa que o resíduo <span class="math inline">\(\mathbf{y}-X\hat{\mathbf{w}}\)</span> deve ser o vetor nulo sempre que <span class="math inline">\(X\)</span> tiver posto completo.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="aplicação-e-verificação-no-dado-real" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Aplicação e Verificação no Dado Real</h1>
<hr>
<section id="calculando-hatmathbfw-de-verdade" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="calculando-hatmathbfw-de-verdade"><span class="header-section-number">5.1</span> Calculando <span class="math inline">\(\hat{\mathbf{w}}\)</span> de Verdade</h2>
<p>Chegou a hora de aplicar a fórmula fechada do Passo (iv) ao problema motivador do Bloco 1: os <span class="math inline">\(N=16\,640\)</span> bairros do California Housing, com <span class="math inline">\(X\in\mathbb{R}^{16640\times 4}\)</span> (as colunas <code>MedInc</code>, <code>HouseAge</code>, <code>AveRooms</code>, <code>AveBedrms</code>) e <span class="math inline">\(\mathbf{y}\in\mathbb{R}^{16640}\)</span> (<code>MedHouseVal</code>). Como a Aula 2 já verificou que <span class="math inline">\(X\)</span> tem posto completo (<span class="math inline">\(\text{rk}(X)=4\)</span>), <span class="math inline">\(X^TX\)</span> é invertível, e a fórmula <span class="math inline">\(\hat{\mathbf{w}}=(X^TX)^{-1}X^T\mathbf{y}\)</span> se aplica diretamente.</p>
<div id="7a4d0b51" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>X_completo <span class="op">=</span> _housing[COLS].to_numpy()</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>y_completo <span class="op">=</span> _housing[<span class="st">"MedHouseVal"</span>].to_numpy()</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Equações Normais, resolvidas diretamente pela fórmula fechada</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>XtX <span class="op">=</span> X_completo.T <span class="op">@</span> X_completo</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>Xty <span class="op">=</span> X_completo.T <span class="op">@</span> y_completo</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>w_hat <span class="op">=</span> np.linalg.inv(XtX) <span class="op">@</span> Xty</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"w_hat (Equações Normais):"</span>, np.<span class="bu">round</span>(w_hat, <span class="dv">5</span>))</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>w_hat (Equações Normais): [ 0.48761  0.01171 -0.18809  0.78255]</code></pre>
</div>
</div>
<p>Para cada dólar (em dezenas de milhares) de renda mediana adicional (<code>MedInc</code>), o modelo associa um aumento de <span class="math inline">\(\approx 0{,}488\)</span> (centenas de milhares de dólares) no preço previsto — o maior peso em módulo entre os quatro, plausível: <code>MedInc</code> é o atributo com a relação mais direta com o valor do imóvel. Note que <code>AveRooms</code> recebe um peso <strong>negativo</strong> (<span class="math inline">\(\approx -0{,}188\)</span>), o que parece contraintuitivo, mas se explica pela Leitura 2 do produto matriz-vetor (Aula 2): o peso de <code>AveRooms</code> é estimado <strong>na presença</strong> de <code>AveBedrms</code>, um atributo fortemente correlacionado (Bloco 6 volta a isso) — o modelo pode estar “compensando” a superposição de informação entre os dois, não afirmando que mais cômodos por domicílio reduza o preço isoladamente.</p>
</section>
<section id="conferência-independente-numpy.linalg.lstsq" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="conferência-independente-numpy.linalg.lstsq"><span class="header-section-number">5.2</span> Conferência Independente: <code>numpy.linalg.lstsq</code></h2>
<p>A fórmula fechada é uma forma de calcular <span class="math inline">\(\hat{\mathbf{w}}\)</span>, mas não a única — <code>numpy.linalg.lstsq</code> resolve o mesmo problema de mínimos quadrados por um algoritmo numérico diferente (decomposição, não inversão explícita de <span class="math inline">\(X^TX\)</span>). Se a nossa derivação do Bloco 4 estiver certa, as duas contas devem coincidir:</p>
<div id="87b9839c" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>w_lstsq, <span class="op">*</span>_ <span class="op">=</span> np.linalg.lstsq(X_completo, y_completo, rcond<span class="op">=</span><span class="va">None</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"w_hat (lstsq):           "</span>, np.<span class="bu">round</span>(w_lstsq, <span class="dv">5</span>))</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"maior diferença absoluta:"</span>, np.<span class="bu">max</span>(np.<span class="bu">abs</span>(w_hat <span class="op">-</span> w_lstsq)))</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>w_hat (lstsq):            [ 0.48761  0.01171 -0.18809  0.78255]
maior diferença absoluta: 1.2878587085651816e-14</code></pre>
</div>
</div>
<p>A diferença máxima entre os dois vetores é da ordem de <span class="math inline">\(10^{-14}\)</span> — zero, a menos de erro de arredondamento de ponto flutuante. Dois algoritmos completamente diferentes (inversão explícita de uma matriz <span class="math inline">\(4\times 4\)</span> vs.&nbsp;decomposição numérica) chegam ao mesmo <span class="math inline">\(\hat{\mathbf{w}}\)</span> — evidência de que a derivação do Bloco 4 não é só elegante no quadro, funciona com dados reais.</p>
</section>
<section id="verificando-a-ortogonalidade-do-resíduo" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="verificando-a-ortogonalidade-do-resíduo"><span class="header-section-number">5.3</span> Verificando a Ortogonalidade do Resíduo</h2>
<p>A promessa central do Passo (iii) foi que o resíduo <span class="math inline">\(\mathbf{y}-X\hat{\mathbf{w}}\)</span> é ortogonal a <strong>cada coluna</strong> de <span class="math inline">\(X\)</span> — não uma afirmação vaga, uma igualdade numérica exata (até erro de arredondamento) que podemos checar:</p>
<div id="b2415e85" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>residuo <span class="op">=</span> y_completo <span class="op">-</span> X_completo <span class="op">@</span> w_hat</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Produto interno do resíduo com cada coluna de X:"</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> j, nome <span class="kw">in</span> <span class="bu">enumerate</span>(COLS):</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    prod <span class="op">=</span> residuo <span class="op">@</span> X_completo[:, j]</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>nome<span class="sc">:10s}</span><span class="ss">: </span><span class="sc">{</span>prod<span class="sc">:.3e}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Produto interno do resíduo com cada coluna de X:
  MedInc    : -4.522e-10
  HouseAge  : -5.039e-09
  AveRooms  : -8.756e-10
  AveBedrms : -1.987e-10</code></pre>
</div>
</div>
<p>Cada produto interno é da ordem de <span class="math inline">\(10^{-9}\)</span> ou menor — e, colocado em perspectiva (dividindo pelas normas de cada vetor envolvido, para comparar “zero relativo” e não só “zero absoluto”), a proporção é da ordem de <span class="math inline">\(10^{-14}\)</span>: numericamente zero, exatamente como o Passo (iii) exigia. Não é coincidência — é a própria equação <span class="math inline">\(X^T(\mathbf{y}-X\hat{\mathbf{w}})=\mathbf{0}\)</span> (Passo iii) verificada numericamente, coluna a coluna.</p>
</section>
<section id="o-tamanho-do-resíduo-o-que-a-ortogonalidade-não-diz" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="o-tamanho-do-resíduo-o-que-a-ortogonalidade-não-diz"><span class="header-section-number">5.4</span> O Tamanho do Resíduo — o Que a Ortogonalidade <em>Não</em> Diz</h2>
<p>Ortogonalidade garante a <strong>direção</strong> do erro (ele mora em <span class="math inline">\(\text{col}(X)^\perp\)</span>), mas nada diz sobre o <strong>tamanho</strong> do erro. Vale a pena medir:</p>
<div id="6cebd7c0" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>norma_residuo <span class="op">=</span> np.linalg.norm(residuo)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>norma_y <span class="op">=</span> np.linalg.norm(y_completo)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>r2 <span class="op">=</span> <span class="dv">1</span> <span class="op">-</span> np.<span class="bu">sum</span>(residuo<span class="op">**</span><span class="dv">2</span>) <span class="op">/</span> np.<span class="bu">sum</span>((y_completo <span class="op">-</span> y_completo.mean())<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"||resíduo|| = </span><span class="sc">{</span>norma_residuo<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"||y||       = </span><span class="sc">{</span>norma_y<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"||resíduo||/||y|| = </span><span class="sc">{</span>norma_residuo<span class="op">/</span>norma_y<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"R² = </span><span class="sc">{</span>r2<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>||resíduo|| = 101.49
||y||       = 298.57
||resíduo||/||y|| = 0.340
R² = 0.518</code></pre>
</div>
</div>
<p>O resíduo tem norma <span class="math inline">\(\approx 101{,}5\)</span> contra <span class="math inline">\(\|\mathbf{y}\|\approx
298{,}6\)</span> — não é pequeno; em termos de <span class="math inline">\(R^2\)</span> (a fração da variação de <code>MedHouseVal</code> “explicada” pelo modelo), o ajuste é <span class="math inline">\(R^2\approx 0{,}518\)</span>: o modelo explica um pouco mais da metade da variação do preço usando só 4 atributos. Isso não é uma falha da matemática do Bloco 4 — a projeção ortogonal <em>garante</em> a melhor aproximação <strong>possível dentro do espaço-coluna de <span class="math inline">\(X\)</span></strong>, não uma boa aproximação em termos absolutos. Com só 4 atributos (faltam localização, qualidade da construção, proximidade da costa, etc.), <span class="math inline">\(\text{col}(X)\)</span> é um subespaço pequeno demais para chegar perto de <span class="math inline">\(\mathbf{y}\)</span> — a projeção é ótima <em>dentro das opções disponíveis</em>, e as opções disponíveis são limitadas pelos atributos escolhidos, não pela matemática da projeção.</p>
</section>
<section id="vendo-o-ajuste-numa-amostra-concreta" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="vendo-o-ajuste-numa-amostra-concreta"><span class="header-section-number">5.5</span> Vendo o Ajuste numa Amostra Concreta</h2>
<p>Voltando à amostra de 6 bairros usada na Aula 2 (mesma semente, <code>random_state=7</code>) — agora com o <span class="math inline">\(\hat{\mathbf{w}}\)</span> de verdade, ajustado a partir de todos os <span class="math inline">\(16\,640\)</span> bairros, não mais um <span class="math inline">\(\mathbf{w}\)</span> inventado:</p>
<div class="fig-resize" style="width: 85%; margin: 0 auto;">
<div id="2b000108" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-9-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
<p>Compare com o gráfico da Aula 2 (mesmos 6 bairros, <span class="math inline">\(\mathbf{w}\)</span> inventado): os erros ali eram grandes e sem padrão claro; aqui, ainda há erro (esperado, dado o <span class="math inline">\(R^2\approx 0{,}518\)</span>), mas o modelo já captura a tendência geral — o bairro 1 (renda mais alta) continua sendo o de previsão mais alta entre os seis, por exemplo. É a diferença entre “um <span class="math inline">\(\mathbf{w}\)</span> qualquer” e “o <span class="math inline">\(\hat{\mathbf{w}}\)</span> que resolve as Equações Normais”: o segundo não é perfeito, mas é <strong>matematicamente o melhor possível</strong> dentro do que os 4 atributos permitem.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Se comparássemos <span class="math inline">\(\hat{\mathbf{w}}\)</span> com uma resolução por eliminação de Gauss do sistema <span class="math inline">\(X^TX\hat{\mathbf{w}}=X^T\mathbf{y}\)</span>, esperaríamos o mesmo resultado da comparação com <code>lstsq</code>?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: o que muda entre <code>lstsq</code> e eliminação de Gauss é o <strong>algoritmo</strong>, não a <strong>equação</strong> que ambos resolvem. Isso muda a resposta?</p>
<ul>
<li>□ Comparar <span class="math inline">\(\hat{\mathbf{w}}\)</span> (Equações Normais) com uma resolução por eliminação de Gauss do mesmo sistema <span class="math inline">\(X^TX\hat{\mathbf{w}}=X^T\mathbf{y}\)</span> daria, a menos de erro de arredondamento, exatamente o mesmo vetor encontrado com <code>lstsq</code>.</li>
<li>□ Se o produto interno do resíduo com cada coluna de <span class="math inline">\(X\)</span> fosse exatamente zero (não apenas próximo de zero, mas matematicamente exato), isso seria uma coincidência numérica desta amostra específica, não uma consequência necessária da teoria.</li>
<li>□ Num ajuste de crescimento populacional, com atributos em escalas bem diferentes das usadas nesta aula, a mesma verificação (produto interno do resíduo com cada coluna <span class="math inline">\(\approx 0\)</span>) continuaria sendo um teste válido de que <span class="math inline">\(\hat{\mathbf{w}}\)</span> foi calculado corretamente.</li>
<li>□ Como o resíduo é ortogonal a cada coluna de <span class="math inline">\(X\)</span>, isso implica que o modelo ajustado explica quase toda a variação de <span class="math inline">\(\mathbf{y}\)</span> (um <span class="math inline">\(R^2\)</span> próximo de <span class="math inline">\(1\)</span>).</li>
</ul>
</div>
</div>
</section>
</section>
<section id="quando-a-fórmula-falha-ou-fica-frágil" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Quando a Fórmula Falha, ou Fica Frágil</h1>
<hr>
<section id="reconectando-com-a-aula-2-posto-completo" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="reconectando-com-a-aula-2-posto-completo"><span class="header-section-number">6.1</span> Reconectando com a Aula 2: Posto Completo</h2>
<p>O Passo (iv) do Bloco 4 usou uma hipótese específica: <span class="math inline">\(X^TX\)</span> é invertível <strong>se, e somente se</strong>, as colunas de <span class="math inline">\(X\)</span> são linearmente independentes — ou seja, <span class="math inline">\(X\)</span> tem posto completo, <span class="math inline">\(\text{rk}(X)=d\)</span> (critério provado na Aula 2, Bloco 5). Essa não é uma hipótese técnica qualquer: é a única coisa que separa “<span class="math inline">\(\hat{\mathbf{w}}\)</span> tem fórmula fechada” de “<span class="math inline">\(\hat{\mathbf{w}}\)</span> não é sequer único”. Vamos ver os dois jeitos como essa hipótese pode falhar — um exato, um só numericamente frágil — reaproveitando exatamente os exemplos da Aula 2.</p>
</section>
<section id="caso-1-multicolinearidade-exata-hatmathbfy-único-hatmathbfw-não" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="caso-1-multicolinearidade-exata-hatmathbfy-único-hatmathbfw-não"><span class="header-section-number">6.2</span> Caso 1: Multicolinearidade Exata — <span class="math inline">\(\hat{\mathbf{y}}\)</span> Único, <span class="math inline">\(\hat{\mathbf{w}}\)</span> Não</h2>
<p>A Aula 2 fabricou uma quinta coluna, <span class="math inline">\(2\times\)</span><code>AveRooms</code>, e mostrou que o posto da matriz de design <strong>não sobe</strong> de 4 para 5 — a nova coluna não traz direção independente. Repetindo o experimento, agora olhando diretamente para a invertibilidade de <span class="math inline">\(X^TX\)</span>:</p>
<div id="a1554076" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>X_com_duplicata <span class="op">=</span> np.column_stack([X_completo, <span class="fl">2.0</span> <span class="op">*</span> X_completo[:, <span class="dv">2</span>]])</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"posto de X:              "</span>, np.linalg.matrix_rank(X_completo))</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"posto de X com duplicata:"</span>, np.linalg.matrix_rank(X_com_duplicata))</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>XtX_dup <span class="op">=</span> X_com_duplicata.T <span class="op">@</span> X_com_duplicata</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"det(X^T X com duplicata):"</span>, np.linalg.det(XtX_dup))</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="cf">try</span>:</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    np.linalg.inv(XtX_dup)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="cf">except</span> np.linalg.LinAlgError <span class="im">as</span> erro:</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"np.linalg.inv falha:"</span>, erro)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>posto de X:               4
posto de X com duplicata: 4
det(X^T X com duplicata): 0.0
np.linalg.inv falha: Singular matrix</code></pre>
</div>
</div>
<p><span class="math inline">\(\det(X^TX)=0\)</span>: a matriz é singular, e <code>np.linalg.inv</code> recusa explicitamente (“Singular matrix”) — não há fórmula fechada <span class="math inline">\(\hat{\mathbf{w}}=(X^TX)^{-1}X^T\mathbf{y}\)</span> possível. Mas note a distinção crucial, já anunciada no Passo (i) do Bloco 4: a <em>projeção</em> <span class="math inline">\(\hat{\mathbf{y}}\)</span> continua perfeitamente bem definida — é o ponto de <span class="math inline">\(\text{col}(X)\)</span> mais próximo de <span class="math inline">\(\mathbf{y}\)</span>, e <span class="math inline">\(\text{col}(X)\)</span> não mudou (a coluna redundante não acrescenta nenhuma direção nova, Aula 2). O que deixou de ser único é <strong>como distribuir o crédito</strong> entre <code>AveRooms</code> e sua cópia <span class="math inline">\(2\times\)</span><code>AveRooms</code> — infinitos <span class="math inline">\(\hat{\mathbf{w}}\)</span> diferentes produzem exatamente o mesmo <span class="math inline">\(\hat{\mathbf{y}}=X\hat{\mathbf{w}}\)</span>. A sombra é única; a “receita” para chegar nela, não.</p>
</section>
<section id="caso-2-quase-multicolinearidade-xtx-mal-condicionada" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="caso-2-quase-multicolinearidade-xtx-mal-condicionada"><span class="header-section-number">6.3</span> Caso 2: Quase-Multicolinearidade — <span class="math inline">\(X^TX\)</span> Mal-Condicionada</h2>
<p>Multicolinearidade <strong>exata</strong> é rara em dados reais. O problema mais comum, já visto na Aula 2, é a quase-dependência entre <code>AveRooms</code> e <code>AveBedrms</code> (correlação <span class="math inline">\(0{,}865\)</span>) — posto continua completo (<span class="math inline">\(4\)</span>), a fórmula fechada ainda existe, mas fica <strong>numericamente frágil</strong>. Reaproveitando exatamente a amostra de 20 bairros e a perturbação de 1% da Aula 2, agora olhando para o número de condição de <span class="math inline">\(X^TX\)</span> em cada par:</p>
<div id="cd9d6c39" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>_amostra_20 <span class="op">=</span> _housing.sample(n<span class="op">=</span><span class="dv">20</span>, random_state<span class="op">=</span><span class="dv">7</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>X_quase_dep <span class="op">=</span> _amostra_20[[<span class="st">"AveRooms"</span>, <span class="st">"AveBedrms"</span>]].to_numpy()</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>X_bem_cond <span class="op">=</span> _amostra_20[[<span class="st">"MedInc"</span>, <span class="st">"HouseAge"</span>]].to_numpy()</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>cond_quase_dep <span class="op">=</span> np.linalg.cond(X_quase_dep.T <span class="op">@</span> X_quase_dep)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>cond_bem_cond <span class="op">=</span> np.linalg.cond(X_bem_cond.T <span class="op">@</span> X_bem_cond)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"número de condição de X^TX (AveRooms, AveBedrms):  </span><span class="sc">{</span>cond_quase_dep<span class="sc">:,.1f}</span><span class="ss">"</span>)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"número de condição de X^TX (MedInc, HouseAge):     </span><span class="sc">{</span>cond_bem_cond<span class="sc">:,.1f}</span><span class="ss">"</span>)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">número de condição de X^TX completo (4 atributos): </span><span class="sc">{</span>np<span class="sc">.</span>linalg<span class="sc">.</span>cond(XtX)<span class="sc">:,.1f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>número de condição de X^TX (AveRooms, AveBedrms):  419.8
número de condição de X^TX (MedInc, HouseAge):     169.1

número de condição de X^TX completo (4 atributos): 23,460.5</code></pre>
</div>
</div>
<p>O par quase-dependente tem número de condição <span class="math inline">\(\approx 420\)</span> contra <span class="math inline">\(\approx 169\)</span> do par bem-condicionado — mais de o dobro, um sinal numérico direto de fragilidade (definição formal na Aula 4). E lembrando o resultado já demonstrado na Aula 2, reproduzido aqui como consequência direta desse número de condição alto: perturbar <code>MedHouseVal</code> em apenas <span class="math inline">\(1\%\)</span> do seu desvio-padrão muda o peso de <code>AveBedrms</code> em <span class="math inline">\(\approx 29{,}5\%\)</span> no par quase-dependente, contra <span class="math inline">\(\approx 0{,}1\%\)</span> no par bem-condicionado sob a mesma perturbação — quase 300 vezes mais sensível. O número de condição do <span class="math inline">\(X^TX\)</span> com os 4 atributos completos (<span class="math inline">\(\approx 23\,460\)</span>) é ainda maior, porque combina a informação redundante de <code>AveRooms</code>/ <code>AveBedrms</code> com a escala natural de todos os atributos — mas o efeito é o mesmo em espécie: <span class="math inline">\(X^TX\)</span> tecnicamente invertível, porém perto o suficiente de singular para que pequenos erros nos dados produzam grandes oscilações no <span class="math inline">\(\hat{\mathbf{w}}\)</span> calculado.</p>
<p><strong>A mesma distinção do Caso 1, com um grau de intensidade menor:</strong> a projeção <span class="math inline">\(\hat{\mathbf{y}}\)</span> (a previsão do modelo) muda pouco com a perturbação — é a <em>decomposição</em> dos pesos <span class="math inline">\(\hat{\mathbf{w}}\)</span> entre as duas colunas quase-redundantes que oscila. Medir e nomear essa sensibilidade com precisão — o número de condição, calculado a partir dos autovalores de <span class="math inline">\(X^TX\)</span>, não só estimado por um experimento de perturbação — é exatamente o que abre a Aula 4.</p>
<div class="fig-resize" style="width: 78%; margin: 0 auto;">
<img src="index_files/mediabag/03399b12a822d6b3b730b1638cfc7cd63c7c475b.svg" class="img-fluid">
</div>
<p>O diagrama resume os dois caminhos: multicolinearidade exata quebra a invertibilidade de <span class="math inline">\(X^TX\)</span> (posto deficiente), enquanto multicolinearidade quase-exata preserva o posto completo mas deixa <span class="math inline">\(X^TX\)</span> mal-condicionada — dois sintomas de gravidade diferente, mas da mesma causa raiz (colunas de <span class="math inline">\(X\)</span> carregando informação redundante), com o mesmo alívio parcial em comum: a projeção <span class="math inline">\(\hat{\mathbf{y}}\)</span> nunca é o problema; o problema mora inteiramente em como <span class="math inline">\(\hat{\mathbf{w}}\)</span> tenta descrevê-la.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Se <span class="math inline">\(X^TX\)</span> está mal-condicionada, a previsão <span class="math inline">\(\hat{\mathbf{y}}=X\hat{\mathbf{w}}\)</span> também fica proporcionalmente instável sob a mesma perturbação dos dados?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: releia o que os números do Caso 2 mostraram sobre <span class="math inline">\(\hat{\mathbf{w}}\)</span> vs.&nbsp;<span class="math inline">\(\hat{\mathbf{y}}\)</span> — a instabilidade tem o mesmo tamanho nos dois?</p>
<ul>
<li>□ Se a coluna duplicada fabricada no Caso 1 fosse uma combinação de duas colunas originais (não um múltiplo de uma única coluna), em vez de exatamente <span class="math inline">\(2\times\)</span><code>AveRooms</code>, o posto de <span class="math inline">\(X\)</span> ainda cairia da mesma forma ao ser adicionada.</li>
<li>□ No caso-limite em que a correlação entre <code>AveRooms</code> e <code>AveBedrms</code> fosse exatamente <span class="math inline">\(1\)</span> (em vez de <span class="math inline">\(0{,}865\)</span>), <span class="math inline">\(X^TX\)</span> deixaria de ser invertível, e a fórmula fechada <span class="math inline">\(\hat{\mathbf{w}}=(X^TX)^{-1}X^T\mathbf{y}\)</span> deixaria de estar definida.</li>
<li>□ Num modelo de crédito com dois atributos quase redundantes (ex.: “renda mensal” e “renda anual dividida por 12”, com pequena diferença por arredondamento), o mesmo sintoma de instabilidade numérica no peso estimado apareceria, mesmo sem nenhuma coluna exatamente duplicada.</li>
<li>□ Como <span class="math inline">\(X^TX\)</span> mal-condicionada torna <span class="math inline">\(\hat{\mathbf{w}}\)</span> instável, isso implica que a previsão <span class="math inline">\(\hat{\mathbf{y}}=X\hat{\mathbf{w}}\)</span> também se torna proporcionalmente instável sob a mesma perturbação dos dados.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="fechamento-e-ponte-para-a-aula-4" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Fechamento e Ponte para a Aula 4</h1>
<hr>
<section id="retomando-as-perguntas-de-abertura" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="retomando-as-perguntas-de-abertura">Retomando as perguntas de abertura</h3>
<ol type="1">
<li><strong>O que significa “a melhor aproximação possível”?</strong> O ponto <span class="math inline">\(\hat{\mathbf{y}}\in\text{col}(X)\)</span> que minimiza <span class="math inline">\(\|\mathbf{y}-\hat{\mathbf{y}}\|\)</span> — e essa minimização é equivalente a uma condição geométrica exata: o resíduo ortogonal a todo o subespaço.</li>
<li><strong>O que é projetar sobre um subespaço, e por que resolve o problema?</strong> É encontrar exatamente esse <span class="math inline">\(\hat{\mathbf{y}}\)</span> — a “sombra” perpendicular do Bloco 2, formalizada no Teorema da Projeção do Bloco 4.</li>
<li><strong>Como isso vira uma fórmula calculável?</strong> As <strong>Equações Normais</strong>, <span class="math inline">\(X^TX\hat{\mathbf{w}}=X^T\mathbf{y}\)</span>, e sob posto completo, <span class="math inline">\(\hat{\mathbf{w}}=(X^TX)^{-1}X^T\mathbf{y}\)</span> — verificado com números reais no Bloco 5 (comparação com <code>lstsq</code>, ortogonalidade do resíduo).</li>
<li><strong>Quando essa fórmula falha, ou fica frágil?</strong> Multicolinearidade exata quebra a invertibilidade de <span class="math inline">\(X^TX\)</span> (<span class="math inline">\(\hat{\mathbf{w}}\)</span> não-único, <span class="math inline">\(\hat{\mathbf{y}}\)</span> ainda único); quase-multicolinearidade preserva o posto completo, mas deixa <span class="math inline">\(X^TX\)</span> mal-condicionada (<span class="math inline">\(\hat{\mathbf{w}}\)</span> instável).</li>
</ol>
</section>
<section id="o-que-fica-em-aberto" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="o-que-fica-em-aberto">O Que Fica em Aberto</h3>
<p>A fórmula fechada <span class="math inline">\(\hat{\mathbf{w}}=(X^TX)^{-1}X^T\mathbf{y}\)</span> é a forma mais simples de <strong>descrever</strong> a solução — mas não é a forma mais <strong>estável</strong> de calculá-la quando <span class="math inline">\(X^TX\)</span> está mal-condicionada, como o Bloco 6 acabou de mostrar. O número de condição foi usado aqui de forma empírica (perturbar os dados e medir o efeito) — a Aula 4 dá a ferramenta exata para medi-lo diretamente a partir da estrutura de <span class="math inline">\(X^TX\)</span> (seus <strong>autovalores</strong> e <strong>autovetores</strong>), sem precisar perturbar nada. Essa mesma ferramenta é o que vai motivar, mais adiante no curso, métodos numéricos mais estáveis do que inverter <span class="math inline">\(X^TX\)</span> diretamente — decomposição <span class="math inline">\(QR\)</span> e <span class="math inline">\(SVD\)</span> — que resolvem as Equações Normais sem nunca formar <span class="math inline">\(X^TX\)</span> explicitamente.</p>
</section>
</section>
<section id="exercícios" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Exercícios</h1>
<section id="questões-discursivas" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="questões-discursivas"><span class="header-section-number">8.1</span> Questões discursivas</h2>
<ol type="1">
<li><p>Explique, com suas próprias palavras e usando a linguagem geométrica do Bloco 2 (a “sombra”), por que minimizar <span class="math inline">\(\|\mathbf{y}-X\mathbf{w}\|\)</span> é equivalente à condição de ortogonalidade <span class="math inline">\((\mathbf{y}-X\hat{\mathbf{w}})\perp\text{col}(X)\)</span>. Por que essa equivalência é o que permite transformar um problema de otimização (minimizar uma distância) numa equação linear (as Equações Normais)?</p></li>
<li><p>Compare os dois casos do Bloco 6 — multicolinearidade exata (posto deficiente) e quase-multicolinearidade (posto completo, mas mal-condicionada) — explicando, para cada um, o que acontece com a projeção <span class="math inline">\(\hat{\mathbf{y}}\)</span> e o que acontece com o vetor de pesos <span class="math inline">\(\hat{\mathbf{w}}\)</span>. Por que a distinção entre essas duas grandezas é a chave para entender os dois casos?</p></li>
<li><p>A Aula 2 provou que <span class="math inline">\(X^TX\)</span> é invertível se, e somente se, <span class="math inline">\(X\)</span> tem posto completo. Explique como essa condição de invertibilidade entra exatamente no Passo (iv) da derivação das Equações Normais desta aula, e o que aconteceria à derivação (não só ao resultado final) se essa condição não fosse satisfeita.</p></li>
</ol>
</section>
<section id="questões-de-verdadeirofalso" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="questões-de-verdadeirofalso"><span class="header-section-number">8.2</span> Questões de Verdadeiro/Falso</h2>
<p>Cada bloco de 4 itens trata do mesmo tema. A questão só é considerada correta se todos os 4 itens forem julgados corretamente (deixar em branco tem penalidade de 20% da nota da questão).</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Sistemas sobredeterminados e a melhor aproximação
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>□ Se um sistema <span class="math inline">\(A\mathbf{x}=\mathbf{b}\)</span> fosse subdeterminado (<span class="math inline">\(n&gt;m\)</span>) em vez de sobredeterminado, ainda haveria um sentido útil para “melhor aproximação” via projeção, mas ele coincidiria trivialmente com uma das infinitas soluções exatas, não com um ponto fora do espaço-coluna de <span class="math inline">\(A\)</span>.</li>
<li>□ No caso-limite em que <span class="math inline">\(\mathbf{y}\)</span> está exatamente sobre o espaço-coluna de <span class="math inline">\(X\)</span>, a “melhor aproximação” <span class="math inline">\(\hat{\mathbf{y}}=X\hat{\mathbf{w}}\)</span> coincide com <span class="math inline">\(\mathbf{y}\)</span>, e o problema de mínimos quadrados se reduz ao caso já resolvido pela Aula 2 (sistema com solução exata).</li>
<li>□ Num problema de previsão de demanda de energia elétrica, com muito mais medições horárias (equações) do que parâmetros do modelo físico a estimar (incógnitas), a mesma lógica de “sistema sobredeterminado sem solução exata, resolvido por projeção” se aplicaria.</li>
<li>□ Como um sistema sobredeterminado não tem solução exata, isso implica que qualquer <span class="math inline">\(\mathbf{w}\)</span> escolhido produzirá um erro de magnitude semelhante — a escolha de <span class="math inline">\(\mathbf{w}\)</span> não afetaria significativamente a qualidade da aproximação.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>A intuição da sombra
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>□ Se a fonte de luz da analogia da sombra viesse de um ângulo oblíquo fixo (não perpendicular ao subespaço), o ponto de chegada no subespaço, em geral, não seria mais o ponto mais próximo do ponto original.</li>
<li>□ No caso-limite em que o subespaço <span class="math inline">\(U\)</span> tem a mesma dimensão do espaço ambiente (<span class="math inline">\(U=V\)</span>), a “sombra” de qualquer ponto sobre <span class="math inline">\(U\)</span> coincide com o próprio ponto, para qualquer ponto escolhido.</li>
<li>□ A ideia de reduzir a dimensionalidade de dados de alta dimensão para visualização (ex.: reduzir atributos de um dataset para 2 dimensões e plotar um gráfico de dispersão) usa, na essência, a mesma operação geométrica de projeção perpendicular discutida nesta aula.</li>
<li>□ Como a projeção perpendicular minimiza a distância ao subespaço, ela produz sempre o ponto de menor norma dentro do subespaço, entre todos os candidatos.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Subespaços e o complemento ortogonal
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>□ Se <span class="math inline">\(U\)</span> e <span class="math inline">\(W\)</span> são dois subespaços distintos de mesma dimensão <span class="math inline">\(M\)</span> dentro de um espaço <span class="math inline">\(V\)</span> de dimensão <span class="math inline">\(D\)</span>, seus complementos ortogonais <span class="math inline">\(U^\perp\)</span> e <span class="math inline">\(W^\perp\)</span> têm, necessariamente, a mesma dimensão entre si (<span class="math inline">\(D-M\)</span>), ainda que <span class="math inline">\(U^\perp \ne W^\perp\)</span> como conjuntos.</li>
<li>□ No caso-limite <span class="math inline">\(M=D\)</span> (o subespaço é o espaço inteiro), o complemento ortogonal se reduz ao subespaço trivial <span class="math inline">\(\{\mathbf{0}\}\)</span>.</li>
<li>□ Em processamento de sinais, decompor um sinal de áudio em uma componente dentro de uma banda de frequência específica (um subespaço) e uma componente fora dela usa a mesma lógica de decomposição única <span class="math inline">\(V=U\oplus U^\perp\)</span> discutida nesta aula.</li>
<li>□ Como todo vetor de <span class="math inline">\(V\)</span> se decompõe de forma única em <span class="math inline">\(U\oplus
U^\perp\)</span>, isso implica que essa decomposição é a única forma possível de escrever qualquer vetor de <span class="math inline">\(V\)</span> como soma de dois vetores de <span class="math inline">\(V\)</span>.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Definição formal de projeção
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>□ Se <span class="math inline">\(\pi:V\to U\)</span> satisfaz <span class="math inline">\(\pi^2=\pi\)</span>, então, para qualquer vetor <span class="math inline">\(\mathbf{u}\)</span> que já pertença a <span class="math inline">\(U\)</span>, necessariamente <span class="math inline">\(\pi(\mathbf{u}) =
\mathbf{u}\)</span>.</li>
<li>□ No caso-limite em que a matriz de projeção <span class="math inline">\(P_\pi\)</span> é a matriz identidade, o subespaço <span class="math inline">\(U\)</span> sobre o qual ela projeta é o espaço ambiente <span class="math inline">\(V\)</span> inteiro.</li>
<li>□ Num sistema de compressão de vídeo que descarta certas componentes de frequência (mantendo só um subconjunto), a operação de manter as componentes retidas e descartar as demais pode ser descrita, de forma exata, por uma matriz de projeção <span class="math inline">\(P_\pi\)</span> com <span class="math inline">\(P_\pi^2=P_\pi\)</span>.</li>
<li>□ Como toda matriz de projeção satisfaz <span class="math inline">\(P_\pi^2=P_\pi\)</span>, isso significa que qualquer matriz quadrada que satisfaça essa condição algébrica também é, necessariamente, simétrica.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Derivação das Equações Normais
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>□ Se a condição de ortogonalidade fosse verificada apenas para algumas colunas de <span class="math inline">\(X\)</span> (não todas), em vez de todas as <span class="math inline">\(d\)</span> colunas, isso não seria suficiente, em geral, para garantir que o resíduo é ortogonal a todo o espaço-coluna de <span class="math inline">\(X\)</span>.</li>
<li>□ No caso-limite <span class="math inline">\(d=1\)</span> (uma única coluna, isto é, <span class="math inline">\(X\)</span> é um vetor-coluna <span class="math inline">\(\mathbf{x}\in\mathbb{R}^N\)</span>), as Equações Normais <span class="math inline">\(X^TX\hat{\mathbf{w}}=X^T\mathbf{y}\)</span> se reduzem a uma única equação escalar, <span class="math inline">\(\hat{w}=\dfrac{\mathbf{x}^T\mathbf{y}}{\mathbf{x}^T\mathbf{x}}\)</span>.</li>
<li>□ Num problema de estimar um único parâmetro físico (temperatura média) a partir de <span class="math inline">\(N\)</span> leituras redundantes de um termômetro (cada leitura sendo <span class="math inline">\(y_i = \theta + \text{ruído}\)</span>), a mesma derivação das Equações Normais levaria a uma estimativa que é, essencialmente, a média das leituras.</li>
<li>□ Como as Equações Normais são obtidas impondo ortogonalidade coluna a coluna, isso implica que, se duas colunas de <span class="math inline">\(X\)</span> forem ortogonais entre si, a equação normal correspondente a cada uma delas pode ser resolvida de forma totalmente independente da outra, sem nenhum termo cruzado.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Invertibilidade de <span class="math inline">\(X^TX\)</span> e a pseudo-inversa
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>□ Se <span class="math inline">\(X\)</span> tivesse posto deficiente (colunas linearmente dependentes), <span class="math inline">\(X^TX\)</span> deixaria de ser invertível, mas isso não impediria, por si só, que existisse <strong>algum</strong> <span class="math inline">\(\hat{\mathbf{w}}\)</span> satisfazendo as Equações Normais — apenas deixaria de haver um único.</li>
<li>□ No caso-limite em que <span class="math inline">\(X\)</span> tem uma única coluna não-nula (<span class="math inline">\(d=1\)</span>, <span class="math inline">\(\mathbf{x}\ne\mathbf{0}\)</span>), <span class="math inline">\(X^TX\)</span> é sempre invertível (é um escalar positivo).</li>
<li>□ Num problema de reconstrução de sinais com uma matriz de observação <span class="math inline">\(X\)</span> de posto deficiente, a pseudo-inversa <span class="math inline">\((X^TX)^{-1}X^T\)</span> não pode ser calculada da forma usual, mas existem generalizações (pseudo-inversa de Moore-Penrose, via SVD) que contornam exatamente esse problema.</li>
<li>□ Como <span class="math inline">\((X^TX)^{-1}X^T\)</span> é chamada de pseudo-inversa de <span class="math inline">\(X\)</span>, isso significa que ela satisfaz <span class="math inline">\(X\cdot(X^TX)^{-1}X^T = I\)</span> (a identidade), do mesmo jeito que uma inversa de matriz quadrada de verdade.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Aplicação numérica e verificação de ortogonalidade
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>□ Se, em vez de comparar <span class="math inline">\(\hat{\mathbf{w}}\)</span> obtido pela fórmula fechada com <code>np.linalg.lstsq</code>, comparássemos com uma resolução por eliminação de Gauss do sistema <span class="math inline">\(X^TX\hat{\mathbf{w}}=X^T\mathbf{y}\)</span>, esperaríamos, a menos de erro de arredondamento, o mesmo vetor.</li>
<li>□ No caso-limite em que <span class="math inline">\(\mathbf{y}\)</span> é o vetor nulo, o <span class="math inline">\(\hat{\mathbf{w}}\)</span> que resolve as Equações Normais (com <span class="math inline">\(X\)</span> de posto completo) é necessariamente o vetor nulo também.</li>
<li>□ Num experimento de física em que um pesquisador mede a mesma grandeza <span class="math inline">\(N\)</span> vezes com ruído aleatório, verificar que o resíduo entre o valor estimado e as medições é ortogonal aos “atributos” do modelo é um teste válido de correção, do mesmo jeito que foi usado nesta aula para o California Housing.</li>
<li>□ Como o resíduo é ortogonal a cada coluna de <span class="math inline">\(X\)</span>, isso implica que o modelo captura toda a informação relevante contida nos dados disponíveis para prever <span class="math inline">\(\mathbf{y}\)</span>.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span><span class="math inline">\(R^2\)</span> e o que a ortogonalidade do resíduo garante
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>□ Se o <span class="math inline">\(R^2\)</span> do ajuste fosse exatamente <span class="math inline">\(0\)</span> (o modelo não explica nada da variação de <span class="math inline">\(\mathbf{y}\)</span> além da média), o resíduo ainda seria ortogonal a cada coluna de <span class="math inline">\(X\)</span>, contanto que <span class="math inline">\(\hat{\mathbf{w}}\)</span> resolva as Equações Normais.</li>
<li>□ No caso-limite <span class="math inline">\(R^2=1\)</span> (ajuste perfeito), o resíduo <span class="math inline">\(\mathbf{y}-X\hat{\mathbf{w}}\)</span> é o vetor nulo.</li>
<li>□ Num modelo de previsão de nota de estudantes usando só o número de horas de sono (um único atributo, claramente insuficiente para prever notas), seria possível obter um <span class="math inline">\(R^2\)</span> baixo e, ainda assim, um resíduo perfeitamente ortogonal a essa única coluna — exatamente como ocorreu com os 4 atributos do California Housing nesta aula.</li>
<li>□ Como o resíduo é sempre ortogonal ao espaço-coluna de <span class="math inline">\(X\)</span> quando <span class="math inline">\(\hat{\mathbf{w}}\)</span> resolve as Equações Normais, um <span class="math inline">\(R^2\)</span> baixo indica necessariamente um erro no cálculo de <span class="math inline">\(\hat{\mathbf{w}}\)</span>, não uma limitação dos atributos escolhidos.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Posto e multicolinearidade exata (conexão com a Aula 2)
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>□ Se a coluna redundante fabricada no Bloco 6 fosse <span class="math inline">\(-5\times\)</span><code>AveRooms</code> em vez de <span class="math inline">\(2\times\)</span><code>AveRooms</code>, o posto de <span class="math inline">\(X\)</span> ainda cairia da mesma forma ao ser adicionada (permaneceria em 4, não subiria para 5).</li>
<li>□ No caso-limite em que todas as <span class="math inline">\(d\)</span> colunas de <span class="math inline">\(X\)</span> fossem múltiplos escalares de uma única coluna não-nula, o posto de <span class="math inline">\(X\)</span> seria exatamente <span class="math inline">\(1\)</span>, independentemente do valor de <span class="math inline">\(d\)</span>.</li>
<li>□ Num dataset de sensores IoT em que um atributo é reportado tanto em Celsius quanto em Fahrenheit (uma transformação linear afim exata da outra, não apenas um múltiplo escalar), a inclusão de ambas as colunas na matriz de design também produziria posto deficiente, pelo mesmo princípio da coluna duplicada exata desta aula.</li>
<li>□ Como a coluna redundante fabricada não acrescenta nenhuma direção independente ao espaço-coluna de <span class="math inline">\(X\)</span>, isso implica que removê-la necessariamente reduz a qualidade das previsões do modelo ajustado.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Quase-multicolinearidade e número de condição (preview da Aula 4)
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>□ Se, em vez de perturbar <code>MedHouseVal</code> em 1% do desvio-padrão, perturbássemos em 10 vezes esse valor (10% do desvio-padrão), a variação relativa esperada no peso de <code>AveBedrms</code> no par quase-dependente seria, ao menos aproximadamente, também maior do que a observada com a perturbação de 1% — o número de condição alto amplifica perturbações maiores tanto quanto amplifica as pequenas.</li>
<li>□ No caso-limite em que o número de condição de <span class="math inline">\(X^TX\)</span> tende a infinito, <span class="math inline">\(X^TX\)</span> se torna, no limite, singular (não invertível).</li>
<li>□ Num modelo de precificação de opções financeiras com duas variáveis de entrada quase redundantes (ex.: duas medidas de volatilidade calculadas por métodos ligeiramente diferentes), a mesma fragilidade numérica (pesos instáveis sob pequena perturbação dos dados) apareceria, mesmo com o posto de <span class="math inline">\(X\)</span> tecnicamente completo.</li>
<li>□ Como o número de condição de <span class="math inline">\(X^TX\)</span> com os 4 atributos completos (<span class="math inline">\(\approx 23\,460\)</span>) é maior do que o do par isolado <code>AveRooms</code>/<code>AveBedrms</code> (<span class="math inline">\(\approx 420\)</span>), isso implica que a previsão <span class="math inline">\(\hat{\mathbf{y}}\)</span> do modelo completo é proporcionalmente mais instável do que a previsão do modelo com só esse par de atributos.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>A matriz de projeção <span class="math inline">\(P_\pi\)</span>
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>□ Se, em vez de projetar <span class="math inline">\(\mathbf{y}\)</span> sobre <span class="math inline">\(\text{col}(X)\)</span>, quiséssemos projetar sobre um subespaço diferente gerado pelas colunas de outra matriz <span class="math inline">\(Z\)</span> (mesmas dimensões de <span class="math inline">\(X\)</span>), a matriz de projeção correspondente seria <span class="math inline">\(P_\pi'=Z(Z^TZ)^{-1}Z^T\)</span>, com a mesma propriedade <span class="math inline">\(P_\pi'^2=P_\pi'\)</span>.</li>
<li>□ No caso-limite em que as colunas de <span class="math inline">\(X\)</span> já são ortonormais (<span class="math inline">\(X^TX=I\)</span>), a matriz de projeção se simplifica para <span class="math inline">\(P_\pi=XX^T\)</span>.</li>
<li>□ Em compressão de imagem via PCA, manter apenas as <span class="math inline">\(k\)</span> componentes principais mais informativas e descartar as demais pode ser descrito por uma matriz de projeção <span class="math inline">\(P_\pi\)</span> com as mesmas propriedades (<span class="math inline">\(P_\pi^2=P_\pi\)</span>, simétrica) discutidas nesta aula.</li>
<li>□ Como <span class="math inline">\(P_\pi=X(X^TX)^{-1}X^T\in\mathbb{R}^{N\times N}\)</span> e toda matriz quadrada invertível que satisfaz <span class="math inline">\(P^2=P\)</span> só pode ser a identidade, isso implica que <span class="math inline">\(P_\pi\)</span> só pode ser a matriz identidade quando <span class="math inline">\(X\)</span> tem posto completo.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Síntese: da falta de solução à ponte para a Aula 4
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>□ Se a Aula 4 mostrasse que o número de condição de <span class="math inline">\(X^TX\)</span> pode ser calculado exatamente a partir da razão entre o maior e o menor autovalor de <span class="math inline">\(X^TX\)</span>, isso tornaria desnecessário o tipo de experimento de perturbação numérica usado no Bloco 6 desta aula para <em>detectar</em> fragilidade — mas o experimento de perturbação continuaria sendo uma forma válida de <em>demonstrar</em> o efeito prático dessa fragilidade.</li>
<li>□ No caso-limite em que <span class="math inline">\(X\)</span> tem colunas mutuamente ortogonais e todas de norma <span class="math inline">\(1\)</span> (uma base ortonormal do espaço-coluna), o número de condição de <span class="math inline">\(X^TX\)</span> é exatamente <span class="math inline">\(1\)</span> — o melhor condicionamento numérico possível.</li>
<li>□ Num pipeline de aprendizado de máquina em que os atributos de entrada são primeiro padronizados (média 0, desvio-padrão 1) antes do ajuste, essa etapa de pré-processamento pode, dependendo dos dados, influenciar o número de condição de <span class="math inline">\(X^TX\)</span> resultante, mesmo sem alterar o posto de <span class="math inline">\(X\)</span>.</li>
<li>□ Como as Equações Normais fornecem uma fórmula fechada exata para <span class="math inline">\(\hat{\mathbf{w}}\)</span> sempre que <span class="math inline">\(X\)</span> tem posto completo, isso implica que essa fórmula é sempre o método numericamente mais recomendado para calcular <span class="math inline">\(\hat{\mathbf{w}}\)</span> na prática, independentemente do número de condição de <span class="math inline">\(X^TX\)</span>.</li>
</ul>
</div>
</div>
</section>
<section id="aviso" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="aviso"><span class="header-section-number">8.3</span> Aviso</h2>
<p>As questões de Verdadeiro/Falso e discursivas ficam sem solução neste arquivo — são para resolução autônoma do aluno, fora do horário de aula.</p>


</section>
</section>

</main> <!-- /main -->
<!-- Parcial estático, igual em toda aula (não é mais gerado por script —
     ver histórico do teaching/generate_lesson_nav.py, removido). Só
     carrega o script que transforma o sumário nativo do Quarto (#TOC,
     "Nesta página") no painel de acordeão "Nesta aula". -->
<script src="../../toc-accordion.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© 2026 Marcos M. Raimundo</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>