<!DOCTYPE html>
<html lang="pt-BR"><head>
<link href="../../../more.png" rel="icon" type="image/png">
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.18">

  <meta name="author" content="Prof.&nbsp;Marcos Medeiros Raimundo">
  <meta name="dcterms.date" content="2026-08-30">
  <title>Marcos M. Raimundo – Aula 3: Projeções Ortogonais e Subespaços</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../../../site_libs/revealjs/dist/theme/quarto-9af0d15343d0ec36e497a4ab60ddbc72.css">
  <link href="../../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <!-- O tema "simple" do RevealJS não carrega bootstrap-icons.css sozinho
       (isso só acontece no formato HTML, via bootstrap) — sem este link, um
       ícone `<i class="bi bi-...">` usado em qualquer include do RevealJS
       (ex.: ../../logos-footer.html) fica invisível nos slides. Caminho
       relativo à página de SAÍDA (aulaNN/slides.html), não a este arquivo:
       site_libs/ mora na raiz do site, três níveis acima de aulaNN/. -->
  <link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-image="../../UNICAMP.png, ../../IC.png" data-background-position="5% 8%, 95% 8%" data-background-size="140px, 140px" class="quarto-title-block center">
  <h1 class="title">Aula 3: Projeções Ortogonais e Subespaços</h1>
  <p class="subtitle">Álgebra Linear e Otimização para Aprendizado de Máquina</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Prof.&nbsp;Marcos Medeiros Raimundo
</div>
</div>
</div>

  <p class="date">2026-08-30</p>
</section>
<section>
<section id="o-problema-que-a-aula-2-deixou-em-aberto" class="title-slide slide level1 center">
<h1>O Problema Que a Aula 2 Deixou em Aberto</h1>

</section>
<section id="revisão-rápida-onde-a-aula-2-parou-1" class="slide level2">
<h2>Revisão Rápida: Onde a Aula 2 Parou</h2>
<div class="fragment">
<p>Aula 2: matriz de design <span class="math inline">\(X\in\mathbb{R}^{N\times d}\)</span>, duas leituras de <span class="math inline">\(A\mathbf{x}\)</span> (linha = previsão, coluna = combinação linear), sistemas lineares com 0, 1 ou <span class="math inline">\(\infty\)</span> soluções via o posto.</p>
</div>
<div class="fragment">
<p>Peça central: <span class="math inline">\(X\mathbf{w}=\mathbf{y}\)</span> tem <span class="math inline">\(N\)</span> equações, <span class="math inline">\(d\)</span> incógnitas. Em ML real, <span class="math inline">\(N\gg d\)</span> — <strong>sobredeterminado</strong>, genericamente <strong>sem solução exata</strong>.</p>
</div>
<h3 id="de-sem-solução-para-melhor-aproximação">De “Sem Solução” Para “Melhor Aproximação”</h3>
<div class="fragment">
<p>“Sem solução exata” não é “sem solução que preste”. O próprio MathML aponta a saída: “a ideia é encontrar o vetor no subespaço gerado pelas colunas de <span class="math inline">\(A\)</span> que está mais próximo de <span class="math inline">\(\mathbf{b}\)</span>” (tradução nossa, §3.8.2).</p>
</div>
<div class="fragment">
<p>“Mais próximo, mas dentro de onde?” — geométrico antes de algébrico. É o fio desta aula.</p>
</div>
</section>
<section id="roteiro-da-aula-1" class="slide level2">
<h2>Roteiro da Aula</h2>
<div class="fragment">
<p><strong>1.</strong> O que significa “a melhor aproximação possível” de <span class="math inline">\(\mathbf{y}\)</span>?</p>
</div>
<div class="fragment">
<p><strong>2.</strong> O que é projetar sobre um subespaço, e por que resolve o problema 1?</p>
</div>
<div class="fragment">
<p><strong>3.</strong> Como isso vira uma fórmula calculável — as <strong>Equações Normais</strong>?</p>
</div>
<div class="fragment">
<p><strong>4.</strong> Quando essa fórmula falha, ou fica frágil, e por quê?</p>
</div>
</section>
<section id="problema-motivador-1" class="slide level2">
<h2>Problema Motivador</h2>
<div class="fragment">
<p>California Housing: <span class="math inline">\(N=16\,640\)</span> bairros, 4 atributos. Sistema <span class="math inline">\(X\mathbf{w}=\mathbf{y}\)</span>: <span class="math inline">\(16\,640\)</span> equações, <span class="math inline">\(4\)</span> incógnitas — sobredeterminado por uma margem enorme.</p>
</div>
<div class="fragment">
<p>Se <span class="math inline">\(X\mathbf{w}\)</span> nunca alcança <span class="math inline">\(\mathbf{y}\)</span> exatamente, <strong>qual</strong> <span class="math inline">\(X\mathbf{w}\)</span> alcançável está mais perto? “Mais perto” — medido como?</p>
</div>
<div class="fig-resize" style="width: 90%; margin: 0 auto;">
<img data-src="index_files/mediabag/cf778620246cb426b33fa7ea626111e4046a5173.svg" class="img-fluid">
</div>
</section>
<section id="pergunta" class="slide level2">
<h2>Pergunta</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Se <span class="math inline">\(X\mathbf{w}=\mathbf{y}\)</span> nunca é alcançado exatamente, existe sempre exatamente uma “melhor” aproximação, ou pode haver várias igualmente boas?</strong></p>
</div>
<div class="callout-content">
<p>Dica: a Aula 2 já classificou o número de soluções <strong>exatas</strong> de um sistema — 0, 1 ou <span class="math inline">\(\infty\)</span>. Trocar “exata” por “aproximada” muda essa contagem?</p>
<ul>
<li>□ Se o sistema fosse subdeterminado (<span class="math inline">\(N&lt;d\)</span>), a pergunta “qual é mais próximo?” mudaria de natureza: de erro irredutível para escolha entre infinitas soluções exatas.</li>
<li>□ No caso-limite <span class="math inline">\(N=d\)</span> com <span class="math inline">\(X\)</span> de posto completo, a melhor aproximação coincide exatamente com <span class="math inline">\(\mathbf{y}\)</span> (erro zero).</li>
<li>□ GPS com mais satélites que coordenadas: mesma lógica de projeção se aplica, outro domínio.</li>
<li>□ Sem solução exata, a Regressão Linear Múltipla perde toda utilidade.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="resposta" class="slide level2">
<h2>Resposta</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Se <span class="math inline">\(X\mathbf{w}=\mathbf{y}\)</span> nunca é alcançado exatamente, existe sempre uma “melhor” aproximação? — Resposta</strong></p>
</div>
<div class="callout-content">
<ul>
<li>✔ Subdeterminado: se solúvel, há <span class="math inline">\(\infty\)</span> soluções exatas — a pergunta vira “qual escolher”, não “qual erro minimizar”.</li>
<li>✔ <span class="math inline">\(N=d\)</span>, posto completo: sistema quadrado invertível, erro zero.</li>
<li>✔ GPS: mesma matemática, outro domínio (localização em vez de preço).</li>
<li>✗ Falta de solução exata não implica falta de utilidade — é exatamente o problema que esta aula resolve com projeção.</li>
</ul>
</div>
</div>
</div>
<div class="fragment">
<p><strong>Voltando à pergunta:</strong> no regime sobredeterminado desta aula (posto completo), existe <strong>exatamente uma</strong> melhor aproximação — é isso que o Bloco 4 vai provar, via projeção ortogonal.</p>
</div>
</section></section>
<section>
<section id="intuição-a-sombra-no-chão-não-no-ar" class="title-slide slide level1 center">
<h1>Intuição: A Sombra no Chão, Não no Ar</h1>

</section>
<section id="a-ideia-antes-da-álgebra-1" class="slide level2">
<h2>A Ideia Antes da Álgebra</h2>
<div class="fragment">
<p>Um ponto <span class="math inline">\(\mathbf{y}\)</span> flutuando no espaço; um subespaço <span class="math inline">\(U\)</span> (reta ou plano pela origem) como “o chão”. Luz perpendicular ao chão <span class="math inline">\(\Rightarrow\)</span> sombra <span class="math inline">\(\hat{\mathbf{y}}\)</span>.</p>
</div>
<div class="fragment">
<p><strong>Propriedade 1:</strong> <span class="math inline">\(\hat{\mathbf{y}}\)</span> é o ponto de <span class="math inline">\(U\)</span> mais próximo de <span class="math inline">\(\mathbf{y}\)</span> — nenhum outro ponto do chão está mais perto.</p>
</div>
<div class="fragment">
<p><strong>Propriedade 2:</strong> o segmento <span class="math inline">\(\mathbf{y}\to\hat{\mathbf{y}}\)</span> é perpendicular a <strong>todo</strong> <span class="math inline">\(U\)</span>, não só à direção da luz.</p>
</div>
<div class="fragment">
<p>A Propriedade 2 é a <em>razão</em> pela qual a Propriedade 1 é verdade — Bloco 4 prova isso formalmente. Por ora: reta ou plano, mesma operação, “chão” com mais dimensões.</p>
</div>
<div class="fig-resize" style="width: 100%; margin: 0 auto;">
<div id="2a919a98" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="index_files/figure-html/cell-3-output-1.png" class="quarto-figure quarto-figure-center" width="1199" height="536"></p>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="o-que-os-dois-painéis-mostram" class="slide level2">
<h2>O Que os Dois Painéis Mostram</h2>
<div class="fragment">
<p>Esquerda: <span class="math inline">\(U\)</span> = reta na direção <span class="math inline">\((2,1)\)</span>; <span class="math inline">\(\mathbf{y}=(1{,}0,3{,}2)\)</span> fora dela. Sombra <span class="math inline">\(\hat{\mathbf{y}}\)</span> = ponto da reta mais próximo; o tracejado encontra a reta em ângulo reto.</p>
</div>
<div class="fragment">
<p>Direita: “chão” = plano <span class="math inline">\(x_3=0\)</span> em <span class="math inline">\(\mathbb{R}^3\)</span>. Projeção só “zera” a componente perpendicular: <span class="math inline">\((1{,}5,1{,}8,2{,}3)\to(1{,}5,1{,}8,0)\)</span>.</p>
</div>
<div class="fragment">
<p>Em ambos, o tracejado é perpendicular a <strong>todo</strong> o subespaço — essa observação generaliza para <span class="math inline">\(\text{col}(X)\)</span>, com <span class="math inline">\(d=4\)</span> dimensões, não <span class="math inline">\(1\)</span> ou <span class="math inline">\(2\)</span>. A álgebra muda; a geometria, não.</p>
</div>
</section>
<section id="pergunta-1" class="slide level2">
<h2>Pergunta</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Se a “luz” da projeção não viesse perpendicular ao chão, o ponto resultante ainda seria o mais próximo de <span class="math inline">\(\mathbf{y}\)</span>?</strong></p>
</div>
<div class="callout-content">
<p>Dica: incline a direção da haste que liga <span class="math inline">\(\mathbf{y}\)</span> à sua sombra — o ponto de chegada continuaria sendo o mais próximo?</p>
<ul>
<li>□ Luz oblíqua (não perpendicular): o ponto resultante ainda seria o ponto do subespaço mais próximo de <span class="math inline">\(\mathbf{y}\)</span>.</li>
<li>□ Se <span class="math inline">\(\mathbf{y}\)</span> já pertencesse a <span class="math inline">\(U\)</span>, a sombra coincidiria com o próprio <span class="math inline">\(\mathbf{y}\)</span>, resíduo de norma zero.</li>
<li>□ Compressão de imagem via componentes principais é, geometricamente, a mesma projeção perpendicular discutida aqui, outro tipo de dado.</li>
<li>□ A sombra perpendicular, por minimizar distância, também maximiza a norma do ponto do subespaço.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="resposta-1" class="slide level2">
<h2>Resposta</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>A “luz” da projeção — Resposta</strong></p>
</div>
<div class="callout-content">
<ul>
<li>✗ Só a luz perpendicular garante o ponto mais próximo; qualquer ângulo oblíquo fixo geralmente erra o mínimo (é a mesma lógica do Teorema de Pitágoras: a hipotenusa de um triângulo oblíquo é maior que o cateto perpendicular).</li>
<li>✔ <span class="math inline">\(\mathbf{y}\in U \Rightarrow \hat{\mathbf{y}}=\mathbf{y}\)</span>, resíduo nulo — caso trivial, mas consistente.</li>
<li>✔ Mesma operação geométrica (projeção ortogonal), outro domínio (compressão/PCA, tema da disciplina de Aprendizado Não Supervisionado).</li>
<li>✗ Minimizar distância a <span class="math inline">\(\mathbf{y}\)</span> não tem relação com a norma do próprio ponto do subespaço — são duas quantidades independentes.</li>
</ul>
</div>
</div>
</div>
<div class="fragment">
<p><strong>Voltando à pergunta:</strong> só a perpendicular funciona — é exatamente a Propriedade 2 que o Bloco 4 vai provar ser <em>equivalente</em> à Propriedade 1 (mais próximo <span class="math inline">\(\iff\)</span> perpendicular), não só uma coincidência do desenho.</p>
</div>
</section></section>
<section>
<section id="subespaços-e-complemento-ortogonal" class="title-slide slide level1 center">
<h1>Subespaços e Complemento Ortogonal</h1>

</section>
<section id="recapitulando-subespaço-e-espaço-coluna-1" class="slide level2">
<h2>Recapitulando: Subespaço e Espaço-Coluna</h2>
<div class="fragment">
<p>Aula 1: subespaço = fechado sob soma/escalar. Aula 2: <strong>espaço-coluna</strong> <span class="math inline">\(\text{col}(X)\)</span> = tudo que <span class="math inline">\(X\mathbf{w}\)</span> alcança.</p>
</div>
<div class="fragment">
<p><span class="math inline">\(X\in\mathbb{R}^{16640\times 4}\)</span>, posto completo: <span class="math inline">\(\text{col}(X)\)</span> tem dimensão <span class="math inline">\(4\)</span> dentro de um ambiente de dimensão <span class="math inline">\(16\,640\)</span> — um “plano” finíssimo boiando num espaço gigantesco. <span class="math inline">\(\mathbf{y}\)</span> quase certamente fora dele.</p>
</div>
</section>
<section id="o-complemento-ortogonal-1" class="slide level2">
<h2>O Complemento Ortogonal</h2>
<div class="fragment">
<p><strong>Definição (MathML, §3.6, tradução nossa):</strong> dado <span class="math inline">\(U\subseteq V\)</span> com <span class="math inline">\(\dim U = M\)</span>, <span class="math inline">\(\dim V = D\)</span>, seu complemento ortogonal <span class="math inline">\(U^\perp\)</span> é um subespaço de dimensão <span class="math inline">\((D-M)\)</span>: todos os vetores de <span class="math inline">\(V\)</span> ortogonais a <strong>todo</strong> vetor de <span class="math inline">\(U\)</span>.</p>
</div>
<div class="fragment">
<p><span class="math inline">\(U\cap U^\perp=\{\mathbf{0}\}\)</span>; todo <span class="math inline">\(\mathbf{x}\in V\)</span> se decompõe de forma <strong>única</strong>: <span class="math display">\[\mathbf{x} = \underbrace{\sum_m \lambda_m\mathbf{b}_m}_{\in\, U} + \underbrace{\sum_j \psi_j\mathbf{b}_j^\perp}_{\in\, U^\perp}\]</span></p>
</div>
<div class="fragment">
<p>Notação compacta: <span class="math inline">\(V = U\oplus U^\perp\)</span> — uma única parte em <span class="math inline">\(U\)</span>, uma única parte em <span class="math inline">\(U^\perp\)</span>, nada sobra de fora.</p>
</div>
<div class="fig-resize" style="width: 70%; margin: 0 auto;">
<div id="bae96fc4" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="index_files/figure-html/cell-4-output-1.png" class="quarto-figure quarto-figure-center" width="591" height="607"></p>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="o-que-o-desenho-mostra" class="slide level2">
<h2>O Que o Desenho Mostra</h2>
<div class="fragment">
<p><span class="math inline">\(D=2\)</span>, <span class="math inline">\(U\)</span> = reta (<span class="math inline">\(M=1\)</span>) <span class="math inline">\(\Rightarrow\)</span> <span class="math inline">\(U^\perp\)</span> = reta perpendicular (<span class="math inline">\(D-M=1\)</span>). <span class="math inline">\(\mathbf{x}=(1,3)\)</span> decompõe-se de forma única: soma das duas setas recupera <span class="math inline">\(\mathbf{x}\)</span>, sem sobra, sem ambiguidade.</p>
</div>
<div class="fragment">
<p>Em <span class="math inline">\(\mathbb{R}^3\)</span> com <span class="math inline">\(U\)</span> = plano (<span class="math inline">\(M=2\)</span>): <span class="math inline">\(U^\perp\)</span> tem dimensão <span class="math inline">\(1\)</span> — o <strong>vetor normal</strong> do MathML, “<span class="math inline">\(\mathbf{w}\)</span> com <span class="math inline">\(\|\mathbf{w}\|=1\)</span>, ortogonal ao plano <span class="math inline">\(U\)</span>” (tradução nossa, §3.6).</p>
</div>
<div class="fragment">
<p>Na regressão: <span class="math inline">\(D=16\,640\)</span>, <span class="math inline">\(M=4\)</span>. <span class="math inline">\(U^\perp=\text{col}(X)^\perp\)</span> tem dimensão <span class="math inline">\(16\,636\)</span> — irrelevante em si; o que importa é que o resíduo <span class="math inline">\(\mathbf{y}-\hat{\mathbf{y}}\)</span> vive exatamente ali.</p>
</div>
</section>
<section id="pergunta-2" class="slide level2">
<h2>Pergunta</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Se <span class="math inline">\(U\)</span> fosse o subespaço trivial <span class="math inline">\(\{\mathbf{0}\}\)</span>, o que seria <span class="math inline">\(U^\perp\)</span>?</strong></p>
</div>
<div class="callout-content">
<p>Dica: <span class="math inline">\(U^\perp\)</span> contém todo vetor ortogonal a <strong>todo</strong> vetor de <span class="math inline">\(U\)</span>. Com <span class="math inline">\(U=\{\mathbf{0}\}\)</span>, quantos vetores de <span class="math inline">\(V\)</span> cumprem isso?</p>
<ul>
<li>□ <span class="math inline">\(U=\{\mathbf{0}\}\)</span> <span class="math inline">\(\Rightarrow\)</span> <span class="math inline">\(U^\perp = V\)</span> (o espaço inteiro).</li>
<li>□ <span class="math inline">\(U=V\)</span> <span class="math inline">\(\Rightarrow\)</span> <span class="math inline">\(U^\perp=\{\mathbf{0}\}\)</span>.</li>
<li>□ O resíduo ortogonal ao espaço-coluna de <span class="math inline">\(X\)</span> satisfaz a própria definição formal de pertencer a <span class="math inline">\(\text{col}(X)^\perp\)</span>, não só “ortogonal” informalmente.</li>
<li>□ Decomposição única de <span class="math inline">\(V\)</span> em <span class="math inline">\(U\oplus U^\perp\)</span> implica <span class="math inline">\(\dim U =
\dim U^\perp\)</span>.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="resposta-2" class="slide level2">
<h2>Resposta</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Subespaço trivial e seu complemento — Resposta</strong></p>
</div>
<div class="callout-content">
<ul>
<li>✔ Todo vetor de <span class="math inline">\(V\)</span> é ortogonal a <span class="math inline">\(\mathbf{0}\)</span> (produto interno com o vetor nulo é sempre <span class="math inline">\(0\)</span>); logo <span class="math inline">\(U^\perp=V\)</span>.</li>
<li>✔ Caso simétrico do anterior: só <span class="math inline">\(\mathbf{0}\)</span> é ortogonal a todo vetor de <span class="math inline">\(V=U\)</span>.</li>
<li>✔ É exatamente a definição de <span class="math inline">\(U^\perp\)</span> aplicada a <span class="math inline">\(U=\text{col}(X)\)</span> — antecipa o Bloco 4.</li>
<li>✗ <span class="math inline">\(\dim U=M\)</span>, <span class="math inline">\(\dim U^\perp=D-M\)</span>; iguais só se <span class="math inline">\(D=2M\)</span>, não em geral (na regressão, <span class="math inline">\(M=4 \ne D-M=16\,636\)</span>).</li>
</ul>
</div>
</div>
</div>
<div class="fragment">
<p><strong>Voltando à pergunta:</strong> o complemento ortogonal de <span class="math inline">\(\{\mathbf{0}\}\)</span> é o espaço todo — caso extremo que confirma a definição, não uma exceção a ela.</p>
</div>
</section></section>
<section>
<section id="o-teorema-da-projeção-premissas-e-passo-a-passo" class="title-slide slide level1 center">
<h1>O Teorema da Projeção: Premissas e Passo a Passo</h1>

</section>
<section id="enunciando-o-problema-com-precisão-1" class="slide level2">
<h2>Enunciando o Problema com Precisão</h2>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Nota</strong></p>
</div>
<div class="callout-content">
<p><strong>Premissas.</strong> 1. Subespaço <span class="math inline">\(U=\text{col}(X)\subseteq\mathbb{R}^N\)</span> (Aula 2). 2. <span class="math inline">\(\mathbf{y}\in\mathbb{R}^N\)</span>, em geral <strong>fora</strong> de <span class="math inline">\(U\)</span> (sobredeterminado). 3. <span class="math inline">\(\hat{\mathbf{y}}\in U\)</span> = ponto de <span class="math inline">\(U\)</span> mais próximo de <span class="math inline">\(\mathbf{y}\)</span> (minimiza <span class="math inline">\(\|\mathbf{y}-\hat{\mathbf{y}}\|\)</span>) — a “sombra” formalizada.</p>
</div>
</div>
</div>
<div class="fragment">
<p>Objetivo: dessas premissas até uma fórmula fechada e calculável para <span class="math inline">\(\hat{\mathbf{w}}\)</span>, com <span class="math inline">\(\hat{\mathbf{y}}=X\hat{\mathbf{w}}\)</span>.</p>
</div>
</section>
<section id="passo-i-mais-próximo-equivale-a-ortogonal-1" class="slide level2">
<h2>Passo (i): “Mais Próximo” Equivale a “Ortogonal”</h2>
<div class="fragment">
<p><strong>MathML (tradução nossa, §3.8.1):</strong> “a projeção é a mais próxima […] disso segue que o segmento […] é ortogonal a <span class="math inline">\(U\)</span>.” Minimizar distância e ser ortogonal a <span class="math inline">\(U\)</span> são a <strong>mesma condição</strong>.</p>
</div>
<div class="fragment">
<p><strong>Por quê:</strong> se o resíduo tivesse componente <strong>dentro</strong> de <span class="math inline">\(U\)</span>, dava para mover <span class="math inline">\(\hat{\mathbf{y}}\)</span> nessa direção e diminuir ainda mais a distância — contradiz mínimo. Logo, no mínimo, resíduo inteiro em <span class="math inline">\(U^\perp\)</span>: <span class="math display">\[\mathbf{y}-\hat{\mathbf{y}} \perp U \iff \mathbf{y}-\hat{\mathbf{y}}\in U^\perp\]</span></p>
</div>
</section>
<section id="passo-ii-escrevendo-hatmathbfy-em-termos-de-x-1" class="slide level2">
<h2>Passo (ii): Escrevendo <span class="math inline">\(\hat{\mathbf{y}}\)</span> em Termos de <span class="math inline">\(X\)</span></h2>
<div class="fragment">
<p><span class="math inline">\(\hat{\mathbf{y}}\in\text{col}(X)\)</span>: pela Leitura 2 (Aula 2), é <span class="math inline">\(X\mathbf{w}\)</span> para algum <span class="math inline">\(\mathbf{w}\)</span>. Chame esse vetor <span class="math inline">\(\hat{\mathbf{w}}\)</span>: <span class="math display">\[\hat{\mathbf{y}} = X\hat{\mathbf{w}}\]</span></p>
</div>
<div class="fragment">
<p>Substituindo no Passo (i): <span class="math display">\[\mathbf{y}-X\hat{\mathbf{w}} \perp \text{col}(X)\]</span></p>
</div>
</section>
<section id="passo-iii-ortogonal-a-cada-coluna-de-x-1" class="slide level2">
<h2>Passo (iii): Ortogonal a <em>Cada Coluna</em> de <span class="math inline">\(X\)</span></h2>
<div class="fragment">
<p>“Ortogonal a <span class="math inline">\(\text{col}(X)\)</span> inteiro” parece gigantesco, mas o MathML mostra que basta checar coluna a coluna (tradução nossa, §3.8.2): <span class="math inline">\(m\)</span> condições simultâneas <span class="math inline">\(\Rightarrow\)</span> sistema <span class="math inline">\(B^T(\mathbf{x}-B\lambda)=\mathbf{0}\)</span>.</p>
</div>
<div class="fragment">
<p><strong>Por quê basta as colunas:</strong> toda combinação linear delas herda a ortogonalidade — a ortogonalidade “passa” pela combinação sem se perder.</p>
</div>
<div class="fragment">
<p>Aplicando ao nosso caso: <span class="math display">\[X^T(\mathbf{y}-X\hat{\mathbf{w}}) = \mathbf{0}\]</span></p>
</div>
</section>
<section id="passo-iv-isolando-hatmathbfw-as-equações-normais-1" class="slide level2">
<h2>Passo (iv): Isolando <span class="math inline">\(\hat{\mathbf{w}}\)</span> — as Equações Normais</h2>
<div class="fragment">
<p>Distribuindo o Passo (iii): <span class="math display">\[X^T\mathbf{y} - X^TX\hat{\mathbf{w}} = \mathbf{0} \iff X^TX\hat{\mathbf{w}} = X^T\mathbf{y}\]</span></p>
</div>
<div class="fragment">
<p><strong>Equações Normais</strong> (MathML, eq. 3.56, tradução nossa) — um sistema linear em <span class="math inline">\(\hat{\mathbf{w}}\)</span>: <span class="math inline">\(X^TX\)</span> no papel de “<span class="math inline">\(A\)</span>”, <span class="math inline">\(X^T\mathbf{y}\)</span> no papel de “<span class="math inline">\(\mathbf{b}\)</span>” — mesma estrutura <span class="math inline">\(A\mathbf{x}=\mathbf{b}\)</span> da Aula 2.</p>
</div>
</section>
<section id="quando-o-sistema-tem-solução-única" class="slide level2">
<h2>Quando o Sistema Tem Solução Única</h2>
<div class="fragment">
<p>MathML (tradução nossa, §3.8.2): colunas de <span class="math inline">\(X\)</span> linearmente independentes <span class="math inline">\(\Rightarrow\)</span> <span class="math inline">\(X^TX\)</span> “regular, pode ser invertida” — exatamente o <strong>posto completo</strong> (<span class="math inline">\(\text{rk}(X)=d\)</span>) da Aula 2, Bloco 5.</p>
</div>
<div class="fragment">
<p>Sob posto completo: <span class="math display">\[\hat{\mathbf{w}} = (X^TX)^{-1}X^T\mathbf{y}\]</span> <span class="math inline">\((X^TX)^{-1}X^T\)</span> = <strong>pseudo-inversa</strong> de <span class="math inline">\(X\)</span> (MathML) — nome que volta quando o curso tratar de SVD.</p>
</div>
<div class="fragment">
<p>Fecha o ciclo da Aula 2: sobredeterminado sem solução exata, mas <strong>com</strong> uma única melhor aproximação sob posto completo — com fórmula fechada.</p>
</div>
<div class="fig-resize" style="width: 65%; margin: 0 auto;">
<img data-src="index_files/mediabag/396cf257be985a28527a0b7f9176b77380327c4a.svg" class="img-fluid">
</div>
</section>
<section id="o-esquema-fecha-o-ciclo" class="slide level2">
<h2>O Esquema Fecha o Ciclo</h2>
<div class="fragment">
<p><span class="math inline">\(\text{col}(X)\)</span> (simplificado como reta — na verdade dimensão <span class="math inline">\(4\)</span>), <span class="math inline">\(\mathbf{y}\)</span> fora dele, <span class="math inline">\(\hat{\mathbf{y}}=X\hat{\mathbf{w}}\)</span> mais próximo, resíduo em ângulo reto — a mesma sombra do Bloco 2, agora com nomes de regressão.</p>
</div>
</section>
<section id="pergunta-3" class="slide level2">
<h2>Pergunta</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>A condição <span class="math inline">\((\mathbf{y}-X\hat{\mathbf{w}})\perp\text{col}(X)\)</span> garante resíduo zero?</strong></p>
</div>
<div class="callout-content">
<p>Dica: “mais próximo” e “ortogonal” são a mesma condição (Passo i) — isso é o mesmo que “erro desaparece”?</p>
<ul>
<li>□ Se o critério fosse minimizar <span class="math inline">\(\|\mathbf{y}-X\mathbf{w}\|_1\)</span> em vez de <span class="math inline">\(L_2\)</span>, a mesma condição de ortogonalidade ainda garantiria a solução.</li>
<li>□ Se <span class="math inline">\(\mathbf{y}\in\text{col}(X)\)</span>, as Equações Normais dão <span class="math inline">\(\hat{\mathbf{w}}\)</span> com <span class="math inline">\(X\hat{\mathbf{w}}=\mathbf{y}\)</span> exatamente.</li>
<li>□ Calibração de sensores (<span class="math inline">\(N\)</span> leituras, <span class="math inline">\(d&lt;N\)</span> parâmetros físicos): mesma derivação das Equações Normais, outro domínio.</li>
<li>□ Ortogonalidade do resíduo <span class="math inline">\(\Rightarrow\)</span> resíduo nulo sempre que <span class="math inline">\(X\)</span> tem posto completo.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="resposta-3" class="slide level2">
<h2>Resposta</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>A condição de ortogonalidade garante resíduo zero? — Resposta</strong></p>
</div>
<div class="callout-content">
<ul>
<li>✗ A equivalência “mínimo <span class="math inline">\(\iff\)</span> ortogonal” (Passo i) é específica da norma <span class="math inline">\(L_2\)</span>/produto interno; a norma <span class="math inline">\(L_1\)</span> não tem essa geometria de ângulo reto, e minimizá-la leva a uma condição diferente (subgradiente nulo, não ortogonalidade).</li>
<li>✔ <span class="math inline">\(\mathbf{y}\in\text{col}(X)\)</span>: a melhor aproximação é o próprio <span class="math inline">\(\mathbf{y}\)</span>, erro zero — caso trivial consistente com a teoria.</li>
<li>✔ Mesma estrutura matemática (mínimos quadrados via projeção), outro domínio (calibração em vez de preço de imóvel).</li>
<li>✗ Ortogonalidade a <span class="math inline">\(\text{col}(X)\)</span> não força resíduo nulo — só força que o resíduo esteja em <span class="math inline">\(\text{col}(X)^\perp\)</span>; ele é zero apenas se <span class="math inline">\(\mathbf{y}\)</span> já estivesse em <span class="math inline">\(\text{col}(X)\)</span>, o que é a exceção, não a regra, no caso sobredeterminado.</li>
</ul>
</div>
</div>
</div>
<div class="fragment">
<p><strong>Voltando à pergunta:</strong> não — ortogonal ao subespaço é bem mais fraco que “igual a zero”; é só a direção do erro que fica fixada (<span class="math inline">\(U^\perp\)</span>), não o seu tamanho.</p>
</div>
</section></section>
<section>
<section id="aplicação-e-verificação-no-dado-real" class="title-slide slide level1 center">
<h1>Aplicação e Verificação no Dado Real</h1>

</section>
<section id="calculando-hatmathbfw-de-verdade-1" class="slide level2">
<h2>Calculando <span class="math inline">\(\hat{\mathbf{w}}\)</span> de Verdade</h2>
<div class="fragment">
<p>Aplicando a fórmula fechada ao problema motivador: <span class="math inline">\(N=16\,640\)</span> bairros, <span class="math inline">\(X\in\mathbb{R}^{16640\times 4}\)</span>, <span class="math inline">\(\mathbf{y}=\)</span> <code>MedHouseVal</code>. Posto completo (Aula 2) <span class="math inline">\(\Rightarrow\)</span> <span class="math inline">\(X^TX\)</span> invertível.</p>
</div>
<div id="be0e053f" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a aria-label="1"></a>X_completo <span class="op">=</span> _housing[COLS].to_numpy()</span>
<span id="cb1-2"><a aria-label="2"></a>y_completo <span class="op">=</span> _housing[<span class="st">"MedHouseVal"</span>].to_numpy()</span>
<span id="cb1-3"><a aria-label="3"></a></span>
<span id="cb1-4"><a aria-label="4"></a><span class="co"># Equações Normais, resolvidas diretamente pela fórmula fechada</span></span>
<span id="cb1-5"><a aria-label="5"></a>XtX <span class="op">=</span> X_completo.T <span class="op">@</span> X_completo</span>
<span id="cb1-6"><a aria-label="6"></a>Xty <span class="op">=</span> X_completo.T <span class="op">@</span> y_completo</span>
<span id="cb1-7"><a aria-label="7"></a>w_hat <span class="op">=</span> np.linalg.inv(XtX) <span class="op">@</span> Xty</span>
<span id="cb1-8"><a aria-label="8"></a></span>
<span id="cb1-9"><a aria-label="9"></a><span class="bu">print</span>(<span class="st">"w_hat (Equações Normais):"</span>, np.<span class="bu">round</span>(w_hat, <span class="dv">5</span>))</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>w_hat (Equações Normais): [ 0.48761  0.01171 -0.18809  0.78255]</code></pre>
</div>
</div>
</section>
<section id="o-que-os-pesos-dizem" class="slide level2">
<h2>O Que os Pesos Dizem</h2>
<div class="fragment">
<p><code>MedInc</code>: peso <span class="math inline">\(\approx 0{,}488\)</span> — maior em módulo, plausível (renda tem relação direta com preço).</p>
</div>
<div class="fragment">
<p><code>AveRooms</code>: peso <strong>negativo</strong> (<span class="math inline">\(\approx -0{,}188\)</span>), contraintuitivo à primeira vista — mas é estimado <strong>na presença</strong> de <code>AveBedrms</code> (correlacionados, Bloco 6); o modelo pode estar “compensando” superposição de informação, não afirmando causalidade isolada.</p>
</div>
</section>
<section id="conferência-independente" class="slide level2">
<h2>Conferência Independente</h2>
<div class="fragment">
<p>Fórmula fechada não é a única forma de calcular <span class="math inline">\(\hat{\mathbf{w}}\)</span> — <code>numpy.linalg.lstsq</code> resolve o mesmo problema por outro algoritmo (decomposição, sem inverter <span class="math inline">\(X^TX\)</span> explicitamente). As duas contas devem coincidir:</p>
</div>
<div id="68a3a85a" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a aria-label="1"></a>w_lstsq, <span class="op">*</span>_ <span class="op">=</span> np.linalg.lstsq(X_completo, y_completo, rcond<span class="op">=</span><span class="va">None</span>)</span>
<span id="cb3-2"><a aria-label="2"></a><span class="bu">print</span>(<span class="st">"w_hat (lstsq):           "</span>, np.<span class="bu">round</span>(w_lstsq, <span class="dv">5</span>))</span>
<span id="cb3-3"><a aria-label="3"></a><span class="bu">print</span>(<span class="st">"maior diferença absoluta:"</span>, np.<span class="bu">max</span>(np.<span class="bu">abs</span>(w_hat <span class="op">-</span> w_lstsq)))</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>w_hat (lstsq):            [ 0.48761  0.01171 -0.18809  0.78255]
maior diferença absoluta: 1.3100631690576847e-14</code></pre>
</div>
</div>
</section>
<section id="o-que-a-comparação-confirma" class="slide level2">
<h2>O Que a Comparação Confirma</h2>
<div class="fragment">
<p>Diferença máxima entre os dois <span class="math inline">\(\hat{\mathbf{w}}\)</span>: ordem de <span class="math inline">\(10^{-14}\)</span> — zero, a menos de arredondamento de ponto flutuante.</p>
</div>
<div class="fragment">
<p>Dois algoritmos completamente diferentes (inversão explícita <span class="math inline">\(4\times 4\)</span> vs.&nbsp;decomposição numérica) chegam ao mesmo resultado — a derivação do Bloco 4 funciona com dados reais, não só no quadro.</p>
</div>
</section>
<section id="verificando-a-ortogonalidade-do-resíduo-1" class="slide level2">
<h2>Verificando a Ortogonalidade do Resíduo</h2>
<div class="fragment">
<p>Promessa do Passo (iii): resíduo <span class="math inline">\(\perp\)</span> cada coluna de <span class="math inline">\(X\)</span> — não vago, uma igualdade numérica exata (a menos de arredondamento). Vamos checar:</p>
</div>
<div id="03d1b424" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a aria-label="1"></a>residuo <span class="op">=</span> y_completo <span class="op">-</span> X_completo <span class="op">@</span> w_hat</span>
<span id="cb5-2"><a aria-label="2"></a></span>
<span id="cb5-3"><a aria-label="3"></a><span class="bu">print</span>(<span class="st">"Produto interno do resíduo com cada coluna de X:"</span>)</span>
<span id="cb5-4"><a aria-label="4"></a><span class="cf">for</span> j, nome <span class="kw">in</span> <span class="bu">enumerate</span>(COLS):</span>
<span id="cb5-5"><a aria-label="5"></a>    prod <span class="op">=</span> residuo <span class="op">@</span> X_completo[:, j]</span>
<span id="cb5-6"><a aria-label="6"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>nome<span class="sc">:10s}</span><span class="ss">: </span><span class="sc">{</span>prod<span class="sc">:.3e}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Produto interno do resíduo com cada coluna de X:
  MedInc    : -4.522e-10
  HouseAge  : -5.039e-09
  AveRooms  : -8.756e-10
  AveBedrms : -1.987e-10</code></pre>
</div>
</div>
</section>
<section id="zero-em-perspectiva" class="slide level2">
<h2>Zero, em Perspectiva</h2>
<div class="fragment">
<p>Cada produto interno: ordem de <span class="math inline">\(10^{-9}\)</span> ou menor. Em proporção (dividido pelas normas): ordem de <span class="math inline">\(10^{-14}\)</span> — numericamente zero, exatamente como o Passo (iii) exigia.</p>
</div>
<div class="fragment">
<p>Não é coincidência: é <span class="math inline">\(X^T(\mathbf{y}-X\hat{\mathbf{w}})=\mathbf{0}\)</span> (Passo iii) verificada numericamente, coluna a coluna.</p>
</div>
</section>
<section id="o-tamanho-do-resíduo" class="slide level2">
<h2>O Tamanho do Resíduo</h2>
<div class="fragment">
<p>Ortogonalidade fixa a <strong>direção</strong> do erro (<span class="math inline">\(\in\text{col}(X)^\perp\)</span>), não o <strong>tamanho</strong>. Vale medir:</p>
</div>
<div id="0ee06757" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a aria-label="1"></a>norma_residuo <span class="op">=</span> np.linalg.norm(residuo)</span>
<span id="cb7-2"><a aria-label="2"></a>norma_y <span class="op">=</span> np.linalg.norm(y_completo)</span>
<span id="cb7-3"><a aria-label="3"></a>r2 <span class="op">=</span> <span class="dv">1</span> <span class="op">-</span> np.<span class="bu">sum</span>(residuo<span class="op">**</span><span class="dv">2</span>) <span class="op">/</span> np.<span class="bu">sum</span>((y_completo <span class="op">-</span> y_completo.mean())<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb7-4"><a aria-label="4"></a></span>
<span id="cb7-5"><a aria-label="5"></a><span class="bu">print</span>(<span class="ss">f"||resíduo|| = </span><span class="sc">{</span>norma_residuo<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb7-6"><a aria-label="6"></a><span class="bu">print</span>(<span class="ss">f"||y||       = </span><span class="sc">{</span>norma_y<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb7-7"><a aria-label="7"></a><span class="bu">print</span>(<span class="ss">f"||resíduo||/||y|| = </span><span class="sc">{</span>norma_residuo<span class="op">/</span>norma_y<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb7-8"><a aria-label="8"></a><span class="bu">print</span>(<span class="ss">f"R² = </span><span class="sc">{</span>r2<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>||resíduo|| = 101.49
||y||       = 298.57
||resíduo||/||y|| = 0.340
R² = 0.518</code></pre>
</div>
</div>
</section>
<section id="o-que-os-números-dizem" class="slide level2">
<h2>O Que os Números Dizem</h2>
<div class="fragment">
<p><span class="math inline">\(\|\text{resíduo}\|\approx 101{,}5\)</span> contra <span class="math inline">\(\|\mathbf{y}\|\approx
298{,}6\)</span>: <span class="math inline">\(R^2\approx 0{,}518\)</span> — o modelo explica pouco mais da metade da variação do preço com só 4 atributos.</p>
</div>
<div class="fragment">
<p><strong>Não é falha da matemática do Bloco 4</strong> — a projeção garante a melhor aproximação <strong>dentro de <span class="math inline">\(\text{col}(X)\)</span></strong>, não uma boa aproximação em termos absolutos. Faltam atributos (localização, qualidade, costa); o subespaço disponível é pequeno demais para chegar perto de <span class="math inline">\(\mathbf{y}\)</span>.</p>
</div>
</section>
<section id="vendo-o-ajuste-numa-amostra-concreta-1" class="slide level2">
<h2>Vendo o Ajuste numa Amostra Concreta</h2>
<div class="fragment">
<p>Amostra de 6 bairros da Aula 2 (<code>random_state=7</code>), agora com <span class="math inline">\(\hat{\mathbf{w}}\)</span> de verdade — ajustado nos <span class="math inline">\(16\,640\)</span> bairros, não mais inventado:</p>
</div>
<div class="fig-resize" style="width: 85%; margin: 0 auto;">
<div id="437be65a" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="index_files/figure-html/cell-9-output-1.png" class="quarto-figure quarto-figure-center" width="885" height="392"></p>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="comparando-com-a-aula-2" class="slide level2">
<h2>Comparando com a Aula 2</h2>
<div class="fragment">
<p>Aula 2 (mesmos 6 bairros, <span class="math inline">\(\mathbf{w}\)</span> <strong>inventado</strong>): erros grandes, sem padrão. Agora, com <span class="math inline">\(\hat{\mathbf{w}}\)</span> <strong>ajustado</strong>: ainda há erro (esperado, <span class="math inline">\(R^2\approx 0{,}518\)</span>), mas a tendência geral já aparece.</p>
</div>
<div class="fragment">
<p>Diferença entre “um <span class="math inline">\(\mathbf{w}\)</span> qualquer” e “o <span class="math inline">\(\hat{\mathbf{w}}\)</span> das Equações Normais”: o segundo não é perfeito, mas é <strong>matematicamente o melhor possível</strong> dentro do que os 4 atributos permitem.</p>
</div>
</section>
<section id="pergunta-4" class="slide level2">
<h2>Pergunta</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Eliminação de Gauss em <span class="math inline">\(X^TX\hat{\mathbf{w}}=X^T\mathbf{y}\)</span> daria o mesmo resultado que <code>lstsq</code>?</strong></p>
</div>
<div class="callout-content">
<p>Dica: o que muda entre <code>lstsq</code> e eliminação de Gauss é o algoritmo, não a equação resolvida.</p>
<ul>
<li>□ Eliminação de Gauss no mesmo sistema <span class="math inline">\(X^TX\hat{\mathbf{w}}=X^T\mathbf{y}\)</span> daria, a menos de arredondamento, o mesmo vetor de <code>lstsq</code>.</li>
<li>□ Produto interno do resíduo com cada coluna exatamente zero seria coincidência numérica desta amostra, não consequência da teoria.</li>
<li>□ Em outro domínio, com outras escalas, a mesma verificação de ortogonalidade continuaria válida como teste de correção.</li>
<li>□ Resíduo ortogonal a cada coluna <span class="math inline">\(\Rightarrow\)</span> <span class="math inline">\(R^2\)</span> próximo de <span class="math inline">\(1\)</span>.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="resposta-4" class="slide level2">
<h2>Resposta</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Comparando algoritmos e o que a ortogonalidade garante — Resposta</strong></p>
</div>
<div class="callout-content">
<ul>
<li>✔ Mesma equação, algoritmos diferentes (inversão, eliminação, decomposição) — todos resolvem o mesmo sistema linear, mesmo resultado a menos de arredondamento.</li>
<li>✗ É consequência <strong>necessária</strong> de <span class="math inline">\(X^T(\mathbf{y}-X\hat{\mathbf{w}})=\mathbf{0}\)</span> (Passo iii), não coincidência — vale para qualquer amostra em que <span class="math inline">\(\hat{\mathbf{w}}\)</span> resolva as Equações Normais.</li>
<li>✔ A verificação é uma identidade algébrica geral (Passo iii), independente de domínio ou escala dos atributos.</li>
<li>✗ Vimos <span class="math inline">\(R^2\approx 0{,}518\)</span> com resíduo ortogonal — ortogonalidade fixa a <em>direção</em> do erro, não seu <em>tamanho</em>; um ajuste ruim pode ter resíduo perfeitamente ortogonal.</li>
</ul>
</div>
</div>
</div>
<div class="fragment">
<p><strong>Voltando à pergunta:</strong> sim — qualquer método correto que resolva <span class="math inline">\(X^TX\hat{\mathbf{w}}=X^T\mathbf{y}\)</span> chega ao mesmo <span class="math inline">\(\hat{\mathbf{w}}\)</span>; a diferença entre métodos é robustez numérica, não o resultado matemático em si (tema que volta na Aula 4).</p>
</div>
</section></section>
<section>
<section id="quando-a-fórmula-falha-ou-fica-frágil" class="title-slide slide level1 center">
<h1>Quando a Fórmula Falha, ou Fica Frágil</h1>

</section>
<section id="reconectando-com-a-aula-2-posto-completo-1" class="slide level2">
<h2>Reconectando com a Aula 2: Posto Completo</h2>
<div class="fragment">
<p>Passo (iv): <span class="math inline">\(X^TX\)</span> invertível <span class="math inline">\(\iff\)</span> colunas de <span class="math inline">\(X\)</span> linearmente independentes <span class="math inline">\(\iff\)</span> <span class="math inline">\(\text{rk}(X)=d\)</span> (Aula 2, Bloco 5).</p>
</div>
<div class="fragment">
<p>Não é hipótese técnica qualquer: é o que separa “<span class="math inline">\(\hat{\mathbf{w}}\)</span> tem fórmula fechada” de “<span class="math inline">\(\hat{\mathbf{w}}\)</span> não é nem único”. Dois jeitos de falhar — um exato, um só frágil — reaproveitando os exemplos da Aula 2.</p>
</div>
</section>
<section id="caso-1-multicolinearidade-exata" class="slide level2">
<h2>Caso 1: Multicolinearidade Exata</h2>
<div class="fragment">
<p>Aula 2: quinta coluna <span class="math inline">\(2\times\)</span><code>AveRooms</code> — posto <strong>não sobe</strong> de 4 para 5. Repetindo, olhando para <span class="math inline">\(X^TX\)</span>:</p>
</div>
<div id="69ba50d8" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a aria-label="1"></a>X_com_duplicata <span class="op">=</span> np.column_stack([X_completo, <span class="fl">2.0</span> <span class="op">*</span> X_completo[:, <span class="dv">2</span>]])</span>
<span id="cb9-2"><a aria-label="2"></a><span class="bu">print</span>(<span class="st">"posto de X:              "</span>, np.linalg.matrix_rank(X_completo))</span>
<span id="cb9-3"><a aria-label="3"></a><span class="bu">print</span>(<span class="st">"posto de X com duplicata:"</span>, np.linalg.matrix_rank(X_com_duplicata))</span>
<span id="cb9-4"><a aria-label="4"></a></span>
<span id="cb9-5"><a aria-label="5"></a>XtX_dup <span class="op">=</span> X_com_duplicata.T <span class="op">@</span> X_com_duplicata</span>
<span id="cb9-6"><a aria-label="6"></a><span class="bu">print</span>(<span class="st">"det(X^T X com duplicata):"</span>, np.linalg.det(XtX_dup))</span>
<span id="cb9-7"><a aria-label="7"></a><span class="cf">try</span>:</span>
<span id="cb9-8"><a aria-label="8"></a>    np.linalg.inv(XtX_dup)</span>
<span id="cb9-9"><a aria-label="9"></a><span class="cf">except</span> np.linalg.LinAlgError <span class="im">as</span> erro:</span>
<span id="cb9-10"><a aria-label="10"></a>    <span class="bu">print</span>(<span class="st">"np.linalg.inv falha:"</span>, erro)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>posto de X:               4
posto de X com duplicata: 4
det(X^T X com duplicata): 0.0
np.linalg.inv falha: Singular matrix</code></pre>
</div>
</div>
</section>
<section id="distinção-crucial" class="slide level2">
<h2>Distinção Crucial</h2>
<div class="fragment">
<p><span class="math inline">\(\det(X^TX)=0\)</span>: <code>np.linalg.inv</code> recusa (“Singular matrix”) — sem fórmula fechada para <span class="math inline">\(\hat{\mathbf{w}}\)</span>.</p>
</div>
<div class="fragment">
<p><strong>Mas:</strong> a <em>projeção</em> <span class="math inline">\(\hat{\mathbf{y}}\)</span> continua bem definida — <span class="math inline">\(\text{col}(X)\)</span> não mudou (coluna redundante não traz direção nova). O que se perde é <strong>como distribuir o crédito</strong> entre <code>AveRooms</code> e sua cópia: infinitos <span class="math inline">\(\hat{\mathbf{w}}\)</span> dão o mesmo <span class="math inline">\(\hat{\mathbf{y}}\)</span>.</p>
</div>
<div class="fragment">
<p>A sombra é única; a “receita” para chegar nela, não.</p>
</div>
</section>
<section id="caso-2-quase-multicolinearidade" class="slide level2">
<h2>Caso 2: Quase-Multicolinearidade</h2>
<div class="fragment">
<p>Multicolinearidade exata é rara em dados reais. Mais comum (Aula 2): <code>AveRooms</code>/<code>AveBedrms</code>, correlação <span class="math inline">\(0{,}865\)</span> — posto completo, fórmula existe, mas <strong>numericamente frágil</strong>.</p>
</div>
<div class="fragment">
<p>Reaproveitando a amostra de 20 bairros e a perturbação de 1% da Aula 2, agora olhando o número de condição de <span class="math inline">\(X^TX\)</span>:</p>
</div>
<div id="6c5b7b1c" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a aria-label="1"></a>_amostra_20 <span class="op">=</span> _housing.sample(n<span class="op">=</span><span class="dv">20</span>, random_state<span class="op">=</span><span class="dv">7</span>)</span>
<span id="cb11-2"><a aria-label="2"></a>X_quase_dep <span class="op">=</span> _amostra_20[[<span class="st">"AveRooms"</span>, <span class="st">"AveBedrms"</span>]].to_numpy()</span>
<span id="cb11-3"><a aria-label="3"></a>X_bem_cond <span class="op">=</span> _amostra_20[[<span class="st">"MedInc"</span>, <span class="st">"HouseAge"</span>]].to_numpy()</span>
<span id="cb11-4"><a aria-label="4"></a></span>
<span id="cb11-5"><a aria-label="5"></a>cond_quase_dep <span class="op">=</span> np.linalg.cond(X_quase_dep.T <span class="op">@</span> X_quase_dep)</span>
<span id="cb11-6"><a aria-label="6"></a>cond_bem_cond <span class="op">=</span> np.linalg.cond(X_bem_cond.T <span class="op">@</span> X_bem_cond)</span>
<span id="cb11-7"><a aria-label="7"></a></span>
<span id="cb11-8"><a aria-label="8"></a><span class="bu">print</span>(<span class="ss">f"número de condição de X^TX (AveRooms, AveBedrms):  </span><span class="sc">{</span>cond_quase_dep<span class="sc">:,.1f}</span><span class="ss">"</span>)</span>
<span id="cb11-9"><a aria-label="9"></a><span class="bu">print</span>(<span class="ss">f"número de condição de X^TX (MedInc, HouseAge):     </span><span class="sc">{</span>cond_bem_cond<span class="sc">:,.1f}</span><span class="ss">"</span>)</span>
<span id="cb11-10"><a aria-label="10"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">número de condição de X^TX completo (4 atributos): </span><span class="sc">{</span>np<span class="sc">.</span>linalg<span class="sc">.</span>cond(XtX)<span class="sc">:,.1f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>número de condição de X^TX (AveRooms, AveBedrms):  419.8
número de condição de X^TX (MedInc, HouseAge):     169.1

número de condição de X^TX completo (4 atributos): 23,460.5</code></pre>
</div>
</div>
</section>
<section id="o-que-os-números-confirmam" class="slide level2">
<h2>O Que os Números Confirmam</h2>
<div class="fragment">
<p>Número de condição: <span class="math inline">\(\approx 420\)</span> (quase-dependente) vs.&nbsp;<span class="math inline">\(\approx 169\)</span> (bem-condicionado) — mais que o dobro. Sinal numérico de fragilidade.</p>
</div>
<div class="fragment">
<p>Perturbação de 1% em <code>MedHouseVal</code>: peso de <code>AveBedrms</code> muda <span class="math inline">\(\approx 29{,}5\%\)</span> no par quase-dependente, contra <span class="math inline">\(\approx 0{,}1\%\)</span> no bem-condicionado — quase 300× mais sensível (Aula 2, reproduzido aqui como consequência do número de condição).</p>
</div>
<div class="fragment">
<p><span class="math inline">\(X^TX\)</span> completo (4 atributos): número de condição <span class="math inline">\(\approx 23\,460\)</span> — ainda maior, combinando a redundância <code>AveRooms</code>/<code>AveBedrms</code> com a escala de todos os atributos.</p>
</div>
</section>
<section id="a-mesma-distinção-do-caso-1-mais-sutil" class="slide level2">
<h2>A Mesma Distinção do Caso 1, Mais Sutil</h2>
<div class="fragment">
<p>A projeção <span class="math inline">\(\hat{\mathbf{y}}\)</span> (previsão) muda pouco com a perturbação — é a <strong>decomposição</strong> de <span class="math inline">\(\hat{\mathbf{w}}\)</span> entre colunas quase-redundantes que oscila.</p>
</div>
<div class="fragment">
<p>Medir essa sensibilidade com precisão — o <strong>número de condição</strong>, via autovalores de <span class="math inline">\(X^TX\)</span> — é o que abre a Aula 4.</p>
</div>
<div class="fig-resize" style="width: 78%; margin: 0 auto;">
<img data-src="index_files/mediabag/03399b12a822d6b3b730b1638cfc7cd63c7c475b.svg" class="img-fluid">
</div>
</section>
<section id="o-diagrama-resume-os-dois-caminhos" class="slide level2">
<h2>O Diagrama Resume os Dois Caminhos</h2>
<div class="fragment">
<p>Mesma causa raiz (colunas redundantes), gravidade diferente. Em ambos: a projeção <span class="math inline">\(\hat{\mathbf{y}}\)</span> nunca é o problema — o problema mora em como <span class="math inline">\(\hat{\mathbf{w}}\)</span> tenta descrevê-la.</p>
</div>
</section>
<section id="pergunta-5" class="slide level2">
<h2>Pergunta</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong><span class="math inline">\(X^TX\)</span> mal-condicionada torna <span class="math inline">\(\hat{\mathbf{y}}\)</span> proporcionalmente instável também?</strong></p>
</div>
<div class="callout-content">
<p>Dica: os números do Caso 2 mostraram a instabilidade em <span class="math inline">\(\hat{\mathbf{w}}\)</span> vs.&nbsp;em <span class="math inline">\(\hat{\mathbf{y}}\)</span> — mesmo tamanho?</p>
<ul>
<li>□ Coluna duplicada como combinação de duas colunas originais (não um múltiplo de uma só): posto de <span class="math inline">\(X\)</span> ainda cairia igual.</li>
<li>□ Correlação AveRooms/AveBedrms exatamente <span class="math inline">\(1\)</span>: <span class="math inline">\(X^TX\)</span> deixaria de ser invertível, fórmula fechada indefinida.</li>
<li>□ Crédito com “renda mensal”/“renda anual÷12” (quase redundantes por arredondamento): mesmo sintoma de instabilidade, sem duplicata exata.</li>
<li>□ <span class="math inline">\(X^TX\)</span> mal-condicionada <span class="math inline">\(\Rightarrow\)</span> <span class="math inline">\(\hat{\mathbf{y}}\)</span> também proporcionalmente instável.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="resposta-5" class="slide level2">
<h2>Resposta</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Mal-condicionamento e o que permanece estável — Resposta</strong></p>
</div>
<div class="callout-content">
<ul>
<li>✔ Qualquer coluna que seja combinação linear exata das demais não acrescenta direção nova ao espaço gerado — o posto cai da mesma forma, com múltiplo único ou combinação.</li>
<li>✔ Correlação <span class="math inline">\(1\)</span> = dependência linear exata <span class="math inline">\(\Rightarrow\)</span> <span class="math inline">\(X^TX\)</span> singular, mesma consequência do Caso 1.</li>
<li>✔ Mesma mecânica de quase-dependência, outro domínio (crédito em vez de imóveis).</li>
<li>✗ É o oposto do que os números mostraram: a <em>projeção</em> <span class="math inline">\(\hat{\mathbf{y}}\)</span> (o ponto mais próximo de <span class="math inline">\(\mathbf{y}\)</span> em <span class="math inline">\(\text{col}(X)\)</span>) é geometricamente determinada e muda pouco; é a <strong>decomposição</strong> em <span class="math inline">\(\hat{\mathbf{w}}\)</span> entre colunas quase-redundantes que oscila descontroladamente.</li>
</ul>
</div>
</div>
</div>
<div class="fragment">
<p><strong>Voltando à pergunta:</strong> não — é exatamente o padrão “sombra estável, receita instável” do Caso 1, só que aqui sem quebra total de posto, apenas fragilidade numérica.</p>
</div>
</section></section>
<section>
<section id="fechamento-e-ponte-para-a-aula-4" class="title-slide slide level1 center">
<h1>Fechamento e Ponte para a Aula 4</h1>

</section>
<section id="retomando-as-perguntas-de-abertura-1" class="slide level2">
<h2>Retomando as Perguntas de Abertura</h2>
<div class="fragment">
<p><strong>1.</strong> “Melhor aproximação” = <span class="math inline">\(\hat{\mathbf{y}}\in\text{col}(X)\)</span> que minimiza <span class="math inline">\(\|\mathbf{y}-\hat{\mathbf{y}}\|\)</span> — equivalente a resíduo ortogonal ao subespaço.</p>
</div>
<div class="fragment">
<p><strong>2.</strong> Projetar = encontrar esse <span class="math inline">\(\hat{\mathbf{y}}\)</span> — a sombra perpendicular, formalizada no Teorema da Projeção.</p>
</div>
<div class="fragment">
<p><strong>3.</strong> Fórmula: Equações Normais <span class="math inline">\(X^TX\hat{\mathbf{w}}=X^T\mathbf{y}\)</span>; sob posto completo, <span class="math inline">\(\hat{\mathbf{w}}=(X^TX)^{-1}X^T\mathbf{y}\)</span> — verificado com dados reais.</p>
</div>
<div class="fragment">
<p><strong>4.</strong> Falha: multicolinearidade exata quebra invertibilidade (<span class="math inline">\(\hat{\mathbf{w}}\)</span> não-único); quase-exata deixa <span class="math inline">\(X^TX\)</span> mal-condicionada (<span class="math inline">\(\hat{\mathbf{w}}\)</span> instável).</p>
</div>
</section>
<section id="ponte-para-a-aula-4" class="slide level2">
<h2>Ponte para a Aula 4</h2>
<div class="fragment">
<p>Fórmula fechada = mais simples de <strong>descrever</strong>, não mais <strong>estável</strong> de <strong>calcular</strong> quando <span class="math inline">\(X^TX\)</span> é mal-condicionada.</p>
</div>
<div class="fragment">
<p>Aqui, número de condição foi medido empiricamente (perturbar e ver o efeito). Aula 4: ferramenta exata via <strong>autovalores/autovetores</strong> de <span class="math inline">\(X^TX\)</span> — sem precisar perturbar nada.</p>
</div>
<div class="fragment">
<p>Motiva, mais adiante, métodos mais estáveis que inverter <span class="math inline">\(X^TX\)</span> diretamente: decomposição <span class="math inline">\(QR\)</span> e <span class="math inline">\(SVD\)</span>.</p>
</div>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>UNICAMP — Instituto de Computação</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true,"boardmarkerWidth":3,"chalkWidth":3},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 800,

        // Factor of the display size that should remain empty around the content
        margin: 2.0e-2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <div class="custom-footer-logos">
      <a href="notas.html" class="back-arrow-slide" title="Voltar às notas" aria-label="Voltar às notas"><i class="bi bi-book-half" aria-hidden="true"></i></a>
      <img src="../../UNICAMP.png" alt="UNICAMP">
      <img src="../../IC.png" alt="Instituto de Computação">
    </div>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copiada");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copiada");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>