{
  "hash": "c883c4e94cab613860846fdbb76ae064",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Aula 3: Projeções Ortogonais e Subespaços\"\nsubtitle: \"Álgebra Linear e Otimização para Aprendizado de Máquina\"\nauthor: \"Prof. Marcos Medeiros Raimundo\"\ndate: \"2026-08-30\"\nlang: pt-BR\nformat:\n  html:\n    include-after-body: ../../lesson-toc-accordion.html\n    output-file: notas.html\n    theme: [flatly, ../../../custom.scss, ../../lesson-theme.scss]\n    code-fold: false\n    toc: true\n    toc-depth: 3\n    number-sections: true\n    fig-width: 8\n    fig-height: 4.5\n  revealjs:\n    transition: slide\n    width: 1280\n    height: 800\n    margin: 0.02\n    fig-responsive: true\n    fig-format: \"svg\"\n    footer: \"UNICAMP — Instituto de Computação\"\n    chalkboard:\n      boardmarker-width: 3\n      chalk-width: 3\n    include-in-header: ../../bootstrap-icons-header.html\n    include-after-body: ../../logos-footer.html\n    title-slide-attributes:\n      data-background-image: \"../../UNICAMP.png, ../../IC.png\"\n      data-background-size: \"140px, 140px\"\n      data-background-position: \"5% 8%, 95% 8%\"\n    theme: [simple, ../../lesson-theme.scss]\n    output-file: slides.html\n    slide-number: true\n    smaller: true\n    scrollable: true\n    fig-width: 8\n    fig-height: 4.5\njupyter: homepage\n---\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n[Slides](slides.html){.see-all aria-label=\"Ver slides\" title=\"Ver slides\"}\n[Lista de aulas](../index.qmd){.see-all .lesson-list-link aria-label=\"Lista de aulas\" title=\"Lista de aulas\"}\n:::\n\n\n\n# Revisão e Introdução\n\n---\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## Revisão Rápida: Onde a Aula 2 Parou\n\nA Aula 2 deu quatro passos, nesta ordem. **Primeiro**, generalizou \"um\nvetor\" para \"um dataset inteiro\" via a matriz de design\n$X\\in\\mathbb{R}^{N\\times d}$ — cada linha uma observação, cada coluna um\natributo. **Segundo**, deu duas leituras ao produto $A\\mathbf{x}$: por\nlinha, uma previsão (produto interno por observação); por coluna, uma\ncombinação linear dos atributos — a mesma fórmula, dois significados,\nambos usados o resto do curso. **Terceiro**, classificou os sistemas\nlineares $A\\mathbf{x}=\\mathbf{b}$ em três casos possíveis — nenhuma,\nexatamente uma, ou infinitas soluções — via o critério do posto da matriz\naumentada, $\\text{rk}(A)=\\text{rk}(A|\\mathbf{b})$, resolvendo um exemplo\ncompleto por Eliminação de Gauss. **Quarto**, tratou de independência\nlinear: um atributo é redundante (multicolinear) quando é combinação\nlinear dos demais, e o **posto** de uma matriz mede exatamente quantas\ncolunas são, de fato, independentes — quando as $d$ colunas de $X$ são\nlinearmente independentes, dizemos que $X$ **tem posto completo**,\n$\\text{rk}(X)=d$.\n\nEsse último fato — posto completo de $X$, não o critério de solvabilidade\ndo terceiro passo (outra aplicação do mesmo conceito de posto, mas sobre\n$A$ e a matriz aumentada, não sobre $X$) — é a peça que esta aula vai\nreusar diretamente no Bloco 4, como a condição exata que garante uma\núnica melhor aproximação. A peça central que fica de tudo isso: em\nRegressão Linear Múltipla, o sistema $X\\mathbf{w}=\\mathbf{y}$ tem $N$\nequações e $d$ incógnitas, e como $N\\gg d$ em praticamente todo problema\nreal, o sistema é **sobredeterminado** — genericamente, **nenhuma solução\nexata**.\n\n## Organizador Prévio: De \"Sem Solução\" Para \"Melhor Aproximação\"\n\nA Aula 2 fechou com essa constatação como um beco aparentemente sem\nsaída: exigir que $X\\mathbf{w}$ alcance $\\mathbf{y}$ exatamente é pedir\ndemais quando há milhares de observações reais e ruidosas. Mas \"sem\nsolução exata\" não é \"sem solução nenhuma que preste\". O próprio livro\nque citamos nas Aulas 1-2 (MathML) já aponta a saída, no capítulo sobre\nprojeções: quando um sistema $A\\mathbf{x}=\\mathbf{b}$ não pode ser\nresolvido exatamente, ainda é possível perguntar qual é a melhor\naproximação — \"a ideia é encontrar o vetor no subespaço gerado pelas\ncolunas de $A$ que está mais próximo de $\\mathbf{b}$\" (tradução nossa,\nMathML, §3.8.2, p. 88). Essa pergunta — \"mais próximo, mas dentro de\nonde?\" — é geométrica antes de ser algébrica, e é exatamente o fio que\nesta aula segue.\n\n## Roteiro da Aula\n\nA pergunta que fecha o Organizador Prévio — \"mais próximo, mas dentro de\nonde?\" — se desdobra em quatro perguntas mais específicas, cada uma\nresolvida em um bloco desta aula:\n\n1. O que significa, geometricamente, \"a melhor aproximação possível\" de\n   $\\mathbf{y}$ por um $X\\mathbf{w}$ alcançável?\n2. O que é projetar um vetor sobre um subespaço, e por que essa operação\n   resolve exatamente o problema da pergunta 1?\n3. Como essa ideia geométrica vira uma fórmula calculável — as **Equações\n   Normais**?\n4. Quando essa fórmula falha, ou fica numericamente frágil, e por quê?\n\n## Problema Motivador\n\nVolte ao *California Housing Dataset* das Aulas 1-2: $N=16\\,640$ bairros\n(a partição de treino), 4 atributos (`MedInc`, `HouseAge`, `AveRooms`,\n`AveBedrms`), e o alvo `MedHouseVal`. O sistema $X\\mathbf{w}=\\mathbf{y}$\ntem $16\\,640$ equações e $4$ incógnitas — sobredeterminado por uma margem\nenorme. Sem resolver nada ainda, pense por um instante: se $X\\mathbf{w}$\nnunca alcança $\\mathbf{y}$ exatamente, **qual** $X\\mathbf{w}$ alcançável\nestá mais perto? E \"mais perto\" — medido como, exatamente?\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Revisão Rápida: Onde a Aula 2 Parou\n\n::: {.fragment}\nAula 2: matriz de design $X\\in\\mathbb{R}^{N\\times d}$, duas leituras de\n$A\\mathbf{x}$ (linha = previsão, coluna = combinação linear), sistemas\nlineares com 0, 1 ou $\\infty$ soluções via o posto da matriz aumentada.\n:::\n\n::: {.fragment}\nTambém: colunas independentes (sem multicolinearidade) $\\Rightarrow$\n**posto completo**, $\\text{rk}(X)=d$. Vamos reusar isso no Bloco 4 — é a\ncondição que garante solução única hoje.\n:::\n\n::: {.fragment}\nPeça central: $X\\mathbf{w}=\\mathbf{y}$ tem $N$ equações, $d$ incógnitas.\nEm ML real, $N\\gg d$ — **sobredeterminado**, genericamente **sem solução\nexata**.\n:::\n\n### De \"Sem Solução\" Para \"Melhor Aproximação\"\n\n::: {.fragment}\n\"Sem solução exata\" não é \"sem solução que preste\". O próprio MathML\naponta a saída: \"a ideia é encontrar o vetor no subespaço gerado pelas\ncolunas de $A$ que está mais próximo de $\\mathbf{b}$\" (tradução nossa,\n§3.8.2).\n:::\n\n::: {.fragment}\n\"Mais próximo, mas dentro de onde?\" — geométrico antes de algébrico. É o\nfio desta aula.\n:::\n\n## Roteiro da Aula\n\n::: {.fragment}\n\"Mais próximo, mas dentro de onde?\" se desdobra em quatro perguntas, uma\npor bloco:\n:::\n\n::: {.fragment}\n**1.** O que significa \"a melhor aproximação possível\" de $\\mathbf{y}$?\n:::\n\n::: {.fragment}\n**2.** O que é projetar sobre um subespaço, e por que resolve o\nproblema 1?\n:::\n\n::: {.fragment}\n**3.** Como isso vira uma fórmula calculável — as **Equações Normais**?\n:::\n\n::: {.fragment}\n**4.** Quando essa fórmula falha, ou fica frágil, e por quê?\n:::\n\n## Problema Motivador\n\n::: {.fragment}\nCalifornia Housing: $N=16\\,640$ bairros, 4 atributos. Sistema\n$X\\mathbf{w}=\\mathbf{y}$: $16\\,640$ equações, $4$ incógnitas —\nsobredeterminado por uma margem enorme.\n:::\n\n::: {.fragment}\nSe $X\\mathbf{w}$ nunca alcança $\\mathbf{y}$ exatamente, **qual**\n$X\\mathbf{w}$ alcançável está mais perto? \"Mais perto\" — medido como?\n:::\n:::\n\n::: {.fig-resize style=\"width: 90%; margin: 0 auto;\"}\n```{.tikz}\n\\usetikzlibrary{shapes.geometric, arrows.meta, positioning}\n\\definecolor{icblue}{HTML}{0085CA}\n\\definecolor{icorange}{HTML}{FF5E00}\n\\definecolor{icred}{HTML}{E03C31}\n\\begin{tikzpicture}[\n  node distance=0.7cm and 0.9cm,\n  block/.style={rectangle, draw=icblue, fill=icblue!8, rounded corners=3pt,\n                align=center, font=\\small, inner sep=6pt,\n                text width=2.9cm, minimum height=1.1cm},\n  decision/.style={diamond, draw=icorange, fill=icorange!10, align=center,\n                    font=\\small, inner sep=1pt, text width=2.5cm, aspect=1.9},\n  concl/.style={rectangle, draw=icred, fill=icred!8, rounded corners=3pt,\n                align=center, font=\\small, inner sep=6pt,\n                text width=2.9cm, minimum height=1.1cm},\n  arrow/.style={-Stealth, thick, color=gray!70}\n]\n  \\node (A) [block] {$\\mathbf{y}$ fora de $\\mathrm{col}(X)$};\n  \\node (B) [block, right=of A] {projeção ortogonal $\\hat{\\mathbf{y}}$};\n  \\node (C) [block, right=of B] {Equações Normais\\\\$X^TX\\hat{\\mathbf{w}}=X^T\\mathbf{y}$};\n  \\node (Q) [decision, right=of C] {$X^TX$ invertível?};\n  \\node (D) [concl, above=1.1cm of Q] {sim: $\\hat{\\mathbf{w}}$ único,\\\\fórmula fechada};\n  \\node (E) [concl, below=1.1cm of Q] {não: $\\hat{\\mathbf{y}}$ único,\\\\$\\hat{\\mathbf{w}}$ não-único (Bloco 6)};\n\n  \\draw [arrow] (A) -- (B);\n  \\draw [arrow] (B) -- (C);\n  \\draw [arrow] (C) -- (Q);\n  \\draw [arrow] (Q) -- (D);\n  \\draw [arrow] (Q) -- (E);\n\\end{tikzpicture}\n```\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n::: {.callout-tip}\n## Se $X\\mathbf{w}=\\mathbf{y}$ nunca é alcançado exatamente, existe sempre exatamente uma \"melhor\" aproximação, ou pode haver várias igualmente boas?\n\nDica: pense em como a Aula 2 já classificou o **número** de soluções de\num sistema exato — nenhuma, uma, ou infinitas. A pergunta agora troca\n\"solução exata\" por \"solução aproximada\". O número de \"melhores\naproximações\" muda de natureza?\n\n- □ Se o sistema $X\\mathbf{w}=\\mathbf{y}$ fosse subdeterminado ($N<d$) em\n  vez de sobredeterminado, ainda faria sentido perguntar qual\n  $X\\mathbf{w}$ é \"mais próximo\" de $\\mathbf{y}$, mas a pergunta mudaria\n  de natureza: deixaria de ser sobre um erro irredutível e passaria a\n  ser sobre escolher entre infinitas soluções exatas.\n- □ No caso-limite $N=d$ com $X$ de posto completo, a \"melhor\n  aproximação\" $X\\hat{\\mathbf{w}}$ coincide exatamente com $\\mathbf{y}$\n  (erro zero).\n- □ Num sistema de posicionamento por GPS, com mais satélites (equações)\n  do que coordenadas a estimar (incógnitas), a mesma lógica de \"melhor\n  aproximação por projeção\" se aplica, ainda que o contexto seja\n  localização geográfica, não preço de imóvel.\n- □ Como nenhum $X\\mathbf{w}$ alcança $\\mathbf{y}$ exatamente num sistema\n  sobredeterminado, a Regressão Linear Múltipla deixa de fornecer\n  qualquer informação útil sobre a relação entre atributos e alvo.\n:::\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Pergunta\n\n::: {.callout-tip}\n## Se $X\\mathbf{w}=\\mathbf{y}$ nunca é alcançado exatamente, existe sempre exatamente uma \"melhor\" aproximação, ou pode haver várias igualmente boas?\n\nDica: a Aula 2 já classificou o número de soluções **exatas** de um\nsistema — 0, 1 ou $\\infty$. Trocar \"exata\" por \"aproximada\" muda essa\ncontagem?\n\n- □ Se o sistema fosse subdeterminado ($N<d$), a pergunta \"qual é mais\n  próximo?\" mudaria de natureza: de erro irredutível para escolha entre\n  infinitas soluções exatas.\n- □ No caso-limite $N=d$ com $X$ de posto completo, a melhor\n  aproximação coincide exatamente com $\\mathbf{y}$ (erro zero).\n- □ GPS com mais satélites que coordenadas: mesma lógica de projeção se\n  aplica, outro domínio.\n- □ Sem solução exata, a Regressão Linear Múltipla perde toda utilidade.\n:::\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Resposta\n\n::: {.callout-tip}\n## Se $X\\mathbf{w}=\\mathbf{y}$ nunca é alcançado exatamente, existe sempre uma \"melhor\" aproximação? — Resposta\n\n- ✔ Subdeterminado: se solúvel, há $\\infty$ soluções exatas — a pergunta\n  vira \"qual escolher\", não \"qual erro minimizar\".\n- ✔ $N=d$, posto completo: sistema quadrado invertível, erro zero.\n- ✔ GPS: mesma matemática, outro domínio (localização em vez de preço).\n- ✗ Falta de solução exata não implica falta de utilidade — é\n  exatamente o problema que esta aula resolve com projeção.\n:::\n\n::: {.fragment}\n**Voltando à pergunta:** no regime sobredeterminado desta aula (posto\ncompleto), existe **exatamente uma** melhor aproximação — é isso que o\nBloco 4 vai provar, via projeção ortogonal.\n:::\n:::\n\n# Intuição: A Sombra no Chão\n\n---\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## A Ideia Antes da Álgebra\n\nAntes de qualquer fórmula, uma imagem concreta. Imagine um ponto\n$\\mathbf{y}$ flutuando no espaço, e um subespaço $U$ — uma reta ou um\nplano passando pela origem — como se fosse o chão. Se uma fonte de luz\nvier exatamente **perpendicular** ao chão, a sombra de $\\mathbf{y}$ sobre\n$U$ é um ponto específico: chame-o $\\hat{\\mathbf{y}}$. Essa sombra tem\nduas propriedades que, juntas, definem tudo o que este bloco precisa:\n\n1. **É o ponto de $U$ mais próximo de $\\mathbf{y}$** — nenhum outro ponto\n   do chão está a uma distância menor de $\\mathbf{y}$ do que a própria\n   sombra.\n2. **O segmento (ponto → sombra) é perpendicular a $U$** — a \"haste\" que\n   liga $\\mathbf{y}$ à sua sombra $\\hat{\\mathbf{y}}$ faz ângulo reto com\n   o chão inteiro, não só com a direção da luz.\n\nEssas duas propriedades não são independentes — a segunda é a razão pela\nqual a primeira é verdade, algo que o Bloco 4 vai provar formalmente. Por\nora, olhe para o desenho: projetar sobre uma reta (subespaço de dimensão\n1) e projetar sobre um plano (subespaço de dimensão 2) são a mesma\noperação, só que o \"chão\" tem mais dimensões.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## A Ideia Antes da Álgebra\n\n::: {.fragment}\nUm ponto $\\mathbf{y}$ flutuando no espaço; um subespaço $U$ como \"o chão\". Luz perpendicular ao chão $\\Rightarrow$\nsombra $\\hat{\\mathbf{y}}$.\n:::\n\n::: {.fragment}\n**Propriedade 1:** $\\hat{\\mathbf{y}}$ é o ponto de $U$ mais próximo de\n$\\mathbf{y}$ — nenhum outro ponto do chão está mais perto.\n:::\n\n::: {.fragment}\n**Propriedade 2:** o segmento $\\mathbf{y}\\to\\hat{\\mathbf{y}}$ é\nperpendicular a **todo** $U$, não só à direção da luz.\n:::\n:::\n\n::: {.fig-resize style=\"width: 70%; margin: 0 auto;\"}\n\n::: {#a598876d .cell execution_count=2}\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-revealjs/cell-3-output-1.svg){fig-align='center'}\n:::\n:::\n\n\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\nNo painel esquerdo, $U$ é a reta gerada pela direção $(2,1)$, e\n$\\mathbf{y}=(1{,}0;3{,}2)$ está fora dela. A sombra $\\hat{\\mathbf{y}}$\n(quadrado laranja) é o ponto da reta mais próximo de $\\mathbf{y}$, e o\nsegmento tracejado (o \"resíduo\") encontra a reta em ângulo reto — não em\nqualquer ângulo. No painel direito, o \"chão\" já é um plano\nbidimensional (o plano $x_3=0$) dentro de um espaço tridimensional:\n$\\mathbf{y}=(1{,}5;1{,}8;\\,2{,}3)$ tem sombra\n$\\hat{\\mathbf{y}}=(1{,}5;1{,}8;\\,0)$ — a projeção simplesmente \"zera\" a\ncomponente perpendicular ao chão, e o segmento tracejado (puramente na\ndireção $x_3$) é, de novo, perpendicular a todo o plano, não só a uma\ndireção dentro dele. É essa segunda observação — perpendicular a **todo**\no subespaço — que vai generalizar para o espaço-coluna de $X$, que tem\n$d=4$ dimensões, não $1$ ou $2$: a \"álgebra\" muda, a geometria não.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## O Que os Dois Painéis Mostram\n\n::: {.fragment}\nEsquerda: $U$ = reta na direção $(2,1)$; $\\mathbf{y}=(1{,}0;3{,}2)$ fora\ndela. Sombra $\\hat{\\mathbf{y}}$ = ponto da reta mais próximo; o\ntracejado encontra a reta em ângulo reto.\n:::\n\n::: {.fragment}\nDireita: \"chão\" = plano $x_3=0$ em $\\mathbb{R}^3$. Projeção só \"zera\" a\ncomponente perpendicular: $(1{,}5;1{,}8;2{,}3)\\to(1{,}5;1{,}8;0)$.\n:::\n\n::: {.fragment}\nEm ambos, o tracejado é perpendicular a **todo** o subespaço — essa\nobservação generaliza para $\\text{col}(X)$, com $d=4$ dimensões, não $1$\nou $2$. A álgebra muda; a geometria, não.\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n::: {.callout-tip}\n## Se a \"luz\" da projeção não viesse perpendicular ao chão, mas num ângulo oblíquo fixo, o ponto resultante ainda seria o mais próximo de $\\mathbf{y}$?\n\nDica: pense no desenho da reta acima. Se você inclinasse a direção da\n\"luz\" (a direção da haste que liga $\\mathbf{y}$ à sua sombra), o ponto\nde chegada na reta mudaria — ele continuaria sendo o ponto mais próximo?\n\n- □ Se a luz não viesse perpendicular ao chão, mas em um ângulo oblíquo\n  fixo, o ponto resultante ainda seria o ponto do subespaço mais\n  próximo de $\\mathbf{y}$.\n- □ Se o ponto $\\mathbf{y}$ já pertencesse ao subespaço $U$, a \"sombra\"\n  de $\\mathbf{y}$ sobre $U$ coincidiria com o próprio $\\mathbf{y}$, e o\n  resíduo teria norma zero.\n- □ Comprimir uma imagem mantendo só suas componentes principais é,\n  geometricamente, projetar cada vetor-pixel sobre um subespaço de\n  menor dimensão — a mesma lógica da sombra perpendicular discutida\n  aqui, aplicada a outro tipo de dado.\n- □ Como a sombra perpendicular minimiza a distância até $\\mathbf{y}$,\n  ela também é, necessariamente, o ponto do subespaço com a **maior**\n  norma possível entre os candidatos considerados.\n:::\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Pergunta\n\n::: {.callout-tip}\n## Se a \"luz\" da projeção não viesse perpendicular ao chão, o ponto resultante ainda seria o mais próximo de $\\mathbf{y}$?\n\nDica: incline a direção da haste que liga $\\mathbf{y}$ à sua sombra — o\nponto de chegada continuaria sendo o mais próximo?\n\n- □ Luz oblíqua (não perpendicular): o ponto resultante ainda seria o\n  ponto do subespaço mais próximo de $\\mathbf{y}$.\n- □ Se $\\mathbf{y}$ já pertencesse a $U$, a sombra coincidiria com o\n  próprio $\\mathbf{y}$, resíduo de norma zero.\n- □ Compressão de imagem via componentes principais é, geometricamente,\n  a mesma projeção perpendicular discutida aqui, outro tipo de dado.\n- □ A sombra perpendicular, por minimizar distância, também maximiza a\n  norma do ponto do subespaço.\n:::\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Resposta\n\n::: {.callout-tip}\n## A \"luz\" da projeção — Resposta\n\n- ✗ Só a luz perpendicular garante o ponto mais próximo; qualquer\n  ângulo oblíquo fixo geralmente erra o mínimo (é a mesma lógica do\n  Teorema de Pitágoras: a hipotenusa de um triângulo oblíquo é maior\n  que o cateto perpendicular).\n- ✔ $\\mathbf{y}\\in U \\Rightarrow \\hat{\\mathbf{y}}=\\mathbf{y}$, resíduo\n  nulo — caso trivial, mas consistente.\n- ✔ Mesma operação geométrica (projeção ortogonal), outro domínio\n  (compressão/PCA, tema da disciplina de Aprendizado Não Supervisionado).\n- ✗ Minimizar distância a $\\mathbf{y}$ não tem relação com a norma do\n  próprio ponto do subespaço — são duas quantidades independentes.\n:::\n\n::: {.fragment}\n**Voltando à pergunta:** só a perpendicular funciona — é exatamente a\nPropriedade 2 que o Bloco 4 vai provar ser *equivalente* à Propriedade 1\n(mais próximo $\\iff$ perpendicular), não só uma coincidência do desenho.\n:::\n:::\n\n# Subespaços e Complemento Ortogonal\n\n---\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## Recapitulando: Subespaço e Espaço-Coluna\n\nA Aula 1 definiu **subespaço** $U\\subseteq V$ como um subconjunto\nfechado sob combinação linear: para quaisquer $\\mathbf{u},\\mathbf{v}\\in\nU$ e escalares $a,b\\in\\mathbb{R}$, $a\\mathbf{u}+b\\mathbf{v}\\in U$ (em\nparticular, $\\mathbf{0}\\in U$ sempre — basta tomar $a=b=0$). A Aula 2\ndeu um exemplo concreto e central para este curso — o **espaço-coluna**\n$$\n\\text{col}(X) = \\{X\\mathbf{w} : \\mathbf{w}\\in\\mathbb{R}^d\\}\\subseteq\\mathbb{R}^N,\n$$\no conjunto de todas as combinações lineares das colunas de $X$ (a\nLeitura 2 do produto matriz-vetor, Aula 2), ou seja, tudo que\n$X\\mathbf{w}$ alcança quando $\\mathbf{w}$ varia livremente por\n$\\mathbb{R}^d$ — e essa definição já garante que $\\text{col}(X)$ é, de\nfato, um subespaço (a distributividade do produto matriz-vetor,\n$X(a\\mathbf{w}_1+b\\mathbf{w}_2)=aX\\mathbf{w}_1+bX\\mathbf{w}_2$, é\nexatamente o fechamento sob combinação linear exigido pela definição).\nCom $X\\in\\mathbb{R}^{16640\\times 4}$ de posto completo (verificado na\nAula 2), $\\text{col}(X)$ é um subespaço de dimensão $4$ dentro de um\nespaço ambiente de dimensão $16\\,640$ — geometricamente, como um plano\nfiníssimo boiando dentro de um espaço gigantesco, e $\\mathbf{y}$ (o\nvetor com as $16\\,640$ observações de `MedHouseVal`) quase certamente\nnão está dentro dele.\n\n## O Complemento Ortogonal\n\nA pergunta natural — \"o que dizer sobre a parte de $\\mathbf{y}$ que\n**não** está em $\\text{col}(X)$?\" — tem uma resposta com nome: o\n**complemento ortogonal**. Dado um subespaço $U$ de um espaço $V$ de\ndimensão $D$, com $U$ de dimensão $M$, o MathML define (tradução nossa,\n§3.6, p. 79):\n\n> \"seu complemento ortogonal $U^\\perp$ é um subespaço de $V$ de dimensão\n> $(D-M)$ e contém todos os vetores em $V$ que são ortogonais a todo\n> vetor em $U$. Além disso, $U\\cap U^\\perp=\\{\\mathbf{0}\\}$, de modo que\n> qualquer vetor $\\mathbf{x}\\in V$ pode ser decomposto de forma única\"\n$$\n\\mathbf{x} = \\sum_{m=1}^{M}\\lambda_m\\mathbf{b}_m + \\sum_{j=1}^{D-M}\\psi_j\\mathbf{b}_j^\\perp,\n\\qquad \\lambda_m,\\psi_j\\in\\mathbb{R} \\qquad \\text{(MathML, eq. 3.36)},\n$$\nonde $(\\mathbf{b}_1,\\dots,\\mathbf{b}_M)$ é uma base de $U$ e\n$(\\mathbf{b}_1^\\perp,\\dots,\\mathbf{b}_{D-M}^\\perp)$ é uma base de\n$U^\\perp$. Em notação compacta, isso se escreve $V = U \\oplus U^\\perp$:\ntodo vetor de $V$ é a soma de **uma única** parte dentro de $U$ com\n**uma única** parte dentro de $U^\\perp$ — nunca duas formas diferentes de\nfazer essa soma, nunca nenhuma parte sobrando de fora.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Recapitulando: Subespaço e Espaço-Coluna\n\n::: {.fragment}\n**Subespaço** $U\\subseteq V$ (Aula 1): fechado sob combinação linear —\npara quaisquer $\\mathbf{u},\\mathbf{v}\\in U$ e escalares $a,b\\in\\mathbb{R}$,\n$a\\mathbf{u}+b\\mathbf{v}\\in U$ (em particular, $\\mathbf{0}\\in U$).\n:::\n\n::: {.fragment}\n**Espaço-coluna** (Aula 2): $\\text{col}(X) = \\{X\\mathbf{w} :\n\\mathbf{w}\\in\\mathbb{R}^d\\}\\subseteq\\mathbb{R}^N$ — todas as combinações\nlineares das colunas de $X$ (Leitura 2 do produto matriz-vetor).\n$\\text{col}(X)$ já é, por construção, um subespaço.\n:::\n\n::: {.fragment}\n$X\\in\\mathbb{R}^{16640\\times 4}$, posto completo: $\\text{col}(X)$ tem\ndimensão $4$ dentro de um ambiente de dimensão $16\\,640$ — um \"plano\"\nfiníssimo boiando num espaço gigantesco. $\\mathbf{y}$ quase certamente\nfora dele.\n:::\n\n## O Complemento Ortogonal\n\n\n::: {.fragment}\n**Definição (MathML, §3.6, tradução nossa):** dado $U\\subseteq V$ com\n$\\dim U = M$, $\\dim V = D$, seu complemento ortogonal $U^\\perp$ é um\nsubespaço de dimensão $(D-M)$: todos os vetores de $V$ ortogonais a\n**todo** vetor de $U$.\n:::\n\n::: {.fragment}\n$U\\cap U^\\perp=\\{\\mathbf{0}\\}$; todo $\\mathbf{x}\\in V$ se decompõe de\nforma **única**:\n$$\\mathbf{x} = \\underbrace{\\sum_m \\lambda_m\\mathbf{b}_m}_{\\in\\, U} + \\underbrace{\\sum_j \\psi_j\\mathbf{b}_j^\\perp}_{\\in\\, U^\\perp}$$\n:::\n\n::: {.fragment}\nNotação compacta: $V = U\\oplus U^\\perp$ — uma única parte em $U$, uma\núnica parte em $U^\\perp$, nada sobra de fora.\n:::\n\n## O Complemento Ortogonal\n:::\n\n::: {.fig-resize style=\"width: 25%; margin: 0 auto;\"}\n\n::: {#3bb8df13 .cell execution_count=3}\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-revealjs/cell-4-output-1.svg){fig-align='center'}\n:::\n:::\n\n\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\nEm $\\mathbb{R}^2$ ($D=2$), com $U$ a reta de dimensão $M=1$, o\ncomplemento ortogonal $U^\\perp$ também tem dimensão $D-M=1$ — a reta\nperpendicular. O vetor $\\mathbf{x}=(1,3)$ se decompõe de forma única em\numa parte sobre $U$ e uma parte sobre $U^\\perp$ (linhas pontilhadas): some\nas duas setas azul/laranja e você recupera exatamente $\\mathbf{x}$, sem\nsobra e sem ambiguidade — não existe uma segunda forma de fazer essa\nsoma. Em $\\mathbb{R}^3$, se $U$ fosse um plano ($M=2$), $U^\\perp$ teria\ndimensão $D-M=1$ — é exatamente o \"vetor normal\" do MathML: \"o vetor\n$\\mathbf{w}$ com $\\|\\mathbf{w}\\|=1$, ortogonal ao plano $U$, é o vetor de\nbase de $U^\\perp$\" (tradução nossa, §3.6, p. 80). No caso da regressão\nque fecha esta aula, $D=16\\,640$ e $M=4$: $U^\\perp=\\text{col}(X)^\\perp$\ntem a dimensão gigantesca $16\\,636$, mas isso não importa para o que\nvamos usar dele — só importa que o resíduo $\\mathbf{y}-\\hat{\\mathbf{y}}$\nvai viver exatamente ali dentro.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n::: {.fragment}\n$D=2$, $U$ = reta ($M=1$) $\\Rightarrow$ $U^\\perp$ = reta perpendicular\n($D-M=1$). $\\mathbf{x}=(1,3)$ decompõe-se de forma única: soma das duas\nsetas recupera $\\mathbf{x}$, sem sobra, sem ambiguidade.\n:::\n\n::: {.fragment}\nEm $\\mathbb{R}^3$ com $U$ = plano ($M=2$): $U^\\perp$ tem dimensão $1$ —\no **vetor normal** do MathML, \"$\\mathbf{w}$ com $\\|\\mathbf{w}\\|=1$,\nortogonal ao plano $U$\" (tradução nossa, §3.6).\n:::\n\n::: {.fragment}\nNa regressão: $D=16\\,640$, $M=4$. $U^\\perp=\\text{col}(X)^\\perp$ tem\ndimensão $16\\,636$ — irrelevante em si; o que importa é que o resíduo\n$\\mathbf{y}-\\hat{\\mathbf{y}}$ vive exatamente ali.\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n::: {.callout-tip}\n## Se $U$ fosse o subespaço trivial $\\{\\mathbf{0}\\}$, o que seria $U^\\perp$?\n\nDica: releia a definição — $U^\\perp$ contém todo vetor ortogonal a\n**todo** vetor de $U$. Se o único vetor de $U$ for $\\mathbf{0}$, quantos\nvetores de $V$ são ortogonais a ele?\n\n- □ Se $U$ fosse o subespaço trivial $\\{\\mathbf{0}\\}$, seu complemento\n  ortogonal $U^\\perp$ seria igual ao espaço $V$ inteiro.\n- □ Se $U=V$ (o subespaço é o espaço inteiro), então\n  $U^\\perp=\\{\\mathbf{0}\\}$.\n- □ Num modelo de regressão em que o resíduo $\\mathbf{y}-\\hat{\\mathbf{y}}$\n  é ortogonal a todo vetor do espaço-coluna de $X$, esse resíduo não é\n  apenas \"ortogonal a ele\" informalmente — ele satisfaz a própria\n  definição formal de pertencer a $\\text{col}(X)^\\perp$.\n- □ Como todo vetor de $V$ se decompõe de forma única numa parte de $U$\n  e uma parte de $U^\\perp$, isso implica que $U$ e $U^\\perp$ têm,\n  necessariamente, a mesma dimensão.\n:::\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Pergunta\n\n::: {.callout-tip}\n## Se $U$ fosse o subespaço trivial $\\{\\mathbf{0}\\}$, o que seria $U^\\perp$?\n\nDica: $U^\\perp$ contém todo vetor ortogonal a **todo** vetor de $U$. Com\n$U=\\{\\mathbf{0}\\}$, quantos vetores de $V$ cumprem isso?\n\n- □ $U=\\{\\mathbf{0}\\}$ $\\Rightarrow$ $U^\\perp = V$ (o espaço inteiro).\n- □ $U=V$ $\\Rightarrow$ $U^\\perp=\\{\\mathbf{0}\\}$.\n- □ O resíduo ortogonal ao espaço-coluna de $X$ satisfaz a própria\n  definição formal de pertencer a $\\text{col}(X)^\\perp$, não só\n  \"ortogonal\" informalmente.\n- □ Decomposição única de $V$ em $U\\oplus U^\\perp$ implica $\\dim U =\n  \\dim U^\\perp$.\n:::\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Resposta\n\n::: {.callout-tip}\n## Subespaço trivial e seu complemento — Resposta\n\n- ✔ Todo vetor de $V$ é ortogonal a $\\mathbf{0}$ (produto interno com o\n  vetor nulo é sempre $0$); logo $U^\\perp=V$.\n- ✔ Caso simétrico do anterior: só $\\mathbf{0}$ é ortogonal a todo\n  vetor de $V=U$.\n- ✔ É exatamente a definição de $U^\\perp$ aplicada a $U=\\text{col}(X)$\n  — antecipa o Bloco 4.\n- ✗ $\\dim U=M$, $\\dim U^\\perp=D-M$; iguais só se $D=2M$, não em geral\n  (na regressão, $M=4 \\ne D-M=16\\,636$).\n:::\n\n::: {.fragment}\n**Voltando à pergunta:** o complemento ortogonal de $\\{\\mathbf{0}\\}$ é o\nespaço todo — caso extremo que confirma a definição, não uma exceção a\nela.\n:::\n:::\n\n# O Teorema da Projeção: Premissas e Passo a Passo\n\n---\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## Enunciando o Problema com Precisão\n\nAntes de derivar qualquer fórmula, vamos deixar explícitas as premissas\n— seguindo a diretriz deste curso de nunca saltar direto para o\nresultado final.\n\n::: {.callout-note}\n## Premissas\n\n1. Temos um subespaço $U=\\text{col}(X)\\subseteq\\mathbb{R}^N$, o\n   espaço-coluna da matriz de design (Aula 2).\n2. Temos um vetor $\\mathbf{y}\\in\\mathbb{R}^N$ que, em geral, **não**\n   pertence a $U$ (o caso sobredeterminado da Aula 2 e do Bloco 1 desta\n   aula).\n3. Definimos $\\hat{\\mathbf{y}}\\in U$ como o ponto de $U$ **mais próximo**\n   de $\\mathbf{y}$ — o que minimiza $\\|\\mathbf{y}-\\hat{\\mathbf{y}}\\|$\n   (a formalização da \"sombra\" do Bloco 2).\n:::\n\nO objetivo dos dois passos seguintes é ir de \"$\\hat{\\mathbf{y}}$ minimiza\na distância\" até uma fórmula fechada e calculável para $\\hat{\\mathbf{w}}$\ntal que $\\hat{\\mathbf{y}}=X\\hat{\\mathbf{w}}$.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Enunciando o Problema com Precisão\n\n::: {.callout-note icon=false}\n**Premissas**\n\n1. Subespaço $U=\\text{col}(X)\\subseteq\\mathbb{R}^N$ (Aula 2).\n2. $\\mathbf{y}\\in\\mathbb{R}^N$, em geral **fora** de $U$ (sobredeterminado).\n3. $\\hat{\\mathbf{y}}\\in U$ = ponto de $U$ mais próximo de $\\mathbf{y}$\n   (minimiza $\\|\\mathbf{y}-\\hat{\\mathbf{y}}\\|$) — a \"sombra\" formalizada.\n:::\n\n::: {.fragment}\nObjetivo: dessas premissas até uma fórmula fechada e calculável para\n$\\hat{\\mathbf{w}}$, com $\\hat{\\mathbf{y}}=X\\hat{\\mathbf{w}}$.\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## Passo (i): Ortogonal a Cada Coluna de $X$ via Otimização\n\nFormalizar \"$\\hat{\\mathbf{y}}$ é o ponto de $U=\\text{col}(X)$ mais\npróximo de $\\mathbf{y}$\" é resolver um problema de otimização. Minimizar\na distância $\\|\\mathbf{y}-\\mathbf{v}\\|$ sobre $\\mathbf{v}\\in U$ é\nequivalente a minimizar o **quadrado** da distância — a raiz quadrada é\ncrescente, então o mínimo cai no mesmo ponto, e o quadrado tem derivada\nmais simples. E como $U=\\text{col}(X)$, já sabemos exatamente como\n$\\mathbf{v}$ varia dentro de $U$: pela Leitura 2 do produto matriz-vetor\n(Aula 2), todo $\\mathbf{v}\\in U$ é $X\\mathbf{w}$ para algum\n$\\mathbf{w}\\in\\mathbb{R}^d$, e $\\mathbf{w}$ não tem restrição nenhuma —\nnão é preciso inventar uma base abstrata de $U$ só para ter variáveis\nlivres para derivar; $\\mathbf{w}$ já **é** essa variável livre, dada de\ngraça pela própria definição de espaço-coluna. Minimizar sobre\n$\\mathbf{v}\\in U$ é, então, o mesmo que minimizar sobre\n$\\mathbf{w}\\in\\mathbb{R}^d$ **sem restrições** — um problema de\notimização irrestrita de verdade:\n$$\n\\hat{\\mathbf{w}} = \\arg\\min_{\\mathbf{w}\\in\\mathbb{R}^d}\\; g(\\mathbf{w}),\n\\qquad g(\\mathbf{w}) = \\|\\mathbf{y}-X\\mathbf{w}\\|^2.\n$$\n\nExpandindo por manipulação de matrizes —\n$(\\mathbf{y}-X\\mathbf{w})^T(\\mathbf{y}-X\\mathbf{w})$, usando que\n$\\mathbf{y}^TX\\mathbf{w}$ é um escalar, logo igual à sua própria\ntransposta $\\mathbf{w}^TX^T\\mathbf{y}$:\n$$\ng(\\mathbf{w}) = \\mathbf{y}^T\\mathbf{y} - 2\\,\\mathbf{y}^TX\\mathbf{w} +\n\\mathbf{w}^TX^TX\\mathbf{w}.\n$$\nUsando as regras de cálculo vetorial $\\nabla_{\\mathbf{w}}(\\mathbf{a}^T\\mathbf{w})=\\mathbf{a}$\ne $\\nabla_{\\mathbf{w}}(\\mathbf{w}^TC\\mathbf{w})=2C\\mathbf{w}$ (para $C$\nsimétrica — e $X^TX$ é simétrica), o gradiente de $g$ é\n$$\n\\nabla_{\\mathbf{w}}\\, g(\\mathbf{w}) = -2X^T\\mathbf{y} + 2X^TX\\mathbf{w} =\n-2\\,X^T(\\mathbf{y}-X\\mathbf{w}).\n$$\nA Hessiana é $2X^TX$, e ela é **sempre semidefinida positiva** — para\nqualquer $X$, $\\mathbf{w}^TX^TX\\mathbf{w}=\\|X\\mathbf{w}\\|^2\\ge 0$ —, o\nsuficiente para $g$ ser convexa, mesmo sem sabermos ainda se $X^TX$ é\ninvertível (essa condição extra só vai entrar no Passo (ii), para\n*isolar* um único $\\hat{\\mathbf{w}}$ — não é necessária para caracterizar\no mínimo). Como o problema é irrestrito e $g$ é convexa, o mínimo é\ncaracterizado pela **condição de otimalidade de primeira ordem para\nproblemas irrestritos** — necessária *e* suficiente para um mínimo\nglobal: o gradiente se anula no ponto ótimo,\n$$\n-2\\,X^T(\\mathbf{y}-X\\hat{\\mathbf{w}}) = \\mathbf{0}\n\\qquad\\Longleftrightarrow\\qquad\nX^T(\\mathbf{y}-X\\hat{\\mathbf{w}}) = \\mathbf{0}.\n$$\n\nEssa equação diz que o resíduo $\\mathbf{y}-X\\hat{\\mathbf{w}}$ é ortogonal\na cada coluna de $X$ individualmente. E como todo vetor de\n$\\text{col}(X)$ é combinação linear das colunas (a mesma Leitura 2 de\nnovo), o resíduo é ortogonal a **qualquer** vetor de $\\text{col}(X)$ — a\nortogonalidade \"passa\" pela combinação linear sem se perder:\n$$\n\\mathbf{y}-X\\hat{\\mathbf{w}} \\;\\perp\\; \\text{col}(X).\n$$\nMinimizar a distância e ser ortogonal a $\\text{col}(X)$, portanto, não\nsão duas condições separadas — são a mesma condição, uma vista pela\ndefinição (mínimo) e a outra pela consequência algébrica de anular o\ngradiente. O MathML batiza essa condição da mesma forma (tradução nossa,\n§3.8.2, p. 85-86, adaptando $B\\to X$): \"obtemos $m$ condições\nsimultâneas [...] o que [...] pode ser escrito como um sistema linear\nhomogêneo [...] $B^T(\\mathbf{x}-B\\lambda)=\\mathbf{0}$\" — o MathML enuncia\nessa condição via uma base abstrata de $U$; aqui chegamos a ela\ndiretamente, otimizando sobre a variável livre $\\mathbf{w}$ que $X$ já\noferece de graça.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Passo (i): \"Mais Próximo\" Equivale a \"Ortogonal a Cada Coluna de $X$\" — Via Otimização\n\n::: {.fragment}\nMinimizar $\\|\\mathbf{y}-\\mathbf{v}\\|$ sobre $\\mathbf{v}\\in U=\\text{col}(X)$\n$\\equiv$ minimizar $\\|\\mathbf{y}-\\mathbf{v}\\|^2$. Podemos definir $\\mathbf{v}=X\\mathbf{w}$ com $\\mathbf{w}\\in\\mathbb{R}^d$ **livre**, onde $\\mathbf{w}$ é a variável livre.\n:::\n\n::: {.fragment}\n$$g(\\mathbf{w}) = \\|\\mathbf{y}-X\\mathbf{w}\\|^2 = \\mathbf{y}^T\\mathbf{y} - 2\\mathbf{y}^TX\\mathbf{w} + \\mathbf{w}^TX^TX\\mathbf{w}$$\nCálculo vetorial: $\\nabla_{\\mathbf{w}} g = -2X^T\\mathbf{y}+2X^TX\\mathbf{w} = -2X^T(\\mathbf{y}-X\\mathbf{w})$.\n:::\n\n::: {.fragment}\nHessiana $2X^TX$ é **sempre semidefinida positiva**\n($\\mathbf{w}^TX^TX\\mathbf{w}=\\|X\\mathbf{w}\\|^2\\ge0$) $\\Rightarrow$ $g$\nconvexa — nem precisa de $X^TX$ invertível ainda. **Condição de\notimalidade de primeira ordem** (irrestrita, necessária e suficiente):\n$$X^T(\\mathbf{y}-X\\hat{\\mathbf{w}}) = \\mathbf{0}$$\n:::\n\n::: {.fragment}\nResíduo ortogonal a cada coluna de $X$ $\\Rightarrow$ (combinação linear)\nortogonal a **todo** $\\text{col}(X)$:\n$$\\mathbf{y}-X\\hat{\\mathbf{w}} \\perp \\text{col}(X)$$\nMesma equação do MathML ($B^T(\\mathbf{x}-B\\lambda)=\\mathbf{0}$, tradução\nnossa, §3.8.2) — ali via base abstrata; aqui, direto com $X$.\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## Passo (ii): Isolando $\\hat{\\mathbf{w}}$ — as Equações Normais\n\nDistribuindo o produto do Passo (i):\n$$\nX^T\\mathbf{y} - X^TX\\hat{\\mathbf{w}} = \\mathbf{0}\n\\qquad\\Longleftrightarrow\\qquad\nX^TX\\hat{\\mathbf{w}} = X^T\\mathbf{y}.\n$$\nO MathML batiza essa equação (tradução nossa, §3.8.2, p. 86, eq. 3.56):\n\"a última expressão é chamada **equação normal**\". Isso ainda não é a\nfórmula fechada de $\\hat{\\mathbf{w}}$ — é um sistema linear em\n$\\hat{\\mathbf{w}}$, com $X^TX\\in\\mathbb{R}^{d\\times d}$ no papel de \"$A$\"\ne $X^T\\mathbf{y}\\in\\mathbb{R}^d$ no papel de \"$\\mathbf{b}$\" (a mesma\nestrutura $A\\mathbf{x}=\\mathbf{b}$ da Aula 2, agora numa matriz derivada\nde $X$, não em $X$ diretamente).\n\n**Quando esse sistema tem solução única.** O MathML completa a derivação\nnotando exatamente a condição que faz $X^TX$ invertível (tradução nossa,\n§3.8.2, p. 86): \"como $b_1,\\dots,b_m$ são uma base de $U$ e, portanto,\nlinearmente independentes, $B^TB\\in\\mathbb{R}^{m\\times m}$ é regular e\npode ser invertida.\" Traduzido para o nosso caso: as colunas de $X$ são\nlinearmente independentes exatamente quando $X$ tem **posto completo**\n($\\text{rk}(X)=d$) — o mesmo critério provado na Aula 2, Bloco 5. Quando\nisso vale, $X^TX$ é invertível, e podemos isolar\n$\\hat{\\mathbf{w}}$:\n$$\n\\hat{\\mathbf{w}} = (X^TX)^{-1}X^T\\mathbf{y}.\n$$\nO MathML chama a matriz $(X^TX)^{-1}X^T$ de **pseudo-inversa** de $X$\n(tradução nossa, §3.8.2, p. 86) — um nome que vai voltar quando o curso\ntratar de decomposições matriciais (SVD), mais adiante. Por ora, a peça\nque fecha o ciclo aberto na Aula 2: o sistema $X\\mathbf{w}=\\mathbf{y}$\nsobredeterminado não tem solução exata, mas **tem**, sob posto completo,\numa única melhor aproximação — e ela tem fórmula fechada.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Passo (ii): Isolando $\\hat{\\mathbf{w}}$ — as Equações Normais\n\n::: {.fragment}\nDistribuindo o Passo (i):\n$$X^T\\mathbf{y} - X^TX\\hat{\\mathbf{w}} = \\mathbf{0} \\iff X^TX\\hat{\\mathbf{w}} = X^T\\mathbf{y}$$\n:::\n\n::: {.fragment}\n**Equações Normais** (MathML, eq. 3.56, tradução nossa) — um sistema\nlinear em $\\hat{\\mathbf{w}}$: $X^TX$ no papel de \"$A$\", $X^T\\mathbf{y}$\nno papel de \"$\\mathbf{b}$\" — mesma estrutura $A\\mathbf{x}=\\mathbf{b}$ da\nAula 2.\n:::\n\n## Quando o Sistema Tem Solução Única\n\n::: {.fragment}\nMathML (tradução nossa, §3.8.2): colunas de $X$ linearmente\nindependentes $\\Rightarrow$ $X^TX$ \"regular, pode ser invertida\" —\nexatamente o **posto completo** ($\\text{rk}(X)=d$) da Aula 2, Bloco 5.\n:::\n\n::: {.fragment}\nSob posto completo:\n$$\\hat{\\mathbf{w}} = (X^TX)^{-1}X^T\\mathbf{y}$$\n$(X^TX)^{-1}X^T$ = **pseudo-inversa** de $X$ (MathML) — nome que volta\nquando o curso tratar de SVD.\n:::\n\n::: {.fragment}\nSobredeterminado sem solução exata, mas **com** aproximação sob posto completo — com fórmula fechada.\n:::\n:::\n\n::: {.fig-resize style=\"width: 65%; margin: 0 auto;\"}\n```{.tikz}\n\\usetikzlibrary{arrows.meta, positioning}\n\\definecolor{icblue}{HTML}{0085CA}\n\\definecolor{icorange}{HTML}{FF5E00}\n\\definecolor{icred}{HTML}{E03C31}\n\\begin{tikzpicture}[scale=1.0]\n  % col(X): reta pela origem, direção (5,1) -- ŷ abaixo é a projeção\n  % ortogonal exata de y sobre essa reta (calculada, não estética).\n  \\draw[icblue, thick] (-2.648,-0.530) -- (2.648,0.530) node[right] {\\small $\\mathrm{col}(X)$};\n  \\node (yhat) at (1.462,0.292) {};\n  \\fill[icorange] (1.462,0.292) circle (2.4pt);\n  \\node[icorange, below right=1pt and 2pt of yhat, font=\\small] {$\\hat{\\mathbf{y}}=X\\hat{\\mathbf{w}}$};\n  \\node (y) at (1.1,2.1) {};\n  \\fill[icred] (1.1,2.1) circle (2.4pt);\n  \\node[icred, above=2pt of y, font=\\small] {$\\mathbf{y}$};\n  \\draw[gray!70, dashed, thick, -{Stealth}] (1.1,2.1) -- (1.462,0.292) node[midway, right, font=\\small, black] {resíduo $\\perp\\, \\mathrm{col}(X)$};\n  % marcador de ângulo reto no ponto de encontro\n  \\draw[gray!70, thick] (1.609,0.322) -- (1.579,0.469) -- (1.432,0.440);\n  \\draw[icblue, -{Stealth}, thick] (1.119,0.224) -- (1.462,0.292);\n\\end{tikzpicture}\n```\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\nO esquema resume os dois passos: $\\text{col}(X)$ é a \"reta\" azul (uma\nrepresentação necessariamente simplificada de um subespaço de dimensão\n$4$), $\\mathbf{y}$ está fora dele, $\\hat{\\mathbf{y}}=X\\hat{\\mathbf{w}}$ é\no ponto mais próximo dentro de $\\text{col}(X)$, e o resíduo (tracejado)\nencontra o subespaço em ângulo reto — a mesma \"sombra\" do Bloco 2, agora\ncom nome de variável de regressão.\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n::: {.callout-tip}\n## A condição $(\\mathbf{y}-X\\hat{\\mathbf{w}})\\perp\\text{col}(X)$ garante que o resíduo seja zero?\n\nDica: releia o Passo (i) — \"mais próximo\" e \"ortogonal\" são a mesma\ncondição. Isso é o mesmo que dizer \"o erro desaparece\"?\n\n- □ Se, em vez de minimizar $\\|\\mathbf{y}-X\\mathbf{w}\\|$ (norma $L_2$),\n  o critério de \"melhor\" fosse minimizar $\\|\\mathbf{y}-X\\mathbf{w}\\|_1$\n  (norma $L_1$), a condição de ortogonalidade\n  $(\\mathbf{y}-X\\hat{\\mathbf{w}})\\perp\\text{col}(X)$ ainda garantiria a\n  solução.\n- □ No caso em que $\\mathbf{y}$ já pertence ao espaço-coluna de $X$, as\n  Equações Normais $X^TX\\hat{\\mathbf{w}}=X^T\\mathbf{y}$ têm como\n  solução um $\\hat{\\mathbf{w}}$ tal que $X\\hat{\\mathbf{w}}=\\mathbf{y}$\n  exatamente (erro zero).\n- □ Num problema de calibração de sensores, em que $\\mathbf{y}$ são\n  leituras redundantes de $N$ sensores e $X$ mapeia $d<N$ parâmetros\n  físicos verdadeiros para essas leituras, a mesma derivação das\n  Equações Normais forneceria a melhor estimativa desses parâmetros por\n  mínimos quadrados.\n- □ Como a condição $(\\mathbf{y}-X\\hat{\\mathbf{w}})\\perp\\text{col}(X)$\n  equivale a $X^T(\\mathbf{y}-X\\hat{\\mathbf{w}})=\\mathbf{0}$, isso\n  significa que o resíduo $\\mathbf{y}-X\\hat{\\mathbf{w}}$ deve ser o\n  vetor nulo sempre que $X$ tiver posto completo.\n:::\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Pergunta\n\n::: {.callout-tip}\n## A condição $(\\mathbf{y}-X\\hat{\\mathbf{w}})\\perp\\text{col}(X)$ garante resíduo zero?\n\nDica: \"mais próximo\" e \"ortogonal\" são a mesma condição (Passo i) — isso\né o mesmo que \"erro desaparece\"?\n\n- □ Se o critério fosse minimizar $\\|\\mathbf{y}-X\\mathbf{w}\\|_1$ em vez\n  de $L_2$, a mesma condição de ortogonalidade ainda garantiria a\n  solução.\n- □ Se $\\mathbf{y}\\in\\text{col}(X)$, as Equações Normais dão\n  $\\hat{\\mathbf{w}}$ com $X\\hat{\\mathbf{w}}=\\mathbf{y}$ exatamente.\n- □ Calibração de sensores ($N$ leituras, $d<N$ parâmetros físicos):\n  mesma derivação das Equações Normais, outro domínio.\n- □ Ortogonalidade do resíduo $\\Rightarrow$ resíduo nulo sempre que $X$\n  tem posto completo.\n:::\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Resposta\n\n::: {.callout-tip}\n## A condição de ortogonalidade garante resíduo zero? — Resposta\n\n- ✗ A equivalência \"mínimo $\\iff$ ortogonal\" (Passo i) é específica da\n  norma $L_2$/produto interno; a norma $L_1$ não tem essa geometria de\n  ângulo reto, e minimizá-la leva a uma condição diferente (subgradiente\n  nulo, não ortogonalidade).\n- ✔ $\\mathbf{y}\\in\\text{col}(X)$: a melhor aproximação é o próprio\n  $\\mathbf{y}$, erro zero — caso trivial consistente com a teoria.\n- ✔ Mesma estrutura matemática (mínimos quadrados via projeção), outro\n  domínio (calibração em vez de preço de imóvel).\n- ✗ Ortogonalidade a $\\text{col}(X)$ não força resíduo nulo — só força\n  que o resíduo esteja em $\\text{col}(X)^\\perp$; ele é zero apenas se\n  $\\mathbf{y}$ já estivesse em $\\text{col}(X)$, o que é a exceção, não a\n  regra, no caso sobredeterminado.\n:::\n\n::: {.fragment}\n**Voltando à pergunta:** não — ortogonal ao subespaço é bem mais fraco\nque \"igual a zero\"; é só a direção do erro que fica fixada\n($U^\\perp$), não o seu tamanho.\n:::\n:::\n\n# Aplicação e Verificação no Dado Real\n\n---\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## Calculando $\\hat{\\mathbf{w}}$ de Verdade\n\nChegou a hora de aplicar a fórmula fechada do Passo (ii) ao problema\nmotivador do Bloco 1: os $N=16\\,640$ bairros do California Housing, com\n$X\\in\\mathbb{R}^{16640\\times 4}$ (as colunas `MedInc`, `HouseAge`,\n`AveRooms`, `AveBedrms`) e $\\mathbf{y}\\in\\mathbb{R}^{16640}$\n(`MedHouseVal`). Como a Aula 2 já verificou que $X$ tem posto completo\n($\\text{rk}(X)=4$), $X^TX$ é invertível, e a fórmula\n$\\hat{\\mathbf{w}}=(X^TX)^{-1}X^T\\mathbf{y}$ se aplica diretamente.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Calculando $\\hat{\\mathbf{w}}$ de Verdade\n\n::: {.fragment}\nAplicando a fórmula fechada ao problema motivador: $N=16\\,640$ bairros,\n$X\\in\\mathbb{R}^{16640\\times 4}$, $\\mathbf{y}=$ `MedHouseVal`. Posto\ncompleto (Aula 2) $\\Rightarrow$ $X^TX$ invertível.\n:::\n:::\n\n::: {#cc98004d .cell execution_count=4}\n``` {.python .cell-code}\nX_completo = _housing[COLS].to_numpy()\ny_completo = _housing[\"MedHouseVal\"].to_numpy()\n\n# Equações Normais, resolvidas diretamente pela fórmula fechada\nXtX = X_completo.T @ X_completo\nXty = X_completo.T @ y_completo\nw_hat = np.linalg.inv(XtX) @ Xty\n\ntabela_w = pd.DataFrame({\"atributo\": COLS, \"ŵ\": np.round(w_hat, 5)})\ntabela_w\n```\n\n::: {.cell-output .cell-output-display execution_count=114}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>atributo</th>\n      <th>ŵ</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>MedInc</td>\n      <td>0.48761</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>HouseAge</td>\n      <td>0.01171</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>AveRooms</td>\n      <td>-0.18809</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>AveBedrms</td>\n      <td>0.78255</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\nA tabela mostra que o peso de maior módulo não é o de `MedInc`\n($\\approx 0{,}488$), como seria fácil supor à primeira vista, mas o de\n`AveBedrms` ($\\approx 0{,}783$) — e isso é uma pista, não uma medida\ndireta de importância. `AveRooms` e `AveBedrms` são atributos fortemente\ncorrelacionados (quantos cômodos, quantos são quartos — Bloco 6 volta a\nisso com números), e a Regressão Linear Múltipla estima cada peso **na\npresença** dos demais (Leitura 2 do produto matriz-vetor, Aula 2):\nquando duas colunas carregam quase a mesma informação, o modelo pode\ndistribuir o efeito combinado entre elas de forma desequilibrada — um\npeso grande e positivo, o outro pequeno ou até **negativo** (`AveRooms`,\n$\\approx -0{,}188$) — sem que isso signifique, isoladamente, que mais\ncômodos reduzam o preço. É um sintoma do problema de multicolinearidade\nque o Bloco 6 vai quantificar e explicar por que fragiliza numericamente\n$X^TX$. O peso de `MedInc` ($\\approx 0{,}488$), por não competir por\ninformação redundante com nenhum outro atributo do modelo, tem leitura\ndireta: cada unidade adicional de renda mediana está associada a um\naumento de $\\approx 0{,}488$ (centenas de milhares de dólares) no preço\nprevisto. Já `HouseAge` tem o menor peso em módulo ($\\approx 0{,}012$) —\na idade do imóvel, sozinha, quase não move a previsão depois de\ncontrolar pelos outros três atributos.\n\n## Conferência Independente: `numpy.linalg.lstsq`\n\nA fórmula fechada é uma forma de calcular $\\hat{\\mathbf{w}}$, mas não a\núnica — `numpy.linalg.lstsq` resolve o mesmo problema de mínimos\nquadrados por um algoritmo numérico diferente (decomposição, não\ninversão explícita de $X^TX$). Se a nossa derivação do Bloco 4 estiver\ncerta, as duas contas devem coincidir:\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## O Que os Pesos Dizem\n\n::: {.fragment}\n`AveBedrms` ($\\approx 0{,}783$) é o maior peso seguido de aior peso em módulo não`MedInc` ($\\approx 0{,}488$). `AveRooms`, $\\approx -0{,}188$ que deveria ter relação está negativo, pista de multicolinearidade, não de\nimportância.\n:::\n\n::: {.fragment}\n`AveRooms`/`AveBedrms` são correlacionados (Bloco 6); pesos estimados\n**na presença** um do outro podem se desequilibrar — um grande, outro\npequeno ou **negativo** (`AveRooms`, $\\approx -0{,}188$) — sem\nsignificado causal isolado.\n:::\n\n::: {.fragment}\n`MedInc` ($\\approx 0{,}488$): sem redundância com os demais, leitura\ndireta. `HouseAge` ($\\approx 0{,}012$): menor peso, quase sem efeito\nmarginal.\n:::\n\n## Conferência Independente\n\n::: {.fragment}\nFórmula fechada não é a única forma de calcular $\\hat{\\mathbf{w}}$ —\n`numpy.linalg.lstsq` resolve o mesmo problema por outro algoritmo\n(decomposição, sem inverter $X^TX$ explicitamente). As duas contas\ndevem coincidir:\n:::\n:::\n\n::: {#75bcb49d .cell execution_count=5}\n``` {.python .cell-code}\nw_lstsq, *_ = np.linalg.lstsq(X_completo, y_completo, rcond=None)\nprint(\"w_hat (lstsq):           \", np.round(w_lstsq, 5))\nprint(\"maior diferença absoluta:\", np.max(np.abs(w_hat - w_lstsq)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nw_hat (lstsq):            [ 0.48761  0.01171 -0.18809  0.78255]\nmaior diferença absoluta: 1.3100631690576847e-14\n```\n:::\n:::\n\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\nA diferença máxima entre os dois vetores é da ordem de $10^{-14}$ —\nzero, a menos de erro de arredondamento de ponto flutuante. Dois\nalgoritmos completamente diferentes (inversão explícita de uma matriz\n$4\\times 4$ vs. decomposição numérica) chegam ao mesmo $\\hat{\\mathbf{w}}$\n— evidência de que a derivação do Bloco 4 não é só elegante no quadro,\nfunciona com dados reais.\n\n## Verificando a Ortogonalidade do Resíduo\n\nA promessa central do Passo (i) foi que o resíduo\n$\\mathbf{y}-X\\hat{\\mathbf{w}}$ é ortogonal a **cada coluna** de $X$ — não\numa afirmação vaga, uma igualdade numérica exata (até erro de\narredondamento) que podemos checar:\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n### O Que a Comparação Confirma\n\n::: {.fragment}\nDiferença máxima entre os dois $\\hat{\\mathbf{w}}$: ordem de $10^{-14}$ —\nzero, a menos de arredondamento de ponto flutuante.\n:::\n\n::: {.fragment}\nDois algoritmos completamente diferentes (inversão explícita $4\\times 4$\nvs. decomposição numérica) chegam ao mesmo resultado — a derivação do\nBloco 4 funciona com dados reais, não só no quadro.\n:::\n\n## Verificando a Ortogonalidade do Resíduo\n\n::: {.fragment}\nPromessa do Passo (i): resíduo $\\perp$ cada coluna de $X$ — não vago,\numa igualdade numérica exata (a menos de arredondamento). Vamos checar:\n:::\n:::\n\n::: {#21c0a7c4 .cell execution_count=6}\n``` {.python .cell-code}\nresiduo = y_completo - X_completo @ w_hat\n\nprint(\"Produto interno do resíduo com cada coluna de X:\")\nfor j, nome in enumerate(COLS):\n    prod = residuo @ X_completo[:, j]\n    print(f\"  {nome:10s}: {prod:.3e}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nProduto interno do resíduo com cada coluna de X:\n  MedInc    : -4.522e-10\n  HouseAge  : -5.039e-09\n  AveRooms  : -8.756e-10\n  AveBedrms : -1.987e-10\n```\n:::\n:::\n\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\nCada produto interno é da ordem de $10^{-9}$ ou menor — e, colocado em\nperspectiva (dividindo pelas normas de cada vetor envolvido, para\ncomparar \"zero relativo\" e não só \"zero absoluto\"), a proporção é da\nordem de $10^{-14}$: numericamente zero, exatamente como o Passo (i)\nexigia. Não é coincidência — é a própria equação\n$X^T(\\mathbf{y}-X\\hat{\\mathbf{w}})=\\mathbf{0}$ (Passo i) verificada\nnumericamente, coluna a coluna.\n\n## O Tamanho do Resíduo — o Que a Ortogonalidade *Não* Diz\n\nOrtogonalidade garante a **direção** do erro (ele mora em\n$\\text{col}(X)^\\perp$), mas nada diz sobre o **tamanho** do erro. Vale a\npena medir:\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n### Zero, em Perspectiva\n\n::: {.fragment}\nCada produto interno: ordem de $10^{-9}$ ou menor. Em proporção (dividido\npelas normas): ordem de $10^{-14}$ — numericamente zero, exatamente como\no Passo (i) exigia.\n:::\n\n::: {.fragment}\nNão é coincidência: é $X^T(\\mathbf{y}-X\\hat{\\mathbf{w}})=\\mathbf{0}$\n(Passo i) verificada numericamente, coluna a coluna.\n:::\n\n## O Tamanho do Resíduo\n\n::: {.fragment}\nOrtogonalidade fixa a **direção** do erro ($\\in\\text{col}(X)^\\perp$),\nnão o **tamanho**. Vale medir:\n:::\n:::\n\n::: {#0dc586f9 .cell execution_count=7}\n``` {.python .cell-code}\nnorma_residuo = np.linalg.norm(residuo)\nnorma_y = np.linalg.norm(y_completo)\nr2 = 1 - np.sum(residuo**2) / np.sum((y_completo - y_completo.mean())**2)\n\nprint(f\"||resíduo|| = {norma_residuo:.2f}\")\nprint(f\"||y||       = {norma_y:.2f}\")\nprint(f\"||resíduo||/||y|| = {norma_residuo/norma_y:.3f}\")\nprint(f\"R² = {r2:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n||resíduo|| = 101.49\n||y||       = 298.57\n||resíduo||/||y|| = 0.340\nR² = 0.518\n```\n:::\n:::\n\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\nO resíduo tem norma $\\approx 101{,}5$ contra $\\|\\mathbf{y}\\|\\approx\n298{,}6$ — não é pequeno; em termos de $R^2$ (a fração da variação de\n`MedHouseVal` \"explicada\" pelo modelo), o ajuste é $R^2\\approx 0{,}518$:\no modelo explica um pouco mais da metade da variação do preço usando só\n4 atributos. Isso não é uma falha da matemática do Bloco 4 — a projeção\nortogonal *garante* a melhor aproximação **possível dentro do espaço-coluna\nde $X$**, não uma boa aproximação em termos absolutos. Com só 4\natributos (faltam localização, qualidade da construção, proximidade da\ncosta, etc.), $\\text{col}(X)$ é um subespaço pequeno demais para chegar\nperto de $\\mathbf{y}$ — a projeção é ótima *dentro das opções\ndisponíveis*, e as opções disponíveis são limitadas pelos atributos\nescolhidos, não pela matemática da projeção.\n\n## Vendo o Ajuste numa Amostra Concreta\n\nVoltando à amostra de 6 bairros usada na Aula 2 (mesma semente,\n`random_state=7`) — agora com o $\\hat{\\mathbf{w}}$ de verdade, ajustado a\npartir de todos os $16\\,640$ bairros, não mais um $\\mathbf{w}$\ninventado:\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n### O Que os Números Dizem\n\n::: {.fragment}\n$\\|\\text{resíduo}\\|\\approx 101{,}5$ contra $\\|\\mathbf{y}\\|\\approx\n298{,}6$: $R^2\\approx 0{,}518$ — o modelo explica pouco mais da metade\nda variação do preço com só 4 atributos.\n:::\n\n::: {.fragment}\n**Não é falha da matemática do Bloco 4** — a projeção garante a melhor\naproximação **dentro de $\\text{col}(X)$**, não uma boa aproximação em\ntermos absolutos. Faltam atributos (localização, qualidade, costa); o\nsubespaço disponível é pequeno demais para chegar perto de\n$\\mathbf{y}$. \n:::\n\n## Vendo o Ajuste numa Amostra Concreta\n\n::: {.fragment}\nAmostra de 6 bairros da Aula 2 (`random_state=7`), agora com\n$\\hat{\\mathbf{w}}$ de verdade — ajustado nos $16\\,640$ bairros, não mais\ninventado:\n:::\n:::\n\n::: {.fig-resize style=\"width: 85%; margin: 0 auto;\"}\n\n::: {#ddf5d22f .cell execution_count=8}\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-revealjs/cell-9-output-1.svg){fig-align='center'}\n:::\n:::\n\n\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\nCompare com o gráfico da Aula 2 (mesmos 6 bairros, $\\mathbf{w}$\ninventado): os erros ali eram grandes e sem padrão claro; aqui, ainda há\nerro (esperado, dado o $R^2\\approx 0{,}518$), mas o modelo já captura a\ntendência geral — o bairro 1 (renda mais alta) continua sendo o de\nprevisão mais alta entre os seis, por exemplo. É a diferença entre \"um\n$\\mathbf{w}$ qualquer\" e \"o $\\hat{\\mathbf{w}}$ que resolve as Equações\nNormais\": o segundo não é perfeito, mas é **matematicamente o melhor\npossível** dentro do que os 4 atributos permitem.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Comparando com a Aula 2\n\n::: {.fragment}\nAula 2 (mesmos 6 bairros, $\\mathbf{w}$ **inventado**): erros grandes,\nsem padrão. Agora, com $\\hat{\\mathbf{w}}$ **ajustado**: ainda há erro\n(esperado, $R^2\\approx 0{,}518$), mas a tendência geral já aparece.\n:::\n\n::: {.fragment}\nDiferença entre \"um $\\mathbf{w}$ qualquer\" e \"o $\\hat{\\mathbf{w}}$ das\nEquações Normais\": o segundo não é perfeito, mas é **matematicamente o\nmelhor possível** dentro do que os 4 atributos permitem.\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n::: {.callout-tip}\n## Se comparássemos $\\hat{\\mathbf{w}}$ com uma resolução por eliminação de Gauss do sistema $X^TX\\hat{\\mathbf{w}}=X^T\\mathbf{y}$, esperaríamos o mesmo resultado da comparação com `lstsq`?\n\nDica: o que muda entre `lstsq` e eliminação de Gauss é o **algoritmo**,\nnão a **equação** que ambos resolvem. Isso muda a resposta?\n\n- □ Comparar $\\hat{\\mathbf{w}}$ (Equações Normais) com uma resolução por\n  eliminação de Gauss do mesmo sistema $X^TX\\hat{\\mathbf{w}}=X^T\\mathbf{y}$\n  daria, a menos de erro de arredondamento, exatamente o mesmo vetor\n  encontrado com `lstsq`.\n- □ Se o produto interno do resíduo com cada coluna de $X$ fosse\n  exatamente zero (não apenas próximo de zero, mas matematicamente\n  exato), isso seria uma coincidência numérica desta amostra específica,\n  não uma consequência necessária da teoria.\n- □ Num ajuste de crescimento populacional, com atributos em escalas\n  bem diferentes das usadas nesta aula, a mesma verificação (produto\n  interno do resíduo com cada coluna $\\approx 0$) continuaria sendo um\n  teste válido de que $\\hat{\\mathbf{w}}$ foi calculado corretamente.\n- □ Como o resíduo é ortogonal a cada coluna de $X$, isso implica que o\n  modelo ajustado explica quase toda a variação de $\\mathbf{y}$ (um\n  $R^2$ próximo de $1$).\n:::\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Pergunta\n\n::: {.callout-tip}\n## Eliminação de Gauss em $X^TX\\hat{\\mathbf{w}}=X^T\\mathbf{y}$ daria o mesmo resultado que `lstsq`?\n\nDica: o que muda entre `lstsq` e eliminação de Gauss é o algoritmo, não\na equação resolvida.\n\n- □ Eliminação de Gauss no mesmo sistema $X^TX\\hat{\\mathbf{w}}=X^T\\mathbf{y}$\n  daria, a menos de arredondamento, o mesmo vetor de `lstsq`.\n- □ Produto interno do resíduo com cada coluna exatamente zero seria\n  coincidência numérica desta amostra, não consequência da teoria.\n- □ Em outro domínio, com outras escalas, a mesma verificação de\n  ortogonalidade continuaria válida como teste de correção.\n- □ Resíduo ortogonal a cada coluna $\\Rightarrow$ $R^2$ próximo de $1$.\n:::\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Resposta\n\n::: {.callout-tip}\n## Comparando algoritmos e o que a ortogonalidade garante — Resposta\n\n- ✔ Mesma equação, algoritmos diferentes (inversão, eliminação,\n  decomposição) — todos resolvem o mesmo sistema linear, mesmo\n  resultado a menos de arredondamento.\n- ✗ É consequência **necessária** de $X^T(\\mathbf{y}-X\\hat{\\mathbf{w}})=\\mathbf{0}$\n  (Passo i), não coincidência — vale para qualquer amostra em que\n  $\\hat{\\mathbf{w}}$ resolva as Equações Normais.\n- ✔ A verificação é uma identidade algébrica geral (Passo i),\n  independente de domínio ou escala dos atributos.\n- ✗ Vimos $R^2\\approx 0{,}518$ com resíduo ortogonal — ortogonalidade\n  fixa a *direção* do erro, não seu *tamanho*; um ajuste ruim pode ter\n  resíduo perfeitamente ortogonal.\n:::\n\n::: {.fragment}\n**Voltando à pergunta:** sim — qualquer método correto que resolva\n$X^TX\\hat{\\mathbf{w}}=X^T\\mathbf{y}$ chega ao mesmo $\\hat{\\mathbf{w}}$; a\ndiferença entre métodos é robustez numérica, não o resultado matemático\nem si (tema que volta na Aula 4).\n:::\n:::\n\n# Quando a Fórmula Falha, ou Fica Frágil\n\n---\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## Reconectando com a Aula 2: Posto Completo\n\nO Passo (ii) do Bloco 4 usou uma hipótese específica: $X^TX$ é\ninvertível **se, e somente se**, as colunas de $X$ são linearmente\nindependentes — ou seja, $X$ tem posto completo, $\\text{rk}(X)=d$\n(critério provado na Aula 2, Bloco 5). Essa não é uma hipótese técnica\nqualquer: é a única coisa que separa \"$\\hat{\\mathbf{w}}$ tem fórmula\nfechada\" de \"$\\hat{\\mathbf{w}}$ não é sequer único\". Vamos ver os dois\njeitos como essa hipótese pode falhar — um exato, um só numericamente\nfrágil — reaproveitando exatamente os exemplos da Aula 2.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Reconectando com a Aula 2: Posto Completo\n\n::: {.fragment}\nPasso (ii): $X^TX$ invertível $\\iff$ colunas de $X$ linearmente\nindependentes $\\iff$ $\\text{rk}(X)=d$ (Aula 2, Bloco 5).\n:::\n\n::: {.fragment}\nNão é hipótese técnica qualquer: é o que separa \"$\\hat{\\mathbf{w}}$ tem\nfórmula fechada\" de \"$\\hat{\\mathbf{w}}$ não é nem único\". Dois jeitos de\nfalhar — um exato, um só frágil — reaproveitando os exemplos da Aula 2.\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n## Caso 1: Multicolinearidade Exata — $\\hat{\\mathbf{y}}$ Único, $\\hat{\\mathbf{w}}$ Não\n\nA Aula 2 fabricou uma quinta coluna, $2\\times$`AveRooms`, e mostrou que o\nposto da matriz de design **não sobe** de 4 para 5 — a nova coluna não\ntraz direção independente. Repetindo o experimento, agora olhando\ndiretamente para a invertibilidade de $X^TX$:\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Caso 1: Multicolinearidade Exata\n\n::: {.fragment}\nAula 2: quinta coluna $2\\times$`AveRooms` — posto **não sobe** de 4 para\n5. Repetindo, olhando para $X^TX$:\n:::\n:::\n\n::: {#f9141453 .cell execution_count=9}\n``` {.python .cell-code}\nX_com_duplicata = np.column_stack([X_completo, 2.0 * X_completo[:, 2]])\nprint(\"posto de X:              \", np.linalg.matrix_rank(X_completo))\nprint(\"posto de X com duplicata:\", np.linalg.matrix_rank(X_com_duplicata))\n\nXtX_dup = X_com_duplicata.T @ X_com_duplicata\nprint(\"det(X^T X com duplicata):\", np.linalg.det(XtX_dup))\ntry:\n    np.linalg.inv(XtX_dup)\nexcept np.linalg.LinAlgError as erro:\n    print(\"np.linalg.inv falha:\", erro)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nposto de X:               4\nposto de X com duplicata: 4\ndet(X^T X com duplicata): 0.0\nnp.linalg.inv falha: Singular matrix\n```\n:::\n:::\n\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n$\\det(X^TX)=0$: a matriz é singular, e `np.linalg.inv` recusa\nexplicitamente (\"Singular matrix\") — não há fórmula fechada\n$\\hat{\\mathbf{w}}=(X^TX)^{-1}X^T\\mathbf{y}$ possível. Mas note a\ndistinção crucial, já anunciada no Passo (i) do Bloco 4: a *projeção*\n$\\hat{\\mathbf{y}}$ continua perfeitamente bem definida — é o ponto de\n$\\text{col}(X)$ mais próximo de $\\mathbf{y}$, e $\\text{col}(X)$ não\nmudou (a coluna redundante não acrescenta nenhuma direção nova, Aula 2).\nO que deixou de ser único é **como distribuir o crédito** entre\n`AveRooms` e sua cópia $2\\times$`AveRooms` — infinitos $\\hat{\\mathbf{w}}$\ndiferentes produzem exatamente o mesmo $\\hat{\\mathbf{y}}=X\\hat{\\mathbf{w}}$.\nA sombra é única; a \"receita\" para chegar nela, não.\n\n## Caso 2: Quase-Multicolinearidade — $X^TX$ Mal-Condicionada\n\nMulticolinearidade **exata** é rara em dados reais. O problema mais\ncomum, já visto na Aula 2, é a quase-dependência entre `AveRooms` e\n`AveBedrms` (correlação $0{,}865$) — posto continua completo ($4$), a\nfórmula fechada ainda existe, mas fica **numericamente frágil**.\nReaproveitando exatamente a amostra de 20 bairros e a perturbação de 1%\nda Aula 2, agora olhando para o número de condição de $X^TX$ em cada\npar:\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Distinção Crucial\n\n::: {.fragment}\n$\\det(X^TX)=0$: `np.linalg.inv` recusa (\"Singular matrix\") — sem fórmula\nfechada para $\\hat{\\mathbf{w}}$.\n:::\n\n::: {.fragment}\n**Mas:** a *projeção* $\\hat{\\mathbf{y}}$ continua bem definida —\n$\\text{col}(X)$ não mudou (coluna redundante não traz direção nova). O\nque se perde é **como distribuir o crédito** entre `AveRooms` e sua\ncópia: infinitos $\\hat{\\mathbf{w}}$ dão o mesmo $\\hat{\\mathbf{y}}$.\n:::\n\n::: {.fragment}\nA sombra é única; a \"receita\" para chegar nela, não.\n:::\n\n## Caso 2: Quase-Multicolinearidade\n\n::: {.fragment}\nMulticolinearidade exata é rara em dados reais. Mais comum (Aula 2):\n`AveRooms`/`AveBedrms`, correlação $0{,}865$ — posto completo, fórmula\nexiste, mas **numericamente frágil**.\n:::\n\n::: {.fragment}\nReaproveitando a amostra de 20 bairros e a perturbação de 1% da Aula 2,\nagora olhando o número de condição de $X^TX$:\n:::\n:::\n\n::: {#12dad81d .cell execution_count=10}\n``` {.python .cell-code}\n_amostra_20 = _housing.sample(n=20, random_state=7)\nX_quase_dep = _amostra_20[[\"AveRooms\", \"AveBedrms\"]].to_numpy()\nX_bem_cond = _amostra_20[[\"MedInc\", \"HouseAge\"]].to_numpy()\n\ncond_quase_dep = np.linalg.cond(X_quase_dep.T @ X_quase_dep)\ncond_bem_cond = np.linalg.cond(X_bem_cond.T @ X_bem_cond)\n\nprint(f\"número de condição de X^TX (AveRooms, AveBedrms):  {cond_quase_dep:,.1f}\")\nprint(f\"número de condição de X^TX (MedInc, HouseAge):     {cond_bem_cond:,.1f}\")\nprint(f\"\\nnúmero de condição de X^TX completo (4 atributos): {np.linalg.cond(XtX):,.1f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nnúmero de condição de X^TX (AveRooms, AveBedrms):  419.8\nnúmero de condição de X^TX (MedInc, HouseAge):     169.1\n\nnúmero de condição de X^TX completo (4 atributos): 23,460.5\n```\n:::\n:::\n\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\nO par quase-dependente tem número de condição $\\approx 420$ contra\n$\\approx 169$ do par bem-condicionado — mais de o dobro, um sinal\nnumérico direto de fragilidade (definição formal na Aula 4). E lembrando\no resultado já demonstrado na Aula 2, reproduzido aqui como consequência\ndireta desse número de condição alto: perturbar `MedHouseVal` em apenas\n$1\\%$ do seu desvio-padrão muda o peso de `AveBedrms` em $\\approx 29{,}5\\%$\nno par quase-dependente, contra $\\approx 0{,}1\\%$ no par bem-condicionado\nsob a mesma perturbação — quase 300 vezes mais sensível. O número de\ncondição do $X^TX$ com os 4 atributos completos ($\\approx 23\\,460$) é\nainda maior, porque combina a informação redundante de `AveRooms`/\n`AveBedrms` com a escala natural de todos os atributos — mas o efeito é\no mesmo em espécie: $X^TX$ tecnicamente invertível, porém perto o\nsuficiente de singular para que pequenos erros nos dados produzam\ngrandes oscilações no $\\hat{\\mathbf{w}}$ calculado.\n\n**A mesma distinção do Caso 1, com um grau de intensidade menor:** a\nprojeção $\\hat{\\mathbf{y}}$ (a previsão do modelo) muda pouco com a\nperturbação — é a *decomposição* dos pesos $\\hat{\\mathbf{w}}$ entre as\nduas colunas quase-redundantes que oscila. Medir e nomear essa\nsensibilidade com precisão — o número de condição, calculado a partir\ndos autovalores de $X^TX$, não só estimado por um experimento de\nperturbação — é exatamente o que abre a Aula 4.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## O Que os Números Confirmam\n\n::: {.fragment}\nNúmero de condição: $\\approx 420$ (quase-dependente) vs. $\\approx 169$\n(bem-condicionado) — mais que o dobro. Sinal numérico de fragilidade.\n:::\n\n::: {.fragment}\nPerturbação de 1% em `MedHouseVal`: peso de `AveBedrms` muda\n$\\approx 29{,}5\\%$ no par quase-dependente, contra $\\approx 0{,}1\\%$ no\nbem-condicionado — quase 300× mais sensível (Aula 2, reproduzido aqui\ncomo consequência do número de condição).\n:::\n\n::: {.fragment}\n$X^TX$ completo (4 atributos): número de condição $\\approx 23\\,460$ —\nainda maior, combinando a redundância `AveRooms`/`AveBedrms` com a\nescala de todos os atributos.\n:::\n\n## A Mesma Distinção do Caso 1, Mais Sutil\n\n::: {.fragment}\nA projeção $\\hat{\\mathbf{y}}$ (previsão) muda pouco com a perturbação —\né a **decomposição** de $\\hat{\\mathbf{w}}$ entre colunas\nquase-redundantes que oscila.\n:::\n\n::: {.fragment}\nMedir essa sensibilidade com precisão — o **número de condição**,\nvia autovalores de $X^TX$ — é o que abre a Aula 4.\n:::\n:::\n\n::: {.fig-resize style=\"width: 78%; margin: 0 auto;\"}\n```{.tikz}\n\\usetikzlibrary{shapes.geometric, arrows.meta, positioning}\n\\definecolor{icblue}{HTML}{0085CA}\n\\definecolor{icorange}{HTML}{FF5E00}\n\\definecolor{icred}{HTML}{E03C31}\n\\begin{tikzpicture}[\n  node distance=0.6cm and 0.8cm,\n  block/.style={rectangle, draw=icblue, fill=icblue!8, rounded corners=3pt,\n                align=center, font=\\small, inner sep=6pt,\n                text width=3.1cm, minimum height=1.0cm},\n  concl/.style={rectangle, draw=icred, fill=icred!8, rounded corners=3pt,\n                align=center, font=\\small, inner sep=6pt,\n                text width=3.4cm, minimum height=1.3cm},\n  arrow/.style={-Stealth, thick, color=gray!70}\n]\n  \\node (M) [block] {multicolinearidade\\\\entre colunas de $X$};\n  \\node (E) [block, above right=0.4cm and 1.3cm of M] {\\textbf{exata}\\\\(ex.: $2\\times$AveRooms)};\n  \\node (Q) [block, below right=0.4cm and 1.3cm of M] {\\textbf{quase-exata}\\\\(ex.: AveRooms/AveBedrms, $r=0{,}865$)};\n  \\node (CE) [concl, right=1.1cm of E] {$X^TX$ singular\\\\$\\hat{\\mathbf{w}}$ não-único\\\\$\\hat{\\mathbf{y}}$ ainda único};\n  \\node (CQ) [concl, right=1.1cm of Q] {$X^TX$ mal-condicionada\\\\$\\hat{\\mathbf{w}}$ instável\\\\número de condição (Aula 4)};\n\n  \\draw [arrow] (M) -- (E);\n  \\draw [arrow] (M) -- (Q);\n  \\draw [arrow] (E) -- (CE);\n  \\draw [arrow] (Q) -- (CQ);\n\\end{tikzpicture}\n```\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\nO diagrama resume os dois caminhos: multicolinearidade exata quebra a\ninvertibilidade de $X^TX$ (posto deficiente), enquanto multicolinearidade\nquase-exata preserva o posto completo mas deixa $X^TX$ mal-condicionada\n— dois sintomas de gravidade diferente, mas da mesma causa raiz\n(colunas de $X$ carregando informação redundante), com o mesmo alívio\nparcial em comum: a projeção $\\hat{\\mathbf{y}}$ nunca é o problema; o\nproblema mora inteiramente em como $\\hat{\\mathbf{w}}$ tenta descrevê-la.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n::: {.fragment}\nMesma causa raiz (colunas redundantes), gravidade diferente. Em ambos:\na projeção $\\hat{\\mathbf{y}}$ nunca é o problema — o problema mora em\ncomo $\\hat{\\mathbf{w}}$ tenta descrevê-la.\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n::: {.callout-tip}\n## Se $X^TX$ está mal-condicionada, a previsão $\\hat{\\mathbf{y}}=X\\hat{\\mathbf{w}}$ também fica proporcionalmente instável sob a mesma perturbação dos dados?\n\nDica: releia o que os números do Caso 2 mostraram sobre $\\hat{\\mathbf{w}}$\nvs. $\\hat{\\mathbf{y}}$ — a instabilidade tem o mesmo tamanho nos dois?\n\n- □ Se a coluna duplicada fabricada no Caso 1 fosse uma combinação de\n  duas colunas originais (não um múltiplo de uma única coluna), em vez\n  de exatamente $2\\times$`AveRooms`, o posto de $X$ ainda cairia da\n  mesma forma ao ser adicionada.\n- □ No caso-limite em que a correlação entre `AveRooms` e `AveBedrms`\n  fosse exatamente $1$ (em vez de $0{,}865$), $X^TX$ deixaria de ser\n  invertível, e a fórmula fechada\n  $\\hat{\\mathbf{w}}=(X^TX)^{-1}X^T\\mathbf{y}$ deixaria de estar\n  definida.\n- □ Num modelo de crédito com dois atributos quase redundantes (ex.:\n  \"renda mensal\" e \"renda anual dividida por 12\", com pequena diferença\n  por arredondamento), o mesmo sintoma de instabilidade numérica no peso\n  estimado apareceria, mesmo sem nenhuma coluna exatamente duplicada.\n- □ Como $X^TX$ mal-condicionada torna $\\hat{\\mathbf{w}}$ instável, isso\n  implica que a previsão $\\hat{\\mathbf{y}}=X\\hat{\\mathbf{w}}$ também se\n  torna proporcionalmente instável sob a mesma perturbação dos dados.\n:::\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Pergunta\n\n::: {.callout-tip}\n## $X^TX$ mal-condicionada torna $\\hat{\\mathbf{y}}$ proporcionalmente instável também?\n\nDica: os números do Caso 2 mostraram a instabilidade em $\\hat{\\mathbf{w}}$\nvs. em $\\hat{\\mathbf{y}}$ — mesmo tamanho?\n\n- □ Coluna duplicada como combinação de duas colunas originais (não um\n  múltiplo de uma só): posto de $X$ ainda cairia igual.\n- □ Correlação AveRooms/AveBedrms exatamente $1$: $X^TX$ deixaria de\n  ser invertível, fórmula fechada indefinida.\n- □ Crédito com \"renda mensal\"/\"renda anual÷12\" (quase redundantes por\n  arredondamento): mesmo sintoma de instabilidade, sem duplicata exata.\n- □ $X^TX$ mal-condicionada $\\Rightarrow$ $\\hat{\\mathbf{y}}$ também\n  proporcionalmente instável.\n:::\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Resposta\n\n::: {.callout-tip}\n## Mal-condicionamento e o que permanece estável — Resposta\n\n- ✔ Qualquer coluna que seja combinação linear exata das demais não\n  acrescenta direção nova ao espaço gerado — o posto cai da mesma\n  forma, com múltiplo único ou combinação.\n- ✔ Correlação $1$ = dependência linear exata $\\Rightarrow$ $X^TX$\n  singular, mesma consequência do Caso 1.\n- ✔ Mesma mecânica de quase-dependência, outro domínio (crédito em vez\n  de imóveis).\n- ✗ É o oposto do que os números mostraram: a *projeção*\n  $\\hat{\\mathbf{y}}$ (o ponto mais próximo de $\\mathbf{y}$ em\n  $\\text{col}(X)$) é geometricamente determinada e muda pouco; é a\n  **decomposição** em $\\hat{\\mathbf{w}}$ entre colunas quase-redundantes\n  que oscila descontroladamente.\n:::\n\n::: {.fragment}\n**Voltando à pergunta:** não — é exatamente o padrão \"sombra estável,\nreceita instável\" do Caso 1, só que aqui sem quebra total de posto,\napenas fragilidade numérica.\n:::\n:::\n\n# Fechamento e Ponte para a Aula 4\n\n---\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n### Retomando as perguntas de abertura {.unnumbered}\n\n1. **O que significa \"a melhor aproximação possível\"?** O ponto\n   $\\hat{\\mathbf{y}}\\in\\text{col}(X)$ que minimiza\n   $\\|\\mathbf{y}-\\hat{\\mathbf{y}}\\|$ — e essa minimização é equivalente\n   a uma condição geométrica exata: o resíduo ortogonal a todo o\n   subespaço.\n2. **O que é projetar sobre um subespaço, e por que resolve o\n   problema?** É encontrar exatamente esse $\\hat{\\mathbf{y}}$ — a\n   \"sombra\" perpendicular do Bloco 2, formalizada no Teorema da\n   Projeção do Bloco 4.\n3. **Como isso vira uma fórmula calculável?** As **Equações Normais**,\n   $X^TX\\hat{\\mathbf{w}}=X^T\\mathbf{y}$, e sob posto completo,\n   $\\hat{\\mathbf{w}}=(X^TX)^{-1}X^T\\mathbf{y}$ — verificado com números\n   reais no Bloco 5 (comparação com `lstsq`, ortogonalidade do resíduo).\n4. **Quando essa fórmula falha, ou fica frágil?** Multicolinearidade\n   exata quebra a invertibilidade de $X^TX$ ($\\hat{\\mathbf{w}}$\n   não-único, $\\hat{\\mathbf{y}}$ ainda único); quase-multicolinearidade\n   preserva o posto completo, mas deixa $X^TX$ mal-condicionada\n   ($\\hat{\\mathbf{w}}$ instável).\n\n### O Que Fica em Aberto {.unnumbered}\n\nA fórmula fechada $\\hat{\\mathbf{w}}=(X^TX)^{-1}X^T\\mathbf{y}$ é a forma\nmais simples de **descrever** a solução — mas não é a forma mais\n**estável** de calculá-la quando $X^TX$ está mal-condicionada, como o\nBloco 6 acabou de mostrar. O número de condição foi usado aqui de forma\nempírica (perturbar os dados e medir o efeito) — a Aula 4 dá a ferramenta\nexata para medi-lo diretamente a partir da estrutura de $X^TX$ (seus\n**autovalores** e **autovetores**), sem precisar perturbar nada. Essa\nmesma ferramenta é o que vai motivar, mais adiante no curso, métodos\nnuméricos mais estáveis do que inverter $X^TX$ diretamente — decomposição\n$QR$ e $SVD$ — que resolvem as Equações Normais sem nunca formar\n$X^TX$ explicitamente.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n## Retomando as Perguntas de Abertura\n\n::: {.fragment}\n**1.** \"Melhor aproximação\" = $\\hat{\\mathbf{y}}\\in\\text{col}(X)$ que\nminimiza $\\|\\mathbf{y}-\\hat{\\mathbf{y}}\\|$ — equivalente a resíduo\nortogonal ao subespaço.\n:::\n\n::: {.fragment}\n**2.** Projetar = encontrar esse $\\hat{\\mathbf{y}}$ — a sombra\nperpendicular, formalizada no Teorema da Projeção.\n:::\n\n::: {.fragment}\n**3.** Fórmula: Equações Normais $X^TX\\hat{\\mathbf{w}}=X^T\\mathbf{y}$;\nsob posto completo, $\\hat{\\mathbf{w}}=(X^TX)^{-1}X^T\\mathbf{y}$ —\nverificado com dados reais.\n:::\n\n::: {.fragment}\n**4.** Falha: multicolinearidade exata quebra invertibilidade\n($\\hat{\\mathbf{w}}$ não-único); quase-exata deixa $X^TX$\nmal-condicionada ($\\hat{\\mathbf{w}}$ instável).\n:::\n\n## Ponte para a Aula 4\n\n::: {.fragment}\nFórmula fechada = mais simples de **descrever**, não mais **estável** de\n**calcular** quando $X^TX$ é mal-condicionada.\n:::\n\n::: {.fragment}\nAqui, número de condição foi medido empiricamente (perturbar e ver o\nefeito). Aula 4: ferramenta exata via **autovalores/autovetores** de\n$X^TX$ — sem precisar perturbar nada.\n:::\n\n::: {.fragment}\nMotiva, mais adiante, métodos mais estáveis que inverter $X^TX$\ndiretamente: decomposição $QR$ e $SVD$.\n:::\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n# Exercícios\n\n## Questões discursivas\n\n1. Explique, com suas próprias palavras e usando a linguagem geométrica\n   do Bloco 2 (a \"sombra\"), por que minimizar $\\|\\mathbf{y}-X\\mathbf{w}\\|$\n   é equivalente à condição de ortogonalidade\n   $(\\mathbf{y}-X\\hat{\\mathbf{w}})\\perp\\text{col}(X)$. Por que essa\n   equivalência é o que permite transformar um problema de otimização\n   (minimizar uma distância) numa equação linear (as Equações Normais)?\n\n2. Compare os dois casos do Bloco 6 — multicolinearidade exata (posto\n   deficiente) e quase-multicolinearidade (posto completo, mas\n   mal-condicionada) — explicando, para cada um, o que acontece com a\n   projeção $\\hat{\\mathbf{y}}$ e o que acontece com o vetor de pesos\n   $\\hat{\\mathbf{w}}$. Por que a distinção entre essas duas grandezas é\n   a chave para entender os dois casos?\n\n3. A Aula 2 provou que $X^TX$ é invertível se, e somente se, $X$ tem\n   posto completo. Explique como essa condição de invertibilidade entra\n   exatamente no Passo (ii) da derivação das Equações Normais desta\n   aula, e o que aconteceria à derivação (não só ao resultado final) se\n   essa condição não fosse satisfeita.\n\n## Questões de Verdadeiro/Falso\n\nCada bloco de 4 itens trata do mesmo tema. A questão só é considerada\ncorreta se todos os 4 itens forem julgados corretamente (deixar em\nbranco tem penalidade de 20% da nota da questão).\n\n::: {.callout-note icon=false}\n## Sistemas sobredeterminados e a melhor aproximação\n\n- □ Se um sistema $A\\mathbf{x}=\\mathbf{b}$ fosse subdeterminado ($n>m$)\n  em vez de sobredeterminado, ainda haveria um sentido útil para\n  \"melhor aproximação\" via projeção, mas ele coincidiria trivialmente\n  com uma das infinitas soluções exatas, não com um ponto fora do\n  espaço-coluna de $A$.\n- □ No caso-limite em que $\\mathbf{y}$ está exatamente sobre o\n  espaço-coluna de $X$, a \"melhor aproximação\"\n  $\\hat{\\mathbf{y}}=X\\hat{\\mathbf{w}}$ coincide com $\\mathbf{y}$, e o\n  problema de mínimos quadrados se reduz ao caso já resolvido pela\n  Aula 2 (sistema com solução exata).\n- □ Num problema de previsão de demanda de energia elétrica, com muito\n  mais medições horárias (equações) do que parâmetros do modelo físico\n  a estimar (incógnitas), a mesma lógica de \"sistema sobredeterminado\n  sem solução exata, resolvido por projeção\" se aplicaria.\n- □ Como um sistema sobredeterminado não tem solução exata, isso\n  implica que qualquer $\\mathbf{w}$ escolhido produzirá um erro de\n  magnitude semelhante — a escolha de $\\mathbf{w}$ não afetaria\n  significativamente a qualidade da aproximação.\n:::\n\n::: {.callout-note icon=false}\n## A intuição da sombra\n\n- □ Se a fonte de luz da analogia da sombra viesse de um ângulo\n  oblíquo fixo (não perpendicular ao subespaço), o ponto de chegada no\n  subespaço, em geral, não seria mais o ponto mais próximo do ponto\n  original.\n- □ No caso-limite em que o subespaço $U$ tem a mesma dimensão do\n  espaço ambiente ($U=V$), a \"sombra\" de qualquer ponto sobre $U$\n  coincide com o próprio ponto, para qualquer ponto escolhido.\n- □ A ideia de reduzir a dimensionalidade de dados de alta dimensão\n  para visualização (ex.: reduzir atributos de um dataset para 2\n  dimensões e plotar um gráfico de dispersão) usa, na essência, a mesma\n  operação geométrica de projeção perpendicular discutida nesta aula.\n- □ Como a projeção perpendicular minimiza a distância ao subespaço,\n  ela produz sempre o ponto de menor norma dentro do subespaço, entre\n  todos os candidatos.\n:::\n\n::: {.callout-note icon=false}\n## Subespaços e o complemento ortogonal\n\n- □ Se $U$ e $W$ são dois subespaços distintos de mesma dimensão $M$\n  dentro de um espaço $V$ de dimensão $D$, seus complementos ortogonais\n  $U^\\perp$ e $W^\\perp$ têm, necessariamente, a mesma dimensão entre si\n  ($D-M$), ainda que $U^\\perp \\ne W^\\perp$ como conjuntos.\n- □ No caso-limite $M=D$ (o subespaço é o espaço inteiro), o\n  complemento ortogonal se reduz ao subespaço trivial $\\{\\mathbf{0}\\}$.\n- □ Em processamento de sinais, decompor um sinal de áudio em uma\n  componente dentro de uma banda de frequência específica (um\n  subespaço) e uma componente fora dela usa a mesma lógica de\n  decomposição única $V=U\\oplus U^\\perp$ discutida nesta aula.\n- □ Como todo vetor de $V$ se decompõe de forma única em $U\\oplus\n  U^\\perp$, isso implica que essa decomposição é a única forma possível\n  de escrever qualquer vetor de $V$ como soma de dois vetores de $V$.\n:::\n\n::: {.callout-note icon=false}\n## Definição formal de projeção\n\n- □ Se $\\pi:V\\to U$ satisfaz $\\pi^2=\\pi$, então, para qualquer vetor\n  $\\mathbf{u}$ que já pertença a $U$, necessariamente $\\pi(\\mathbf{u}) =\n  \\mathbf{u}$.\n- □ No caso-limite em que a matriz de projeção $P_\\pi$ é a matriz\n  identidade, o subespaço $U$ sobre o qual ela projeta é o espaço\n  ambiente $V$ inteiro.\n- □ Num sistema de compressão de vídeo que descarta certas componentes\n  de frequência (mantendo só um subconjunto), a operação de manter as\n  componentes retidas e descartar as demais pode ser descrita, de\n  forma exata, por uma matriz de projeção $P_\\pi$ com $P_\\pi^2=P_\\pi$.\n- □ Como toda matriz de projeção satisfaz $P_\\pi^2=P_\\pi$, isso\n  significa que qualquer matriz quadrada que satisfaça essa condição\n  algébrica também é, necessariamente, simétrica.\n:::\n\n::: {.callout-note icon=false}\n## Derivação das Equações Normais\n\n- □ Se a condição de ortogonalidade fosse verificada apenas para\n  algumas colunas de $X$ (não todas), em vez de todas as $d$ colunas,\n  isso não seria suficiente, em geral, para garantir que o resíduo é\n  ortogonal a todo o espaço-coluna de $X$.\n- □ No caso-limite $d=1$ (uma única coluna, isto é, $X$ é um vetor-coluna\n  $\\mathbf{x}\\in\\mathbb{R}^N$), as Equações Normais\n  $X^TX\\hat{\\mathbf{w}}=X^T\\mathbf{y}$ se reduzem a uma única equação\n  escalar, $\\hat{w}=\\dfrac{\\mathbf{x}^T\\mathbf{y}}{\\mathbf{x}^T\\mathbf{x}}$.\n- □ Num problema de estimar um único parâmetro físico (temperatura\n  média) a partir de $N$ leituras redundantes de um termômetro (cada\n  leitura sendo $y_i = \\theta + \\text{ruído}$), a mesma derivação das\n  Equações Normais levaria a uma estimativa que é, essencialmente, a\n  média das leituras.\n- □ Como as Equações Normais são obtidas impondo ortogonalidade\n  coluna a coluna, isso implica que, se duas colunas de $X$ forem\n  ortogonais entre si, a equação normal correspondente a cada uma delas\n  pode ser resolvida de forma totalmente independente da outra, sem\n  nenhum termo cruzado.\n:::\n\n::: {.callout-note icon=false}\n## Invertibilidade de $X^TX$ e a pseudo-inversa\n\n- □ Se $X$ tivesse posto deficiente (colunas linearmente dependentes),\n  $X^TX$ deixaria de ser invertível, mas isso não impediria, por si só,\n  que existisse **algum** $\\hat{\\mathbf{w}}$ satisfazendo as Equações\n  Normais — apenas deixaria de haver um único.\n- □ No caso-limite em que $X$ tem uma única coluna não-nula\n  ($d=1$, $\\mathbf{x}\\ne\\mathbf{0}$), $X^TX$ é sempre invertível\n  (é um escalar positivo).\n- □ Num problema de reconstrução de sinais com uma matriz de\n  observação $X$ de posto deficiente, a pseudo-inversa\n  $(X^TX)^{-1}X^T$ não pode ser calculada da forma usual, mas existem\n  generalizações (pseudo-inversa de Moore-Penrose, via SVD) que\n  contornam exatamente esse problema.\n- □ Como $(X^TX)^{-1}X^T$ é chamada de pseudo-inversa de $X$, isso\n  significa que ela satisfaz $X\\cdot(X^TX)^{-1}X^T = I$ (a identidade),\n  do mesmo jeito que uma inversa de matriz quadrada de verdade.\n:::\n\n::: {.callout-note icon=false}\n## Aplicação numérica e verificação de ortogonalidade\n\n- □ Se, em vez de comparar $\\hat{\\mathbf{w}}$ obtido pela fórmula\n  fechada com `np.linalg.lstsq`, comparássemos com uma resolução por\n  eliminação de Gauss do sistema $X^TX\\hat{\\mathbf{w}}=X^T\\mathbf{y}$,\n  esperaríamos, a menos de erro de arredondamento, o mesmo vetor.\n- □ No caso-limite em que $\\mathbf{y}$ é o vetor nulo, o\n  $\\hat{\\mathbf{w}}$ que resolve as Equações Normais (com $X$ de posto\n  completo) é necessariamente o vetor nulo também.\n- □ Num experimento de física em que um pesquisador mede a mesma\n  grandeza $N$ vezes com ruído aleatório, verificar que o resíduo entre\n  o valor estimado e as medições é ortogonal aos \"atributos\" do modelo\n  é um teste válido de correção, do mesmo jeito que foi usado nesta\n  aula para o California Housing.\n- □ Como o resíduo é ortogonal a cada coluna de $X$, isso implica que\n  o modelo captura toda a informação relevante contida nos dados\n  disponíveis para prever $\\mathbf{y}$.\n:::\n\n::: {.callout-note icon=false}\n## $R^2$ e o que a ortogonalidade do resíduo garante\n\n- □ Se o $R^2$ do ajuste fosse exatamente $0$ (o modelo não explica\n  nada da variação de $\\mathbf{y}$ além da média), o resíduo ainda\n  seria ortogonal a cada coluna de $X$, contanto que $\\hat{\\mathbf{w}}$\n  resolva as Equações Normais.\n- □ No caso-limite $R^2=1$ (ajuste perfeito), o resíduo\n  $\\mathbf{y}-X\\hat{\\mathbf{w}}$ é o vetor nulo.\n- □ Num modelo de previsão de nota de estudantes usando só o número de\n  horas de sono (um único atributo, claramente insuficiente para\n  prever notas), seria possível obter um $R^2$ baixo e, ainda assim, um\n  resíduo perfeitamente ortogonal a essa única coluna — exatamente como\n  ocorreu com os 4 atributos do California Housing nesta aula.\n- □ Como o resíduo é sempre ortogonal ao espaço-coluna de $X$ quando\n  $\\hat{\\mathbf{w}}$ resolve as Equações Normais, um $R^2$ baixo indica\n  necessariamente um erro no cálculo de $\\hat{\\mathbf{w}}$, não uma\n  limitação dos atributos escolhidos.\n:::\n\n::: {.callout-note icon=false}\n## Posto e multicolinearidade exata (conexão com a Aula 2)\n\n- □ Se a coluna redundante fabricada no Bloco 6 fosse\n  $-5\\times$`AveRooms` em vez de $2\\times$`AveRooms`, o posto de $X$\n  ainda cairia da mesma forma ao ser adicionada (permaneceria em 4, não\n  subiria para 5).\n- □ No caso-limite em que todas as $d$ colunas de $X$ fossem\n  múltiplos escalares de uma única coluna não-nula, o posto de $X$\n  seria exatamente $1$, independentemente do valor de $d$.\n- □ Num dataset de sensores IoT em que um atributo é reportado tanto em\n  Celsius quanto em Fahrenheit (uma transformação linear afim exata da\n  outra, não apenas um múltiplo escalar), a inclusão de ambas as\n  colunas na matriz de design também produziria posto deficiente, pelo\n  mesmo princípio da coluna duplicada exata desta aula.\n- □ Como a coluna redundante fabricada não acrescenta nenhuma direção\n  independente ao espaço-coluna de $X$, isso implica que removê-la\n  necessariamente reduz a qualidade das previsões do modelo ajustado.\n:::\n\n::: {.callout-note icon=false}\n## Quase-multicolinearidade e número de condição (preview da Aula 4)\n\n- □ Se, em vez de perturbar `MedHouseVal` em 1% do desvio-padrão,\n  perturbássemos em 10 vezes esse valor (10% do desvio-padrão), a\n  variação relativa esperada no peso de `AveBedrms` no par\n  quase-dependente seria, ao menos aproximadamente, também maior do\n  que a observada com a perturbação de 1% — o número de condição alto\n  amplifica perturbações maiores tanto quanto amplifica as pequenas.\n- □ No caso-limite em que o número de condição de $X^TX$ tende a\n  infinito, $X^TX$ se torna, no limite, singular (não invertível).\n- □ Num modelo de precificação de opções financeiras com duas\n  variáveis de entrada quase redundantes (ex.: duas medidas de\n  volatilidade calculadas por métodos ligeiramente diferentes), a mesma\n  fragilidade numérica (pesos instáveis sob pequena perturbação dos\n  dados) apareceria, mesmo com o posto de $X$ tecnicamente completo.\n- □ Como o número de condição de $X^TX$ com os 4 atributos completos\n  ($\\approx 23\\,460$) é maior do que o do par isolado\n  `AveRooms`/`AveBedrms` ($\\approx 420$), isso implica que a previsão\n  $\\hat{\\mathbf{y}}$ do modelo completo é proporcionalmente mais\n  instável do que a previsão do modelo com só esse par de atributos.\n:::\n\n::: {.callout-note icon=false}\n## A matriz de projeção $P_\\pi$\n\n- □ Se, em vez de projetar $\\mathbf{y}$ sobre $\\text{col}(X)$,\n  quiséssemos projetar sobre um subespaço diferente gerado pelas\n  colunas de outra matriz $Z$ (mesmas dimensões de $X$), a matriz de\n  projeção correspondente seria $P_\\pi'=Z(Z^TZ)^{-1}Z^T$, com a mesma\n  propriedade $P_\\pi'^2=P_\\pi'$.\n- □ No caso-limite em que as colunas de $X$ já são ortonormais\n  ($X^TX=I$), a matriz de projeção se simplifica para $P_\\pi=XX^T$.\n- □ Em compressão de imagem via PCA, manter apenas as $k$ componentes\n  principais mais informativas e descartar as demais pode ser descrito\n  por uma matriz de projeção $P_\\pi$ com as mesmas propriedades\n  ($P_\\pi^2=P_\\pi$, simétrica) discutidas nesta aula.\n- □ Como $P_\\pi=X(X^TX)^{-1}X^T\\in\\mathbb{R}^{N\\times N}$ e toda matriz\n  quadrada invertível que satisfaz $P^2=P$ só pode ser a identidade,\n  isso implica que $P_\\pi$ só pode ser a matriz identidade quando $X$\n  tem posto completo.\n:::\n\n::: {.callout-note icon=false}\n## Síntese: da falta de solução à ponte para a Aula 4\n\n- □ Se a Aula 4 mostrasse que o número de condição de $X^TX$ pode ser\n  calculado exatamente a partir da razão entre o maior e o menor\n  autovalor de $X^TX$, isso tornaria desnecessário o tipo de\n  experimento de perturbação numérica usado no Bloco 6 desta aula para\n  *detectar* fragilidade — mas o experimento de perturbação continuaria\n  sendo uma forma válida de *demonstrar* o efeito prático dessa\n  fragilidade.\n- □ No caso-limite em que $X$ tem colunas mutuamente ortogonais e\n  todas de norma $1$ (uma base ortonormal do espaço-coluna), o número\n  de condição de $X^TX$ é exatamente $1$ — o melhor condicionamento\n  numérico possível.\n- □ Num pipeline de aprendizado de máquina em que os atributos de\n  entrada são primeiro padronizados (média 0, desvio-padrão 1) antes do\n  ajuste, essa etapa de pré-processamento pode, dependendo dos dados,\n  influenciar o número de condição de $X^TX$ resultante, mesmo sem\n  alterar o posto de $X$.\n- □ Como as Equações Normais fornecem uma fórmula fechada exata para\n  $\\hat{\\mathbf{w}}$ sempre que $X$ tem posto completo, isso implica que\n  essa fórmula é sempre o método numericamente mais recomendado para\n  calcular $\\hat{\\mathbf{w}}$ na prática, independentemente do número\n  de condição de $X^TX$.\n:::\n\n## Aviso\n\nAs questões de Verdadeiro/Falso e discursivas ficam sem solução neste\narquivo — são para resolução autônoma do aluno, fora do horário de aula.\n\n:::\n\n",
    "supporting": [
      "index_files/figure-revealjs"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}