<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-BR" xml:lang="pt-BR"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Marcos M. Raimundo — Instituto de Computação, UNICAMP">

<title>Revisão Integrada — O Fio Probabilístico das Aulas 1–4 – Marcos M. Raimundo</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../more.png" rel="icon" type="image/png">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-de6b2afc8591517e0c1f78da07193c80.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Marcos M. Raimundo</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Procurar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Alternar de navegação" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../teaching/index.html"> 
<span class="menu-text">Teaching</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../projects/index.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../publications/index.html"> 
<span class="menu-text">Publications</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../people/index.html"> 
<span class="menu-text">People</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../contact.html"> 
<span class="menu-text">Contact</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/marcosmrai"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://scholar.google.com.br/citations?user=ibe0jfQAAAAJ&amp;hl=pt-BR"> <i class="bi bi-mortarboard-fill" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Nesta página</h2>
   
  <ul>
  <li><a href="#abertura-amarrando-os-quatro-fios" id="toc-abertura-amarrando-os-quatro-fios" class="nav-link active" data-scroll-target="#abertura-amarrando-os-quatro-fios"><span class="header-section-number">1</span> Abertura — Amarrando os Quatro Fios</a></li>
  <li><a href="#bloco-1-distribuição-e-decisão-revisão-da-aula-1" id="toc-bloco-1-distribuição-e-decisão-revisão-da-aula-1" class="nav-link" data-scroll-target="#bloco-1-distribuição-e-decisão-revisão-da-aula-1"><span class="header-section-number">2</span> Bloco 1 — Distribuição e Decisão (revisão da Aula 1)</a></li>
  <li><a href="#bloco-2-independência-e-teoria-da-decisão-revisão-da-aula-2" id="toc-bloco-2-independência-e-teoria-da-decisão-revisão-da-aula-2" class="nav-link" data-scroll-target="#bloco-2-independência-e-teoria-da-decisão-revisão-da-aula-2"><span class="header-section-number">3</span> Bloco 2 — Independência e Teoria da Decisão (revisão da Aula 2)</a></li>
  <li><a href="#bloco-3-partição-gulosa-e-verossimilhança-categórica-revisão-da-aula-3" id="toc-bloco-3-partição-gulosa-e-verossimilhança-categórica-revisão-da-aula-3" class="nav-link" data-scroll-target="#bloco-3-partição-gulosa-e-verossimilhança-categórica-revisão-da-aula-3"><span class="header-section-number">4</span> Bloco 3 — Partição Gulosa e Verossimilhança Categórica (revisão da Aula 3)</a></li>
  <li><a href="#bloco-4-estimando-o-risco-que-nunca-observamos-revisão-da-aula-4" id="toc-bloco-4-estimando-o-risco-que-nunca-observamos-revisão-da-aula-4" class="nav-link" data-scroll-target="#bloco-4-estimando-o-risco-que-nunca-observamos-revisão-da-aula-4"><span class="header-section-number">5</span> Bloco 4 — Estimando o Risco que Nunca Observamos (revisão da Aula 4)</a></li>
  <li><a href="#bloco-5-síntese-as-quatro-peças-uma-estrutura" id="toc-bloco-5-síntese-as-quatro-peças-uma-estrutura" class="nav-link" data-scroll-target="#bloco-5-síntese-as-quatro-peças-uma-estrutura"><span class="header-section-number">6</span> Bloco 5 — Síntese: As Quatro Peças, Uma Estrutura</a></li>
  <li><a href="#fechamento" id="toc-fechamento" class="nav-link" data-scroll-target="#fechamento"><span class="header-section-number">7</span> Fechamento</a></li>
  <li><a href="#exercícios" id="toc-exercícios" class="nav-link" data-scroll-target="#exercícios"><span class="header-section-number">8</span> Exercícios</a>
  <ul class="collapse">
  <li><a href="#questões-discursivas" id="toc-questões-discursivas" class="nav-link" data-scroll-target="#questões-discursivas"><span class="header-section-number">8.1</span> Questões discursivas</a></li>
  <li><a href="#questões-de-verdadeirofalso" id="toc-questões-de-verdadeirofalso" class="nav-link" data-scroll-target="#questões-de-verdadeirofalso"><span class="header-section-number">8.2</span> Questões de Verdadeiro/Falso</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Outros formatos</h2><ul><li><a href="slides.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Revisão Integrada — O Fio Probabilístico das Aulas 1–4</h1>
<p class="subtitle lead">Aula 5 — Distribuição, Verossimilhança e Risco: o que as Quatro Primeiras Aulas Tinham em Comum</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor</div>
    <div class="quarto-title-meta-contents">
             <p>Marcos M. Raimundo — Instituto de Computação, UNICAMP </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Data de Publicação</div>
    <div class="quarto-title-meta-contents">
      <p class="date">31 de agosto de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><a href="slides.html" class="see-all" aria-label="Ver slides" title="Ver slides">Slides</a> <a href="../../../teaching/supervised-learning/index.html" class="see-all lesson-list-link" aria-label="Lista de aulas" title="Lista de aulas">Lista de aulas</a></p>
<section id="abertura-amarrando-os-quatro-fios" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Abertura — Amarrando os Quatro Fios</h1>
<p>A Aula 4 terminou anunciando que a próxima aula construiria o primeiro modelo paramétrico do curso — regressão linear, ajustada por máxima verossimilhança sob ruído gaussiano. Essa aula ainda vai acontecer (agora como Aula 6). Antes dela, vale parar um momento, porque as quatro aulas que já demos — Beta e limiar de decisão, Naive Bayes e teoria da decisão, árvores CART, validação cruzada e Bootstrap — parecem, na superfície, quatro assuntos técnicos distintos, cada um com seu próprio algoritmo e seu próprio jargão. Não são. Por trás da fachada, as quatro usam a mesma estrutura de três peças, anunciada já no primeiro slide do curso: uma <strong>distribuição</strong> assumida sobre os dados, uma <strong>verossimilhança</strong> usada para ajustá-la aos dados observados, e uma <strong>decisão</strong> fundamentada num risco — esperado, quando é calculável exatamente, ou estimado, quando não é.</p>
<p>Esta aula não introduz nada matematicamente novo. É uma revisão organizada em torno de um único fio condutor experimental — o dataset real <em>Pima Indians Diabetes</em> — que vai atravessar, em sequência, as quatro lentes já vistas.</p>
<p><strong>O roteiro de hoje, em cinco perguntas:</strong></p>
<ol type="1">
<li>O que exatamente as quatro aulas tinham em comum, por trás da fachada de “algoritmos diferentes”?</li>
<li>Como a mesma pergunta — “qual é o formato dos dados?” — aparece disfarçada em Beta, Naive Bayes e árvore de decisão?</li>
<li>Por que “maximizar verossimilhança” e “minimizar impureza/erro” são, estruturalmente, a mesma operação?</li>
<li>Por que nunca observamos o risco de verdade — só conseguimos estimá-lo — e o que a Aula 4 fez sobre isso?</li>
<li>Que peça ainda falta para completar o quadro, e é isso que a Aula 6 resolve?</li>
</ol>
<p><strong>O problema motivador.</strong> <em>Pima Indians Diabetes</em> é um dataset real de 768 pacientes, com oito atributos clínicos (glicose, pressão, IMC, idade etc.) e um alvo binário — diabético ou não. Nenhuma das Aulas 1–4 usou exatamente este dataset (a Aula 1 usou Beta sintética; as Aulas 2 e 4 usaram <em>Breast Cancer Wisconsin</em>; a Aula 3 usou <em>California Housing</em>). É precisamente por isso que ele serve bem hoje: vamos usar o <strong>mesmo</strong> par de atributos (Glicose e IMC) nas quatro lentes, uma de cada vez, para deixar visível o que muda entre elas — e, mais importante, o que <strong>não</strong> muda.</p>
<div id="36b653df" class="cell" data-execution_count="2">
<div class="cell-output cell-output-stdout">
<pre><code>N após limpeza: 752  (diabéticos: 264, não-diabéticos: 488, prevalência: 35.1%)</code></pre>
</div>
</div>
<p>Depois de remover os códigos de valor ausente (<code>Glucose==0</code>, <code>BMI==0</code> — nenhum paciente vivo tem glicose ou IMC zero, então zero aqui significa “não medido”, não “medido e igual a zero”), restam 752 pacientes: 264 diabéticos e 488 não-diabéticos, prevalência de 35,1%. Guarde esse número — ele vai reaparecer no Bloco 1 como a priori real deste problema, contrastando com a priori sintética de 95%/5% que a Aula 1 usou para deixar o efeito bem exagerado e visível.</p>
</section>
<section id="bloco-1-distribuição-e-decisão-revisão-da-aula-1" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Bloco 1 — Distribuição e Decisão (revisão da Aula 1)</h1>
<p>A Aula 1 nunca mencionou “diabetes”: trabalhou com duas populações sintéticas em uma única variável <span class="math inline">\(x \in [0,1]\)</span>, geradas por <span class="math inline">\(\text{Beta}(2,5)\)</span> (classe A) e <span class="math inline">\(\text{Beta}(6,3)\)</span> (classe B), numa proporção deliberadamente extrema de <span class="math inline">\(\pi_A=0{,}95\)</span> contra <span class="math inline">\(\pi_B=0{,}05\)</span>. A turma respondeu, intuitivamente, que o corte ótimo entre as duas classes deveria ficar <strong>no cruzamento das curvas condicionais</strong> <span class="math inline">\(p(x\mid\mathcal{C}_A)\)</span> e <span class="math inline">\(p(x\mid\mathcal{C}_B)\)</span> — e essa resposta se revelou errada: o corte que minimiza o erro total é o cruzamento das <strong>conjuntas</strong> <span class="math inline">\(p(x\mid\mathcal{C}_k)\,\pi_k\)</span>, que pondera cada densidade pela frequência real da sua classe. A mesma lição reapareceu, no caso discreto, na triagem médica de DLFC: com sensibilidade <span class="math inline">\(90\%\)</span>, falso positivo <span class="math inline">\(3\%\)</span> e prevalência de apenas <span class="math inline">\(1\%\)</span>, um teste positivo ainda deixa a probabilidade de doença em apenas <span class="math inline">\(23\%\)</span> — a priori baixa, não a verossimilhança alta, é quem decide.</p>
<p>Hoje, a mesma máquina — ajuste de Beta por classe, comparação de cruzamentos — roda sobre um dado real: a coluna <strong>Glicose</strong> do Pima Indians Diabetes, separada por diabético/não-diabético.</p>
<div id="6820e036" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-4-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Beta ajustada | não-diabético: a=3.49, b=4.50   |   diabético: a=3.18, b=1.78
priori real: pi(não-diabético)=0.649, pi(diabético)=0.351</code></pre>
</div>
</div>
<p>O ajuste (via <code>scipy.stats.beta.fit</code>, o mesmo estimador de máxima verossimilhança usado na Aula 1 — sem forma fechada simples, porque as estatísticas suficientes da Beta são <span class="math inline">\(\sum\ln x_n\)</span> e <span class="math inline">\(\sum\ln(1-x_n)\)</span>, não a média aritmética) dá <span class="math inline">\(\text{Beta}(3{,}49,\,4{,}50)\)</span> para não-diabéticos e <span class="math inline">\(\text{Beta}(3{,}18,\,1{,}78)\)</span> para diabéticos: a curva dos diabéticos é visivelmente deslocada para glicoses mais altas, exatamente como o exame clínico sugere.</p>
<p>A priori real aqui é <span class="math inline">\(\pi(\text{não-diabético}) \approx 0{,}649\)</span> e <span class="math inline">\(\pi(\text{diabético}) \approx 0{,}351\)</span> — assimétrica, mas <strong>muito</strong> menos extrema do que os <span class="math inline">\(0{,}95/0{,}05\)</span> sintéticos da Aula 1. Isso já é uma primeira lição sobre a diferença entre laboratório e mundo real: a Aula 1 escolheu uma assimetria extrema de propósito, para que o efeito do deslocamento do corte fosse visualmente óbvio; o mundo real raramente é tão gentil.</p>
<div id="d40e85ac" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-5-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>t_cond = 134.2 mg/dL -&gt; 81 alarmes falsos + 116 escapes = 197 erros
t_conj = 148.3 mg/dL -&gt; 37 alarmes falsos + 157 escapes = 194 erros</code></pre>
</div>
</div>
<p>O cruzamento das condicionais cai em <span class="math inline">\(134{,}2\)</span> mg/dL, produzindo <span class="math inline">\(81\)</span> alarmes falsos e <span class="math inline">\(116\)</span> escapes (<span class="math inline">\(197\)</span> erros no total). Pesando cada curva pela priori real, o cruzamento das conjuntas se desloca para <span class="math inline">\(148{,}3\)</span> mg/dL — mais alarmes falsos evitados às custas de mais escapes, mas o total cai para <span class="math inline">\(194\)</span> erros. O princípio geométrico é <em>idêntico</em> ao da Aula 1 (<span class="math inline">\(x \in \mathcal{R}_A \iff p(x,\mathcal{C}_A) &gt; p(x,\mathcal{C}_B)\)</span>, PRML eqs. 1.78–1.79): decidir pela conjunta maior é decidir pela posteriori maior, porque a evidência <span class="math inline">\(p(x)\)</span> não depende de <span class="math inline">\(k\)</span>. A diferença é de <strong>magnitude</strong>, não de mecanismo: com prioris <span class="math inline">\(65\%/35\%\)</span>, o deslocamento do corte e o ganho em erros totais são modestos (<span class="math inline">\(197 \to 194\)</span>), bem mais discretos do que a virada dramática que a razão <span class="math inline">\(19\)</span> para <span class="math inline">\(1\)</span> da Aula 1 produzia. Isso não é uma falha do princípio — é exatamente o que se espera quando a assimetria de classes é ela mesma mais moderada.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Se a prevalência de diabetes nesta população fosse exatamente <span class="math inline">\(50\%\)</span>, o que aconteceria com a distância entre o cruzamento das condicionais e o cruzamento das conjuntas?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: pense no papel exato que <span class="math inline">\(\pi_k\)</span> desempenha na equação <span class="math inline">\(p(x,\mathcal{C}_k) = p(x\mid\mathcal{C}_k)\,\pi_k\)</span> quando <span class="math inline">\(\pi_A=\pi_B\)</span>.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Prioris, Cruzamentos e o Caso Real
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>□ Se a prevalência real fosse exatamente <span class="math inline">\(50\%/50\%\)</span>, o cruzamento das condicionais e o cruzamento das conjuntas coincidiriam exatamente, e a distinção entre os dois deixaria de ter qualquer efeito prático.</li>
<li>□ Como a razão de prioris hoje (<span class="math inline">\(65/35 \approx 1{,}86\)</span>) é muito menor que a da Aula 1 (<span class="math inline">\(95/5 = 19\)</span>), o deslocamento do corte hoje é necessariamente menor em termos absolutos de mg/dL, mas o argumento matemático que o produz é o mesmo.</li>
<li>□ Num exame de triagem para uma doença ainda mais rara que a prevalência de <span class="math inline">\(1\%\)</span> usada no exemplo da DLFC — digamos, <span class="math inline">\(0{,}01\%\)</span> — o efeito “sensibilidade alta não implica probabilidade pós-teste alta” ficaria ainda mais pronunciado, não menos.</li>
<li>□ Já que o corte pela conjunta reduziu o número total de erros (<span class="math inline">\(197 \to 194\)</span>), ele necessariamente reduziu tanto o número de alarmes falsos quanto o número de escapes, individualmente.</li>
</ul>
</div>
</div>
</section>
<section id="bloco-2-independência-e-teoria-da-decisão-revisão-da-aula-2" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Bloco 2 — Independência e Teoria da Decisão (revisão da Aula 2)</h1>
<p>A Aula 2 generalizou o Bloco 1 de duas formas ao mesmo tempo: de uma variável para <span class="math inline">\(d\)</span> variáveis, e de um limiar simples para uma teoria da decisão completa (perda <span class="math inline">\(L(k,a)\)</span>, risco posterior <span class="math inline">\(\rho(a\mid x) = \sum_k L(k,a)\,p(\mathcal{C}_k\mid x)\)</span>, risco de Bayes <span class="math inline">\(R^\star\)</span>). A ponte entre as duas foi o Naive Bayes: assumir independência condicional entre atributos dado a classe, <span class="math inline">\(p(\mathbf{x}\mid\mathcal{C}_k) = \prod_i p(x_i\mid\mathcal{C}_k)\)</span>, para não precisar estimar uma densidade conjunta em <span class="math inline">\(d\)</span> dimensões com poucos dados. No <em>Breast Cancer Wisconsin</em>, essa suposição teve um preço mensurável: os atributos <code>smoothness_mean</code> e <code>concavity_mean</code> tinham correlação intra-classe de <span class="math inline">\(0{,}64\)</span> nos tumores malignos e <span class="math inline">\(0{,}22\)</span> nos benignos, e ignorar essa correlação (covariância diagonal, Naive Bayes) custou cerca de <span class="math inline">\(2\)</span> pontos percentuais de acurácia (<span class="math inline">\(85\%\)</span> contra <span class="math inline">\(87\%\)</span> da Gaussiana de covariância plena).</p>
<p>Hoje, acrescentamos <strong>IMC</strong> à Glicose do Pima e repetimos exatamente essa comparação.</p>
<div id="b3c6ce19" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-6-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>correlação Glicose x IMC | não-diabético: 0.123   |   diabético: 0.057
acurácia cov. plena: 0.7646   |   acurácia Naive Bayes (diagonal): 0.7646</code></pre>
</div>
</div>
<p>A correlação intra-classe entre Glicose e IMC é <span class="math inline">\(0{,}123\)</span> nos não-diabéticos e <span class="math inline">\(0{,}057\)</span> nos diabéticos — bem mais baixa do que os <span class="math inline">\(0{,}64/0{,}22\)</span> do <em>Breast Cancer Wisconsin</em>. E o resultado bate com a expectativa: as acurácias de covariância plena e diagonal são <strong>idênticas até a quarta casa decimal</strong> (<span class="math inline">\(76{,}46\%\)</span>), porque com correlação tão baixa, as elipses de covariância plena já são quase circulares — a covariância diagonal não está descartando quase nenhuma informação real. Este é o ponto que a Aula 2 já havia adiantado, citando Domingos &amp; Pazzani (1997) via PRML §8.2.2: “classifica bem, estima mal”. Aqui completamos a lição: o preço da suposição de independência <strong>não é uma constante do método</strong> — é uma função de quanto os atributos realmente covariam dentro de cada classe. No <em>Breast Cancer Wisconsin</em> o preço foi de <span class="math inline">\(2\)</span> pontos; aqui, foi de zero.</p>
<p>Vale também lembrar a peça que a Aula 2 empilhou por cima do Naive Bayes: a teoria da decisão geral. Numa triagem de diabetes, o custo de um <strong>escape</strong> (diabético não identificado, que não recebe tratamento) tipicamente excede o custo de um <strong>alarme falso</strong> (paciente saudável encaminhado para um exame extra). O limiar de decisão ótimo sob essa assimetria de custos não é o de <span class="math inline">\(0{,}5\)</span> de probabilidade posterior — desloca-se para favorecer detectar mais diabéticos às custas de mais alarmes falsos, exatamente pela mesma lógica de <span class="math inline">\(\rho(a\mid x) = \sum_k L(k,a)\,p(\mathcal{C}_k\mid x)\)</span> que a Aula 2 formalizou.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Se Glicose e IMC fossem perfeitamente correlacionados dentro de cada classe (<span class="math inline">\(\rho=1\)</span>), a Gaussiana de covariância plena e o Naive Bayes ainda coincidiriam?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: pense no que a covariância diagonal literalmente descarta, e no que sobra quando ela descarta tudo que existe para descartar.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Naive Bayes: Quando a Independência Custa Caro
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>□ Se Glicose e IMC fossem perfeitamente correlacionados (<span class="math inline">\(\rho=1\)</span>) dentro de cada classe, a Gaussiana diagonal (Naive Bayes) descartaria uma informação real e relevante, ao contrário do caso desta aula onde <span class="math inline">\(\rho\approx0\)</span>.</li>
<li>□ Num problema com <span class="math inline">\(100\)</span> atributos em que apenas dois são fortemente correlacionados entre si e os outros <span class="math inline">\(98\)</span> são praticamente independentes uns dos outros, o Naive Bayes pagaria um preço de acurácia comparável ao preço pago quando todos os <span class="math inline">\(100\)</span> atributos são fortemente correlacionados entre si.</li>
<li>□ Num sistema de recomendação que assume, para simplificar, que o interesse de um usuário por “filmes de ação” e por “filmes com efeitos especiais” são condicionalmente independentes dado o gênero preferido do usuário, o mesmo tipo de preço de correlação ignorada se aplica, mesmo fora do domínio médico desta aula.</li>
<li>□ Como a suposição de independência do Naive Bayes é sempre uma simplificação da realidade, conclui-se que ela sempre reduz a acurácia do classificador em relação a um modelo de covariância plena, ainda que por uma margem pequena.</li>
</ul>
</div>
</div>
</section>
<section id="bloco-3-partição-gulosa-e-verossimilhança-categórica-revisão-da-aula-3" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Bloco 3 — Partição Gulosa e Verossimilhança Categórica (revisão da Aula 3)</h1>
<p>A Aula 3 abandonou a suposição de família paramétrica: em vez de assumir Beta ou Gaussiana, a árvore de decisão deixa o próprio dado escolher a forma da partição, greedy, um split por vez. A tese central daquela aula foi mostrar que “reduzir impureza” (entropia ou Gini) <strong>é</strong>, matematicamente, maximizar verossimilhança — para uma folha de classificação, a categórica <span class="math inline">\(\hat p_{\tau k} = n_{\tau k}/N_\tau\)</span> que maximiza a log-verossimilhança é exatamente a que minimiza a entropia daquela folha, porque <span class="math inline">\(\ell_\tau(\hat p_\tau) = -N_\tau H(\hat p_\tau)\)</span>. A árvore construída sobre o <em>California Housing</em> (regressão, <code>MedInc</code>/<code>HouseAge</code>, cinco folhas) tornou esse processo concreto, split por split.</p>
<p>Hoje, crescemos uma árvore pequena — mas de <strong>classificação</strong>, não de regressão, o que deixa a conexão entropia/Gini/MLE ainda mais direta — sobre Glicose e IMC no Pima.</p>
<div id="939cc42c" class="cell" data-execution_count="6">
<div class="cell-output cell-output-stdout">
<pre><code>|--- Glicose &lt;= 123.50
|   |--- class: 0
|--- Glicose &gt;  123.50
|   |--- Glicose &lt;= 154.50
|   |   |--- IMC &lt;= 41.65
|   |   |   |--- class: 0
|   |   |--- IMC &gt;  41.65
|   |   |   |--- class: 1
|   |--- Glicose &gt;  154.50
|   |   |--- class: 1

N treino=526, N teste=226
acurácia treino=0.7738, acurácia teste=0.7522</code></pre>
</div>
</div>
<div class="fig-resize" style="width: 90%; margin: 0 auto;">
<img src="index_files/mediabag/66412053d4c65d500f81db952d95c171080267e7.svg" class="img-fluid">
</div>
<p>A árvore, limitada a <span class="math inline">\(4\)</span> folhas para caber num quadro didático, chega a <span class="math inline">\(77{,}4\%\)</span> de acurácia de treino e <span class="math inline">\(75{,}2\%\)</span> de teste — guarde os dois números, eles voltam no Bloco 4. As folhas contam uma história clinicamente sensata: quem tem Glicose <span class="math inline">\(\le 123{,}5\)</span> mg/dL raramente é diabético (<span class="math inline">\(\hat p=17{,}2\%\)</span>, folha A, <span class="math inline">\(n=302\)</span>); quem tem Glicose <span class="math inline">\(&gt;154{,}5\)</span> quase sempre é (<span class="math inline">\(\hat p=78{,}5\%\)</span>, folha D); a faixa intermediária (<span class="math inline">\(123{,}5\)</span> a <span class="math inline">\(154{,}5\)</span>) se divide pelo IMC — abaixo de <span class="math inline">\(41{,}65\)</span> ainda majoritariamente não-diabético (<span class="math inline">\(\hat p=39{,}7\%\)</span>, folha B), acima disso fortemente diabético (<span class="math inline">\(\hat p=93{,}3\%\)</span>, folha C, mas só <span class="math inline">\(n=15\)</span> pacientes — um lembrete de que folhas pequenas merecem menos confiança).</p>
<div id="623caf1c" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-8-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Raiz: H=0.648 nats, Gini=0.456, erro bruto=0.352
Após split: H=0.551 nats (IG=0.097), Gini=0.369 (ganho=0.087), erro bruto=0.272</code></pre>
</div>
</div>
<p>O primeiro split (<code>Glicose ≤ 123,5</code>) reduz a entropia de <span class="math inline">\(0{,}648\)</span> para <span class="math inline">\(0{,}551\)</span> nats — um ganho de informação <span class="math inline">\(IG=0{,}097\)</span> nats, exatamente <span class="math inline">\(I(S;\mathcal{C})\)</span> na notação da Aula 3, onde <span class="math inline">\(S\)</span> é o lado do split. O Gini cai de <span class="math inline">\(0{,}456\)</span> para <span class="math inline">\(0{,}369\)</span> (ganho de <span class="math inline">\(0{,}087\)</span>), e o erro bruto (se cada folha previsse sua classe majoritária) cai de <span class="math inline">\(35{,}2\%\)</span> para <span class="math inline">\(27{,}2\%\)</span>. As três medidas concordam em direção — o split ajuda — porque, ao contrário do contraexemplo deliberado que a Aula 3 construiu (dois splits com erro bruto empatado em <span class="math inline">\(0{,}25\)</span> mas <span class="math inline">\(IG\)</span> bem diferente: <span class="math inline">\(0{,}216\)</span> contra <span class="math inline">\(0{,}131\)</span> nats), este split real não empata as três métricas por acidente de construção.</p>
<p>E vale reencontrar aqui o contraste geométrico com o Bloco 2: a fronteira desta árvore é <strong>axis-aligned</strong> — cada split corta perpendicular a um eixo (Glicose ou IMC), nunca na diagonal. As elipses de covariância do Bloco 2, por outro lado, podem se inclinar livremente. Nenhuma das duas fronteiras é “melhor” em abstrato — cada uma paga um preço estrutural diferente, exatamente a limitação que a Aula 3 nomeou explicitamente ao fechar aquele bloco.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Um médico usa a regra manual “Glicose acima de 140 mg/dL <span class="math inline">\(\Rightarrow\)</span> suspeita de diabetes” — isso é, estruturalmente, uma árvore de decisão? Se for, por que a árvore do algoritmo é “melhor” (ou não é)?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: pense no que faz algo ser uma árvore de decisão — é o algoritmo de ajuste, ou a forma da regra final?</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Árvore, Impureza e a Regra do Médico
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>□ A regra manual do médico (“Glicose <span class="math inline">\(&gt;140 \Rightarrow\)</span> suspeita”) é estruturalmente uma árvore de decisão degenerada, com uma única folha de decisão e nenhum critério de impureza envolvido na sua escolha.</li>
<li>□ Se um split greedy reduzisse a impureza de uma folha, mas o split seguinte (dentro da mesma sub-árvore) só fosse vantajoso se combinado com um terceiro split ainda não considerado, o algoritmo guloso da Aula 3 identificaria essa combinação de qualquer forma, porque avalia globalmente todos os splits futuros antes de escolher o atual.</li>
<li>□ Num sistema de recomendação de crédito que decide “aprovar automaticamente” só quando o escore de crédito supera um limiar único, a mesma lógica de “regra de um único corte” do médico se aplica, com a mesma limitação de não capturar interações entre atributos.</li>
<li>□ Como o algoritmo guloso da árvore encontrou um split com <span class="math inline">\(IG\)</span> positivo na raiz, conclui-se que esse split individual é necessariamente parte da árvore de profundidade ilimitada (sem limite de folhas) que minimizaria globalmente a impureza total.</li>
</ul>
</div>
</div>
</section>
<section id="bloco-4-estimando-o-risco-que-nunca-observamos-revisão-da-aula-4" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Bloco 4 — Estimando o Risco que Nunca Observamos (revisão da Aula 4)</h1>
<p>A Aula 4 mudou de assunto: em vez de um modelo, o objeto de estudo passou a ser o <em>procedimento</em> de medir o desempenho de um modelo. A tese central foi que o erro de treino <span class="math inline">\(\hat R(\theta)\)</span> é uma estimativa <strong>enviesada para baixo</strong> do risco esperado <span class="math inline">\(R(\theta) = \mathbb{E}_{(X,Y)\sim P}[\mathcal{L}(Y,f_\theta(X))]\)</span> — no <em>Breast Cancer Wisconsin</em>, a acurácia de treino chegou a <span class="math inline">\(100\%\)</span> a partir da profundidade <span class="math inline">\(6\)</span>, enquanto a de teste tinha seu pico em <span class="math inline">\(92{,}98\%\)</span> na profundidade <span class="math inline">\(5\)</span>. A validação cruzada de <span class="math inline">\(5\)</span> ou <span class="math inline">\(10\)</span> folds foi apresentada como uma simulação de amostragem repetida de <span class="math inline">\(P(X,Y)\)</span> (ESL §7.10) — e, honestamente, o experimento daquela aula mostrou LOOCV (sem viés teórico, mas caro) produzindo uma estimativa <em>menor</em> (<span class="math inline">\(89{,}4\%\)</span>) do que <span class="math inline">\(5\)</span>-fold e <span class="math inline">\(10\)</span>-fold repetidos (<span class="math inline">\(\sim92\)</span>–<span class="math inline">\(93\%\)</span>), um resultado específico daquela amostra, não uma garantia geral. A CV escolheu, por custo-complexidade, uma árvore de <span class="math inline">\(4\)</span> folhas empatando com a de <span class="math inline">\(19\)</span> folhas em <span class="math inline">\(91{,}8\%\)</span> de teste; a regra de <span class="math inline">\(1\)</span> desvio-padrão levou a uma árvore de só <span class="math inline">\(2\)</span> folhas, com um custo real de <span class="math inline">\(1{,}7\)</span> ponto percentual (<span class="math inline">\(90{,}1\%\)</span>). O Bootstrap, por fim, respondeu uma pergunta <em>diferente</em> da CV: não “qual é o risco esperado do procedimento”, mas “quão incerta é uma estatística já calculada” — com intervalos de confiança de <span class="math inline">\([87{,}7\%,95{,}9\%]\)</span> (reamostrando o teste) e <span class="math inline">\([88{,}9\%,93{,}6\%]\)</span> (reamostrando e reajustando o treino).</p>
<p>Hoje, aplicamos exatamente esse arsenal — CV e Bootstrap — para avaliar honestamente a árvore de <span class="math inline">\(4\)</span> folhas do Bloco 3.</p>
<div id="a3048c70" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-9-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>CV 5-fold: [0.755 0.714 0.695 0.695 0.705]  média=0.7128  dp=0.0221
split único (teste): 0.7522
Bootstrap (reamostra teste): média=0.7522  IC95=[0.6903,0.8097]
Bootstrap (reamostra+reajusta treino): média=0.7433  IC95=[0.6924,0.7788]</code></pre>
</div>
</div>
<p>A <span class="math inline">\(5\)</span>-fold CV no conjunto de treino dá uma média de <span class="math inline">\(71{,}3\%\)</span> com desvio-padrão de <span class="math inline">\(2{,}2\%\)</span> — no formato “média<span class="math inline">\(\pm\)</span>desvio” que a Aula 4 insistiu ser obrigatório, <span class="math inline">\(71{,}3\%\pm2{,}2\%\)</span>. A acurácia do nosso único split de teste, <span class="math inline">\(75{,}2\%\)</span>, cai perto do <strong>topo</strong> da faixa revelada pelos cinco folds (que vão de <span class="math inline">\(69{,}5\%\)</span> a <span class="math inline">\(75{,}5\%\)</span>) — não porque a CV esteja “errada”, mas porque um único split é, como a Aula 4 insistiu, um único sorteio de uma distribuição, e o sorteio de hoje calhou de ser um dos mais favoráveis dessa distribuição. É exatamente o motivo de reportar CV com desvio-padrão, não um único número: o número isolado do split de teste, sem esse contexto, sugeriria um desempenho mais otimista do que a média honesta.</p>
<p>O Bootstrap reafirma a distinção conceitual da Aula 4: reamostrar as previsões do teste (mantendo o modelo fixo) mede a <strong>incerteza de medição</strong> daquele número específico (<span class="math inline">\(75{,}2\%\)</span>, IC<span class="math inline">\(_{95\%}=[69{,}0\%,81{,}0\%]\)</span>); reamostrar e reajustar o treino mede a <strong>instabilidade do procedimento</strong> de ajuste em si (<span class="math inline">\(74{,}3\%\)</span>, IC<span class="math inline">\(_{95\%}=[69{,}2\%,77{,}9\%]\)</span>) — duas perguntas relacionadas, mas não idênticas, exatamente como a Aula 4 separou.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>A média de CV (<span class="math inline">\(71{,}3\%\)</span>) ficou abaixo da acurácia do nosso split único de teste (<span class="math inline">\(75{,}2\%\)</span>). Isso significa que o split de teste foi “escolhido a dedo” ou está errado de algum jeito?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: pense na CV como cinco sorteios de uma distribuição, e o split de teste como um sexto sorteio independente da mesma distribuição.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>CV, Split Único e o que “Discrepância” Significa
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>□ Se a acurácia do split único estivesse dentro da faixa observada nos cinco folds de CV, isso por si só já seria evidência de que o split de teste não foi selecionado de forma tendenciosa.</li>
<li>□ No limite em que o conjunto de teste tivesse infinitos pontos, a acurácia medida nele convergiria para o risco esperado verdadeiro <span class="math inline">\(R(\theta)\)</span>, e a distância entre essa acurácia e a média de CV desapareceria.</li>
<li>□ Numa pesquisa eleitoral por amostragem, duas pesquisas com metodologias igualmente corretas podem legitimamente divergir por alguns pontos percentuais só por acaso de amostragem — a mesma lógica estatística que explica a diferença entre CV e o split único desta aula.</li>
<li>□ Como a CV usa <span class="math inline">\(5\)</span> vezes mais “medições” do que um único split de teste, a média de CV é sempre mais próxima do risco esperado verdadeiro do que qualquer split único poderia ser, em qualquer amostra particular.</li>
</ul>
</div>
</div>
</section>
<section id="bloco-5-síntese-as-quatro-peças-uma-estrutura" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Bloco 5 — Síntese: As Quatro Peças, Uma Estrutura</h1>
<p>Chegou a hora de desenhar o mapa completo. Nas quatro aulas, a mesma sequência de três perguntas se repete, só que respondida por máquinas diferentes:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><strong>Distribuição assumida</strong></th>
<th><strong>Verossimilhança usada para ajustar</strong></th>
<th><strong>Decisão / risco</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Aula 1</strong></td>
<td>Beta<span class="math inline">\((x\mid a,b)\)</span> por classe</td>
<td><span class="math inline">\(\sum\ln x_n,\ \sum\ln(1-x_n)\)</span> (sem forma fechada; <code>scipy.stats.beta.fit</code>)</td>
<td>corte no cruzamento das <strong>conjuntas</strong> <span class="math inline">\(p(x,\mathcal{C}_k)\)</span></td>
</tr>
<tr class="even">
<td><strong>Aula 2</strong></td>
<td>Gaussiana com <span class="math inline">\(\Sigma\)</span> diagonal (Naive Bayes) ou plena</td>
<td>fatoração <span class="math inline">\(\prod_i p(x_i\mid\mathcal{C}_k)\)</span> assumida</td>
<td>risco posterior <span class="math inline">\(\rho(a\mid x)=\sum_k L(k,a)\,p(\mathcal{C}_k\mid x)\)</span></td>
</tr>
<tr class="odd">
<td><strong>Aula 3</strong></td>
<td>categórica <span class="math inline">\(\hat p_{\tau k}\)</span> por folha</td>
<td>MLE categórica <span class="math inline">\(=-N_\tau H(\hat p_\tau)\)</span></td>
<td>partição greedy por ganho de informação (IG)</td>
</tr>
<tr class="even">
<td><strong>Aula 4</strong></td>
<td>amostra i.i.d. de <span class="math inline">\(P(X,Y)\)</span> (suposição sobre o <em>processo gerador</em>, não sobre <span class="math inline">\(x\)</span>)</td>
<td><span class="math inline">\(\hat R(\theta)\)</span> recalculado em cada fold/réplica</td>
<td><span class="math inline">\(R(\theta)\)</span>: nunca observado, só estimado (CV, Bootstrap)</td>
</tr>
</tbody>
</table>
<p>A coluna do meio é o ponto que mais se disfarça: em toda aula, algum objeto foi <strong>maximizado</strong> — uma log-verossimilhança, ainda que às vezes escrita como “minimizar entropia” ou “minimizar soma de quadrados”. Na Aula 3, a equivalência foi provada explicitamente (<span class="math inline">\(-N_\tau H(\hat p_\tau)\)</span>); nas Aulas 1 e 2, é a definição padrão de MLE; na Aula 4, o objeto que se maximiza (ajustar <span class="math inline">\(\theta\)</span> ao treino) é justamente o que se torna <strong>enganoso</strong> como medida de risco — a mesma operação de ajuste que funciona bem na coluna do meio se torna a fonte do viés otimista que a coluna da direita precisa corrigir.</p>
<p>Vale registrar, com a mesma honestidade que a Aula 4 pediu para os resultados numéricos, um cuidado de <strong>notação</strong>: o símbolo <span class="math inline">\(k\)</span> significa índice de classe (<span class="math inline">\(\mathcal{C}_k\)</span>) nas Aulas 1–3, mas número de <em>folds</em> na Aula 4 — dois usos completamente distintos do mesmo símbolo. E o custo/penalidade de complexidade aparece como multiplicador de custo assimétrico na Aula 2 (<span class="math inline">\(L(k,a)\)</span>, <span class="math inline">\(c_I/c_{II}\)</span>) e como penalidade de custo-complexidade (<span class="math inline">\(\lambda\)</span>, ou <code>ccp_alpha</code>) nas Aulas 3–4 — parentes conceituais (ambos trocam “ajuste” por “algum outro objetivo”), mas não a mesma quantidade. Não é um erro do curso: é a colisão natural de um alfabeto finito de símbolos sendo reciclado ao longo de quatro aulas — mas vale a pena nomear explicitamente, porque confundir os dois usos de <span class="math inline">\(k\)</span> é exatamente o tipo de erro que “decorar a fórmula sem entender a mecânica” produz.</p>
<div class="fig-resize" style="width: 100%; margin: 0 auto;">
<img src="index_files/mediabag/905e36bbe8cd3a985c3d8a69065832b29cb7bae6.svg" class="img-fluid">
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>A Aula 6 vai construir regressão linear com sua própria distribuição, verossimilhança e decisão. Isso significa que regressão linear “é a mesma coisa” que uma árvore de decisão, só escrita com notação diferente?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dica: pense na diferença entre “usar os mesmos ingredientes” e “fazer o mesmo prato”.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Mesma Estrutura, Técnicas Diferentes
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>□ Se dois algoritmos compartilham a mesma estrutura de três peças (distribuição, verossimilhança, decisão), isso implica que eles vão sempre produzir a mesma fronteira de decisão sobre o mesmo dado.</li>
<li>□ No limite em que a distribuição assumida por um modelo está completamente errada (por exemplo, assumir Beta quando os dados são multimodais e não têm nada a ver com Beta), a etapa de verossimilhança ainda maximiza alguma coisa, mas o resultado da etapa de decisão pode ser sistematicamente ruim, mesmo com a maximização executada “corretamente”.</li>
<li>□ Um estudante que aprende primeiro a estrutura de três peças desta aula, antes de ver o algoritmo específico de regressão linear na Aula 6, deveria ser capaz de prever que existirá algo desempenhando o papel de “distribuição assumida” ali também — mesmo sem ainda saber qual é.</li>
<li>□ Como as quatro aulas revisadas hoje compartilham a mesma estrutura de três peças, conclui-se que a escolha de qual distribuição assumir (Beta, Gaussiana, categórica, i.i.d. de <span class="math inline">\(P(X,Y)\)</span>) é um detalhe secundário que pouco afeta o resultado final de cada técnica.</li>
</ul>
</div>
</div>
</section>
<section id="fechamento" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Fechamento</h1>
<p>Voltando ao roteiro de abertura, com uma frase cada:</p>
<ol type="1">
<li><strong>O que as quatro aulas tinham em comum:</strong> a mesma estrutura de três peças — uma distribuição assumida, uma verossimilhança maximizada para ajustá-la, e uma decisão fundamentada em risco.</li>
<li><strong>Como “qual é o formato dos dados?” se disfarça:</strong> como parâmetros de uma Beta, como uma fatoração de independência condicional, e como a proporção categórica dentro de uma folha — três respostas diferentes à mesma pergunta.</li>
<li><strong>Por que maximizar verossimilhança <span class="math inline">\(=\)</span> minimizar impureza/erro:</strong> porque, para uma categórica, a log-verossimilhança é literalmente <span class="math inline">\(-N_\tau H(\hat p_\tau)\)</span> — não uma analogia, uma identidade algébrica.</li>
<li><strong>Por que nunca observamos o risco de verdade:</strong> porque <span class="math inline">\(R(\theta)\)</span> é uma esperança sobre a distribuição populacional desconhecida <span class="math inline">\(P(X,Y)\)</span>; a Aula 4 respondeu simulando repetidamente essa amostragem via CV, e quantificando a incerteza remanescente via Bootstrap.</li>
<li><strong>Que peça falta:</strong> todas as quatro verossimilhanças de hoje foram sobre densidades, fatorações ou frequências categóricas — nenhuma foi sobre um alvo contínuo ligado linearmente aos atributos. Essa é exatamente a peça que a Aula 6 (Regressão Linear e Máxima Verossimilhança) adiciona: mínimos quadrados como MLE sob um modelo de ruído gaussiano — o mesmo princípio de sempre, agora aplicado a um modelo paramétrico contínuo em vez de uma densidade, uma árvore, ou um esquema de reamostragem.</li>
</ol>
</section>
<section id="exercícios" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Exercícios</h1>
<section id="questões-discursivas" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="questões-discursivas"><span class="header-section-number">8.1</span> Questões discursivas</h2>
<ol type="1">
<li><p>A Aula 1 usou prioris sintéticas de <span class="math inline">\(95\%/5\%\)</span>; hoje, no Pima Indians Diabetes, as prioris reais são de aproximadamente <span class="math inline">\(65\%/35\%\)</span>. Explique, usando a equação da conjunta <span class="math inline">\(p(x,\mathcal{C}_k)=p(x\mid\mathcal{C}_k)\,\pi_k\)</span>, por que o deslocamento do corte ótimo em relação ao cruzamento das condicionais é menor quando a assimetria de prioris é menor — e por que isso não contradiz o princípio geométrico da Aula 1.</p></li>
<li><p>No Bloco 2, a suposição de independência condicional do Naive Bayes teve preço zero (Glicose/IMC no Pima) mas preço de <span class="math inline">\(2\)</span> pontos percentuais no Breast Cancer Wisconsin (Aula 2). Explique por que o preço dessa suposição não é uma propriedade fixa do método Naive Bayes, relacionando sua resposta à correlação intra-classe medida em cada caso.</p></li>
<li><p>A Aula 4 mostrou que a CV de <span class="math inline">\(5\)</span> folds no Bloco 4 desta aula produziu uma média de <span class="math inline">\(71{,}3\%\)</span>, enquanto o split único de teste da árvore do Bloco 3 deu <span class="math inline">\(75{,}2\%\)</span>. Discuta por que essa diferença não é evidência de erro em nenhuma das duas medidas, e proponha um experimento (com dados novos ou reamostrados) que ajudaria a decidir se <span class="math inline">\(75{,}2\%\)</span> é um valor tipicamente otimista para este procedimento.</p></li>
</ol>
</section>
<section id="questões-de-verdadeirofalso" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="questões-de-verdadeirofalso"><span class="header-section-number">8.2</span> Questões de Verdadeiro/Falso</h2>
<p>Cada bloco de 4 itens trata do mesmo tema. A questão só é considerada correta se todos os 4 itens forem julgados corretamente (deixar em branco tem penalidade de 20% da nota da questão).</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Prioris Reais vs.&nbsp;Sintéticas (Aula 1)
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>□ Se a prevalência real de diabetes nesta população fosse de <span class="math inline">\(0{,}1\%\)</span> em vez de <span class="math inline">\(35{,}1\%\)</span>, o cruzamento das conjuntas se deslocaria ainda mais em direção à cauda da distribuição dos diabéticos, tornando o corte ótimo mais extremo do que o observado hoje.</p></li>
<li><p>□ Como a Aula 1 usou uma razão de prioris de <span class="math inline">\(19\)</span> para <span class="math inline">\(1\)</span> e esta aula usa uma razão de aproximadamente <span class="math inline">\(1{,}86\)</span> para <span class="math inline">\(1\)</span>, conclui-se que o cruzamento das conjuntas de hoje está estruturalmente mais próximo do cruzamento das condicionais do que estava na Aula 1.</p></li>
<li><p>□ Num problema de detecção de fraude em que apenas <span class="math inline">\(0{,}5\%\)</span> das transações são fraudulentas, o mesmo argumento do cruzamento de conjuntas (em vez de condicionais) se aplica, mesmo que a variável observada não seja glicose nem tenha suporte em <span class="math inline">\([0,1]\)</span>.</p></li>
<li><p>□ Já que a Beta ajustada aos diabéticos (<span class="math inline">\(a=3{,}18,\ b=1{,}78\)</span>) tem parâmetros diferentes da Beta ajustada aos não-diabéticos (<span class="math inline">\(a=3{,}49,\ b=4{,}50\)</span>), isso por si só garante que as duas curvas nunca se cruzam mais de uma vez no intervalo <span class="math inline">\([0,1]\)</span>.</p></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Beta como Estimador de Densidade (Aula 1)
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>□ No limite em que <span class="math inline">\(a=b=1\)</span>, a distribuição Beta se reduz à uniforme em <span class="math inline">\([0,1]\)</span>, e o ajuste por máxima verossimilhança deixaria de conseguir distinguir as duas classes por qualquer diferença de forma.</p></li>
<li><p>□ Se, em vez de ajustar uma Beta por máxima verossimilhança, alguém decidisse usar a média e o desvio-padrão amostrais para “adivinhar” <span class="math inline">\(a\)</span> e <span class="math inline">\(b\)</span> por um método de momentos, o resultado coincidiria exatamente com o obtido por <code>scipy.stats.beta.fit</code>, porque ambos otimizam a mesma função.</p></li>
<li><p>□ Num sensor industrial que mede uma proporção (por exemplo, fração de peças defeituosas por lote, sempre em <span class="math inline">\([0,1]\)</span>), o mesmo ajuste de Beta por classe (lote bom vs.&nbsp;lote ruim) se aplicaria naturalmente, sem exigir Gaussiana ou outra família com suporte ilimitado.</p></li>
<li><p>□ Como a Beta ajustada aos não-diabéticos tem <span class="math inline">\(b_0=4{,}50 &gt; a_0=3{,}49\)</span>, conclui-se que essa distribuição é necessariamente simétrica em torno de <span class="math inline">\(0{,}5\)</span>.</p></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Erro Tipo I/II e Assimetria de Custos (Aula 1)
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>□ No limite em que o custo de um escape (diabético não identificado) tende a infinito relativamente ao custo de um alarme falso, o limiar de decisão ótimo se deslocaria para a esquerda, classificando cada vez mais pacientes como diabéticos até declarar quase todos positivos.</p></li>
<li><p>□ Se um exame de triagem fosse ajustado para ter exatamente zero alarmes falsos, isso garantiria automaticamente que ele também tem poucos escapes, já que os dois tipos de erro tendem a se mover na mesma direção quando o limiar muda.</p></li>
<li><p>□ Num sistema de moderação de conteúdo automatizado que decide entre “remover” e “manter” uma postagem, a mesma lógica de troca entre Erro Tipo I (remover conteúdo legítimo) e Erro Tipo II (manter conteúdo problemático) se aplica, com custos claramente diferentes conforme o contexto da plataforma.</p></li>
<li><p>□ Como o corte pela conjunta (Bloco 1 desta aula) reduziu o número total de erros em relação ao corte pelas condicionais, conclui-se que ele é a escolha certa independentemente de qualquer consideração sobre o custo relativo de alarmes falsos e escapes.</p></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Independência Condicional: Preço Variável (Aula 2)
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>□ Se, em vez de Glicose e IMC, o Bloco 2 tivesse usado dois atributos definidos de forma redundante (por exemplo, “IMC em kg/m²” e “IMC em unidades arbitrárias que são o dobro do IMC em kg/m²”), a correlação intra-classe entre eles seria próxima de <span class="math inline">\(1\)</span>, e a suposição de independência do Naive Bayes pagaria um preço bem maior do que o observado hoje.</p></li>
<li><p>□ Como o Naive Bayes produziu exatamente a mesma acurácia que a Gaussiana de covariância plena no Pima (Glicose/IMC), conclui-se que, para qualquer par de atributos deste dataset, a suposição de independência condicional nunca custaria nada.</p></li>
<li><p>□ Num modelo de triagem de spam que assume independência condicional entre a presença das palavras “grátis” e “promoção” dado o rótulo (spam/não-spam), o preço dessa suposição dependeria de quão correlacionadas essas duas palavras realmente são dentro de cada classe — a mesma lógica do Bloco 2, fora do domínio médico.</p></li>
<li><p>□ Se duas variáveis fossem independentes tanto na classe A quanto na classe B, mas com médias diferentes entre as classes, a Gaussiana de covariância diagonal (Naive Bayes) ainda poderia separar as duas classes razoavelmente bem, sem qualquer prejuízo vindo da suposição de independência.</p></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Teoria da Decisão e Risco Posterior (Aula 2)
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>□ Se a matriz de perdas <span class="math inline">\(L(k,a)\)</span> atribuísse custo zero a todo acerto e custo idêntico a qualquer tipo de erro (Tipo I ou Tipo II), o limiar de decisão que minimiza o risco posterior <span class="math inline">\(\rho(a\mid x)\)</span> coincidiria com o limiar de <span class="math inline">\(0{,}5\)</span> de probabilidade posterior.</p></li>
<li><p>□ Num cenário em que o custo de um escape é dez vezes o custo de um alarme falso, o limiar ótimo de probabilidade posterior para declarar “diabético” seria maior do que <span class="math inline">\(0{,}5\)</span>, tornando mais difícil, não mais fácil, declarar a classe rara.</p></li>
<li><p>□ Numa seguradora que decide entre “aceitar apólice” e “recusar apólice” com custos assimétricos entre aceitar um mau pagador e recusar um bom pagador, a mesma estrutura de risco posterior <span class="math inline">\(\rho(a\mid x)=\sum_k L(k,a)p(\mathcal{C}_k\mid x)\)</span> se aplica, com a mesma lógica de deslocamento de limiar por assimetria de custo.</p></li>
<li><p>□ Como o risco de Bayes <span class="math inline">\(R^\star\)</span> é definido como o valor esperado do risco posterior mínimo sobre a distribuição de <span class="math inline">\(X\)</span>, ele é sempre estritamente positivo, mesmo quando as classes não se sobrepõem em nenhum ponto do espaço de atributos.</p></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Naive Bayes: Generativo, Não Discriminativo (Aula 2)
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>□ Se um modelo generativo (como o Naive Bayes Gaussiano) estimar <span class="math inline">\(p(\mathbf{x}\mid\mathcal{C}_k)\)</span> e <span class="math inline">\(\pi_k\)</span> corretamente para cada classe, ele automaticamente também é capaz de gerar novos exemplos sintéticos plausíveis de cada classe, amostrando dessas densidades — capacidade que um classificador puramente discriminativo, que só estima <span class="math inline">\(p(\mathcal{C}_k\mid\mathbf{x})\)</span> diretamente, não tem por construção.</p></li>
<li><p>□ Como o Naive Bayes é um modelo generativo, ele necessariamente tem acurácia de classificação igual ou maior do que qualquer modelo discriminativo treinado com os mesmos dados.</p></li>
<li><p>□ Num cenário de poucos dados de treino, a estrutura extra imposta por um modelo generativo (como a fatoração de independência do Naive Bayes) pode compensar a falta de dados o suficiente para superar um modelo discriminativo mais flexível mas sem essa estrutura — o mesmo tipo de troca “menos flexibilidade, mais parcimônia” discutida no Bloco 3 desta aula sobre árvores.</p></li>
<li><p>□ Se duas classes tiverem exatamente a mesma densidade condicional <span class="math inline">\(p(\mathbf{x}\mid\mathcal{C}_k)\)</span>, mas prioris diferentes, um modelo generativo ainda conseguiria, em princípio, produzir uma fronteira de decisão não trivial entre elas, baseada só na diferença de prioris.</p></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Impureza como Verossimilhança (Aula 3)
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>□ Se todas as folhas de uma árvore de classificação tivessem exatamente <span class="math inline">\(\hat p_{\tau k}=1\)</span> para alguma classe <span class="math inline">\(k\)</span> e <span class="math inline">\(0\)</span> para as demais (pureza total), a entropia de cada folha seria zero e a log-verossimilhança do modelo, avaliada nos próprios dados de treino, seria a maior possível (<span class="math inline">\(0\)</span>, já que <span class="math inline">\(\ln 1=0\)</span>).</p></li>
<li><p>□ Como reduzir entropia é equivalente a maximizar a log-verossimilhança categórica (<span class="math inline">\(\ell_\tau(\hat p_\tau)=-N_\tau H(\hat p_\tau)\)</span>), qualquer split que reduza a entropia ponderada também reduz necessariamente o erro bruto de classificação (proporção de pontos mal classificados pela regra de majoritária).</p></li>
<li><p>□ Num modelo de regressão logística ajustado por máxima verossimilhança (fora do escopo desta aula, mas análogo em espírito), a mesma lógica de “ajustar parâmetros para maximizar a probabilidade dos dados observados” se aplicaria, ainda que a forma funcional da verossimilhança seja diferente da categórica usada nas folhas de uma árvore.</p></li>
<li><p>□ Se duas folhas tivessem o mesmo número de pontos <span class="math inline">\(N_\tau\)</span> e a mesma proporção majoritária <span class="math inline">\(\hat p_{\tau,\text{maj}}\)</span>, elas teriam necessariamente a mesma entropia e o mesmo Gini, independentemente de qualquer outra diferença entre elas.</p></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Miopia Gulosa e Interações (Aula 3)
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>□ Se dois atributos só forem informativos em <strong>combinação</strong> (por exemplo, “Glicose alta E IMC alto” prediz diabetes, mas nenhum dos dois isoladamente prediz bem), um algoritmo guloso de árvore pode demorar mais splits — ou nunca — para capturar essa interação, comparado a um cenário em que cada atributo já é informativo isoladamente.</p></li>
<li><p>□ Como a árvore do Bloco 3 encontrou um split de raiz com ganho de informação positivo, isso garante que esse mesmo split apareceria na raiz de qualquer árvore treinada com um subconjunto diferente, mas ainda representativo, dos mesmos pacientes.</p></li>
<li><p>□ Num algoritmo de busca de rotas que escolhe, a cada cruzamento, a rua que parece mais rápida sem simular o trajeto completo até o destino, a mesma limitação de miopia gulosa das árvores de decisão se aplica — a melhor escolha local não garante a melhor rota global.</p></li>
<li><p>□ Se a árvore permitisse profundidade ilimitada (uma folha por paciente), a miopia gulosa deixaria de ser um problema, porque toda combinação de atributos relevante acabaria sendo capturada em algum nível suficientemente profundo da árvore.</p></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Axis-Aligned vs.&nbsp;Elipses (Aulas 2 e 3)
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>□ Se a fronteira de decisão verdadeira entre duas classes fosse exatamente uma reta na diagonal do espaço de atributos (não paralela a nenhum eixo), uma árvore de decisão precisaria, em geral, de mais splits para aproximá-la do que uma Gaussiana com covariância plena adequadamente ajustada.</p></li>
<li><p>□ Como a árvore do Bloco 3 e a Gaussiana do Bloco 2 usam exatamente os mesmos dois atributos (Glicose e IMC), suas fronteiras de decisão são necessariamente muito parecidas visualmente, independentemente da forma funcional de cada modelo.</p></li>
<li><p>□ Num problema de visão computacional em que a fronteira de decisão relevante depende de uma combinação linear de pixels vizinhos (não alinhada aos eixos originais da imagem), a mesma limitação estrutural das árvores axis-aligned se aplicaria, favorecendo modelos capazes de fronteiras oblíquas.</p></li>
<li><p>□ Se um conjunto de dados tiver uma fronteira de decisão verdadeiramente alinhada aos eixos (por exemplo, “diabético se, e somente se, Glicose <span class="math inline">\(&gt;140\)</span>”), a árvore de decisão deveria, em geral, precisar de menos splits para representá-la do que uma Gaussiana de covariância plena precisaria de parâmetros ajustados para aproximá-la bem.</p></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Erro de Treino e Validação (Aula 4)
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>□ Se a árvore do Bloco 3 tivesse sido avaliada apenas nos dados de treino usados para ajustá-la, a acurácia relatada (<span class="math inline">\(77{,}4\%\)</span>) seria uma estimativa otimista do desempenho esperado em pacientes novos, mesmo sem qualquer intenção de enganar.</p></li>
<li><p>□ Como a acurácia de teste (<span class="math inline">\(75{,}2\%\)</span>) desta árvore é menor que a acurácia de treino (<span class="math inline">\(77{,}4\%\)</span>), a diferença de <span class="math inline">\(2{,}2\)</span> pontos percentuais garante, por si só, que este modelo está sofrendo de overfitting severo, no mesmo grau do experimento de profundidade <span class="math inline">\(15\)</span> da Aula 4.</p></li>
<li><p>□ Num sistema de aprovação de crédito treinado com dados históricos e nunca reavaliado com clientes novos, o mesmo viés otimista do erro de treino se aplicaria à métrica interna de acurácia usada pela equipe de desenvolvimento.</p></li>
<li><p>□ Se um modelo tivesse acurácia de treino e de teste exatamente iguais, isso provaria que o modelo generaliza perfeitamente para qualquer paciente futuro, não só para os presentes no conjunto de teste usado.</p></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Duas Perguntas do Bootstrap (Aula 4)
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>□ Se o objetivo fosse responder “quão confiável é a acurácia de <span class="math inline">\(75{,}2\%\)</span> medida no meu conjunto de teste fixo, sem retreinar nada”, a técnica correta seria reamostrar as previsões do teste com reposição, não reamostrar e reajustar o conjunto de treino.</p></li>
<li><p>□ Como as duas aplicações do Bootstrap desta aula (reamostrar teste vs.&nbsp;reamostrar+reajustar treino) produziram intervalos de confiança parcialmente sobrepostos (<span class="math inline">\([69{,}0\%,81{,}0\%]\)</span> e <span class="math inline">\([69{,}2\%,77{,}9\%]\)</span>), conclui-se que elas estão, na prática, respondendo à mesma pergunta estatística.</p></li>
<li><p>□ Numa pesquisa médica que quer saber não só “qual é a acurácia deste modelo específico” mas “quão instável é o processo de treinar este tipo de modelo nesta população”, reamostrar e reajustar o conjunto de treino é a técnica mais adequada, não reamostrar só as previsões de um modelo já fixo.</p></li>
<li><p>□ Se o intervalo de confiança do Bootstrap para uma estatística for muito largo, isso significa necessariamente que o código do Bootstrap tem um erro de implementação, já que reamostragem com reposição deveria sempre produzir intervalos estreitos.</p></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Vazamento de Dados e Relato Honesto (Aula 4)
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>□ No limite em que a normalização de atributos (subtrair a média, dividir pelo desvio-padrão) for calculada usando a amostra inteira antes do split de validação cruzada, em vez de dentro de cada fold, a estimativa de erro produzida se aproxima da estimativa otimista do erro de treino, mesmo que nenhum rótulo seja usado diretamente nesse cálculo.</p></li>
<li><p>□ Como o experimento de vazamento do ESL (Aula 4) usou rótulos artificialmente aleatórios só para tornar o efeito visível com clareza didática, conclui-se que esse tipo de vazamento não ocorre em datasets reais, onde o rótulo tem relação genuína com os atributos.</p></li>
<li><p>□ Numa competição de previsão de preços de imóveis em que os participantes normalizam os atributos usando toda a base disponível antes de fazer sua própria validação cruzada interna, o mesmo mecanismo de vazamento de informação da Aula 4 se aplica, mesmo fora do domínio médico desta aula.</p></li>
<li><p>□ Reportar somente a média da acurácia de validação cruzada, sem o desvio-padrão, produz um número tecnicamente correto (a média está certa), então essa prática não constitui um problema de honestidade estatística — é apenas uma escolha de estilo de relatório, sem custo prático.</p></li>
</ul>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<!-- Parcial estático, igual em toda aula (não é mais gerado por script —
     ver histórico do teaching/generate_lesson_nav.py, removido). Só
     carrega o script que transforma o sumário nativo do Quarto (#TOC,
     "Nesta página") no painel de acordeão "Nesta aula". -->
<script src="../../toc-accordion.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© 2026 Marcos M. Raimundo</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>