<!DOCTYPE html>
<html lang="pt-BR"><head>
<link href="../../../more.png" rel="icon" type="image/png">
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.18">

  <meta name="author" content="Marcos M. Raimundo — Instituto de Computação, UNICAMP">
  <meta name="dcterms.date" content="2026-08-31">
  <title>Marcos M. Raimundo – Revisão Integrada — O Fio Probabilístico das Aulas 1–4</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../../../site_libs/revealjs/dist/theme/quarto-9af0d15343d0ec36e497a4ab60ddbc72.css">
  <link href="../../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <!-- O tema "simple" do RevealJS não carrega bootstrap-icons.css sozinho
       (isso só acontece no formato HTML, via bootstrap) — sem este link, um
       ícone `<i class="bi bi-...">` usado em qualquer include do RevealJS
       (ex.: ../../logos-footer.html) fica invisível nos slides. Caminho
       relativo à página de SAÍDA (aulaNN/slides.html), não a este arquivo:
       site_libs/ mora na raiz do site, três níveis acima de aulaNN/. -->
  <link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-image="../../UNICAMP.png, ../../IC.png" data-background-position="5% 8%, 95% 8%" data-background-size="140px, 140px" class="quarto-title-block center">
  <h1 class="title">Revisão Integrada — O Fio Probabilístico das Aulas 1–4</h1>
  <p class="subtitle">Aula 5 — Distribuição, Verossimilhança e Risco: o que as Quatro Primeiras Aulas Tinham em Comum</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Marcos M. Raimundo — Instituto de Computação, UNICAMP
</div>
</div>
</div>

  <p class="date">2026-08-31</p>
</section>
<section>
<section id="abertura-amarrando-os-quatro-fios" class="title-slide slide level1 center">
<h1>Abertura — Amarrando os Quatro Fios</h1>

</section>
<section id="da-aula-4-para-hoje" class="slide level2">
<h2>Da Aula 4 para Hoje</h2>
<p>A Aula 4 prometeu: a próxima aula seria regressão linear, mínimos quadrados como MLE gaussiana.</p>
<div class="fragment">
<p><strong>Antes disso — uma pausa.</strong> Beta+limiar, Naive Bayes, árvores, CV/Bootstrap parecem quatro assuntos distintos.</p>
</div>
<div class="fragment">
<p><strong>Não são.</strong> Todos usam a mesma estrutura de três peças, anunciada desde o slide 1 do curso: <strong>distribuição → verossimilhança → decisão fundamentada em risco.</strong></p>
</div>
</section>
<section id="roteiro-cinco-perguntas" class="slide level2">
<h2>Roteiro — Cinco Perguntas</h2>
<div class="fragment">
<p><strong>1.</strong> O que as quatro aulas tinham em comum, por trás da fachada de “algoritmos diferentes”?</p>
</div>
<div class="fragment">
<p><strong>2.</strong> Como “qual é o formato dos dados?” aparece disfarçada em Beta, Naive Bayes e árvore?</p>
</div>
<div class="fragment">
<p><strong>3.</strong> Por que “maximizar verossimilhança” <span class="math inline">\(=\)</span> “minimizar impureza/erro”?</p>
</div>
<div class="fragment">
<p><strong>4.</strong> Por que nunca observamos o risco de verdade, só o estimamos?</p>
</div>
<div class="fragment">
<p><strong>5.</strong> Que peça falta, e é isso que a Aula 6 resolve?</p>
</div>
</section>
<section id="o-fio-condutor-de-hoje" class="slide level2">
<h2>O Fio Condutor de Hoje</h2>
<ul>
<li><strong><em>Pima Indians Diabetes</em></strong>: 768 pacientes, 8 atributos clínicos, alvo binário (diabético/não).</li>
<li>Nenhuma aula anterior usou exatamente este dataset — Aula 1: Beta sintética; Aulas 2 e 4: <em>Breast Cancer Wisconsin</em>; Aula 3: <em>California Housing</em>.</li>
</ul>
<div class="fragment">
<p>Hoje: <strong>o mesmo par (Glicose, IMC)</strong> atravessa as quatro lentes, uma de cada vez — para deixar visível o que muda entre elas, e o que <strong>não</strong> muda.</p>
</div>
<div id="36b653df" class="cell" data-execution_count="2">
<div class="cell-output cell-output-stdout">
<pre><code>N após limpeza: 752  (diabéticos: 264, não-diabéticos: 488, prevalência: 35.1%)</code></pre>
</div>
</div>
</section>
<section id="o-dado-limpo" class="slide level2">
<h2>O Dado, Limpo</h2>
<ul>
<li>Removidos códigos de ausência (<code>Glucose==0</code>, <code>BMI==0</code>).</li>
<li>Restam <strong>752 pacientes</strong>: 264 diabéticos, 488 não-diabéticos.</li>
<li><strong>Prevalência real: 35,1%</strong> — guardar esse número para o Bloco 1.</li>
</ul>
</section></section>
<section>
<section id="bloco-1-distribuição-e-decisão-revisão-da-aula-1" class="title-slide slide level1 center">
<h1>Bloco 1 — Distribuição e Decisão (revisão da Aula 1)</h1>
<p><strong>Aula 1, em síntese:</strong> duas populações sintéticas, <span class="math inline">\(\text{Beta}(2,5)\)</span> vs.&nbsp;<span class="math inline">\(\text{Beta}(6,3)\)</span>, prioris <span class="math inline">\(95\%/5\%\)</span>.</p>
<div class="fragment">
<p>Resposta intuitiva da turma — <strong>corte no cruzamento das condicionais</strong> — estava <strong>errada</strong>.</p>
</div>
<div class="fragment">
<p>Corte correto: cruzamento das <strong>conjuntas</strong> <span class="math inline">\(p(x\mid\mathcal{C}_k)\pi_k\)</span>. Mesma lição na triagem médica: sensibilidade <span class="math inline">\(90\%\)</span> + prevalência <span class="math inline">\(1\%\)</span> <span class="math inline">\(\Rightarrow\)</span> só <span class="math inline">\(23\%\)</span> de chance de doença.</p>
</div>
<div class="fragment">
<p><strong>Hoje:</strong> mesma máquina, dado real — <strong>Glicose</strong> do Pima, por diabético/não-diabético.</p>
</div>
<div id="6820e036" class="cell" data-execution_count="3">

<div class="cell-output cell-output-stdout">
<pre><code>Beta ajustada | não-diabético: a=3.49, b=4.50   |   diabético: a=3.18, b=1.78
priori real: pi(não-diabético)=0.649, pi(diabético)=0.351</code></pre>
</div>
</div>
<img data-src="index_files/figure-revealjs/cell-4-output-1.svg" class="img-fluid quarto-figure quarto-figure-center r-stretch"></section>
<section id="o-ajuste-sobre-dado-real" class="slide level2">
<h2>O Ajuste, sobre Dado Real</h2>
<ul>
<li><span class="math inline">\(\text{Beta}(3{,}49,\,4{,}50)\)</span> — não-diabético; <span class="math inline">\(\text{Beta}(3{,}18,\,1{,}78)\)</span> — diabético.</li>
<li>Ajuste por <code>scipy.stats.beta.fit</code> — mesmo MLE da Aula 1 (sem forma fechada; estatísticas suficientes <span class="math inline">\(\sum\ln x_n,\ \sum\ln(1-x_n)\)</span>, não a média).</li>
</ul>
<div class="fragment">
<p>Priori real: <span class="math inline">\(\pi(\text{não-diab.})\approx 0{,}649\)</span>, <span class="math inline">\(\pi(\text{diab.})\approx 0{,}351\)</span> — assimétrica, mas <strong>bem menos extrema</strong> que os <span class="math inline">\(95\%/5\%\)</span> sintéticos da Aula 1.</p>
</div>
<div id="d40e85ac" class="cell" data-execution_count="4">

<div class="cell-output cell-output-stdout">
<pre><code>t_cond = 134.2 mg/dL -&gt; 81 alarmes falsos + 116 escapes = 197 erros
t_conj = 148.3 mg/dL -&gt; 37 alarmes falsos + 157 escapes = 194 erros</code></pre>
</div>
</div>
<img data-src="index_files/figure-revealjs/cell-5-output-1.svg" class="img-fluid quarto-figure quarto-figure-center r-stretch"></section>
<section id="o-corte-se-desloca-mas-pouco" class="slide level2">
<h2>O Corte se Desloca — Mas Pouco</h2>
<div class="fragment">
<p><span class="math inline">\(t_{\text{cond}} = 134{,}2\)</span> mg/dL <span class="math inline">\(\to\)</span> <span class="math inline">\(81\)</span> alarmes falsos <span class="math inline">\(+\)</span> <span class="math inline">\(116\)</span> escapes <span class="math inline">\(=\)</span> <strong>197 erros</strong>.</p>
</div>
<div class="fragment">
<p><span class="math inline">\(t_{\text{conj}} = 148{,}3\)</span> mg/dL <span class="math inline">\(\to\)</span> <span class="math inline">\(37\)</span> alarmes falsos <span class="math inline">\(+\)</span> <span class="math inline">\(157\)</span> escapes <span class="math inline">\(=\)</span> <strong>194 erros</strong>.</p>
</div>
<div class="fragment">
<p>Mesmo princípio da Aula 1 (<span class="math inline">\(x\in\mathcal{R}_A \iff p(x,\mathcal{C}_A)&gt;p(x,\mathcal{C}_B)\)</span>) — mas com prioris <span class="math inline">\(65/35\)</span> (não <span class="math inline">\(95/5\)</span>), o ganho é <strong>modesto</strong>, não uma virada dramática. Diferença de magnitude, não de mecanismo.</p>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Se a prevalência de diabetes nesta população fosse exatamente <span class="math inline">\(50\%\)</span>, o que aconteceria com a distância entre o cruzamento das condicionais e o cruzamento das conjuntas?</strong></p>
</div>
<div class="callout-content">
<p>Dica: pense no papel exato que <span class="math inline">\(\pi_k\)</span> desempenha na equação <span class="math inline">\(p(x,\mathcal{C}_k) = p(x\mid\mathcal{C}_k)\,\pi_k\)</span> quando <span class="math inline">\(\pi_A=\pi_B\)</span>.</p>
</div>
</div>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Prioris, Cruzamentos e o Caso Real</strong></p>
</div>
<div class="callout-content">
<ul>
<li>□ Se a prevalência real fosse exatamente <span class="math inline">\(50\%/50\%\)</span>, o cruzamento das condicionais e o cruzamento das conjuntas coincidiriam exatamente, e a distinção entre os dois deixaria de ter qualquer efeito prático.</li>
<li>□ Como a razão de prioris hoje (<span class="math inline">\(65/35 \approx 1{,}86\)</span>) é muito menor que a da Aula 1 (<span class="math inline">\(95/5 = 19\)</span>), o deslocamento do corte hoje é necessariamente menor em termos absolutos de mg/dL, mas o argumento matemático que o produz é o mesmo.</li>
<li>□ Num exame de triagem para uma doença ainda mais rara que a prevalência de <span class="math inline">\(1\%\)</span> usada no exemplo da DLFC — digamos, <span class="math inline">\(0{,}01\%\)</span> — o efeito “sensibilidade alta não implica probabilidade pós-teste alta” ficaria ainda mais pronunciado, não menos.</li>
<li>□ Já que o corte pela conjunta reduziu o número total de erros (<span class="math inline">\(197 \to 194\)</span>), ele necessariamente reduziu tanto o número de alarmes falsos quanto o número de escapes, individualmente.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="prioris-cruzamentos-e-o-caso-real-resposta" class="slide level2">
<h2>Prioris, Cruzamentos e o Caso Real — Resposta</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Dica</strong></p>
</div>
<div class="callout-content">
<ul>
<li>✔ Com <span class="math inline">\(\pi_A=\pi_B\)</span>, a ponderação <span class="math inline">\(p(x\mid\mathcal{C}_k)\,\pi_k\)</span> vira só um fator comum <span class="math inline">\(\pi \cdot p(x\mid\mathcal{C}_k)\)</span>, e comparar conjuntas volta a ser exatamente comparar condicionais — os dois cruzamentos coincidem.</li>
<li>✔ A magnitude do deslocamento (em mg/dL, ou em erros totais evitados) depende da razão de prioris; o mecanismo — ponderar cada densidade pela frequência da sua classe — é idêntico em qualquer razão.</li>
<li>✔ Prevalência ainda menor <span class="math inline">\(\Rightarrow\)</span> priori <span class="math inline">\(p(D)\)</span> ainda menor no denominador de Bayes <span class="math inline">\(\Rightarrow\)</span> a probabilidade pós-teste cai ainda mais em relação à sensibilidade nominal, exatamente na mesma direção do exemplo dos <span class="math inline">\(23\%\)</span>.</li>
<li>✗ O corte pela conjunta trocou uma coisa pela outra: <strong>caiu</strong> o número de alarmes falsos (<span class="math inline">\(81\to37\)</span>) mas <strong>subiu</strong> o número de escapes (<span class="math inline">\(116\to157\)</span>); só o <em>total</em> caiu. Reduzir o total nunca garante reduzir as duas parcelas.</li>
</ul>
</div>
</div>
</div>
<div class="fragment">
<p><strong>Voltando à pergunta:</strong> com prioris iguais, os dois cruzamentos colapsam num só — é a assimetria de classes, e só ela, que os separa.</p>
</div>
</section>
<section id="se-a-prevalência-fosse-50-retomando" class="slide level2">
<h2>Se a Prevalência Fosse 50%? — Retomando</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Dica</strong></p>
</div>
<div class="callout-content">
<div class="fragment">
<p><em>(Agora responda: o que sobra da distinção condicional/conjunta quando as duas classes são igualmente frequentes?)</em></p>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="bloco-2-independência-e-teoria-da-decisão-revisão-da-aula-2" class="title-slide slide level1 center">
<h1>Bloco 2 — Independência e Teoria da Decisão (revisão da Aula 2)</h1>
<p><strong>Aula 2, em síntese:</strong> de <span class="math inline">\(1\)</span> variável para <span class="math inline">\(d\)</span>; de um limiar para teoria da decisão completa (<span class="math inline">\(\rho(a\mid x) = \sum_k L(k,a)\,p(\mathcal{C}_k\mid x)\)</span>).</p>
<div class="fragment">
<p>Ponte: Naive Bayes <span class="math inline">\(\Rightarrow\)</span> <span class="math inline">\(p(\mathbf{x}\mid\mathcal{C}_k) = \prod_i p(x_i\mid\mathcal{C}_k)\)</span> — independência condicional assumida.</p>
</div>
<div class="fragment">
<p>No <em>Breast Cancer Wisconsin</em>: correlação intra-classe <span class="math inline">\(0{,}64\)</span>/<span class="math inline">\(0{,}22\)</span> <span class="math inline">\(\Rightarrow\)</span> preço de <span class="math inline">\(2\)</span> pontos percentuais (<span class="math inline">\(85\%\)</span> vs.&nbsp;<span class="math inline">\(87\%\)</span>).</p>
</div>
<div class="fragment">
<p><strong>Hoje:</strong> acrescentar <strong>IMC</strong> à Glicose no Pima, repetir a mesma comparação.</p>
</div>
<div id="b3c6ce19" class="cell" data-execution_count="5">

<div class="cell-output cell-output-stdout">
<pre><code>correlação Glicose x IMC | não-diabético: 0.123   |   diabético: 0.057
acurácia cov. plena: 0.7646   |   acurácia Naive Bayes (diagonal): 0.7646</code></pre>
</div>
</div>
<img data-src="index_files/figure-revealjs/cell-6-output-1.svg" class="img-fluid quarto-figure quarto-figure-center r-stretch"></section>
<section id="o-preço-é-dos-dados-não-do-método" class="slide level2">
<h2>O Preço é dos Dados, Não do Método</h2>
<div class="fragment">
<p>Correlação Glicose <span class="math inline">\(\times\)</span> IMC: <span class="math inline">\(0{,}123\)</span> (não-diab.) e <span class="math inline">\(0{,}057\)</span> (diab.) — bem mais baixa que os <span class="math inline">\(0{,}64/0{,}22\)</span> do <em>Breast Cancer Wisconsin</em>.</p>
</div>
<div class="fragment">
<p>Acurácias: covariância plena <span class="math inline">\(=\)</span> diagonal (Naive Bayes) <span class="math inline">\(=\)</span> <strong><span class="math inline">\(76{,}46\%\)</span></strong>, idênticas até a 4ª casa decimal.</p>
</div>
<div class="fragment">
<p>“Classifica bem, estima mal” (Domingos &amp; Pazzani, 1997) — no <em>Breast Cancer</em> o preço foi <span class="math inline">\(2\)</span> pontos; <strong>aqui foi zero</strong>. O preço da independência é do <strong>dado</strong>, não do método.</p>
</div>
<div class="fragment">
<p><strong>Teoria da decisão (Aula 2):</strong> custo de escape <span class="math inline">\(&gt;\)</span> custo de alarme falso em triagem <span class="math inline">\(\Rightarrow\)</span> limiar ótimo <span class="math inline">\(\ne 0{,}5\)</span>, via <span class="math inline">\(\rho(a\mid x)=\sum_k L(k,a)\,p(\mathcal{C}_k\mid x)\)</span>.</p>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Se Glicose e IMC fossem perfeitamente correlacionados dentro de cada classe (<span class="math inline">\(\rho=1\)</span>), a Gaussiana de covariância plena e o Naive Bayes ainda coincidiriam?</strong></p>
</div>
<div class="callout-content">
<p>Dica: pense no que a covariância diagonal literalmente descarta, e no que sobra quando ela descarta tudo que existe para descartar.</p>
</div>
</div>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Naive Bayes: Quando a Independência Custa Caro</strong></p>
</div>
<div class="callout-content">
<ul>
<li>□ Se Glicose e IMC fossem perfeitamente correlacionados (<span class="math inline">\(\rho=1\)</span>) dentro de cada classe, a Gaussiana diagonal (Naive Bayes) descartaria uma informação real e relevante, ao contrário do caso desta aula onde <span class="math inline">\(\rho\approx0\)</span>.</li>
<li>□ Num problema com <span class="math inline">\(100\)</span> atributos em que apenas dois são fortemente correlacionados entre si e os outros <span class="math inline">\(98\)</span> são praticamente independentes uns dos outros, o Naive Bayes pagaria um preço de acurácia comparável ao preço pago quando todos os <span class="math inline">\(100\)</span> atributos são fortemente correlacionados entre si.</li>
<li>□ Num sistema de recomendação que assume, para simplificar, que o interesse de um usuário por “filmes de ação” e por “filmes com efeitos especiais” são condicionalmente independentes dado o gênero preferido do usuário, o mesmo tipo de preço de correlação ignorada se aplica, mesmo fora do domínio médico desta aula.</li>
<li>□ Como a suposição de independência do Naive Bayes é sempre uma simplificação da realidade, conclui-se que ela sempre reduz a acurácia do classificador em relação a um modelo de covariância plena, ainda que por uma margem pequena.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="naive-bayes-quando-a-independência-custa-caro-resposta" class="slide level2">
<h2>Naive Bayes: Quando a Independência Custa Caro — Resposta</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Dica</strong></p>
</div>
<div class="callout-content">
<ul>
<li>✔ Com <span class="math inline">\(\rho=1\)</span>, a covariância diagonal ignora toda a estrutura de dependência real que existe entre as duas variáveis — o preço da suposição de independência seria máximo, não nulo como no caso de hoje.</li>
<li>✗ O preço de correlação ignorada concentra-se nos atributos correlacionados; ter <span class="math inline">\(98\)</span> atributos independentes ao lado dos <span class="math inline">\(2\)</span> correlacionados não piora o preço pago por ignorar a correlação <strong>desses dois</strong> — é aproximadamente o mesmo problema em miniatura, não amplificado por atributos irrelevantes ao efeito.</li>
<li>✔ Mesma estrutura (independência condicional assumida entre atributos, dado uma variável latente), fora do domínio médico — a mecânica de “classifica razoavelmente, estima mal a conjunta” se transfere.</li>
<li>✗ O caso desta aula (Glicose/IMC) é uma contraprova direta: correlação quase nula <span class="math inline">\(\Rightarrow\)</span> preço de acurácia <strong>zero</strong>, não “pequeno mas sempre presente”. O preço pode ser genuinamente nulo, não apenas pequeno.</li>
</ul>
</div>
</div>
</div>
<div class="fragment">
<p><strong>Voltando à pergunta:</strong> com <span class="math inline">\(\rho=1\)</span>, a covariância diagonal jogaria fora exatamente a informação que faz a diferença — as duas abordagens deixariam de coincidir.</p>
</div>
</section>
<section id="correlação-perfeita-retomando" class="slide level2">
<h2>Correlação Perfeita? — Retomando</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Dica</strong></p>
</div>
<div class="callout-content">
<div class="fragment">
<p><em>(Agora responda: com <span class="math inline">\(\rho=1\)</span>, o que exatamente a covariância diagonal descarta?)</em></p>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="bloco-3-partição-gulosa-e-verossimilhança-categórica-revisão-da-aula-3" class="title-slide slide level1 center">
<h1>Bloco 3 — Partição Gulosa e Verossimilhança Categórica (revisão da Aula 3)</h1>
<p><strong>Aula 3, em síntese:</strong> sem família paramétrica — o dado escolhe a partição, greedy, split por split.</p>
<div class="fragment">
<p>Tese central: <strong>reduzir impureza <span class="math inline">\(=\)</span> maximizar verossimilhança.</strong> Para folha categórica, <span class="math inline">\(\hat p_{\tau k} = n_{\tau k}/N_\tau\)</span> maximiza <span class="math inline">\(\ell_\tau(\hat p_\tau) = -N_\tau H(\hat p_\tau)\)</span>.</p>
</div>
<div class="fragment">
<p>Árvore do <em>California Housing</em> (regressão, <span class="math inline">\(5\)</span> folhas) tornou isso concreto.</p>
</div>
<div class="fragment">
<p><strong>Hoje:</strong> árvore pequena de <strong>classificação</strong> (não regressão) sobre Glicose+IMC — conexão entropia/Gini/MLE ainda mais direta.</p>
</div>
<div id="939cc42c" class="cell" data-execution_count="6">
<div class="cell-output cell-output-stdout">
<pre><code>|--- Glicose &lt;= 123.50
|   |--- class: 0
|--- Glicose &gt;  123.50
|   |--- Glicose &lt;= 154.50
|   |   |--- IMC &lt;= 41.65
|   |   |   |--- class: 0
|   |   |--- IMC &gt;  41.65
|   |   |   |--- class: 1
|   |--- Glicose &gt;  154.50
|   |   |--- class: 1

N treino=526, N teste=226
acurácia treino=0.7738, acurácia teste=0.7522</code></pre>
</div>
</div>
<div class="fig-resize" style="width: 90%; margin: 0 auto;">
<img data-src="index_files/mediabag/66412053d4c65d500f81db952d95c171080267e7.svg" class="img-fluid">
</div>
</section>
<section id="a-árvore-split-por-split" class="slide level2">
<h2>A Árvore, Split por Split</h2>
<ul>
<li><span class="math inline">\(4\)</span> folhas: acurácia treino <span class="math inline">\(77{,}4\%\)</span>, teste <span class="math inline">\(75{,}2\%\)</span> — <strong>guardar para o Bloco 4</strong>.</li>
<li>Folha A (Glicose <span class="math inline">\(\le 123{,}5\)</span>): <span class="math inline">\(n=302\)</span>, <span class="math inline">\(\hat p(\text{diab.})=17{,}2\%\)</span>.</li>
<li>Folha D (Glicose <span class="math inline">\(&gt;154{,}5\)</span>): <span class="math inline">\(n=93\)</span>, <span class="math inline">\(\hat p=78{,}5\%\)</span>.</li>
<li>Faixa intermediária dividida pelo IMC: folha B (<span class="math inline">\(\hat p=39{,}7\%\)</span>) vs.&nbsp;folha C (<span class="math inline">\(\hat p=93{,}3\%\)</span>, mas <span class="math inline">\(n=15\)</span> — cautela com folhas pequenas).</li>
</ul>
<div id="623caf1c" class="cell" data-execution_count="7">

<div class="cell-output cell-output-stdout">
<pre><code>Raiz: H=0.648 nats, Gini=0.456, erro bruto=0.352
Após split: H=0.551 nats (IG=0.097), Gini=0.369 (ganho=0.087), erro bruto=0.272</code></pre>
</div>
</div>
<img data-src="index_files/figure-revealjs/cell-8-output-1.svg" class="img-fluid quarto-figure quarto-figure-center r-stretch"></section>
<section id="impureza-cai-nas-três-medidas" class="slide level2">
<h2>Impureza Cai — Nas Três Medidas</h2>
<div class="fragment">
<p><span class="math inline">\(H\)</span>: <span class="math inline">\(0{,}648 \to 0{,}551\)</span> nats (<span class="math inline">\(IG=0{,}097 = I(S;\mathcal{C})\)</span>, notação da Aula 3).</p>
</div>
<div class="fragment">
<p>Gini: <span class="math inline">\(0{,}456 \to 0{,}369\)</span> (ganho <span class="math inline">\(0{,}087\)</span>). Erro bruto: <span class="math inline">\(35{,}2\% \to 27{,}2\%\)</span>.</p>
</div>
<div class="fragment">
<p>Aqui as três métricas concordam — diferente do contraexemplo da Aula 3 (<span class="math inline">\(IG=0{,}216\)</span> vs.&nbsp;<span class="math inline">\(0{,}131\)</span> nats com erro bruto empatado em <span class="math inline">\(0{,}25\)</span>).</p>
</div>
<div class="fragment">
<p><strong>Contraste geométrico com o Bloco 2:</strong> árvore <span class="math inline">\(=\)</span> fronteira <em>axis-aligned</em>; elipses Gaussianas podem inclinar livremente — a limitação estrutural que a Aula 3 nomeou ao final.</p>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Um médico usa a regra manual “Glicose acima de 140 mg/dL <span class="math inline">\(\Rightarrow\)</span> suspeita de diabetes” — isso é, estruturalmente, uma árvore de decisão? Se for, por que a árvore do algoritmo é “melhor” (ou não é)?</strong></p>
</div>
<div class="callout-content">
<p>Dica: pense no que faz algo ser uma árvore de decisão — é o algoritmo de ajuste, ou a forma da regra final?</p>
</div>
</div>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Árvore, Impureza e a Regra do Médico</strong></p>
</div>
<div class="callout-content">
<ul>
<li>□ A regra manual do médico (“Glicose <span class="math inline">\(&gt;140 \Rightarrow\)</span> suspeita”) é estruturalmente uma árvore de decisão degenerada, com uma única folha de decisão e nenhum critério de impureza envolvido na sua escolha.</li>
<li>□ Se um split greedy reduzisse a impureza de uma folha, mas o split seguinte (dentro da mesma sub-árvore) só fosse vantajoso se combinado com um terceiro split ainda não considerado, o algoritmo guloso da Aula 3 identificaria essa combinação de qualquer forma, porque avalia globalmente todos os splits futuros antes de escolher o atual.</li>
<li>□ Num sistema de recomendação de crédito que decide “aprovar automaticamente” só quando o escore de crédito supera um limiar único, a mesma lógica de “regra de um único corte” do médico se aplica, com a mesma limitação de não capturar interações entre atributos.</li>
<li>□ Como o algoritmo guloso da árvore encontrou um split com <span class="math inline">\(IG\)</span> positivo na raiz, conclui-se que esse split individual é necessariamente parte da árvore de profundidade ilimitada (sem limite de folhas) que minimizaria globalmente a impureza total.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="árvore-impureza-e-a-regra-do-médico-resposta" class="slide level2">
<h2>Árvore, Impureza e a Regra do Médico — Resposta</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Dica</strong></p>
</div>
<div class="callout-content">
<ul>
<li>✔ Uma regra de corte único é o caso degenerado de uma árvore com uma folha de decisão — só que ajustada “à mão”, sem otimizar impureza sobre dados, e sem nenhuma folha alternativa.</li>
<li>✗ É exatamente a <strong>miopia gulosa</strong> que a Aula 3 apontou como limitação: o algoritmo escolhe o melhor split <em>imediato</em>, sem simular combinações futuras — pode perder uma combinação de splits que só compensa em conjunto.</li>
<li>✔ Mesma limitação estrutural (corte único, sem interação entre atributos), transferida para outro domínio — crédito em vez de diagnóstico.</li>
<li>✗ Um split com <span class="math inline">\(IG&gt;0\)</span> na raiz é ótimo <em>localmente</em>, não necessariamente parte da árvore globalmente ótima — a busca gulosa não garante otimalidade global, mesma advertência da Aula 3.</li>
</ul>
</div>
</div>
</div>
<div class="fragment">
<p><strong>Voltando à pergunta:</strong> sim, é uma árvore degenerada — mas sem o processo de ajuste por impureza que dá à árvore do algoritmo a chance de encontrar um corte melhor do que um número “redondo” escolhido a olho.</p>
</div>
</section>
<section id="a-regra-do-médico-retomando" class="slide level2">
<h2>A Regra do Médico — Retomando</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Dica</strong></p>
</div>
<div class="callout-content">
<div class="fragment">
<p><em>(Agora responda: o que a árvore do algoritmo tem que a regra manual do médico não tem?)</em></p>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="bloco-4-estimando-o-risco-que-nunca-observamos-revisão-da-aula-4" class="title-slide slide level1 center">
<h1>Bloco 4 — Estimando o Risco que Nunca Observamos (revisão da Aula 4)</h1>
<p><strong>Aula 4, em síntese:</strong> <span class="math inline">\(\hat R(\theta)\)</span> enviesado para baixo; <em>Breast Cancer</em>: treino <span class="math inline">\(100\%\)</span> na profundidade <span class="math inline">\(6\)</span>, teste no pico em <span class="math inline">\(92{,}98\%\)</span> (profundidade <span class="math inline">\(5\)</span>).</p>
<div class="fragment">
<p>CV <span class="math inline">\(=\)</span> simulação de amostragem repetida de <span class="math inline">\(P(X,Y)\)</span>. Honestidade: LOOCV (<span class="math inline">\(89{,}4\%\)</span>) <em>abaixo</em> de <span class="math inline">\(5\)</span>-/<span class="math inline">\(10\)</span>-fold (<span class="math inline">\(\sim92\)</span>–<span class="math inline">\(93\%\)</span>) nessa amostra específica.</p>
</div>
<div class="fragment">
<p>CV escolheu árvore de <span class="math inline">\(4\)</span> folhas empatando com <span class="math inline">\(19\)</span> folhas em <span class="math inline">\(91{,}8\%\)</span>; regra de <span class="math inline">\(1\)</span> desvio-padrão <span class="math inline">\(\to\)</span> <span class="math inline">\(2\)</span> folhas, custo real de <span class="math inline">\(1{,}7\)</span> p.p. (<span class="math inline">\(90{,}1\%\)</span>).</p>
</div>
<div class="fragment">
<p>Bootstrap <span class="math inline">\(\ne\)</span> CV: pergunta diferente. IC<span class="math inline">\(_{95\%}\)</span>: <span class="math inline">\([87{,}7\%,95{,}9\%]\)</span> (teste) e <span class="math inline">\([88{,}9\%,93{,}6\%]\)</span> (treino reajustado).</p>
</div>
<div class="fragment">
<p><strong>Hoje:</strong> o mesmo arsenal, sobre a árvore de <span class="math inline">\(4\)</span> folhas do Bloco 3.</p>
</div>
<div id="a3048c70" class="cell" data-execution_count="8">

<div class="cell-output cell-output-stdout">
<pre><code>CV 5-fold: [0.755 0.714 0.695 0.695 0.705]  média=0.7128  dp=0.0221
split único (teste): 0.7522
Bootstrap (reamostra teste): média=0.7522  IC95=[0.6903,0.8097]
Bootstrap (reamostra+reajusta treino): média=0.7433  IC95=[0.6924,0.7788]</code></pre>
</div>
</div>
<img data-src="index_files/figure-revealjs/cell-9-output-1.svg" class="img-fluid quarto-figure quarto-figure-center r-stretch"></section>
<section id="um-único-número-nunca-basta" class="slide level2">
<h2>Um Único Número Nunca Basta</h2>
<div class="fragment">
<p>CV <span class="math inline">\(5\)</span>-fold: <strong><span class="math inline">\(71{,}3\%\pm2{,}2\%\)</span></strong> (formato obrigatório da Aula 4: média <span class="math inline">\(\pm\)</span> desvio).</p>
</div>
<div class="fragment">
<p>Split único de teste: <span class="math inline">\(75{,}2\%\)</span> — perto do <strong>topo</strong> da faixa dos <span class="math inline">\(5\)</span> folds (<span class="math inline">\(69{,}5\%\)</span>–<span class="math inline">\(75{,}5\%\)</span>). Não é “CV errada”: é um sorteio favorável de uma distribuição.</p>
</div>
<div class="fragment">
<p><strong>Bootstrap teste</strong> (modelo fixo): incerteza de <em>medição</em> — IC<span class="math inline">\(_{95\%}=[69{,}0\%,81{,}0\%]\)</span>.</p>
</div>
<div class="fragment">
<p><strong>Bootstrap treino+reajuste</strong>: incerteza do <em>procedimento</em> — IC<span class="math inline">\(_{95\%}=[69{,}2\%,77{,}9\%]\)</span>. Perguntas relacionadas, <strong>não</strong> idênticas.</p>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>A média de CV (<span class="math inline">\(71{,}3\%\)</span>) ficou abaixo da acurácia do nosso split único de teste (<span class="math inline">\(75{,}2\%\)</span>). Isso significa que o split de teste foi “escolhido a dedo” ou está errado de algum jeito?</strong></p>
</div>
<div class="callout-content">
<p>Dica: pense na CV como cinco sorteios de uma distribuição, e o split de teste como um sexto sorteio independente da mesma distribuição.</p>
</div>
</div>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>CV, Split Único e o que “Discrepância” Significa</strong></p>
</div>
<div class="callout-content">
<ul>
<li>□ Se a acurácia do split único estivesse dentro da faixa observada nos cinco folds de CV, isso por si só já seria evidência de que o split de teste não foi selecionado de forma tendenciosa.</li>
<li>□ No limite em que o conjunto de teste tivesse infinitos pontos, a acurácia medida nele convergiria para o risco esperado verdadeiro <span class="math inline">\(R(\theta)\)</span>, e a distância entre essa acurácia e a média de CV desapareceria.</li>
<li>□ Numa pesquisa eleitoral por amostragem, duas pesquisas com metodologias igualmente corretas podem legitimamente divergir por alguns pontos percentuais só por acaso de amostragem — a mesma lógica estatística que explica a diferença entre CV e o split único desta aula.</li>
<li>□ Como a CV usa <span class="math inline">\(5\)</span> vezes mais “medições” do que um único split de teste, a média de CV é sempre mais próxima do risco esperado verdadeiro do que qualquer split único poderia ser, em qualquer amostra particular.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="cv-split-único-e-o-que-discrepância-significa-resposta" class="slide level2">
<h2>CV, Split Único e o que “Discrepância” Significa — Resposta</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Dica</strong></p>
</div>
<div class="callout-content">
<ul>
<li>✔ Estar dentro da faixa observada é compatível com “não foi escolhido a dedo” — é a assinatura de um sorteio comum, não incomum, da mesma distribuição de acurácias.</li>
<li>✔ Com teste infinito, a variância amostral do estimador de teste vai a zero, e ele converge para <span class="math inline">\(R(\theta)\)</span> — a mesma lógica de “mais dados, menos ruído” que explica o desvio-padrão da CV encolher com <span class="math inline">\(N\)</span> maior.</li>
<li>✔ Mesma mecânica estatística (ruído de amostragem finita produzindo divergência legítima entre estimativas igualmente válidas), fora do domínio de aprendizado de máquina.</li>
<li>✗ “Mais medições” reduz a variância da <em>média</em> de CV em relação a uma única medição, mas não torna a média de CV automaticamente mais próxima do risco verdadeiro <strong>nesta amostra particular</strong> — em qualquer sorteio específico, o número com menos ruído teórico ainda pode, por acaso, estar mais distante da verdade do que um número mais ruidoso.</li>
</ul>
</div>
</div>
</div>
<div class="fragment">
<p><strong>Voltando à pergunta:</strong> não, a discrepância é o comportamento esperado de dois sorteios independentes da mesma distribuição de acurácias — nenhum dos dois precisa estar “errado”.</p>
</div>
</section>
<section id="cv-abaixo-do-split-único-retomando" class="slide level2">
<h2>CV Abaixo do Split Único? — Retomando</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Dica</strong></p>
</div>
<div class="callout-content">
<div class="fragment">
<p><em>(Agora responda: o split de teste foi “escolhido a dedo”, ou é só ruído de amostragem?)</em></p>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="bloco-5-síntese-as-quatro-peças-uma-estrutura" class="title-slide slide level1 center">
<h1>Bloco 5 — Síntese: As Quatro Peças, Uma Estrutura</h1>

</section>
<section id="o-mapa-completo" class="slide level2">
<h2>O Mapa Completo</h2>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Distribuição</th>
<th>Verossimilhança</th>
<th>Decisão/Risco</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Aula 1</td>
<td>Beta por classe</td>
<td>log-momentos (sem forma fechada)</td>
<td>cruzamento das conjuntas</td>
</tr>
<tr class="even">
<td>Aula 2</td>
<td>Gaussiana (<span class="math inline">\(\Sigma\)</span> diag./plena)</td>
<td><span class="math inline">\(\prod_i p(x_i\mid\mathcal{C}_k)\)</span></td>
<td>risco posterior <span class="math inline">\(\rho(a\mid x)\)</span></td>
</tr>
<tr class="odd">
<td>Aula 3</td>
<td>categórica por folha</td>
<td>MLE <span class="math inline">\(=-N_\tau H(\hat p_\tau)\)</span></td>
<td>partição greedy por IG</td>
</tr>
<tr class="even">
<td>Aula 4</td>
<td>amostra i.i.d. de <span class="math inline">\(P(X,Y)\)</span></td>
<td><span class="math inline">\(\hat R(\theta)\)</span> por fold/réplica</td>
<td><span class="math inline">\(R(\theta)\)</span> estimado, não observado</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p><strong>A coluna do meio se disfarça:</strong> “minimizar entropia” e “minimizar soma de quadrados” <strong>são</strong> maximizar verossimilhança.</p>
</div>
<div class="fragment">
<p><strong>Cuidado de notação:</strong> <span class="math inline">\(k\)</span> <span class="math inline">\(=\)</span> índice de classe (Aulas 1–3) <span class="math inline">\(\ne\)</span> <span class="math inline">\(k\)</span> <span class="math inline">\(=\)</span> número de <em>folds</em> (Aula 4). <span class="math inline">\(\lambda\)</span>/custo <span class="math inline">\(=\)</span> multiplicador de custo assimétrico (Aula 2) <span class="math inline">\(\ne\)</span> penalidade de custo-complexidade (Aulas 3–4). Colisão de símbolos, não erro — mas vale nomear.</p>
</div>
<div class="fig-resize" style="width: 100%; margin: 0 auto;">
<img data-src="index_files/mediabag/905e36bbe8cd3a985c3d8a69065832b29cb7bae6.svg" class="img-fluid">
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>A Aula 6 vai construir regressão linear com sua própria distribuição, verossimilhança e decisão. Isso significa que regressão linear “é a mesma coisa” que uma árvore de decisão, só escrita com notação diferente?</strong></p>
</div>
<div class="callout-content">
<p>Dica: pense na diferença entre “usar os mesmos ingredientes” e “fazer o mesmo prato”.</p>
</div>
</div>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Mesma Estrutura, Técnicas Diferentes</strong></p>
</div>
<div class="callout-content">
<ul>
<li>□ Se dois algoritmos compartilham a mesma estrutura de três peças (distribuição, verossimilhança, decisão), isso implica que eles vão sempre produzir a mesma fronteira de decisão sobre o mesmo dado.</li>
<li>□ No limite em que a distribuição assumida por um modelo está completamente errada (por exemplo, assumir Beta quando os dados são multimodais e não têm nada a ver com Beta), a etapa de verossimilhança ainda maximiza alguma coisa, mas o resultado da etapa de decisão pode ser sistematicamente ruim, mesmo com a maximização executada “corretamente”.</li>
<li>□ Um estudante que aprende primeiro a estrutura de três peças desta aula, antes de ver o algoritmo específico de regressão linear na Aula 6, deveria ser capaz de prever que existirá algo desempenhando o papel de “distribuição assumida” ali também — mesmo sem ainda saber qual é.</li>
<li>□ Como as quatro aulas revisadas hoje compartilham a mesma estrutura de três peças, conclui-se que a escolha de qual distribuição assumir (Beta, Gaussiana, categórica, i.i.d. de <span class="math inline">\(P(X,Y)\)</span>) é um detalhe secundário que pouco afeta o resultado final de cada técnica.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="mesma-estrutura-técnicas-diferentes-resposta" class="slide level2">
<h2>Mesma Estrutura, Técnicas Diferentes — Resposta</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Dica</strong></p>
</div>
<div class="callout-content">
<ul>
<li>✗ Compartilhar a estrutura (três peças) não implica compartilhar a distribuição assumida, a forma da verossimilhança, ou a regra de decisão específica — os “ingredientes” são análogos, o “prato” final é diferente em cada aula.</li>
<li>✔ É exatamente o erro de “qual das três peças está errada?” citado desde o slide 1 do curso: a maximização pode estar tecnicamente correta e o resultado ainda ser ruim, porque a peça errada foi a suposição distributiva, não o processo de ajuste.</li>
<li>✔ Reconhecer a estrutura antes do conteúdo específico é a competência que esta aula pretende deixar — antecipar “vai existir uma peça assim” é, precisamente, o que significa ter entendido o padrão, não só as quatro instâncias dele.</li>
<li>✗ A escolha da distribuição assumida é, ao contrário, a peça que a Aula 1 chamou de “quase sempre a que está errada” quando um modelo falha — ela é central, não secundária, para o resultado final.</li>
</ul>
</div>
</div>
</div>
<div class="fragment">
<p><strong>Voltando à pergunta:</strong> mesmos ingredientes (distribuição, verossimilhança, decisão), pratos diferentes — reconhecer a receita não elimina a diferença entre os pratos.</p>
</div>
</section>
<section id="mesma-estrutura-retomando" class="slide level2">
<h2>Mesma Estrutura? — Retomando</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Dica</strong></p>
</div>
<div class="callout-content">
<div class="fragment">
<p><em>(Agora responda: compartilhar a estrutura torna as quatro técnicas intercambiáveis?)</em></p>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="fechamento" class="title-slide slide level1 center">
<h1>Fechamento</h1>

</section>
<section id="o-que-aprendemos-hoje" class="slide level2 scrollable">
<h2>O que Aprendemos Hoje</h2>
<ol type="1">
<li>Mesma estrutura de três peças em toda aula: <strong>distribuição <span class="math inline">\(\to\)</span> verossimilhança <span class="math inline">\(\to\)</span> decisão/risco</strong>.</li>
<li>“Qual é o formato dos dados?” reaparece como parâmetros de Beta, fatoração de independência, ou proporção categórica.</li>
<li>Maximizar verossimilhança <span class="math inline">\(=\)</span> minimizar impureza — identidade algébrica, não analogia (<span class="math inline">\(-N_\tau H(\hat p_\tau)\)</span>).</li>
<li><span class="math inline">\(R(\theta)\)</span> nunca é observado; CV simula amostragem repetida, Bootstrap quantifica a incerteza remanescente.</li>
</ol>
<div class="fragment">
<p><strong>Próxima aula:</strong> Regressão Linear — mínimos quadrados como máxima verossimilhança sob ruído gaussiano, o mesmo princípio agora sobre um modelo paramétrico contínuo.</p>
</div>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>UNICAMP — Instituto de Computação</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true,"boardmarkerWidth":3,"chalkWidth":3},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 800,

        // Factor of the display size that should remain empty around the content
        margin: 2.0e-2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <div class="custom-footer-logos">
      <a href="notas.html" class="back-arrow-slide" title="Voltar às notas" aria-label="Voltar às notas"><i class="bi bi-book-half" aria-hidden="true"></i></a>
      <img src="../../UNICAMP.png" alt="UNICAMP">
      <img src="../../IC.png" alt="Instituto de Computação">
    </div>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copiada");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copiada");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>