<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-BR" xml:lang="pt-BR"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Marcos M. Raimundo — Instituto de Computação, UNICAMP">

<title>Árvores de Decisão — Particionamento Guloso – Marcos M. Raimundo</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../more.png" rel="icon" type="image/png">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-de6b2afc8591517e0c1f78da07193c80.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Marcos M. Raimundo</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Procurar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Alternar de navegação" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../teaching/index.html"> 
<span class="menu-text">Teaching</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../projects/index.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../publications/index.html"> 
<span class="menu-text">Publications</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../people/index.html"> 
<span class="menu-text">People</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../contact.html"> 
<span class="menu-text">Contact</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/marcosmrai"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://scholar.google.com.br/citations?user=ibe0jfQAAAAJ&amp;hl=pt-BR"> <i class="bi bi-mortarboard-fill" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Nesta página</h2>
   
  <ul>
  <li><a href="#proposta-da-aula" id="toc-proposta-da-aula" class="nav-link active" data-scroll-target="#proposta-da-aula"><span class="header-section-number">1</span> Proposta da Aula</a>
  <ul class="collapse">
  <li><a href="#pergunta" id="toc-pergunta" class="nav-link" data-scroll-target="#pergunta"><span class="header-section-number">1.1</span> Pergunta</a></li>
  </ul></li>
  <li><a href="#árvores-como-estimação-não-paramétrica" id="toc-árvores-como-estimação-não-paramétrica" class="nav-link" data-scroll-target="#árvores-como-estimação-não-paramétrica"><span class="header-section-number">2</span> Árvores Como Estimação Não-Paramétrica</a>
  <ul class="collapse">
  <li><a href="#pergunta-1" id="toc-pergunta-1" class="nav-link" data-scroll-target="#pergunta-1"><span class="header-section-number">2.1</span> Pergunta</a></li>
  </ul></li>
  <li><a href="#árvores-de-regressão-verossimilhança-gaussiana" id="toc-árvores-de-regressão-verossimilhança-gaussiana" class="nav-link" data-scroll-target="#árvores-de-regressão-verossimilhança-gaussiana"><span class="header-section-number">3</span> Árvores de Regressão: Verossimilhança Gaussiana</a>
  <ul class="collapse">
  <li><a href="#crescimento-guloso-busca-exaustiva-por-variável-e-limiar" id="toc-crescimento-guloso-busca-exaustiva-por-variável-e-limiar" class="nav-link" data-scroll-target="#crescimento-guloso-busca-exaustiva-por-variável-e-limiar"><span class="header-section-number">3.1</span> Crescimento guloso: busca exaustiva por variável e limiar</a></li>
  <li><a href="#mais-folhas-melhor-ajuste-sempre-em-degraus" id="toc-mais-folhas-melhor-ajuste-sempre-em-degraus" class="nav-link" data-scroll-target="#mais-folhas-melhor-ajuste-sempre-em-degraus"><span class="header-section-number">3.2</span> Mais folhas, melhor ajuste — sempre em degraus</a></li>
  <li><a href="#pergunta-2" id="toc-pergunta-2" class="nav-link" data-scroll-target="#pergunta-2"><span class="header-section-number">3.3</span> Pergunta</a></li>
  <li><a href="#o-algoritmo" id="toc-o-algoritmo" class="nav-link" data-scroll-target="#o-algoritmo"><span class="header-section-number">3.4</span> O Algoritmo</a></li>
  <li><a href="#pergunta-3" id="toc-pergunta-3" class="nav-link" data-scroll-target="#pergunta-3"><span class="header-section-number">3.5</span> Pergunta</a></li>
  </ul></li>
  <li><a href="#teoria-da-informação-medindo-probabilidade" id="toc-teoria-da-informação-medindo-probabilidade" class="nav-link" data-scroll-target="#teoria-da-informação-medindo-probabilidade"><span class="header-section-number">4</span> Teoria da Informação: Medindo Probabilidade</a>
  <ul class="collapse">
  <li><a href="#entropia-quanto-uma-distribuição-surpreende" id="toc-entropia-quanto-uma-distribuição-surpreende" class="nav-link" data-scroll-target="#entropia-quanto-uma-distribuição-surpreende"><span class="header-section-number">4.1</span> Entropia: Quanto uma Distribuição Surpreende</a></li>
  <li><a href="#entropia-condicional-o-que-sobra-depois-de-observar" id="toc-entropia-condicional-o-que-sobra-depois-de-observar" class="nav-link" data-scroll-target="#entropia-condicional-o-que-sobra-depois-de-observar"><span class="header-section-number">4.2</span> Entropia Condicional: o que Sobra Depois de Observar</a></li>
  <li><a href="#informação-mútua" id="toc-informação-mútua" class="nav-link" data-scroll-target="#informação-mútua"><span class="header-section-number">4.3</span> Informação Mútua</a></li>
  <li><a href="#o-ganho-de-informação-da-aula-2-é-informação-mútua" id="toc-o-ganho-de-informação-da-aula-2-é-informação-mútua" class="nav-link" data-scroll-target="#o-ganho-de-informação-da-aula-2-é-informação-mútua"><span class="header-section-number">4.4</span> O Ganho de Informação da Aula 2 é Informação Mútua</a></li>
  <li><a href="#quem-diz-mais-sobre-a-classe" id="toc-quem-diz-mais-sobre-a-classe" class="nav-link" data-scroll-target="#quem-diz-mais-sobre-a-classe"><span class="header-section-number">4.5</span> Quem Diz Mais Sobre a Classe?</a></li>
  <li><a href="#pergunta-4" id="toc-pergunta-4" class="nav-link" data-scroll-target="#pergunta-4"><span class="header-section-number">4.6</span> Pergunta</a></li>
  </ul></li>
  <li><a href="#árvores-de-classificação-verossimilhança-categórica-entropia-e-gini" id="toc-árvores-de-classificação-verossimilhança-categórica-entropia-e-gini" class="nav-link" data-scroll-target="#árvores-de-classificação-verossimilhança-categórica-entropia-e-gini"><span class="header-section-number">5</span> Árvores de Classificação: Verossimilhança Categórica, Entropia e Gini</a>
  <ul class="collapse">
  <li><a href="#entropia-e-gini-mesmo-formato" id="toc-entropia-e-gini-mesmo-formato" class="nav-link" data-scroll-target="#entropia-e-gini-mesmo-formato"><span class="header-section-number">5.1</span> Entropia e Gini: mesmo formato</a></li>
  <li><a href="#um-contraexemplo-deliberado-por-que-não-usar-a-taxa-de-erro-bruta" id="toc-um-contraexemplo-deliberado-por-que-não-usar-a-taxa-de-erro-bruta" class="nav-link" data-scroll-target="#um-contraexemplo-deliberado-por-que-não-usar-a-taxa-de-erro-bruta"><span class="header-section-number">5.2</span> Um contraexemplo deliberado: por que não usar a taxa de erro bruta?</a></li>
  </ul></li>
  <li><a href="#custo-vs.-complexidade-a-poda-de-árvores" id="toc-custo-vs.-complexidade-a-poda-de-árvores" class="nav-link" data-scroll-target="#custo-vs.-complexidade-a-poda-de-árvores"><span class="header-section-number">6</span> Custo vs.&nbsp;Complexidade: a Poda de Árvores</a>
  <ul class="collapse">
  <li><a href="#critérios-de-parada-regularizar-enquanto-a-árvore-cresce" id="toc-critérios-de-parada-regularizar-enquanto-a-árvore-cresce" class="nav-link" data-scroll-target="#critérios-de-parada-regularizar-enquanto-a-árvore-cresce"><span class="header-section-number">6.1</span> Critérios de Parada: Regularizar Enquanto a Árvore Cresce</a></li>
  <li><a href="#poda-em-ação" id="toc-poda-em-ação" class="nav-link" data-scroll-target="#poda-em-ação"><span class="header-section-number">6.2</span> Poda em ação</a></li>
  <li><a href="#pergunta-5" id="toc-pergunta-5" class="nav-link" data-scroll-target="#pergunta-5"><span class="header-section-number">6.3</span> Pergunta</a></li>
  </ul></li>
  <li><a href="#limites-das-árvores" id="toc-limites-das-árvores" class="nav-link" data-scroll-target="#limites-das-árvores"><span class="header-section-number">7</span> Limites das Árvores</a>
  <ul class="collapse">
  <li><a href="#splits-alinhados-aos-eixos-podem-ser-muito-subótimos" id="toc-splits-alinhados-aos-eixos-podem-ser-muito-subótimos" class="nav-link" data-scroll-target="#splits-alinhados-aos-eixos-podem-ser-muito-subótimos"><span class="header-section-number">7.1</span> Splits alinhados aos eixos podem ser muito subótimos</a></li>
  <li><a href="#instabilidade-pequenas-mudanças-árvores-bem-diferentes" id="toc-instabilidade-pequenas-mudanças-árvores-bem-diferentes" class="nav-link" data-scroll-target="#instabilidade-pequenas-mudanças-árvores-bem-diferentes"><span class="header-section-number">7.2</span> Instabilidade: pequenas mudanças, árvores bem diferentes</a></li>
  <li><a href="#partição-rígida-previsões-descontínuas" id="toc-partição-rígida-previsões-descontínuas" class="nav-link" data-scroll-target="#partição-rígida-previsões-descontínuas"><span class="header-section-number">7.3</span> Partição rígida: previsões descontínuas</a>
  <ul class="collapse">
  <li><a href="#retomando-as-perguntas-de-abertura" id="toc-retomando-as-perguntas-de-abertura" class="nav-link" data-scroll-target="#retomando-as-perguntas-de-abertura">Retomando as perguntas de abertura</a></li>
  <li><a href="#ponte-para-a-aula-4" id="toc-ponte-para-a-aula-4" class="nav-link" data-scroll-target="#ponte-para-a-aula-4">Ponte para a Aula 4</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#exercícios" id="toc-exercícios" class="nav-link" data-scroll-target="#exercícios"><span class="header-section-number">8</span> Exercícios</a>
  <ul class="collapse">
  <li><a href="#questões-discursivas" id="toc-questões-discursivas" class="nav-link" data-scroll-target="#questões-discursivas"><span class="header-section-number">8.1</span> Questões discursivas</a></li>
  <li><a href="#questões-de-verdadeirofalso" id="toc-questões-de-verdadeirofalso" class="nav-link" data-scroll-target="#questões-de-verdadeirofalso"><span class="header-section-number">8.2</span> Questões de Verdadeiro/Falso</a></li>
  <li><a href="#aviso" id="toc-aviso" class="nav-link" data-scroll-target="#aviso"><span class="header-section-number">8.3</span> Aviso</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Outros formatos</h2><ul><li><a href="slides.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Árvores de Decisão — Particionamento Guloso</h1>
<p class="subtitle lead">Aula 3 — Fundamentos Estatísticos do Aprendizado Supervisionado</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor</div>
    <div class="quarto-title-meta-contents">
             <p>Marcos M. Raimundo — Instituto de Computação, UNICAMP </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Data de Publicação</div>
    <div class="quarto-title-meta-contents">
      <p class="date">30 de agosto de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><a href="slides.html" class="see-all" aria-label="Ver slides" title="Ver slides">Slides</a> <a href="../../../teaching/supervised-learning/index.html" class="see-all lesson-list-link" aria-label="Lista de aulas" title="Lista de aulas">Lista de aulas</a></p>
<section id="proposta-da-aula" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Proposta da Aula</h1>
<p>As Aulas 1 e 2 construíram uma família inteira de classificadores — gaussiano com covariância compartilhada, Naive Bayes — que compartilham uma escolha silenciosa: a <strong>forma</strong> da fronteira de decisão é fixada <em>antes</em> de qualquer dado ser observado. Se a suposição paramétrica é uma reta (ou um hiperplano), a fronteira será sempre uma reta, não importa o que os dados digam. Essa é a pergunta que abre a aula de hoje:</p>
<blockquote class="blockquote">
<p><strong>E se deixássemos os próprios dados decidirem a forma da fronteira, sem suposição paramétrica alguma?</strong></p>
</blockquote>
<p>A resposta é uma árvore de decisão: um modelo que particiona o espaço de entrada em regiões, guiado inteiramente pelos dados de treino, sem comprometer-se com nenhuma família de curvas antes de olhar para eles. A tentação é tratar essa ideia como pura heurística — “vá cortando o espaço até que fique homogêneo” — e é assim que a maioria dos cursos introduz o assunto. Esta aula argumenta o contrário: o critério que decide onde cortar é <strong>o mesmo princípio de máxima verossimilhança</strong> que já apareceu em cada aula deste curso, só que aplicado a um modelo diferente — não mais um modelo paramétrico fixo (uma reta, uma gaussiana), mas um modelo <strong>constante por partes</strong>, cuja forma nasce do próprio particionamento.</p>
<p>Três perguntas guiam o resto da aula:</p>
<ol type="1">
<li>O que, exatamente, uma árvore está estimando?</li>
<li>Por que a regra de “escolher o corte que reduz mais a impureza” é, por baixo do capô, uma maximização de verossimilhança?</li>
<li>Que preço se paga por essa liberdade — e é sempre um bom negócio?</li>
</ol>
<section id="pergunta" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="pergunta"><span class="header-section-number">1.1</span> Pergunta</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Se uma árvore não fixa nenhuma família paramétrica antes de ver os dados, ela está livre de qualquer suposição estrutural sobre o problema?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Volte à proposta desta aula antes de responder: “deixar os dados decidirem a forma” é o mesmo que “não assumir nada”?</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Dica
</div>
</div>
<div class="callout-body-container callout-body">
<p>Julgue V ou F — a questão só conta se acertar os 4 itens:</p>
<ul>
<li>□ Como a árvore deixa a partição emergir dos dados, ela está livre de qualquer suposição estrutural sobre o problema — a única suposição do curso até agora estava do lado dos modelos paramétricos das Aulas 1–2.</li>
<li>□ Se o critério de “corte que reduz mais a impureza” fosse mesmo uma heurística arbitrária, sem nenhuma conexão de verossimilhança por trás, ainda seria esperado, sem exigir explicação alguma, que ele coincidisse exatamente com o estimador de máxima verossimilhança para dois modelos probabilísticos diferentes (gaussiano e categórico) — como esta aula vai mostrar que coincide.</li>
<li>□ No caso limite em que a família paramétrica escolhida nas Aulas 1–2 (por exemplo, gaussiana com covariância compartilhada) já é exatamente a forma verdadeira da fronteira, ainda haveria alguma vantagem, mesmo pequena, em usar uma árvore no lugar dela.</li>
<li>□ Num problema de controle de qualidade industrial em que se sabe, por engenharia, que uma peça é defeituosa sempre que uma única medição de temperatura excede um limiar fixo já conhecido, há uma vantagem prática em ainda assim treinar uma árvore de decisão genérica em vez de simplesmente codificar essa regra conhecida.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="árvores-como-estimação-não-paramétrica" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Árvores Como Estimação Não-Paramétrica</h1>
<p>Uma árvore de decisão parte o espaço de entrada <span class="math inline">\(\mathcal{X}\)</span> em regiões retangulares, alinhadas aos eixos — cada corte fixa um limiar numa única variável. O resultado é uma coleção de regiões que, juntas, cobrem todo o espaço sem se sobrepor. Dentro de cada região, o modelo é o mais simples possível: uma <strong>constante</strong>. Em classificação, essa constante é a proporção (ou a classe majoritária) dos pontos de treino que caíram ali; em regressão, é a média dos alvos que caíram ali.</p>
<p>O processo de decidir, para um novo ponto <span class="math inline">\(\mathbf{x}\)</span>, a qual região ele pertence é sequencial: começa numa pergunta binária (“<span class="math inline">\(x_1 \le
\theta_1\)</span>?”), segue para a próxima pergunta dependendo da resposta, e assim por diante — exatamente a travessia de uma árvore binária, do nó raiz até uma folha.</p>
<div class="fig-resize" style="width: 80%; margin-left: -10%;">
<div id="99a0f9b0" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-3-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
<p>A árvore por trás dessa partição é a travessia que gera essas cinco regiões, cada corte testando uma única variável contra um limiar:</p>
<div class="fig-resize" style="width: 50%; margin: 0 auto;">
<img src="index_files/mediabag/8a79f1266794cedd5541567da907f6b24e9d925e.svg" class="img-fluid">
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Isto <strong>não</strong> é um modelo probabilístico gráfico
</div>
</div>
<div class="callout-body-container callout-body">
<p>Vale marcar essa fronteira de vocabulário desde já: uma árvore de decisão não representa uma distribuição de probabilidade conjunta com dependências entre variáveis, como as redes que aparecem em outras partes deste curso. Ela é, simplesmente, uma função — determinística, dado o treino — que mapeia <span class="math inline">\(\mathbf{x}\)</span> para uma região, e a região para uma constante.</p>
</div>
</div>
<p>Note a inversão de papéis em relação às Aulas 1–2: lá, <span class="math inline">\(\mathbf{x}\)</span> entrava numa fórmula fixa (gaussiana, produto de Bernoullis) cujos <em>parâmetros</em> eram estimados dos dados, mas cuja <em>forma funcional</em> era escolhida por nós, de antemão. Aqui, a própria forma — quantas regiões, onde ficam os cortes — é aprendida dos dados. Isso é, em sentido estrito, uma estimativa <strong>não-paramétrica</strong> de <span class="math inline">\(p(\mathcal{C}_k \mid
\mathbf{x})\)</span> (em classificação) ou de <span class="math inline">\(\mathbb{E}[t\mid\mathbf{x}]\)</span> (em regressão): não-paramétrica não porque não haja números para ajustar, mas porque o número de “parâmetros” efetivos (quantas regiões, com que forma) cresce com os próprios dados, em vez de ser fixado a priori.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Modelos generativos vs.&nbsp;preditivos
</div>
</div>
<div class="callout-body-container callout-body">
<p>Nas Aulas 1 e 2, o caminho até a decisão passava sempre pelo mesmo lugar: ajustar <span class="math inline">\(p(\mathbf{x}\mid\mathcal{C}_k)\)</span> para cada classe (a densidade condicional), multiplicar pela priori <span class="math inline">\(\pi_k\)</span>, e obter a posteriori <span class="math inline">\(p(\mathcal{C}_k\mid\mathbf{x})\)</span> pelo Teorema de Bayes. Chamamos esse caminho de <strong>modelo generativo</strong>: ele modela como os dados de cada classe são gerados, e a regra de decisão é uma consequência derivada desse modelo.</p>
<p>A árvore de decisão não faz isso. Em nenhum momento do procedimento existe uma densidade de <span class="math inline">\(\mathbf{x}\)</span> — nem geral, nem por classe. Cada folha estima diretamente a proporção de cada classe entre os pontos que caíram ali, <span class="math inline">\(\hat p(\mathcal{C}_k \mid \mathbf{x}\in\mathcal{R}_\tau) =
n_{\tau k}/N_\tau\)</span>: uma estimativa direta da <strong>posteriori</strong>, sem passar por uma densidade condicional de classe. É o primeiro modelo <strong>preditivo</strong> (ou discriminativo, em sentido amplo) do curso — ele aprende <span class="math inline">\(p(\mathcal{C}_k\mid\mathbf{x})\)</span> (ou <span class="math inline">\(\mathbb{E}[t\mid
\mathbf{x}]\)</span>, em regressão) diretamente, sem nunca modelar a distribuição de <span class="math inline">\(\mathbf{x}\)</span> pelo caminho.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Paramétrico vs.&nbsp;não-paramétrico, mais formalmente
</div>
</div>
<div class="callout-body-container callout-body">
<p>Um modelo é <strong>paramétrico</strong> quando é indexado por um vetor de parâmetros <span class="math inline">\(\theta \in \mathbb{R}^d\)</span> de dimensão <span class="math inline">\(d\)</span> <strong>fixa</strong>, escolhida antes de ver os dados e que não cresce com o tamanho da amostra <span class="math inline">\(N\)</span>. A gaussiana da Aula 1 (<span class="math inline">\(\theta=(\mu,\sigma^2)\)</span>, <span class="math inline">\(d=2\)</span>) e o Naive Bayes da Aula 2 são exemplos: por maior que seja <span class="math inline">\(N\)</span>, o número de parâmetros ajustados continua o mesmo.</p>
<p>Um modelo é <strong>não-paramétrico</strong> quando sua complexidade efetiva — o número de graus de liberdade que de fato se ajustam aos dados — cresce com <span class="math inline">\(N\)</span>, em vez de ser fixada a priori. Numa árvore, esse papel é desempenhado pelo número de folhas: nada impede, em princípio, que uma árvore sem limite de profundidade continue crescendo à medida que mais dados chegam, criando mais regiões e mais constantes locais. “Não-paramétrico” não significa “sem parâmetro nenhum” — significa que o <strong>número</strong> de parâmetros não está fixado de antemão.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Verossimilhança e o estimador de máxima verossimilhança (MLE)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dado um modelo probabilístico <span class="math inline">\(p(\mathbf{x}\mid\theta)\)</span> e uma amostra observada <span class="math inline">\(\mathcal{D}=\{\mathbf{x}_1,\dots,\mathbf{x}_N\}\)</span> i.i.d., a <strong>função de verossimilhança</strong> é a mesma expressão da densidade conjunta, mas vista como função de <span class="math inline">\(\theta\)</span> com os dados fixos: <span class="math display">\[
L(\theta; \mathcal{D}) = p(\mathcal{D}\mid\theta) = \prod_{n=1}^N
p(\mathbf{x}_n\mid\theta).
\]</span> Repare na inversão de papéis em relação a uma densidade comum: <span class="math inline">\(p(\mathbf{x}\mid\theta)\)</span> varia <span class="math inline">\(\mathbf{x}\)</span> com <span class="math inline">\(\theta\)</span> fixo; <span class="math inline">\(L(\theta;\mathcal{D})\)</span> varia <span class="math inline">\(\theta\)</span> com os dados fixos. O <strong>estimador de máxima verossimilhança</strong> (MLE) é o valor de <span class="math inline">\(\theta\)</span> que torna os dados observados os mais prováveis possível sob o modelo: <span class="math display">\[
\hat\theta_{\text{MLE}} = \arg\max_\theta L(\theta;\mathcal{D}) =
\arg\max_\theta \ln L(\theta;\mathcal{D}),
\]</span> usando o logaritmo (monótono crescente, não muda o <span class="math inline">\(\arg\max\)</span>) para trocar produtório por somatório.</p>
<p><strong>Exemplo canônico: a gaussiana.</strong> Para <span class="math inline">\(x_n \sim \mathcal{N}(\mu,
\sigma^2)\)</span> i.i.d., a log-verossimilhança é <span class="math inline">\(\ell(\mu,\sigma^2) =
-\frac{N}{2}\ln(2\pi\sigma^2) - \frac{1}{2\sigma^2}\sum_n(x_n-\mu)^2\)</span>. Maximizando em <span class="math inline">\(\mu\)</span> (com <span class="math inline">\(\sigma^2\)</span> fixo) obtém-se <span class="math inline">\(\hat\mu_{\text{MLE}}
= \bar{x}\)</span>, a média amostral; maximizando também em <span class="math inline">\(\sigma^2\)</span> obtém-se <span class="math inline">\(\hat\sigma^2_{\text{MLE}} = \frac{1}{N}\sum_n(x_n-\bar x)^2\)</span> — note o <span class="math inline">\(N\)</span> no denominador, não <span class="math inline">\(N-1\)</span>: o MLE da variância é <strong>enviesado</strong> para baixo em amostras finitas, um fato que reaparece quando estimadores de covariância forem discutidos mais adiante no curso.</p>
<p>Este é exatamente o mecanismo que o próximo bloco usa para justificar a média como previsão de uma folha de regressão — e a Seção seguinte repete o mesmo argumento para uma folha de classificação, só que com uma verossimilhança categórica em vez de gaussiana.</p>
</div>
</div>
<p>Os próximos dois blocos tratam, em sequência, do critério que decide <em>onde</em> colocar cada corte — primeiro em regressão, onde a álgebra é mais simples e a conexão com verossimilhança aparece de forma direta; depois em classificação, onde a mesma lógica se veste de “impureza”.</p>
<section id="pergunta-1" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="pergunta-1"><span class="header-section-number">2.1</span> Pergunta</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>O que muda, na prática, entre “escolher uma família de curvas” e “deixar a partição emergir dos dados”?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Julgue V ou F — a questão só conta se acertar os 4 itens:</p>
<ul>
<li>□ No limite em que o número de pontos de treino tende a infinito, tanto um modelo paramétrico corretamente especificado quanto uma árvore convergem para a fronteira verdadeira — mas o modelo paramétrico, por ter menos a estimar, tende a precisar de menos dados para chegar perto dela.</li>
<li>□ Se, em vez de uma família paramétrica de baixa dimensão, escolhêssemos uma família paramétrica muito flexível (por exemplo, um polinômio de grau altíssimo), a distinção entre “forma fixa” e “forma que emerge dos dados” desapareceria, já que ambas passam a se ajustar a quase qualquer formato.</li>
<li>□ Num problema de previsão de safra agrícola em que a relação entre chuva e produtividade é conhecida por seguir aproximadamente uma curva em forma de sino, escolher uma família paramétrica que já capture esse formato (em vez de uma árvore) tende a exigir menos dados para um bom ajuste.</li>
<li>□ Como uma árvore não assume nenhuma família paramétrica específica, conclui-se que ela nunca introduz nenhum viés sobre a forma da fronteira, ao contrário de um modelo paramétrico.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="árvores-de-regressão-verossimilhança-gaussiana" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Árvores de Regressão: Verossimilhança Gaussiana</h1>
<p>Comece pelo caso mais simples: um único alvo contínuo <span class="math inline">\(t\)</span>, e uma variável de entrada <span class="math inline">\(x\)</span>. Suponha que a partição do espaço já esteja dada — isto é, já sabemos quais pontos caem em qual região. A pergunta que sobra é: qual valor prever dentro de cada região?</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Duplo registro: intuição, depois formalismo
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Intuição.</strong> Se você tem um monte de números e precisa escolher <strong>um só</strong> para representar todos eles, minimizando o erro quadrático total, o candidato óbvio é a média. É basicamente o que se faz ao “resumir” um conjunto de medições.</p>
<p><strong>Formalismo.</strong> Isso não é só intuição — é a solução exata de um problema de otimização. Se <span class="math inline">\(\mathcal{R}_\tau\)</span> é uma região (folha) com <span class="math inline">\(N_\tau\)</span> pontos de treino e alvos <span class="math inline">\(t_n\)</span>, o valor <span class="math inline">\(y_\tau\)</span> que minimiza a soma de quadrados <span class="math display">\[
Q_\tau = \sum_{\mathbf{x}_n \in \mathcal{R}_\tau} (t_n - y_\tau)^2
\]</span> é exatamente a média amostral, <span class="math display">\[
y_\tau = \frac{1}{N_\tau} \sum_{\mathbf{x}_n \in \mathcal{R}_\tau} t_n .
\]</span> (Derivada de <span class="math inline">\(Q_\tau\)</span> em relação a <span class="math inline">\(y_\tau\)</span>, igualada a zero — o mesmo argumento de mínimos quadrados de sempre.)</p>
</div>
</div>
<p>Até aqui, nada novo: “minimizar soma de quadrados” é a receita que todo mundo já usou. O ponto central deste bloco é outro: <strong>essa receita é, ela mesma, uma maximização de verossimilhança</strong> — e não por acaso, é a mesma equivalência entre mínimos quadrados e máxima verossimilhança que a Aula 5 vai formalizar para hiperplanos, aqui aplicada a um modelo bem mais simples: uma constante por folha.</p>
<p>Suponha que, dentro da folha <span class="math inline">\(\tau\)</span>, os alvos sigam um modelo gaussiano com média constante <span class="math inline">\(y_\tau\)</span> e variância compartilhada <span class="math inline">\(\sigma^2\)</span>: <span class="math display">\[
t_n \mid \mathbf{x}_n \in \mathcal{R}_\tau \;\sim\; \mathcal{N}(y_\tau,
\sigma^2).
\]</span> A log-verossimilhança dos <span class="math inline">\(N_\tau\)</span> pontos da folha, como função de <span class="math inline">\(y_\tau\)</span> (com <span class="math inline">\(\sigma^2\)</span> fixo), é <span class="math display">\[
\ell_\tau(y_\tau) = -\frac{N_\tau}{2}\ln(2\pi\sigma^2) -
\frac{1}{2\sigma^2} \sum_{\mathbf{x}_n \in \mathcal{R}_\tau} (t_n -
y_\tau)^2 .
\]</span></p>
<p>O caminho de <span class="math inline">\(\ell_\tau\)</span> até <span class="math inline">\(Q_\tau\)</span>, passo a passo, sem pular nada:</p>
<ol type="1">
<li><strong>Isole o que depende de <span class="math inline">\(y_\tau\)</span>.</strong> O primeiro termo, <span class="math inline">\(-\frac{N_\tau}{2}\ln(2\pi\sigma^2)\)</span>, não contém <span class="math inline">\(y_\tau\)</span> — é uma constante para efeito desta maximização (depende só de <span class="math inline">\(N_\tau\)</span> e do <span class="math inline">\(\sigma^2\)</span> fixado). Maximizar <span class="math inline">\(\ell_\tau(y_\tau)\)</span> é, portanto, o mesmo que maximizar só o segundo termo: <span class="math display">\[
\arg\max_{y_\tau} \ell_\tau(y_\tau) = \arg\max_{y_\tau}
\left[-\frac{1}{2\sigma^2} \sum_{\mathbf{x}_n \in \mathcal{R}_\tau}
(t_n - y_\tau)^2\right].
\]</span></li>
<li><strong>Troque o sinal.</strong> <span class="math inline">\(\frac{1}{2\sigma^2}\)</span> é uma constante <strong>positiva</strong>. Maximizar <span class="math inline">\(-\frac{1}{2\sigma^2}\cdot(\text{algo})\)</span> equivale a minimizar esse “algo” (multiplicar por um número negativo inverte quem é máximo e quem é mínimo). Logo: <span class="math display">\[
\arg\max_{y_\tau} \ell_\tau(y_\tau) = \arg\min_{y_\tau}
\sum_{\mathbf{x}_n \in \mathcal{R}_\tau} (t_n - y_\tau)^2 =
\arg\min_{y_\tau} Q_\tau(y_\tau).
\]</span> Este é o elo central: <strong>maximizar a verossimilhança gaussiana e minimizar a soma de quadrados são, literalmente, o mesmo problema de otimização</strong> — não duas ideias parecidas, a mesma conta.</li>
<li><strong>Resolva o mínimo.</strong> Derive <span class="math inline">\(Q_\tau\)</span> em relação a <span class="math inline">\(y_\tau\)</span> e iguale a zero: <span class="math display">\[
\frac{dQ_\tau}{dy_\tau} = -2\sum_{\mathbf{x}_n \in \mathcal{R}_\tau}
(t_n - y_\tau) = 0 \;\Longrightarrow\; \sum_{\mathbf{x}_n \in
\mathcal{R}_\tau} t_n = N_\tau\, y_\tau \;\Longrightarrow\; y_\tau =
\frac{1}{N_\tau}\sum_{\mathbf{x}_n \in \mathcal{R}_\tau} t_n .
\]</span> A mesma média amostral do argumento puramente geométrico do início do bloco — só que agora chegamos lá partindo de uma suposição probabilística explícita sobre os dados, não de uma escolha arbitrária de função de perda.</li>
</ol>
<p>A verificação abaixo confirma isso numericamente, com dados simulados: testamos vários candidatos para <span class="math inline">\(y_\tau\)</span> e mostramos que o máximo da log-verossimilhança bate exatamente com a média amostral.</p>
<div id="6ef06303" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Verificação: MLE gaussiano numa folha == minimizar soma de quadrados</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>t_folha <span class="op">=</span> rng.normal(<span class="fl">5.0</span>, <span class="fl">2.0</span>, size<span class="op">=</span><span class="dv">15</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> loglik_gauss(t, y, sigma2):</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    N <span class="op">=</span> <span class="bu">len</span>(t)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">-</span><span class="fl">0.5</span> <span class="op">*</span> N <span class="op">*</span> np.log(<span class="dv">2</span> <span class="op">*</span> np.pi <span class="op">*</span> sigma2) <span class="op">-</span> np.<span class="bu">sum</span>((t <span class="op">-</span> y) <span class="op">**</span> <span class="dv">2</span>) <span class="op">/</span> (<span class="dv">2</span> <span class="op">*</span> sigma2)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>y_hat <span class="op">=</span> t_folha.mean()</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>sigma2_fixo <span class="op">=</span> t_folha.var()</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>candidatos <span class="op">=</span> np.linspace(y_hat <span class="op">-</span> <span class="dv">2</span>, y_hat <span class="op">+</span> <span class="dv">2</span>, <span class="dv">9</span>)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> y <span class="kw">in</span> candidatos:</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    marca <span class="op">=</span> <span class="st">"  &lt;-- máximo"</span> <span class="cf">if</span> np.isclose(y, y_hat, atol<span class="op">=</span><span class="fl">0.3</span>) <span class="cf">else</span> <span class="st">""</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"y_tau=</span><span class="sc">{</span>y<span class="sc">:6.3f}</span><span class="ss">   loglik=</span><span class="sc">{</span>loglik_gauss(t_folha, y, sigma2_fixo)<span class="sc">:8.3f}{</span>marca<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">média amostral (y_hat) = </span><span class="sc">{</span>y_hat<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>y_tau= 2.116   loglik= -39.336
y_tau= 2.616   loglik= -35.342
y_tau= 3.116   loglik= -32.490
y_tau= 3.616   loglik= -30.778
y_tau= 4.116   loglik= -30.207  &lt;-- máximo
y_tau= 4.616   loglik= -30.778
y_tau= 5.116   loglik= -32.490
y_tau= 5.616   loglik= -35.342
y_tau= 6.116   loglik= -39.336

média amostral (y_hat) = 4.116</code></pre>
</div>
</div>
<p>O máximo da verossimilhança e a média amostral coincidem, como esperado: <strong>prever a média em cada folha não é uma convenção arbitrária — é o estimador de máxima verossimilhança sob um modelo gaussiano com variância compartilhada.</strong></p>
<section id="crescimento-guloso-busca-exaustiva-por-variável-e-limiar" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="crescimento-guloso-busca-exaustiva-por-variável-e-limiar"><span class="header-section-number">3.1</span> Crescimento guloso: busca exaustiva por variável e limiar</h2>
<p>Se a partição do espaço já está dada, calcular o <span class="math inline">\(y_\tau\)</span> ótimo em cada folha é trivial (é só tirar a média). O problema difícil é escolher a partição em si — quais variáveis cortar, com que limiares, em que ordem. Otimizar a estrutura inteira de uma árvore de uma só vez, mesmo com um número fixo de nós, é computacionalmente inviável: o número de estruturas possíveis explode combinatorialmente com o número de nós e de variáveis candidatas.</p>
<p>A saída prática é gulosa: comece com um único nó (toda a região de entrada), e cresça a árvore adicionando um par de folhas de cada vez. Para decidir o próximo corte, faça uma busca exaustiva sobre (a) qual variável cortar e (b) que limiar usar — para cada combinação candidata, calcule o <span class="math inline">\(Q_\tau\)</span> resultante nas duas folhas geradas, e escolha a combinação que resulta no menor <span class="math inline">\(Q\)</span> somado. A figura abaixo ilustra essa busca para uma única variável: percorrendo os candidatos a limiar, a soma de quadrados residual tem um mínimo bem definido.</p>
<div class="fig-resize" style="width: 70%; margin: 0 auto;">
<div id="4fd42482" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-7-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
<p>Repare que essa busca é míope por construção: ela escolhe o corte que minimiza <span class="math inline">\(Q\)</span> <strong>agora</strong>, sem olhar para o que esse corte habilita (ou impede) nos próximos níveis da árvore. O Bloco 4 volta a esse ponto.</p>
<p>Vamos agora crescer uma árvore de regressão de verdade sobre uma função mais complexa (uma senoide com ruído), variando o número de folhas permitido, para ver o que acontece quando a árvore cresce demais ou de menos.</p>
</section>
<section id="mais-folhas-melhor-ajuste-sempre-em-degraus" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="mais-folhas-melhor-ajuste-sempre-em-degraus"><span class="header-section-number">3.2</span> Mais folhas, melhor ajuste — sempre em degraus</h2>
<div class="fig-resize" style="width: 100%; margin: 0 auto;">
<div id="e63d191f" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-8-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
<p>Com poucas folhas, a árvore mal acompanha a curva; com mais folhas, ela aproxima bem — mas <strong>nunca deixa de ser uma função em degraus</strong>, descontínua nos limiares. Guarde essa observação: ela volta, como limitação estrutural, no Bloco 5.</p>
</section>
<section id="pergunta-2" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="pergunta-2"><span class="header-section-number">3.3</span> Pergunta</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Se duas folhas de uma árvore de regressão têm o mesmo número de pontos, a que tem maior soma de quadrados residuais <span class="math inline">\(Q_\tau\)</span> tem, necessariamente, maior variância dos alvos dentro dela?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Julgue V ou F — a questão só conta se acertar os 4 itens:</p>
<ul>
<li>□ No limite em que duas folhas têm exatamente a mesma variância mas números de pontos muito diferentes (uma com 10 pontos, outra com 10.000), a folha maior terá, necessariamente, <span class="math inline">\(Q_\tau\)</span> muito maior, mesmo com variância idêntica.</li>
<li>□ Se, em vez de comparar duas folhas com o mesmo <span class="math inline">\(N_\tau\)</span>, comparássemos duas folhas com <span class="math inline">\(N_\tau\)</span> diferentes, a folha de maior <span class="math inline">\(Q_\tau\)</span> ainda teria, necessariamente, maior variância amostral.</li>
<li>□ Ao comparar a dispersão de dois grupos de pacientes num estudo médico, um com 50 e outro com 500, a soma dos quadrados dos desvios (análoga a <span class="math inline">\(Q_\tau\)</span>) não é uma métrica justa para comparar “quão dispersos” os grupos são, a menos que se normalize pelo tamanho de cada grupo.</li>
<li>□ Como <span class="math inline">\(Q_\tau\)</span> e a variância amostral <span class="math inline">\(\hat\sigma^2=Q_\tau/N_\tau\)</span> diferem só por uma constante quando <span class="math inline">\(N_\tau\)</span> é fixo, conclui-se que minimizar <span class="math inline">\(Q_\tau\)</span> ao comparar candidatos de corte diferentes (que geram folhas de tamanhos diferentes) é equivalente a minimizar a variância média resultante.</li>
</ul>
</div>
</div>
</section>
<section id="o-algoritmo" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="o-algoritmo"><span class="header-section-number">3.4</span> O Algoritmo</h2>
<p>Tudo o que vimos até aqui — a média como previsão de folha, o <span class="math inline">\(Q_\tau\)</span> como critério, a busca exaustiva por um limiar — já é o suficiente para escrever o algoritmo por trás de qualquer árvore de regressão, por extenso:</p>
<blockquote class="blockquote">
<p><strong>Algoritmo — crescimento guloso de uma árvore de regressão</strong></p>
<ol type="1">
<li>Comece com uma única região <span class="math inline">\(\mathcal{R}_0\)</span>, contendo todos os pontos de treino.</li>
<li>Enquanto houver folhas elegíveis para corte (respeitando um critério de parada, como profundidade máxima ou número mínimo de pontos por folha):
<ol type="a">
<li>Para <strong>cada folha atual</strong> <span class="math inline">\(\mathcal{R}\)</span>, e para <strong>cada variável</strong> <span class="math inline">\(x_j\)</span>, teste todo limiar candidato <span class="math inline">\(s\)</span> (tipicamente, os pontos médios entre valores consecutivos de <span class="math inline">\(x_j\)</span> observados em <span class="math inline">\(\mathcal{R}\)</span>); calcule <span class="math inline">\(Q(\mathcal{R}, j, s) = \sum_{\mathcal{R}_{\text{esq}}}(t_n-\bar t_{\text{esq}})^2 + \sum_{\mathcal{R}_{\text{dir}}}(t_n-\bar t_{\text{dir}})^2\)</span>.</li>
<li>Escolha, entre <strong>todas</strong> as combinações (folha, variável, limiar) testadas, a que minimiza <span class="math inline">\(Q\)</span>.</li>
<li>Substitua essa folha por suas duas novas regiões.</li>
</ol></li>
<li>Pare quando nenhuma folha elegível reduzir <span class="math inline">\(Q\)</span> o suficiente, ou quando o critério de parada for atingido.</li>
</ol>
</blockquote>
<p>O ponto que costuma passar despercebido no passo 2: a busca não é “escolha o próximo corte dentro desta folha” — é uma busca <strong>entre todas as folhas atuais ao mesmo tempo</strong>. A cada rodada, o algoritmo pergunta “de todos os cortes possíveis, em qualquer folha, qual reduz mais o erro total?”, e só então corta ali. Isso é o que torna o crescimento <strong>guloso</strong>: a decisão de qual folha aprofundar, e não só onde cortar dentro dela, também é míope — feita rodada a rodada, sem enxergar o que essa escolha habilita (ou impede) adiante.</p>
<p>Vamos ver isso em ação, num dataset real de regressão: <strong>California Housing</strong> (preço mediano de imóveis por região censitária, a partir de 8 atributos contínuos — o mesmo dataset já usado em <code>optimization-linear-algebra</code> para outro fim). Dois cuidados de tratamento, feitos explicitamente antes de qualquer ajuste:</p>
<ul>
<li>Usamos só a partição de treino já separada no dataset (16.640 regiões), e dela sorteamos uma amostra de 500 pontos — o bastante para a árvore ter uma forma interessante, pequeno o bastante para cada conta caber numa tabela que se lê numa tela.</li>
<li>Para poder desenhar a partição em duas dimensões (e comparar diretamente com a figura de <span class="math inline">\(\theta_1,\dots,\theta_4\)</span> do início do bloco anterior), restringimos a busca a <strong>duas</strong> das oito variáveis: <code>MedInc</code> (renda mediana da região, em dezenas de milhares de dólares) e <code>HouseAge</code> (idade mediana dos imóveis, em anos). Uma árvore de produção buscaria sobre as oito; aqui a restrição é só didática, para manter a figura legível — o algoritmo em si não muda em nada.</li>
</ul>
<div id="d0f7cd7a" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Carrega o dataset real (California Housing) — primeira vez nesta aula</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> huggingface_hub.utils <span class="im">import</span> logging <span class="im">as</span> hf_logging</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>hf_logging.set_verbosity_error()</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> datasets <span class="im">import</span> disable_progress_bar</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>disable_progress_bar()</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> datasets <span class="im">import</span> load_dataset</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>_ch <span class="op">=</span> load_dataset(<span class="st">"gvlassis/california_housing"</span>)[<span class="st">"train"</span>].to_pandas()</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>amostra <span class="op">=</span> _ch.sample(n<span class="op">=</span><span class="dv">500</span>, random_state<span class="op">=</span><span class="dv">20260824</span>).reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>NOMES_VAR <span class="op">=</span> [<span class="st">"MedInc"</span>, <span class="st">"HouseAge"</span>]  <span class="co"># restrição didática: 2 das 8 variáveis</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>X_ch <span class="op">=</span> amostra[NOMES_VAR].values</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>t_ch <span class="op">=</span> amostra[<span class="st">"MedHouseVal"</span>].values  <span class="co"># preço mediano, em $100 mil</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>MIN_POR_FOLHA <span class="op">=</span> <span class="dv">10</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> melhor_corte(idx):</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Busca exaustiva do Algoritmo, passo 2a-2b, restrita a uma única folha."""</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>    Xr, tr <span class="op">=</span> X_ch[idx], t_ch[idx]</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>    melhor <span class="op">=</span> <span class="va">None</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(NOMES_VAR)):</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>        valores <span class="op">=</span> np.unique(Xr[:, j])</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>        limiares <span class="op">=</span> (valores[:<span class="op">-</span><span class="dv">1</span>] <span class="op">+</span> valores[<span class="dv">1</span>:]) <span class="op">/</span> <span class="dv">2</span></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> s <span class="kw">in</span> limiares:</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>            esq <span class="op">=</span> Xr[:, j] <span class="op">&lt;=</span> s</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>            n_esq, n_dir <span class="op">=</span> esq.<span class="bu">sum</span>(), (<span class="op">~</span>esq).<span class="bu">sum</span>()</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> n_esq <span class="op">&lt;</span> MIN_POR_FOLHA <span class="kw">or</span> n_dir <span class="op">&lt;</span> MIN_POR_FOLHA:</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>                <span class="cf">continue</span></span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>            te, td <span class="op">=</span> tr[esq], tr[<span class="op">~</span>esq]</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>            q <span class="op">=</span> np.<span class="bu">sum</span>((te <span class="op">-</span> te.mean())<span class="op">**</span><span class="dv">2</span>) <span class="op">+</span> np.<span class="bu">sum</span>((td <span class="op">-</span> td.mean())<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> melhor <span class="kw">is</span> <span class="va">None</span> <span class="kw">or</span> q <span class="op">&lt;</span> melhor[<span class="dv">0</span>]:</span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a>                melhor <span class="op">=</span> (q, j, s)</span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> melhor  <span class="co"># (Q após o corte, índice da variável, limiar)</span></span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Amostra: N=</span><span class="sc">{</span><span class="bu">len</span>(t_ch)<span class="sc">}</span><span class="ss"> pontos, variáveis=</span><span class="sc">{</span>NOMES_VAR<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Q da região inicial (raiz): </span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">sum</span>((t_ch <span class="op">-</span> t_ch.mean())<span class="op">**</span><span class="dv">2</span>)<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Amostra: N=500 pontos, variáveis=['MedInc', 'HouseAge']
Q da região inicial (raiz): 616.336</code></pre>
</div>
</div>
<p>O código acima <strong>é</strong> o algoritmo — não uma ilustração dele. <code>melhor_corte</code> implementa exatamente os passos 2a–2b para uma única região; o crescimento da árvore é só chamar essa função repetidamente, revisando todas as folhas abertas.</p>
<p><strong>Split 1 (a raiz).</strong> A primeira chamada de <code>melhor_corte</code> sobre a região inteira:</p>
<div id="e580f5e2" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>raiz <span class="op">=</span> np.arange(<span class="bu">len</span>(t_ch))</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>q1, j1, s1 <span class="op">=</span> melhor_corte(raiz)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Melhor corte da raiz: </span><span class="sc">{</span>NOMES_VAR[j1]<span class="sc">}</span><span class="ss"> &lt;= </span><span class="sc">{</span>s1<span class="sc">:.4f}</span><span class="ss">  (Q depois do corte: </span><span class="sc">{</span>q1<span class="sc">:.3f}</span><span class="ss">)"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Melhor corte da raiz: MedInc &lt;= 4.8973  (Q depois do corte: 410.254)</code></pre>
</div>
</div>
<div id="4b699364" class="cell" data-execution_count="11">
<div class="cell-output cell-output-stdout">
<pre><code>Esquerda (MedInc &lt;= 4.90): n=387, média=1.679, Q=261.555
Direita  (MedInc &gt;  4.90): n=113, média=3.214, Q=148.700</code></pre>
</div>
</div>
<p><strong>Splits 2 e 3 (os dois filhos da raiz, “o nível de baixo”).</strong> Em vez de escolher qual dos dois aprofundar primeiro, vamos cortar <strong>os dois</strong> — exatamente o passo 2 do algoritmo aplicado, em sequência, às duas folhas que acabaram de nascer:</p>
<div id="0fb5391b" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>q2, j2, s2 <span class="op">=</span> melhor_corte(idxL)   <span class="co"># melhor corte do filho esquerdo</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>q3, j3, s3 <span class="op">=</span> melhor_corte(idxR)   <span class="co"># melhor corte do filho direito</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Melhor corte de 'esquerda':  </span><span class="sc">{</span>NOMES_VAR[j2]<span class="sc">}</span><span class="ss"> &lt;= </span><span class="sc">{</span>s2<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Melhor corte de 'direita':   </span><span class="sc">{</span>NOMES_VAR[j3]<span class="sc">}</span><span class="ss"> &lt;= </span><span class="sc">{</span>s3<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Melhor corte de 'esquerda':  MedInc &lt;= 2.7162
Melhor corte de 'direita':   MedInc &lt;= 6.5004</code></pre>
</div>
</div>
<div id="f08d0bab" class="cell" data-execution_count="13">
<div class="cell-output cell-output-stdout">
<pre><code>LL: n=132, média=1.255, Q=42.094
LR: n=255, média=1.899, Q=183.423
RL: n= 75, média=2.782, Q=71.747
RR: n= 38, média=4.067, Q=35.302</code></pre>
</div>
</div>
<p>Depois dessas três chamadas, a árvore tem <strong>4 folhas</strong> (<code>LL</code>, <code>LR</code>, <code>RL</code>, <code>RR</code>) — uma na raiz, duas no nível de baixo. Falta a quarta chamada do enunciado: <strong>mais um corte, num nível abaixo desse</strong>. O algoritmo não escolhe isso arbitrariamente — ele testa <code>melhor_corte</code> nas quatro folhas atuais e compara a <strong>redução</strong> de <span class="math inline">\(Q\)</span> que cada uma ofereceria:</p>
<div id="88fd6362" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> nome, idx <span class="kw">in</span> folhas4.items():</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    q_antes <span class="op">=</span> resumo(idx)[<span class="st">"Q"</span>]</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    q_depois, j, s <span class="op">=</span> melhor_corte(idx)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>nome<span class="sc">}</span><span class="ss">: Q_antes=</span><span class="sc">{</span>q_antes<span class="sc">:7.3f}</span><span class="ss">  melhor corte=</span><span class="sc">{</span>NOMES_VAR[j]<span class="sc">}</span><span class="ss">&lt;= </span><span class="sc">{</span>s<span class="sc">:.4f}</span><span class="ss">"</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"  Q_depois=</span><span class="sc">{</span>q_depois<span class="sc">:7.3f}</span><span class="ss">  reducao=</span><span class="sc">{</span>q_antes<span class="op">-</span>q_depois<span class="sc">:7.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>LL: Q_antes= 42.094  melhor corte=MedInc&lt;= 1.7662  Q_depois= 38.476  reducao=  3.618
LR: Q_antes=183.423  melhor corte=HouseAge&lt;= 40.5000  Q_depois=165.814  reducao= 17.608
RL: Q_antes= 71.747  melhor corte=HouseAge&lt;= 35.5000  Q_depois= 51.701  reducao= 20.045
RR: Q_antes= 35.302  melhor corte=MedInc&lt;= 9.7356  Q_depois= 23.920  reducao= 11.382</code></pre>
</div>
</div>
<p>A folha <code>RL</code> vence — sua redução de <span class="math inline">\(Q\)</span> (<span class="math inline">\({\approx}20{,}0\)</span>) é quase o dobro da segunda colocada. É ali, e só ali, que o algoritmo corta na quarta rodada:</p>
<div id="0beb55db" class="cell" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>q4, j4, s4 <span class="op">=</span> melhor_corte(idxRL)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Split 4 (folha 'RL'): </span><span class="sc">{</span>NOMES_VAR[j4]<span class="sc">}</span><span class="ss"> &lt;= </span><span class="sc">{</span>s4<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Split 4 (folha 'RL'): HouseAge &lt;= 35.5000</code></pre>
</div>
</div>
<div id="b4e9e98a" class="cell" data-execution_count="16">
<div class="cell-output cell-output-stdout">
<pre><code>LL: n=132, média=1.255, Q=42.094
LR: n=255, média=1.899, Q=183.423
RR: n= 38, média=4.067, Q=35.302
RLa: n= 56, média=2.481, Q=28.514
RLb: n= 19, média=3.670, Q=23.187</code></pre>
</div>
</div>
<p>Chegamos exatamente à forma pedida: um corte na raiz, os dois filhos cortados, e mais um corte no nível seguinte — <strong>5 folhas</strong>, 4 cortes. A árvore e a partição do plano ficam assim:</p>
<div class="fig-resize" style="width: 70%; margin: 0 auto;">
<img src="index_files/mediabag/b934efd97d897e4fabd68ef55194bc968a0b9d43.svg" class="img-fluid">
</div>
<div class="fig-resize" style="width: 60%; margin: 0 auto;">
<div id="71a454ef" class="cell" data-execution_count="17">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-18-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
<p><strong>O quinto corte.</strong> Com 5 folhas abertas, o algoritmo repete o mesmo passo: testar <code>melhor_corte</code> em cada uma, e cortar onde a redução de <span class="math inline">\(Q\)</span> for maior.</p>
<div id="37575a40" class="cell" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> nome, idx <span class="kw">in</span> folhas5.items():</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>    resultado <span class="op">=</span> melhor_corte(idx)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    q_antes <span class="op">=</span> resumo(idx)[<span class="st">"Q"</span>]</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> resultado <span class="kw">is</span> <span class="va">None</span>:</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>nome<span class="sc">}</span><span class="ss">: sem corte válido (menos de </span><span class="sc">{</span><span class="dv">2</span><span class="op">*</span>MIN_POR_FOLHA<span class="sc">}</span><span class="ss"> pontos)"</span>)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">continue</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    q_depois, j, s <span class="op">=</span> resultado</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>nome<span class="sc">}</span><span class="ss">: Q_antes=</span><span class="sc">{</span>q_antes<span class="sc">:7.3f}</span><span class="ss">  melhor corte=</span><span class="sc">{</span>NOMES_VAR[j]<span class="sc">}</span><span class="ss">&lt;= </span><span class="sc">{</span>s<span class="sc">:.4f}</span><span class="ss">"</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"  Q_depois=</span><span class="sc">{</span>q_depois<span class="sc">:7.3f}</span><span class="ss">  reducao=</span><span class="sc">{</span>q_antes<span class="op">-</span>q_depois<span class="sc">:7.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>LL: Q_antes= 42.094  melhor corte=MedInc&lt;= 1.7662  Q_depois= 38.476  reducao=  3.618
LR: Q_antes=183.423  melhor corte=HouseAge&lt;= 40.5000  Q_depois=165.814  reducao= 17.608
RR: Q_antes= 35.302  melhor corte=MedInc&lt;= 9.7356  Q_depois= 23.920  reducao= 11.382
RLa: Q_antes= 28.514  melhor corte=MedInc&lt;= 5.5890  Q_depois= 24.486  reducao=  4.028
RLb: sem corte válido (menos de 20 pontos)</code></pre>
</div>
</div>
<div class="fig-resize" style="width: 55%; margin: 0 auto;">
<div id="84d7e242" class="cell" data-execution_count="19">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-20-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Vencedora: 'LR' — é ali que o quinto corte acontece.</code></pre>
</div>
</div>
</div>
<p><code>RLb</code>, com só 19 pontos, nem entra na disputa — não sobram <span class="math inline">\(2\times 10\)</span> pontos para dividir. Entre as quatro folhas restantes, <code>LR</code> vence com folga: tem o maior <span class="math inline">\(Q\)</span> inicial (é a folha mais numerosa, com 255 pontos) e ainda comporta uma redução grande, cortando por <code>HouseAge</code>. O quinto corte não acontece na folha mais “carente” (a de maior <span class="math inline">\(Q\)</span> resolveria a raiz de novo, por exemplo) nem na mais recém-criada — acontece onde a <strong>conta</strong> aponta o maior ganho, e só aí.</p>
<p>Essa é a mecânica completa por trás de cada divisão de uma árvore, do primeiro corte ao centésimo: nenhuma delas é definida por regra alguma que não seja “teste tudo, meça <span class="math inline">\(Q\)</span>, escolha o menor”. As seções seguintes trocam a variável contínua <span class="math inline">\(t\)</span> por uma variável categórica — o algoritmo continua sendo o mesmo; só o critério de comparação entre um corte e outro muda de soma de quadrados para impureza.</p>
</section>
<section id="pergunta-3" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="pergunta-3"><span class="header-section-number">3.5</span> Pergunta</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Por que o algoritmo escolhe cortar a folha <code>LR</code> no quinto passo, e não a folha com o maior <span class="math inline">\(Q\)</span> atual, nem a que acabou de nascer no quarto corte?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Escreva sua resposta e compare com um colega antes de avançar (2 min).</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Dica
</div>
</div>
<div class="callout-body-container callout-body">
<p>Julgue V ou F — a questão só conta se acertar os 4 itens:</p>
<ul>
<li>□ Se o critério fosse “sempre aprofundar a folha com mais pontos”, o quarto corte (a divisão de <code>RL</code>) não teria acontecido, pois <code>LL</code> (132 pontos) e <code>LR</code> (255 pontos) tinham mais pontos do que <code>RL</code> (113 pontos).</li>
<li>□ Se <code>RLb</code> tivesse exatamente <span class="math inline">\(2\times\text{MIN\_POR\_FOLHA}\)</span> pontos no total, isso já garantiria a existência de um limiar candidato válido para cortá-la.</li>
<li>□ Se a busca do quinto corte considerasse as 8 variáveis originais do California Housing em vez de só 2, a redução de <span class="math inline">\(Q\)</span> do vencedor jamais poderia ser menor do que a observada com 2 variáveis.</li>
<li>□ Como <code>LR</code> tinha o maior <span class="math inline">\(Q\)</span> inicial entre as cinco folhas e também venceu, conclui-se que, em geral, escolher a folha de maior <span class="math inline">\(Q\)</span> atual é equivalente a escolher a de maior redução possível.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="teoria-da-informação-medindo-probabilidade" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Teoria da Informação: Medindo Probabilidade</h1>
<p>Nas Aulas 1 e 2 construímos um vocabulário para relações entre variáveis aleatórias — conjunta <span class="math inline">\(p(x,y)\)</span>, condicional <span class="math inline">\(p(x\mid y)\)</span>, marginal <span class="math inline">\(p(x)\)</span>, independência (<span class="math inline">\(p(x,y)=p(x)p(y)\)</span>), independência condicional. Esse vocabulário é <strong>qualitativo</strong>: diz <em>que tipo</em> de relação existe, mas não dá um número para “o quanto”. Duas perguntas ficaram sem resposta quantitativa: quanto uma distribuição é incerta? E quanto duas variáveis se afastam de ser independentes?</p>
<p>Teoria da informação responde as duas com a mesma ideia central: <strong>medir probabilidade em unidades de incerteza</strong>. É essa régua que a árvore de classificação vai usar, no bloco seguinte, para decidir onde cortar. Três perguntas guiam este bloco:</p>
<ol type="1">
<li>O que significa, formalmente, “uma distribuição é incerta”?</li>
<li>Quanto de incerteza sobre uma variável sobra depois de observar outra?</li>
<li>Como resumir, num único número, o quanto duas variáveis se afastam da independência?</li>
</ol>
<section id="entropia-quanto-uma-distribuição-surpreende" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="entropia-quanto-uma-distribuição-surpreende"><span class="header-section-number">4.1</span> Entropia: Quanto uma Distribuição Surpreende</h2>
<p>Comece por um único resultado <span class="math inline">\(x\)</span> de uma variável aleatória <span class="math inline">\(X\)</span>. Quanto mais improvável ele é, mais ele “surpreende” ao ser observado. Defina a <strong>surpresa</strong> (ou <em>informação</em>) de um resultado como</p>
<p><span class="math display">\[
s(x) = -\ln p(x).
\]</span></p>
<p>Um evento certo (<span class="math inline">\(p=1\)</span>) tem surpresa <span class="math inline">\(0\)</span>: não há nada a aprender ao observar o que já se sabia que ia acontecer. Um evento raro (<span class="math inline">\(p\to 0\)</span>) tem surpresa arbitrariamente grande. A <strong>entropia</strong> de <span class="math inline">\(X\)</span> é a surpresa média, ponderada pela própria distribuição — quanto, <em>em expectativa</em>, você aprende ao observar um valor de <span class="math inline">\(X\)</span>:</p>
<p><span class="math display">\[
H(X) = \mathbb{E}[s(X)] = -\sum_x p(x)\ln p(x).
\]</span></p>
<p>(Usamos logaritmo natural, medindo incerteza em <strong>nats</strong> — a mesma convenção que o Bloco 4 vai usar para a entropia de uma folha. A formulação clássica de Shannon usa <span class="math inline">\(\log_2\)</span>, medindo em <strong>bits</strong>; a única diferença é a escala, <span class="math inline">\(\ln 2 \approx 0{,}693\)</span> vezes menor em nats — nenhuma propriedade qualitativa muda com a base.)</p>
<p><span class="math inline">\(H(X)=0\)</span> quando <span class="math inline">\(X\)</span> é determinística (<span class="math inline">\(p(x)=1\)</span> para um único valor); é <strong>máxima</strong> quando <span class="math inline">\(X\)</span> é uniforme — a incerteza é maior quando nenhum resultado é favorecido. Para uma variável binária com <span class="math inline">\(p(X{=}1)=p\)</span>,</p>
<div id="7fae963d" class="cell" data-execution_count="21">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> H(p):</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Entropia (nats) de uma Bernoulli(p)."""</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> p <span class="kw">in</span> (<span class="dv">0</span>, <span class="dv">1</span>):</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="fl">0.0</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">-</span>(p <span class="op">*</span> np.log(p) <span class="op">+</span> (<span class="dv">1</span> <span class="op">-</span> p) <span class="op">*</span> np.log(<span class="dv">1</span> <span class="op">-</span> p))</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> p <span class="kw">in</span> [<span class="fl">0.001</span>, <span class="fl">0.10</span>, <span class="fl">0.30</span>, <span class="fl">0.50</span>, <span class="fl">0.70</span>, <span class="fl">0.90</span>, <span class="fl">0.999</span>]:</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"p=</span><span class="sc">{</span>p<span class="sc">:.3f}</span><span class="ss">   H(p)=</span><span class="sc">{</span>H(p)<span class="sc">:.4f}</span><span class="ss"> nats"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>p=0.001   H(p)=0.0079 nats
p=0.100   H(p)=0.3251 nats
p=0.300   H(p)=0.6109 nats
p=0.500   H(p)=0.6931 nats
p=0.700   H(p)=0.6109 nats
p=0.900   H(p)=0.3251 nats
p=0.999   H(p)=0.0079 nats</code></pre>
</div>
</div>
<p>A entropia cresce à medida que <span class="math inline">\(p\)</span> se aproxima de <span class="math inline">\(0{,}5\)</span> (máxima incerteza sobre o resultado de uma moeda honesta, <span class="math inline">\(H(0{,}5)=\ln 2
\approx 0{,}693\)</span> nats) e cai a zero nas bordas (resultado praticamente certo). Essa é a mesma curva côncava que vai reaparecer no Bloco 4, agora medindo a incerteza sobre a <strong>classe</strong> de um ponto numa folha — o vocabulário é idêntico, só a variável <span class="math inline">\(X\)</span> muda de “um resultado genérico” para “a classe <span class="math inline">\(\mathcal{C}_k\)</span>”.</p>
</section>
<section id="entropia-condicional-o-que-sobra-depois-de-observar" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="entropia-condicional-o-que-sobra-depois-de-observar"><span class="header-section-number">4.2</span> Entropia Condicional: o que Sobra Depois de Observar</h2>
<p>A entropia de uma única variável generaliza para um par <span class="math inline">\((X,Y)\)</span>: a <strong>entropia conjunta</strong> <span class="math inline">\(H(X,Y) = -\sum_{x,y} p(x,y)\ln p(x,y)\)</span> mede a incerteza sobre o par inteiro. A pergunta mais interessante, porém, é outra: <em>dado que já observei <span class="math inline">\(X\)</span>, quanta incerteza ainda resta sobre <span class="math inline">\(Y\)</span>?</em> Essa é a <strong>entropia condicional</strong>,</p>
<p><span class="math display">\[
H(Y\mid X) = \sum_x p(x)\, H(Y\mid X{=}x) = -\sum_{x,y} p(x,y)\ln
p(y\mid x).
\]</span></p>
<p>Ela obedece à <strong>regra da cadeia da entropia</strong> — o análogo, em incerteza, da regra do produto de probabilidades (<span class="math inline">\(p(x,y)=p(x)p(y\mid
x)\)</span>) que já vimos na Aula 1:</p>
<p><span class="math display">\[
H(X,Y) = H(X) + H(Y\mid X).
\]</span></p>
<p>A leitura: a incerteza sobre o par se decompõe em “incerteza sobre <span class="math inline">\(X\)</span>” mais “incerteza que sobra sobre <span class="math inline">\(Y\)</span>, uma vez que <span class="math inline">\(X\)</span> é conhecido”.</p>
<p><strong>Por que independência implica <span class="math inline">\(H(Y\mid X) = H(Y)\)</span>, passo a passo.</strong> Não é só intuição de que “conhecer <span class="math inline">\(X\)</span> não ajuda” — sai direto da definição:</p>
<ol type="1">
<li><strong>Independência (Aula 2)</strong> diz que <span class="math inline">\(p(y\mid x) = p(y)\)</span> para todo <span class="math inline">\(x,y\)</span>: a distribuição condicional de <span class="math inline">\(Y\)</span> dado <span class="math inline">\(X{=}x\)</span> é, literalmente, a mesma distribuição para qualquer <span class="math inline">\(x\)</span> — não muda com <span class="math inline">\(x\)</span>.</li>
<li>A entropia condicional num ponto fixo, <span class="math inline">\(H(Y\mid X{=}x) = -\sum_y
p(y\mid x)\ln p(y\mid x)\)</span>, depende só dessa distribuição. Como ela não muda com <span class="math inline">\(x\)</span> (passo 1), <span class="math inline">\(H(Y\mid X{=}x) = H(Y)\)</span> para <strong>todo</strong> <span class="math inline">\(x\)</span> — a mesma entropia, qualquer que seja o valor observado de <span class="math inline">\(X\)</span>.</li>
<li>Substituindo na definição de entropia condicional: <span class="math display">\[
H(Y\mid X) = \sum_x p(x)\, H(Y\mid X{=}x) = \sum_x p(x)\, H(Y) =
H(Y) \underbrace{\sum_x p(x)}_{=\,1} = H(Y),
\]</span> onde o último passo usa só a normalização da marginal de <span class="math inline">\(X\)</span>.</li>
</ol>
<p>Ou seja: <span class="math inline">\(H(Y\mid X)\)</span> é uma <strong>média ponderada</strong> de <span class="math inline">\(H(Y\mid X{=}x)\)</span> ao longo de <span class="math inline">\(x\)</span>; se todos os termos dessa média já valem <span class="math inline">\(H(Y)\)</span> (passo 2), a média inteira também vale <span class="math inline">\(H(Y)\)</span> — não há nada mais sutil por trás. No outro extremo, se <span class="math inline">\(Y\)</span> é uma função determinística de <span class="math inline">\(X\)</span>, <span class="math inline">\(H(Y\mid X{=}x)=0\)</span> para todo <span class="math inline">\(x\)</span> (dado <span class="math inline">\(x\)</span>, <span class="math inline">\(Y\)</span> fica sabido com certeza), então <span class="math inline">\(H(Y\mid X)=0\)</span> pelo mesmo argumento: observar <span class="math inline">\(X\)</span> elimina toda a incerteza sobre <span class="math inline">\(Y\)</span>.</p>
</section>
<section id="informação-mútua" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="informação-mútua"><span class="header-section-number">4.3</span> Informação Mútua</h2>
<p>Combine as duas ideias acima: <span class="math inline">\(H(Y)\)</span> é a incerteza original sobre <span class="math inline">\(Y\)</span>; <span class="math inline">\(H(Y\mid X)\)</span> é o que sobra depois de observar <span class="math inline">\(X\)</span>. A diferença é quanto <strong>observar <span class="math inline">\(X\)</span> reduziu</strong> a incerteza sobre <span class="math inline">\(Y\)</span> — isso é a <strong>informação mútua</strong>:</p>
<p><span class="math display">\[
I(X;Y) = H(Y) - H(Y\mid X) = H(X) - H(X\mid Y) = \sum_{x,y}
p(x,y)\,\ln\frac{p(x,y)}{p(x)\,p(y)}.
\]</span></p>
<p>(As três expressões são iguais — é só álgebra a partir da regra da cadeia acima; a simetria <span class="math inline">\(I(X;Y)=I(Y;X)\)</span> não é óbvia à primeira vista, mas cai direto dela.) A terceira forma é a que conecta diretamente à Aula 2: o termo dentro do logaritmo é exatamente a razão entre a conjunta verdadeira e a conjunta <em>que existiria se <span class="math inline">\(X,Y\)</span> fossem independentes</em> (<span class="math inline">\(p(x)p(y)\)</span>). Segue que</p>
<p><span class="math display">\[
I(X;Y) = 0 \iff p(x,y) = p(x)\,p(y) \text{ para todo } x,y \iff X, Y
\text{ são independentes.}
\]</span></p>
<p>Ou seja: <strong>independência (Aula 2) é exatamente o caso <span class="math inline">\(I(X;Y)=0\)</span></strong>, e a informação mútua é a régua que mede, em nats, o quanto uma conjunta observada se afasta desse caso. (Também vale <span class="math inline">\(I(X;Y)\geq 0\)</span> sempre — informação mútua nunca é negativa; a prova usa a desigualdade de Jensen sobre a concavidade do logaritmo e não é reproduzida aqui, mas o fato é usado livremente a partir de agora.)</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Por que “distância até a independência” e não literalmente uma distância
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(I(X;Y)\)</span> tem a forma de uma <strong>divergência de Kullback-Leibler</strong>, <span class="math inline">\(D_{KL}\big(p(x,y)\,\|\,p(x)p(y)\big)\)</span> — uma medida de quão diferente uma distribuição é de outra. Como toda KL, ela não é simétrica em suas duas entradas nem satisfaz a desigualdade triangular, então “distância” aqui é uma metáfora, não uma métrica no sentido formal. O que se mantém da metáfora: <span class="math inline">\(I=0\)</span> só quando as duas distribuições coincidem (a conjunta real e a conjunta sob independência), e <span class="math inline">\(I\)</span> cresce conforme elas se afastam.</p>
</div>
</div>
</section>
<section id="o-ganho-de-informação-da-aula-2-é-informação-mútua" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="o-ganho-de-informação-da-aula-2-é-informação-mútua"><span class="header-section-number">4.4</span> O Ganho de Informação da Aula 2 é Informação Mútua</h2>
<p>Vamos quantificar o próprio exemplo da Aula 2. Duas palavras de um e-mail, “grátis” (<span class="math inline">\(G\)</span>) e “ganhador” (<span class="math inline">\(W\)</span>), eram <strong>condicionalmente independentes dada a classe</strong> (<span class="math inline">\(\mathcal{C}=\text{spam}\)</span> ou <span class="math inline">\(\text{ham}\)</span>, <span class="math inline">\(\pi_{\text{spam}}=0{,}5\)</span>), com</p>
<p><span class="math display">\[
p(G{=}1\mid\text{spam})=0{,}85,\quad p(W{=}1\mid\text{spam})=0{,}60,
\qquad p(G{=}1\mid\text{ham})=0{,}03,\quad p(W{=}1\mid\text{ham})=0{,}02.
\]</span></p>
<p>Naquela aula, comparamos só a célula <span class="math inline">\((1,1)\)</span>: marginalizando a classe, <span class="math inline">\(p(G{=}1,W{=}1)=0{,}255\)</span> contra <span class="math inline">\(p(G{=}1)\,p(W{=}1)=0{,}136\)</span> se fossem independentes — evidência de que <span class="math inline">\(G\)</span> e <span class="math inline">\(W\)</span> são <strong>marginalmente dependentes</strong>, apesar de condicionalmente independentes dada a classe. Agora podemos ir além de uma célula e medir a dependência inteira, em nats, com <span class="math inline">\(I(G;W)\)</span>:</p>
<div id="95309c12" class="cell" data-execution_count="23">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>pi_spam <span class="op">=</span> <span class="fl">0.5</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>pG_spam, pW_spam <span class="op">=</span> <span class="fl">0.85</span>, <span class="fl">0.60</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>pG_ham,  pW_ham  <span class="op">=</span> <span class="fl">0.03</span>, <span class="fl">0.02</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> conjunta_dado_classe(pg, pw):</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> {(<span class="dv">1</span>,<span class="dv">1</span>): pg<span class="op">*</span>pw, (<span class="dv">1</span>,<span class="dv">0</span>): pg<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>pw), (<span class="dv">0</span>,<span class="dv">1</span>): (<span class="dv">1</span><span class="op">-</span>pg)<span class="op">*</span>pw, (<span class="dv">0</span>,<span class="dv">0</span>): (<span class="dv">1</span><span class="op">-</span>pg)<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>pw)}</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>j_spam <span class="op">=</span> conjunta_dado_classe(pG_spam, pW_spam)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>j_ham  <span class="op">=</span> conjunta_dado_classe(pG_ham, pW_ham)</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>conjunta <span class="op">=</span> {k: pi_spam<span class="op">*</span>j_spam[k] <span class="op">+</span> (<span class="dv">1</span><span class="op">-</span>pi_spam)<span class="op">*</span>j_ham[k] <span class="cf">for</span> k <span class="kw">in</span> j_spam}</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>pG1 <span class="op">=</span> conjunta[(<span class="dv">1</span>,<span class="dv">1</span>)] <span class="op">+</span> conjunta[(<span class="dv">1</span>,<span class="dv">0</span>)]</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>pW1 <span class="op">=</span> conjunta[(<span class="dv">1</span>,<span class="dv">1</span>)] <span class="op">+</span> conjunta[(<span class="dv">0</span>,<span class="dv">1</span>)]</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> H_lista(ps):</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">-</span><span class="bu">sum</span>(p<span class="op">*</span>np.log(p) <span class="cf">for</span> p <span class="kw">in</span> ps <span class="cf">if</span> p <span class="op">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>H_G, H_W <span class="op">=</span> H_lista([pG1, <span class="dv">1</span><span class="op">-</span>pG1]), H_lista([pW1, <span class="dv">1</span><span class="op">-</span>pW1])</span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>H_GW <span class="op">=</span> H_lista(conjunta.values())</span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>I_GW <span class="op">=</span> H_G <span class="op">+</span> H_W <span class="op">-</span> H_GW</span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"conjunta p(G,W) = </span><span class="sc">{</span> {k: <span class="bu">round</span>(v,<span class="dv">4</span>) <span class="cf">for</span> k,v <span class="kw">in</span> conjunta.items()} <span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"p(G=1)=</span><span class="sc">{</span>pG1<span class="sc">:.3f}</span><span class="ss">  p(W=1)=</span><span class="sc">{</span>pW1<span class="sc">:.3f}</span><span class="ss">  (produto se independentes: </span><span class="sc">{</span>pG1<span class="op">*</span>pW1<span class="sc">:.4f}</span><span class="ss">)"</span>)</span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"H(G)=</span><span class="sc">{</span>H_G<span class="sc">:.4f}</span><span class="ss">  H(W)=</span><span class="sc">{</span>H_W<span class="sc">:.4f}</span><span class="ss">  H(G,W)=</span><span class="sc">{</span>H_GW<span class="sc">:.4f}</span><span class="ss">  (nats)"</span>)</span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"I(G;W) = H(G)+H(W)-H(G,W) = </span><span class="sc">{</span>I_GW<span class="sc">:.4f}</span><span class="ss"> nats  (&gt; 0: confirma a dependência marginal)"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>conjunta p(G,W) = {(1, 1): 0.2553, (1, 0): 0.1847, (0, 1): 0.0547, (0, 0): 0.5053}
p(G=1)=0.440  p(W=1)=0.310  (produto se independentes: 0.1364)
H(G)=0.6859  H(W)=0.6191  H(G,W)=1.1644  (nats)
I(G;W) = H(G)+H(W)-H(G,W) = 0.1406 nats  (&gt; 0: confirma a dependência marginal)</code></pre>
</div>
</div>
<p><span class="math inline">\(I(G;W)\approx 0{,}14\)</span> nats confirma, com um único número, o que a Aula 2 já mostrava célula a célula: as duas palavras não são marginalmente independentes. Mas a pergunta mais relevante para uma árvore de decisão é outra — não “<span class="math inline">\(G\)</span> e <span class="math inline">\(W\)</span> dependem uma da outra?”, e sim <strong>“<span class="math inline">\(G\)</span> e <span class="math inline">\(W\)</span> dizem algo sobre a classe?”</strong>. É essa a pergunta que <span class="math inline">\(I(G;\mathcal{C})\)</span> e <span class="math inline">\(I(W;\mathcal{C})\)</span> respondem:</p>
</section>
<section id="quem-diz-mais-sobre-a-classe" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="quem-diz-mais-sobre-a-classe"><span class="header-section-number">4.5</span> Quem Diz Mais Sobre a Classe?</h2>
<div id="6a3eb434" class="cell" data-execution_count="25">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>H_G_dado_C <span class="op">=</span> pi_spam<span class="op">*</span>H_lista([pG_spam, <span class="dv">1</span><span class="op">-</span>pG_spam]) <span class="op">+</span> (<span class="dv">1</span><span class="op">-</span>pi_spam)<span class="op">*</span>H_lista([pG_ham, <span class="dv">1</span><span class="op">-</span>pG_ham])</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>H_W_dado_C <span class="op">=</span> pi_spam<span class="op">*</span>H_lista([pW_spam, <span class="dv">1</span><span class="op">-</span>pW_spam]) <span class="op">+</span> (<span class="dv">1</span><span class="op">-</span>pi_spam)<span class="op">*</span>H_lista([pW_ham, <span class="dv">1</span><span class="op">-</span>pW_ham])</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>I_G_C <span class="op">=</span> H_G <span class="op">-</span> H_G_dado_C</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>I_W_C <span class="op">=</span> H_W <span class="op">-</span> H_W_dado_C</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"I(G;C) = H(G) - H(G|C) = </span><span class="sc">{</span>I_G_C<span class="sc">:.4f}</span><span class="ss"> nats"</span>)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"I(W;C) = H(W) - H(W|C) = </span><span class="sc">{</span>I_W_C<span class="sc">:.4f}</span><span class="ss"> nats"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>I(G;C) = H(G) - H(G|C) = 0.4072 nats
I(W;C) = H(W) - H(W|C) = 0.2336 nats</code></pre>
</div>
</div>
<div class="fig-resize" style="width: 60%; margin: 0 auto;">
<div id="101d6f16" class="cell" data-execution_count="26">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-27-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
<p><span class="math inline">\(I(G;\mathcal{C})\approx 0{,}41\)</span> nats é quase o dobro de <span class="math inline">\(I(W;\mathcal{C})\approx 0{,}23\)</span> nats: “grátis” reduz mais a incerteza sobre spam/ham do que “ganhador” — apesar de <span class="math inline">\(W\)</span> ter, sozinha, <strong>menos</strong> entropia própria (<span class="math inline">\(H(W) &lt; H(G)\)</span>, ela já é mais previsível de saída). É exatamente esse tipo de comparação — quanto uma variável candidata reduz a incerteza sobre a classe — que o próximo bloco usa para escolher onde uma árvore de classificação corta: o critério tradicionalmente chamado de <strong>ganho de informação</strong> é, sem disfarce, <span class="math inline">\(I(\text{variável de corte}\,;\,\text{classe})\)</span>, calculado localmente dentro de cada nó.</p>
</section>
<section id="pergunta-4" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="pergunta-4"><span class="header-section-number">4.6</span> Pergunta</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Se uma variável candidata a corte tem entropia própria <span class="math inline">\(H(X)\)</span> baixa (ela já é bem previsível), isso garante que ela também é pouco informativa sobre a classe, <span class="math inline">\(I(X;\mathcal{C})\)</span> baixo?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Pense no exemplo de “ganhador” antes de responder.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Julgue V ou F — a questão só conta se acertar os 4 itens:
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>□ <span class="math inline">\(I(X;\mathcal{C})\)</span> nunca pode ser maior que <span class="math inline">\(H(X)\)</span>, porque não é possível reduzir mais incerteza sobre a classe do que a própria variável carrega.</li>
<li>□ Ter <span class="math inline">\(H(X)\)</span> baixo garante <span class="math inline">\(I(X;\mathcal{C})\)</span> baixo, já que uma variável pouco incerta não tem “espaço” para informar muito.</li>
<li>□ No exemplo de “grátis” e “ganhador”, <span class="math inline">\(H(W) &lt; H(G)\)</span> e ainda assim <span class="math inline">\(I(W;\mathcal{C}) &lt; I(G;\mathcal{C})\)</span> — a variável de entropia menor também informou menos sobre a classe, mas isso é coincidência do exemplo, não uma implicação geral.</li>
<li>□ <span class="math inline">\(I(X;\mathcal{C})=0\)</span> é compatível com <span class="math inline">\(H(X)\)</span> alto — por exemplo, se <span class="math inline">\(X\)</span> for uniforme e completamente independente da classe.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="árvores-de-classificação-verossimilhança-categórica-entropia-e-gini" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Árvores de Classificação: Verossimilhança Categórica, Entropia e Gini</h1>
<p>Em classificação, a folha não prevê um número — prevê uma distribuição sobre classes. Dentro da folha <span class="math inline">\(\tau\)</span>, com <span class="math inline">\(N_\tau\)</span> pontos de treino, seja <span class="math inline">\(n_{\tau k}\)</span> a contagem de pontos da classe <span class="math inline">\(k\)</span>. O modelo mais simples possível para essas contagens é categórico, com parâmetro <span class="math inline">\(p_{\tau k}\)</span> (a probabilidade de um ponto da folha pertencer à classe <span class="math inline">\(k\)</span>). A pergunta é a mesma do bloco anterior, só que para uma distribuição categórica: qual <span class="math inline">\(p_{\tau k}\)</span> maximiza a verossimilhança dos dados observados na folha?</p>
<div id="af391721" class="cell" data-execution_count="27">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Verificação: MLE categórico numa folha == proporção empírica</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>contagens <span class="op">=</span> [<span class="dv">7</span>, <span class="dv">3</span>]   <span class="co"># 7 pontos de uma classe, 3 de outra, numa folha</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>N_tau <span class="op">=</span> <span class="bu">sum</span>(contagens)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> loglik_categorica(contagens, p):</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>    n <span class="op">=</span> np.array(contagens, dtype<span class="op">=</span><span class="bu">float</span>)</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.<span class="bu">sum</span>(n <span class="op">*</span> np.log(p))</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>p_hat <span class="op">=</span> np.array(contagens) <span class="op">/</span> N_tau</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>candidatos_p <span class="op">=</span> [p_hat, [<span class="fl">0.5</span>, <span class="fl">0.5</span>], [<span class="fl">0.9</span>, <span class="fl">0.1</span>], [<span class="fl">0.6</span>, <span class="fl">0.4</span>], [<span class="fl">0.75</span>, <span class="fl">0.25</span>]]</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> p <span class="kw">in</span> candidatos_p:</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>    p <span class="op">=</span> np.array(p)</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"p=</span><span class="sc">{</span>p<span class="sc">}</span><span class="ss">   loglik=</span><span class="sc">{</span>loglik_categorica(contagens, p)<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">proporção empírica (p_hat) = </span><span class="sc">{</span>p_hat<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>p=[0.7 0.3]   loglik=-6.1086
p=[0.5 0.5]   loglik=-6.9315
p=[0.9 0.1]   loglik=-7.6453
p=[0.6 0.4]   loglik=-6.3247
p=[0.75 0.25]   loglik=-6.1727

proporção empírica (p_hat) = [0.7 0.3]</code></pre>
</div>
</div>
<p>De novo, o máximo bate exatamente com a proporção empírica <span class="math inline">\(\hat p_{\tau k} = n_{\tau k}/N_\tau\)</span> — o mesmo padrão do Bloco 2, agora para uma distribuição categórica em vez de gaussiana. A verificação numérica confirma o resultado, mas não mostra <em>por que</em> ele é verdadeiro — a derivação abaixo fecha essa lacuna, do mesmo jeito explícito usado no Bloco 2 para a média.</p>
<p>Suponha que, dentro da folha <span class="math inline">\(\tau\)</span>, a classe de cada ponto seja sorteada de forma i.i.d. de uma distribuição categórica com parâmetro <span class="math inline">\(p_\tau=(p_{\tau 1},\dots,p_{\tau K})\)</span>, sujeito a <span class="math inline">\(\sum_k p_{\tau
k}=1\)</span> (é um vetor de probabilidades, não <span class="math inline">\(K\)</span> números livres): <span class="math display">\[
y_n \mid \mathbf{x}_n\in\mathcal{R}_\tau \;\sim\; \text{Categórica}(p_\tau),
\qquad n=1,\dots,N_\tau .
\]</span> Cada ponto de classe <span class="math inline">\(k\)</span> contribui um fator <span class="math inline">\(p_{\tau k}\)</span> para a verossimilhança; agrupando os <span class="math inline">\(n_{\tau k}\)</span> pontos de cada classe, a log-verossimilhança da folha, como função de <span class="math inline">\(p_\tau\)</span>, é <span class="math display">\[
\ell_\tau(p_\tau) = \sum_{n=1}^{N_\tau} \ln p_{\tau,\, y_n} =
\sum_k n_{\tau k} \ln p_{\tau k} .
\]</span></p>
<p>O caminho de <span class="math inline">\(\ell_\tau\)</span> até <span class="math inline">\(\hat p_{\tau k}\)</span>, passo a passo, sem pular nada:</p>
<ol type="1">
<li><strong>Identifique a restrição.</strong> <span class="math inline">\(p_\tau\)</span> não pode ser maximizado livremente coordenada a coordenada — é um vetor de probabilidades, então <span class="math inline">\(\sum_k p_{\tau k}=1\)</span> é uma restrição que qualquer máximo precisa respeitar.</li>
<li><strong>Monte o Lagrangiano.</strong> Para maximizar <span class="math inline">\(\ell_\tau(p_\tau)\)</span> sujeito a essa restrição, introduza um multiplicador <span class="math inline">\(\lambda\)</span>: <span class="math display">\[
\mathcal{L}(p_\tau,\lambda) = \sum_k n_{\tau k}\ln p_{\tau k} +
\lambda\Big(1-\sum_k p_{\tau k}\Big).
\]</span></li>
<li><strong>Derive em relação a cada <span class="math inline">\(p_{\tau k}\)</span> e iguale a zero.</strong> <span class="math display">\[
\frac{\partial \mathcal{L}}{\partial p_{\tau k}} =
\frac{n_{\tau k}}{p_{\tau k}} - \lambda = 0
\;\Longrightarrow\; p_{\tau k} = \frac{n_{\tau k}}{\lambda} .
\]</span> Isso já mostra que o máximo é <strong>proporcional</strong> à contagem <span class="math inline">\(n_{\tau k}\)</span> — falta só fixar a constante de proporcionalidade <span class="math inline">\(1/\lambda\)</span>.</li>
<li><strong>Use a restrição para achar <span class="math inline">\(\lambda\)</span>.</strong> Substituindo <span class="math inline">\(p_{\tau
k}=n_{\tau k}/\lambda\)</span> em <span class="math inline">\(\sum_k p_{\tau k}=1\)</span>: <span class="math display">\[
\sum_k \frac{n_{\tau k}}{\lambda} = \frac{N_\tau}{\lambda} = 1
\;\Longrightarrow\; \lambda = N_\tau,
\]</span> e portanto <span class="math display">\[
\hat p_{\tau k} = \frac{n_{\tau k}}{N_\tau} ,
\]</span> exatamente a proporção empírica que a verificação numérica já confirmou — agora com a álgebra completa por trás.</li>
<li><strong>Substitua <span class="math inline">\(\hat p_\tau\)</span> de volta na log-verossimilhança.</strong> Usando <span class="math inline">\(n_{\tau k}=N_\tau\hat p_{\tau k}\)</span> (passo 4): <span class="math display">\[
\ell_\tau(\hat p_\tau) = \sum_k n_{\tau k}\ln \hat p_{\tau k} =
\sum_k N_\tau \hat p_{\tau k}\ln \hat p_{\tau k} = N_\tau \sum_k
\hat p_{\tau k}\ln \hat p_{\tau k} = -N_\tau\, H(\hat p_\tau),
\]</span> onde <span class="math inline">\(H(p)=-\sum_k p_k\ln p_k\)</span> é a <strong>entropia</strong> da distribuição de classes na folha (convenção padrão, com o sinal negativo) — o último passo é só a definição de <span class="math inline">\(H\)</span> aplicada a <span class="math inline">\(\hat p_\tau\)</span>, com o sinal trocado por causa do <span class="math inline">\(-\sum\)</span> da definição.</li>
</ol>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span>A conexão central da aula: impureza é log-verossimilhança de perfil
</div>
</div>
<div class="callout-body-container callout-body">
<p>A derivação acima mostra, sem atalho, que <span class="math display">\[
\textbf{maximizar a log-verossimilhança} \;\equiv\; \textbf{minimizar a
entropia da folha.}
\]</span></p>
<p>É exatamente esse o critério mais comum para decidir onde cortar uma árvore de classificação — só que costuma ser apresentado como “reduzir a impureza”, sem que a conexão com verossimilhança seja mencionada. Ela é a mesma equivalência do Bloco 2 (mínimos quadrados = MLE gaussiano), agora do lado categórico: lá, a restrição vinha de derivar <span class="math inline">\(Q_\tau\)</span> direto; aqui, veio de um Lagrangiano, porque <span class="math inline">\(p_\tau\)</span> vive num simplex, não em <span class="math inline">\(\mathbb{R}^K\)</span> livre — mas o padrão “log-verossimilhança maximizada tem uma forma fechada e reconhecível” é o mesmo.</p>
</div>
</div>
<p>O Bloco 4 (Teoria da Informação) já adiantou a peça que falta: a entropia <span class="math inline">\(H(\hat p_\tau)\)</span> de uma folha é a mesma entropia <span class="math inline">\(H(X)\)</span> definida ali, só que aplicada à variável “classe de um ponto sorteado da folha”. Isso permite escrever, com precisão, o que significa “reduzir a impureza ao cortar” — não é uma analogia, é a mesma informação mútua de novo. Para um candidato de corte <span class="math inline">\(s\)</span> no nó <span class="math inline">\(\tau\)</span>, que separa os <span class="math inline">\(N_\tau\)</span> pontos em <span class="math inline">\(N_{\text{esq}}\)</span> à esquerda e <span class="math inline">\(N_{\text{dir}}\)</span> à direita, o <strong>ganho de informação</strong> é</p>
<p><span class="math display">\[
IG(\tau, s) = H(\hat p_\tau) - \left[\frac{N_{\text{esq}}}{N_\tau}
H(\hat p_{\text{esq}}) + \frac{N_{\text{dir}}}{N_\tau}
H(\hat p_{\text{dir}})\right].
\]</span></p>
<p>Compare com a definição de informação mútua do Bloco 4, <span class="math inline">\(I(X;Y) = H(Y) - H(Y\mid X)\)</span>: o termo entre colchetes acima é exatamente <span class="math inline">\(H(\mathcal{C}\mid S)\)</span>, a entropia condicional da classe dado o <strong>indicador de lado do corte</strong> <span class="math inline">\(S\in\{\text{esq},\text{dir}\}\)</span>, calculada empiricamente nos <span class="math inline">\(N_\tau\)</span> pontos do nó. Logo</p>
<p><span class="math display">\[
IG(\tau, s) = I(S ; \mathcal{C}),
\]</span></p>
<p>a informação mútua entre “qual lado do corte <span class="math inline">\(s\)</span>” e a classe, <strong>localmente</strong>, dentro do nó <span class="math inline">\(\tau\)</span>. A busca gulosa dos Blocos 2–3 — “teste toda variável e limiar, escolha o que reduz mais o erro” — em classificação é, sem nenhuma metáfora, “teste toda variável e limiar, escolha o que <strong>maximiza a informação mútua com a classe</strong>”. É por isso que esse critério tem o nome que tem.</p>
<section id="entropia-e-gini-mesmo-formato" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="entropia-e-gini-mesmo-formato"><span class="header-section-number">5.1</span> Entropia e Gini: mesmo formato</h2>
<p>A entropia tem a forma que se espera de uma medida de incerteza:</p>
<div class="fig-resize" style="width: 65%; margin: 0 auto;">
<div id="93c0e4aa" class="cell" data-execution_count="28">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-29-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
<p>O <strong>índice de Gini</strong>, <span class="math inline">\(G(p) = \sum_k p_{\tau k}(1-p_{\tau k})\)</span>, tem uma interpretação própria, diferente da conexão com verossimilhança: é a probabilidade de errar ao classificar um ponto sorteado da folha usando um segundo rótulo, também sorteado independentemente segundo as mesmas proporções <span class="math inline">\(p_\tau\)</span> — um classificador aleatório “ingênuo”. Não é um estimador de máxima verossimilhança de forma tão direta quanto a entropia, mas compartilha o mesmo formato geral (zero nas bordas, máximo em <span class="math inline">\(p=0{,}5\)</span>) e é computacionalmente mais barato (sem logaritmo).</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Aviso</span>Aviso de leitura
</div>
</div>
<div class="callout-body-container callout-body">
<p>Uma formulação comum de “cross-entropy” para árvores é escrita, em algumas fontes, <strong>sem</strong> o sinal negativo — <span class="math inline">\(\sum_k p_{\tau k}\ln
p_{\tau k}\)</span> — e ainda assim descrita em prosa como tendo “máximo em <span class="math inline">\(p=0{,}5\)</span>”. Isso só é consistente se o sinal negativo padrão da entropia estiver implícito: a fórmula sem o sinal tem, na verdade, <strong>mínimo</strong> (mais negativo) em <span class="math inline">\(p=0{,}5\)</span>, e vale <span class="math inline">\(0\)</span> nas bordas — o oposto. Usamos aqui a convenção padrão (com o sinal), que é a única consistente com “impureza aumenta com incerteza” e com o gráfico acima.</p>
</div>
</div>
</section>
<section id="um-contraexemplo-deliberado-por-que-não-usar-a-taxa-de-erro-bruta" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="um-contraexemplo-deliberado-por-que-não-usar-a-taxa-de-erro-bruta"><span class="header-section-number">5.2</span> Um contraexemplo deliberado: por que não usar a taxa de erro bruta?</h2>
<p>A alternativa mais óbvia a entropia e Gini seria a taxa de erro de classificação em si — a fração de pontos mal classificados na folha, se prevermos sempre a classe majoritária. Ela é simples e intuitiva. O próximo exemplo mostra por que ela é uma escolha ruim para <em>crescer</em> a árvore, mesmo sendo aceitável para <em>podar</em>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Diagnóstico: dois splits, qual você prefere?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Um nó com 400 pontos de cada classe (800 no total) pode ser dividido de duas formas:</p>
<ul>
<li><strong>Split 1:</strong> folha esquerda com (300, 100), folha direita com (100,
<ol start="300" type="1">
<li>— ambas com 400 pontos.</li>
</ol></li>
<li><strong>Split 2:</strong> folha esquerda com (400, 200) — 600 pontos —, folha direita <strong>pura</strong>, com (0, 200) — 200 pontos.</li>
</ul>
<p>Antes de calcular: você acha que as duas opções têm a mesma qualidade, olhando só a taxa de erro de classificação?</p>
</div>
</div>
<div id="dadbe815" class="cell" data-execution_count="29">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> gini_idx(contagens):</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>    n <span class="op">=</span> <span class="bu">sum</span>(contagens)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>    p <span class="op">=</span> contagens[<span class="dv">0</span>] <span class="op">/</span> n</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="dv">2</span> <span class="op">*</span> p <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> p)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> entropia_idx(contagens):</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>    n <span class="op">=</span> <span class="bu">sum</span>(contagens)</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>    ps <span class="op">=</span> [c <span class="op">/</span> n <span class="cf">for</span> c <span class="kw">in</span> contagens <span class="cf">if</span> c <span class="op">&gt;</span> <span class="dv">0</span>]</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">-</span><span class="bu">sum</span>(p <span class="op">*</span> np.log(p) <span class="cf">for</span> p <span class="kw">in</span> ps)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> erro_classificacao(contagens):</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>    n <span class="op">=</span> <span class="bu">sum</span>(contagens)</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="dv">1</span> <span class="op">-</span> <span class="bu">max</span>(contagens) <span class="op">/</span> n</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> medida_ponderada(medida, esq, dir_):</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>    n_esq, n_dir <span class="op">=</span> <span class="bu">sum</span>(esq), <span class="bu">sum</span>(dir_)</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>    n <span class="op">=</span> n_esq <span class="op">+</span> n_dir</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (n_esq <span class="op">*</span> medida(esq) <span class="op">+</span> n_dir <span class="op">*</span> medida(dir_)) <span class="op">/</span> n</span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>pai <span class="op">=</span> (<span class="dv">400</span>, <span class="dv">400</span>)</span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>split1 <span class="op">=</span> ((<span class="dv">300</span>, <span class="dv">100</span>), (<span class="dv">100</span>, <span class="dv">300</span>))</span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>split2 <span class="op">=</span> ((<span class="dv">400</span>, <span class="dv">200</span>), (<span class="dv">0</span>, <span class="dv">200</span>))</span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a>H_pai, G_pai <span class="op">=</span> entropia_idx(pai), gini_idx(pai)</span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Nó pai: entropia=</span><span class="sc">{</span>H_pai<span class="sc">:.4f}</span><span class="ss">  gini=</span><span class="sc">{</span>G_pai<span class="sc">:.4f}</span><span class="ch">\n</span><span class="ss">"</span>)</span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-27"><a href="#cb27-27" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> nome, (esq, dir_) <span class="kw">in</span> [(<span class="st">"Split 1"</span>, split1), (<span class="st">"Split 2"</span>, split2)]:</span>
<span id="cb27-28"><a href="#cb27-28" aria-hidden="true" tabindex="-1"></a>    h_filhos <span class="op">=</span> medida_ponderada(entropia_idx, esq, dir_)</span>
<span id="cb27-29"><a href="#cb27-29" aria-hidden="true" tabindex="-1"></a>    g_filhos <span class="op">=</span> medida_ponderada(gini_idx, esq, dir_)</span>
<span id="cb27-30"><a href="#cb27-30" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>nome<span class="sc">}</span><span class="ss">: erro=</span><span class="sc">{</span>medida_ponderada(erro_classificacao, esq, dir_)<span class="sc">:.4f}</span><span class="ss">  "</span></span>
<span id="cb27-31"><a href="#cb27-31" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"gini=</span><span class="sc">{</span>g_filhos<span class="sc">:.4f}</span><span class="ss"> (ganho=</span><span class="sc">{</span>G_pai<span class="op">-</span>g_filhos<span class="sc">:.4f}</span><span class="ss">)  "</span></span>
<span id="cb27-32"><a href="#cb27-32" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"entropia=</span><span class="sc">{</span>h_filhos<span class="sc">:.4f}</span><span class="ss"> (IG=</span><span class="sc">{</span>H_pai<span class="op">-</span>h_filhos<span class="sc">:.4f}</span><span class="ss">)"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Nó pai: entropia=0.6931  gini=0.5000

Split 1: erro=0.2500  gini=0.3750 (ganho=0.1250)  entropia=0.5623 (IG=0.1308)
Split 2: erro=0.2500  gini=0.3333 (ganho=0.1667)  entropia=0.4774 (IG=0.2158)</code></pre>
</div>
</div>
<p>As duas opções têm <strong>exatamente a mesma</strong> taxa de erro de classificação ponderada (<span class="math inline">\(0{,}25\)</span>) — a métrica bruta é cega para a diferença entre elas. Mas Gini e entropia <strong>preferem o Split 2</strong> (valores menores nos filhos, ganhos maiores): <span class="math inline">\(IG(\text{Split 2})\approx0{,}216\)</span> nats contra <span class="math inline">\(IG(\text{Split 1})\approx0{,}131\)</span> nats — o Split 2 é o que mais reduz a incerteza sobre a classe, exatamente o que a Seção anterior definiu como informação mútua entre o corte e a classe. (A mesma leitura de “ganho” vale para o índice de Gini, mas ali é só uma diferença de impureza — a igualdade com informação mútua é uma propriedade só da entropia.) Ele produz uma folha perfeitamente pura, o que a taxa de erro bruta simplesmente não enxerga, porque só olha quem “ganha a maioria”, não o quão desequilibrada é essa maioria.</p>
<p>Isso explica a assimetria de uso: entropia e Gini são diferenciáveis e mais sensíveis à distribuição interna da folha, por isso são preferidas para <em>crescer</em> a árvore (o critério de otimização se beneficia de gradientes bem-comportados); a taxa de erro bruta, mais grosseira, é geralmente reservada para a fase de <em>poda</em> — assunto do próximo bloco.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Julgue V ou F: entropia, Gini e taxa de erro para crescer/podar árvores
</div>
</div>
<div class="callout-body-container callout-body">
<p>Julgue V ou F — a questão só conta se acertar os 4 itens:</p>
<ul>
<li>□ Se todas as decisões de corte usassem a taxa de erro bruta como critério de crescimento, o Split 2 do contraexemplo desta aula (folha direita pura) não teria vantagem alguma sobre o Split 1.</li>
<li>□ No limite em que uma folha tem uma única classe presente, o ganho de informação de um corte que produz duas folhas puras é igual à própria entropia do nó pai.</li>
<li>□ Num conjunto de diagnóstico médico com 95% de pacientes saudáveis e 5% doentes, o nó representando toda a base já tem entropia baixa mesmo sem nenhum corte, simplesmente pela composição das classes.</li>
<li>□ Como Gini e entropia têm o mesmo formato geral (zero nas bordas, máximo em <span class="math inline">\(p=0{,}5\)</span>), qualquer corte preferido pela entropia é necessariamente também preferido pelo Gini.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="custo-vs.-complexidade-a-poda-de-árvores" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Custo vs.&nbsp;Complexidade: a Poda de Árvores</h1>
<p>Todo modelo dos últimos blocos foi ajustado do mesmo jeito: cresça (ou ajuste) até que ele explique o treino o melhor possível. Isso é, em geral, uma péssima ideia — um modelo com liberdade suficiente (uma árvore sem limite de folhas é o exemplo mais literal) consegue reduzir o erro de treino a praticamente zero, memorizando peculiaridades daquela amostra específica em vez de captar o padrão que se repetiria em dados novos. O que se quer não é o modelo que erra menos <strong>no treino</strong>, é o que erra menos <strong>em dados que ele não viu</strong>. Essa tensão — entre o quanto um modelo se ajusta ao que já foi visto e o quanto ele generaliza — é o tema deste bloco, e reaparece, com nomes diferentes, em praticamente todo o resto do curso (regularização, seleção de modelo, o vício-variância da Aula 4). Em árvores, o nome que essa tensão ganha é <strong>custo-complexidade</strong>, e existem dois grandes grupos de mecanismo para enfrentá-la: limitar o crescimento <strong>enquanto</strong> a árvore é construída (os critérios de parada abaixo) ou deixá-la crescer livre e cortar de volta <strong>depois</strong> (a <strong>poda</strong>, o resto deste bloco).</p>
<section id="critérios-de-parada-regularizar-enquanto-a-árvore-cresce" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="critérios-de-parada-regularizar-enquanto-a-árvore-cresce"><span class="header-section-number">6.1</span> Critérios de Parada: Regularizar Enquanto a Árvore Cresce</h2>
<p>Antes de chegar à poda, vale nomear a forma mais direta — e mais usada na prática — de limitar uma árvore: um punhado de hiperparâmetros que restringem o crescimento nó a nó, à medida que o algoritmo guloso do Bloco 2 decide cada corte. Cada um limita um aspecto diferente da complexidade <span class="math inline">\(|T|\)</span> que aparece na fórmula de custo-complexidade abaixo — só que como uma restrição rígida, decidida antes de ver o resultado, em vez de uma penalidade suave decidida depois:</p>
<ul>
<li><strong>Altura máxima</strong> (<code>max_depth</code>): limita quantos cortes sucessivos separam a raiz de qualquer folha — ou seja, quantas perguntas a árvore pode fazer sobre um único ponto antes de decidir.</li>
<li><strong>Número mínimo de amostras por folha</strong> (<code>min_samples_leaf</code>): impede que uma folha final tenha poucos pontos — sem esse limite, a árvore pode literalmente criar uma folha por ponto (overfitting no extremo), e cada estimativa <span class="math inline">\(\hat\mu_\tau\)</span> ou <span class="math inline">\(\hat p_{\tau k}\)</span> passa a ter uma base amostral mínima garantida.</li>
<li><strong>Número mínimo de amostras para tentar um corte</strong> (<code>min_samples_split</code>): parecido, mas verificado <strong>antes</strong> de tentar dividir um nó — se o nó já tem poucos pontos, o algoritmo nem chega a avaliar candidatos a corte ali.</li>
<li><strong>Número máximo de folhas</strong> (<code>max_leaf_nodes</code>): limita diretamente <span class="math inline">\(|T|\)</span> — o mesmo termo de complexidade da fórmula de custo-complexidade a seguir, só que como teto fixo em vez de penalidade.</li>
<li><strong>Ganho mínimo de impureza para aceitar um corte</strong> (<code>min_impurity_decrease</code>): só aceita um corte se ele reduzir a impureza por pelo menos um valor fixo — é exatamente o critério “pare quando o próximo corte não ajudar muito” que o parágrafo a seguir mostra ser traiçoeiro.</li>
</ul>
<p>Todos esses critérios agem <strong>durante</strong> a construção, olhando só a decisão local de cada nó — por isso são chamados de <strong>pré-poda</strong> (<em>pre-pruning</em>), em contraste com a poda propriamente dita (<em>post-pruning</em>), que primeiro deixa a árvore crescer por completo e só depois decide o que cortar. O restante deste bloco mostra por que esse segundo caminho, mais caro computacionalmente, resolve um problema que nenhum critério de parada consegue resolver por conta própria — a miopia da busca gulosa:</p>
<p>O Bloco 2 já registrou uma faceta do problema: a busca gulosa decide cada corte olhando só o ganho imediato. Isso tem uma consequência prática incômoda para o último critério da lista acima (<code>min_impurity_decrease</code>) — <strong>empiricamente</strong>, é comum que nenhum dos cortes disponíveis produza uma redução significativa de erro, e ainda assim, algumas divisões depois, uma redução substancial apareça. Um critério de parada baseado só em “pare quando o próximo corte não ajudar muito” cortaria a árvore cedo demais, perdendo esses ganhos adiados — e o mesmo vale, em menor grau, para qualquer um dos outros critérios: um teto fixo (<code>max_depth</code>, <code>max_leaf_nodes</code>, …) é o mesmo valor para toda a árvore, mesmo que um ramo se beneficiasse de mais profundidade e outro, de menos.</p>
<p>A prática recomendada inverte a lógica: cresça uma árvore <strong>grande</strong> (baseada só no número de pontos por folha, sem se preocupar com overfitting), e <strong>depois</strong> pode de volta. A poda é guiada por um critério de custo-complexidade que soma o erro residual de todas as folhas (o <strong>custo</strong>, no sentido de quão mal a árvore se ajusta ao próprio treino) a uma penalidade proporcional ao <strong>número de folhas</strong> (a <strong>complexidade</strong>, no sentido de quantos graus de liberdade a árvore usa): <span class="math display">\[
C(T) = \underbrace{\sum_{\tau=1}^{|T|} Q_\tau(T)}_{\text{custo}} +
\underbrace{\lambda |T|}_{\text{complexidade}} .
\]</span> O parâmetro <span class="math inline">\(\lambda \ge 0\)</span> controla o trade-off: <span class="math inline">\(\lambda=0\)</span> não pena nada (a árvore completa, sem poda, sempre “vence” — puro custo, zero penalidade de complexidade); <span class="math inline">\(\lambda\)</span> grande pena fortemente árvores complexas, empurrando a poda para árvores bem menores. Não existe um <span class="math inline">\(\lambda\)</span> “correto” universal — o valor certo depende de quanto ruído há nos dados e de quantos pontos se tem para estimar cada folha, e por isso é escolhido empiricamente, não derivado de teoria.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>O que é um conjunto de validação, e por que separar os dados
</div>
</div>
<div class="callout-body-container callout-body">
<p>Até aqui, “treino” significava simplesmente “os dados usados para ajustar o modelo” — a média de uma folha, a proporção de classes, o próprio corte escolhido, tudo veio do treino. A partir deste bloco, precisamos de uma segunda fatia de dados com um papel bem diferente: o <strong>conjunto de validação</strong>, reservado desde o início e nunca usado para ajustar nada (nem um corte, nem a estimativa de uma folha) — só para medir, depois que a árvore já está pronta, o quão bem ela se sai.</p>
<p>A razão para separar os dois não é burocracia, é estatística: medir o erro de um modelo <strong>nos mesmos dados usados para ajustá-lo</strong> é uma estimativa <strong>otimista</strong> — inflada — do quão bem ele generaliza. O caso extremo é a própria árvore completa deste bloco: ela pode chegar a <span class="math inline">\(100\%\)</span> de acerto no treino (uma folha por ponto, se preciso), o que não diz nada sobre o desempenho em um dado novo. O conjunto de validação, por nunca ter influenciado o ajuste, dá uma estimativa honesta do erro de generalização — é o mesmo raciocínio que a Aula 4 desta disciplina generaliza para a escolha de qualquer hiperparâmetro de complexidade, não só o <span class="math inline">\(\lambda\)</span> de poda de uma árvore.</p>
<p>O que fazemos abaixo é a versão mais simples possível dessa ideia: uma única divisão treino/validação, <span class="math inline">\(60\%/40\%\)</span>, sorteada uma vez. Essa simplicidade tem um custo que só será tratado com o devido cuidado na <strong>Aula 4</strong> (Validação Cruzada e Bootstrap): uma única divisão desperdiça dados (os <span class="math inline">\(40\%\)</span> de validação não ajudam a ajustar a árvore) e a estimativa de erro resultante depende de qual divisão específica saiu no sorteio — trocar a semente aleatória desloca um pouco onde cai o “melhor” <span class="math inline">\(\lambda\)</span>. A Aula 4 resolve os dois problemas reamostrando repetidamente, em vez de dividir uma única vez.</p>
</div>
</div>
</section>
<section id="poda-em-ação" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="poda-em-ação"><span class="header-section-number">6.2</span> Poda em ação</h2>
<div class="fig-resize" style="width: 90%; margin: 0 auto;">
<div id="d0e57375" class="cell" data-execution_count="31">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-32-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Árvore completa: 39 folhas
Melhor lambda (validação): 0.0104 -&gt; 10 folhas</code></pre>
</div>
</div>
</div>
<p>O padrão é o mesmo que reaparece, formalizado, na Aula 4: a acurácia de <strong>treino</strong> só piora conforme <span class="math inline">\(\lambda\)</span> cresce e a árvore encolhe (menos capacidade de memorizar o próprio treino) — mas a acurácia de <strong>validação</strong> tem um ponto ótimo no meio, nem a árvore completa (overfitting) nem a árvore excessivamente podada (underfitting).</p>
</section>
<section id="pergunta-5" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="pergunta-5"><span class="header-section-number">6.3</span> Pergunta</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Por que “pare quando o próximo corte não reduzir muito o erro” é uma estratégia de parada ruim?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Julgue V ou F — a questão só conta se acertar os 4 itens:</p>
<ul>
<li>□ No limite em que todo corte candidato, em qualquer nível, sempre reduz o erro por uma quantidade pequena mas positiva, um critério de “pare quando a redução for menor que um limiar fixo” eventualmente para a árvore, mesmo que cortes futuros muito bons ainda estivessem disponíveis mais adiante.</li>
<li>□ Se o critério de parada, em vez de olhar só o próximo corte, pudesse olhar dois níveis à frente (checando se algum neto de um corte candidato produz uma redução grande, mesmo que o corte imediato não produza), esse critério ainda sofreria do mesmo tipo de miopia, só que adiada por um nível.</li>
<li>□ Num algoritmo de busca em jogos como xadrez, um jogador que só avalia a qualidade imediata de cada lance pode recusar um sacrifício de peça que parece ruim agora mas abre caminho para xeque-mate poucas jogadas depois — o mesmo tipo de miopia do critério de parada por corte único.</li>
<li>□ Como crescer a árvore por completo e depois podar evita a miopia do critério de parada por corte único, conclui-se que a árvore completa, antes da poda, já é a estrutura ótima entre todas as árvores possíveis com aquele número final de folhas.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="limites-das-árvores" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Limites das Árvores</h1>
<p>A mesma liberdade que permite a uma árvore capturar qualquer fronteira — sem suposição paramétrica — cobra um preço em três frentes distintas. Vamos ver cada uma com um exemplo concreto, não só em abstrato.</p>
<section id="splits-alinhados-aos-eixos-podem-ser-muito-subótimos" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="splits-alinhados-aos-eixos-podem-ser-muito-subótimos"><span class="header-section-number">7.1</span> Splits alinhados aos eixos podem ser muito subótimos</h2>
<p>Toda fronteira de uma árvore é uma sequência de cortes paralelos aos eixos. Isso é ótimo quando a fronteira “verdadeira” também é alinhada aos eixos — e pode ser péssimo quando não é. O caso mais claro é exatamente aquele que a Aula 2 tratou como o caso fácil: duas classes gaussianas com covariância compartilhada e correlacionada, cuja fronteira ótima é uma <strong>única reta</strong>, não alinhada aos eixos.</p>
<div class="fig-resize" style="width: 90%; margin: 0 auto;">
<div id="102cb6ee" class="cell" data-execution_count="32">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/cell-33-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
<p>Mesmo com 8 níveis de profundidade, a árvore aproxima a reta diagonal com uma escadinha de cortes horizontais e verticais — nunca alcança a reta em si, e precisa de folhas cada vez mais numerosas para chegar perto. A gaussiana da Aula 2 resolve o mesmo problema com <strong>uma única direção</strong>, porque sua forma paramétrica já é adequada a esse tipo de fronteira. É o espelho exato do argumento de abertura desta aula: a forma fixa é ótima quando acerta o formato certo, e a árvore é ótima quando não se sabe (ou não se quer assumir) qual é esse formato.</p>
</section>
<section id="instabilidade-pequenas-mudanças-árvores-bem-diferentes" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="instabilidade-pequenas-mudanças-árvores-bem-diferentes"><span class="header-section-number">7.2</span> Instabilidade: pequenas mudanças, árvores bem diferentes</h2>
<p>Uma segunda limitação, menos visível numa figura só, é que a estrutura aprendida é sensível a detalhes do conjunto de treino — remover ou adicionar poucos pontos pode mudar qual variável e qual limiar são escolhidos logo no primeiro corte (o corte da raiz, que reverbera por toda a árvore abaixo dele).</p>
<div id="0f05c528" class="cell" data-execution_count="33">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>X_inst, y_inst <span class="op">=</span> X_diag.copy(), y_diag.copy()</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>arv_original <span class="op">=</span> DecisionTreeClassifier(max_depth<span class="op">=</span><span class="dv">2</span>, random_state<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>arv_original.fit(X_inst, y_inst)</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove 5 pontos específicos (uma perturbação pequena, ~1% dos dados).</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Gerador local e com seed própria (não o `rng` global desta aula): a</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a><span class="co"># demonstração precisa de uma amostra de 5 pontos específica que desloque</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a><span class="co"># o corte, e prender isso ao estado do `rng` global a tornaria frágil a</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a><span class="co"># qualquer mudança em chunks anteriores.</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>rng_perturbacao <span class="op">=</span> np.random.default_rng(<span class="dv">241</span>)</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>idx_remover <span class="op">=</span> rng_perturbacao.choice(<span class="bu">len</span>(X_inst), size<span class="op">=</span><span class="dv">5</span>, replace<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>mascara <span class="op">=</span> np.ones(<span class="bu">len</span>(X_inst), dtype<span class="op">=</span><span class="bu">bool</span>)</span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>mascara[idx_remover] <span class="op">=</span> <span class="va">False</span></span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>arv_perturbada <span class="op">=</span> DecisionTreeClassifier(max_depth<span class="op">=</span><span class="dv">2</span>, random_state<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>arv_perturbada.fit(X_inst[mascara], y_inst[mascara])</span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> descreve_raiz(arvore):</span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a>    var <span class="op">=</span> arvore.tree_.feature[<span class="dv">0</span>]</span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a>    limiar <span class="op">=</span> arvore.tree_.threshold[<span class="dv">0</span>]</span>
<span id="cb30-22"><a href="#cb30-22" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="ss">f"x_</span><span class="sc">{</span>var<span class="op">+</span><span class="dv">1</span><span class="sc">}</span><span class="ss"> &lt;= </span><span class="sc">{</span>limiar<span class="sc">:.3f}</span><span class="ss">"</span></span>
<span id="cb30-23"><a href="#cb30-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-24"><a href="#cb30-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Corte da raiz, árvore original:   "</span>, descreve_raiz(arv_original))</span>
<span id="cb30-25"><a href="#cb30-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Corte da raiz, com 5 pontos a menos:"</span>, descreve_raiz(arv_perturbada))</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Corte da raiz, árvore original:    x_2 &lt;= 0.014
Corte da raiz, com 5 pontos a menos: x_2 &lt;= -0.113</code></pre>
</div>
</div>
<p>Remover só 5 pontos (<span class="math inline">\(1\%\)</span> da amostra) já desloca o limiar do corte da raiz de <span class="math inline">\(0{,}014\)</span> para <span class="math inline">\(-0{,}113\)</span> — a mesma variável <span class="math inline">\(x_2\)</span> ainda vence, mas o ponto de corte se move o suficiente para redesenhar as duas regiões de forma perceptível. Dependendo de quais pontos especificamente saem, uma perturbação desse tamanho pode até trocar qual variável entra primeiro no corte da raiz — não é preciso um exemplo extremo para isso acontecer, só um sorteio específico de poucos pontos. Nada disso aconteceria com um ajuste de mínimos quadrados, cujo hiperplano se move suavemente com pequenas mudanças nos dados. Esta é exatamente a instabilidade que, mais adiante no curso (Aula 9, Ensemble Theory), deixa de ser só uma fraqueza: é o ingrediente que torna o <em>bagging</em> — a média de muitas árvores levemente diferentes — eficaz.</p>
</section>
<section id="partição-rígida-previsões-descontínuas" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="partição-rígida-previsões-descontínuas"><span class="header-section-number">7.3</span> Partição rígida: previsões descontínuas</h2>
<p>A terceira limitação já apareceu no Bloco 2, na figura da senoide: cada ponto do espaço pertence a exatamente uma folha, e a previsão salta no limiar entre duas folhas vizinhas. Isso é neutro em classificação (uma fronteira sempre existe em algum lugar), mas é particularmente ruim em regressão, quando o alvo verdadeiro é uma função suave — a árvore produz descontinuidades exatamente onde a função verdadeira não tem nenhuma.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>O que fica desta aula
</div>
</div>
<div class="callout-body-container callout-body">
<p>Nenhum dos dois extremos — fronteira sempre linear (Aulas 1–2) ou totalmente livre (árvores) — é gratuito. A forma fixa é barata e estável, mas erra sistematicamente quando o formato certo não é o assumido; a árvore acerta qualquer formato, mas paga em instabilidade e miopia gulosa. A pergunta que abre a Aula 4 é: como escolher, de forma sistemática (não por tentativa e erro), o <strong>tanto de complexidade</strong> certo para um problema — seja o <span class="math inline">\(\lambda\)</span> de poda de uma árvore, seja qualquer outro hiperparâmetro de complexidade?</p>
</div>
</div>
<section id="retomando-as-perguntas-de-abertura" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="retomando-as-perguntas-de-abertura">Retomando as perguntas de abertura</h3>
<ol type="1">
<li><strong>O que uma árvore está estimando?</strong> Uma função constante por partes — de <span class="math inline">\(p(\mathbf{x}\mid\mathcal{C}_k)\)</span> ou de <span class="math inline">\(\mathbb{E}[t\mid\mathbf{x}]\)</span> —, cuja própria forma (não só seus parâmetros) vem dos dados.</li>
<li><strong>Por que “reduzir a impureza” é maximizar verossimilhança?</strong> Porque a proporção empírica de classes numa folha é o MLE categórico, e maximizar essa log-verossimilhança é, algebricamente, minimizar a entropia — o mesmo argumento que já valia para a média (MLE gaussiano) em regressão.</li>
<li><strong>Que preço se paga pela liberdade?</strong> Splits alinhados aos eixos podem ser muito subótimos, a estrutura aprendida é instável a pequenas mudanças no treino, e a partição é rígida — produzindo descontinuidades que uma função suave não tem.</li>
</ol>
</section>
<section id="ponte-para-a-aula-4" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="ponte-para-a-aula-4">Ponte para a Aula 4</h3>
<p>Toda árvore precisa de uma escolha de complexidade — quantas folhas, que <span class="math inline">\(\lambda\)</span> de poda — e essa escolha, até aqui, foi feita “olhando o gráfico” de uma divisão treino/validação específica. A Aula 4 formaliza esse procedimento: valida por reamostragem (cross-validation), trata o erro de validação como uma <strong>estimativa estatística</strong> de uma quantidade não observável (o erro de generalização), e usa o Bootstrap para quantificar a incerteza dessa estimativa.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Julgue V ou F: limites estruturais das árvores
</div>
</div>
<div class="callout-body-container callout-body">
<p>Julgue V ou F — a questão só conta se acertar os 4 itens:</p>
<ul>
<li>□ No limite em que a profundidade máxima não é limitada e há pelo menos um ponto de treino distinto por folha, o erro de treino de uma árvore de classificação tende a zero, independentemente de quão complexa seja a verdadeira fronteira de decisão.</li>
<li>□ Se as 500 amostras do exemplo do California Housing fossem substituídas por outra amostra, sorteada com outra semente aleatória, o corte escolhido para a raiz poderia mudar, mesmo mantendo as mesmas duas variáveis candidatas.</li>
<li>□ Numa aplicação de visão computacional em que cada variável de entrada é um pixel, uma árvore de cortes alinhados aos eixos enfrentaria a mesma limitação de aproximar só em degraus fronteiras não alinhadas a pixels individuais.</li>
<li>□ Como instabilidade estrutural e partição rígida vêm do mesmo processo de ajuste guloso, uma regra de desempate determinística para cortes quase empatados eliminaria também a rigidez da partição e suas descontinuidades.</li>
</ul>
</div>
</div>
</section>
</section>
</section>
<section id="exercícios" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Exercícios</h1>
<section id="questões-discursivas" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="questões-discursivas"><span class="header-section-number">8.1</span> Questões discursivas</h2>
<ol type="1">
<li><p>Explique, com suas próprias palavras, por que dizer “a árvore escolhe o corte que reduz mais a impureza” é equivalente a dizer “a árvore escolhe o corte que maximiza a log-verossimilhança dos dados na folha”. Sua explicação deve mencionar tanto o caso de regressão quanto o de classificação.</p></li>
<li><p>Construa (ou descreva) um par de splits de um nó de classificação com a mesma taxa de erro de classificação ponderada, mas com Gini ou entropia diferentes — diferente do exemplo usado na aula. Explique por que isso acontece.</p></li>
<li><p>Um colega propõe usar apenas a taxa de erro de classificação (não Gini nem entropia) tanto para crescer quanto para podar uma árvore. Argumente por que essa escolha é razoável para podar, mas problemática para crescer.</p></li>
</ol>
</section>
<section id="questões-de-verdadeirofalso" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="questões-de-verdadeirofalso"><span class="header-section-number">8.2</span> Questões de Verdadeiro/Falso</h2>
<p>Cada bloco de 4 itens trata do mesmo tema. A questão só é considerada correta se todos os 4 itens forem julgados corretamente (deixar em branco tem penalidade de 20% da nota da questão).</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Árvores como estimação não-paramétrica
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>□ Se, em vez de cortes alinhados aos eixos, uma árvore pudesse usar cortes ao longo de qualquer direção linear (hiperplanos oblíquos), mantendo a mesma lógica gulosa de escolher o corte que mais reduz <span class="math inline">\(Q\)</span>, ela deixaria de ser um modelo não-paramétrico.</p></li>
<li><p>□ Se o número mínimo de pontos por folha for reduzido a <span class="math inline">\(1\)</span> e a profundidade máxima não for limitada, o número de parâmetros efetivos de uma árvore pode crescer até se igualar ao número de pontos de treino <span class="math inline">\(N\)</span>.</p></li>
<li><p>□ Suponha que se queira usar uma árvore para modelar a distribuição conjunta completa <span class="math inline">\(p(\mathbf{x}, y)\)</span>, não só a fronteira de decisão. Isso é possível diretamente com o mesmo procedimento de ajuste desta aula, sem nenhuma modificação.</p></li>
<li><p>□ Numa árvore com uma única folha (nenhum corte realizado), a estimativa em classificação se reduz à priori marginal <span class="math inline">\(\hat\pi_k\)</span> da amostra de treino, ignorando completamente <span class="math inline">\(\mathbf{x}\)</span>.</p></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>O estimador ótimo numa folha de regressão
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>□ Se, em vez de uma verossimilhança gaussiana, assumíssemos uma verossimilhança de Laplace (dupla exponencial) para os alvos de uma folha, o estimador de máxima verossimilhança de <span class="math inline">\(y_\tau\)</span> deixaria de ser a média amostral e passaria a ser a mediana amostral.</p></li>
<li><p>□ Se todos os <span class="math inline">\(N_\tau\)</span> alvos de uma folha forem idênticos entre si (variância zero), o valor mínimo de <span class="math inline">\(Q_\tau\)</span> é zero, e a log-verossimilhança gaussiana correspondente, no limite <span class="math inline">\(\sigma^2\to 0\)</span>, tende a <span class="math inline">\(+\infty\)</span>.</p></li>
<li><p>□ Uma folha com <span class="math inline">\(N_\tau=1\)</span> ainda define um <span class="math inline">\(Q_\tau\)</span> mínimo bem definido e igual a zero, mas a variância amostral desse único ponto não pode ser estimada de forma não-enviesada (o denominador <span class="math inline">\(N_\tau
- 1\)</span> seria zero).</p></li>
<li><p>□ Como <span class="math inline">\(Q_\tau\)</span> e a variância amostral <span class="math inline">\(\hat\sigma^2_\tau =
Q_\tau/N_\tau\)</span> diferem apenas por uma constante multiplicativa, qualquer corte que minimize <span class="math inline">\(Q_\tau\)</span> nas duas folhas geradas também minimiza, necessariamente, a variância combinada dessas folhas.</p></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Crescimento guloso e sua miopia
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>□ Se o critério fosse “sempre aprofundar a folha mais numerosa” em vez de “maior redução de <span class="math inline">\(Q\)</span>”, o resultado seria idêntico ao crescimento guloso descrito na aula, já que a folha mais numerosa tende a ter o maior <span class="math inline">\(Q\)</span>.</p></li>
<li><p>□ No limite em que o número mínimo de pontos por folha tende a zero, a busca exaustiva de limiares dentro de uma folha com <span class="math inline">\(N_\tau\)</span> pontos distintos passa a testar até <span class="math inline">\(N_\tau - 1\)</span> limiares candidatos.</p></li>
<li><p>□ Se, em vez de um único alvo, tivéssemos alvos multivariados <span class="math inline">\(\mathbf{t}\in\mathbb{R}^p\)</span> e definíssemos <span class="math inline">\(Q_\tau\)</span> como a soma das somas de quadrados de cada componente, o mesmo algoritmo de busca exaustiva continuaria bem definido, sem alteração na lógica do Passo 2.</p></li>
<li><p>□ Como a busca escolhe sempre o corte de menor <span class="math inline">\(Q\)</span> entre as duas folhas geradas, a árvore final construída por esse processo guloso é, necessariamente, a de menor <span class="math inline">\(Q\)</span> total entre todas as árvores com o mesmo número de folhas.</p></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Entropia e informação mútua
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>□ Se uma variável <span class="math inline">\(X\)</span> tem <span class="math inline">\(K\)</span> resultados possíveis e é uniforme entre eles, sua entropia tende a <span class="math inline">\(\ln K\)</span> nats — e, no limite em que <span class="math inline">\(K\to\infty\)</span> mantendo a uniformidade, <span class="math inline">\(H(X)\to\infty\)</span>.</p></li>
<li><p>□ Se <span class="math inline">\(Y\)</span> fosse uma função determinística e invertível de <span class="math inline">\(X\)</span> (conhecer <span class="math inline">\(Y\)</span> permite recuperar <span class="math inline">\(X\)</span> exatamente, e vice-versa), então <span class="math inline">\(I(X;Y) = H(X) = H(Y)\)</span>.</p></li>
<li><p>□ Considere duas moedas honestas lançadas de forma totalmente independente, sem qualquer relação causal entre elas. Mesmo assim, numa amostra finita de <span class="math inline">\(N\)</span> lançamentos, a informação mútua empírica calculada a partir das frequências observadas dificilmente será exatamente zero, mesmo que a informação mútua populacional verdadeira seja zero.</p></li>
<li><p>□ Como <span class="math inline">\(I(X;Y)\)</span> é sempre não-negativa e vale zero exatamente na independência, uma informação mútua alta necessariamente implica que <span class="math inline">\(X\)</span> causa <span class="math inline">\(Y\)</span> (ou vice-versa).</p></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Ganho de informação e a conexão MLE categórico–entropia
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>□ Se, em vez de comparar <span class="math inline">\(H(\hat p_\tau)\)</span> com a <strong>média ponderada</strong> das entropias dos filhos, comparássemos com a MAIOR das duas entropias, o valor resultante ainda seria igual à informação mútua <span class="math inline">\(I(S;\mathcal{C})\)</span>.</p></li>
<li><p>□ No caso extremo em que um corte separa perfeitamente as duas classes (ambas as folhas filhas ficam com <span class="math inline">\(H=0\)</span>), o ganho de informação desse corte é exatamente igual a <span class="math inline">\(H(\hat p_\tau)\)</span> — o maior valor possível para aquele nó.</p></li>
<li><p>□ Numa folha com 3 classes, em contagens <span class="math inline">\((10,10,10)\)</span>, o MLE categórico dessa folha ainda seria a proporção empírica <span class="math inline">\((1/3,1/3,1/3)\)</span>, com entropia dada pela mesma fórmula, agora somando sobre 3 termos.</p></li>
<li><p>□ Como maximizar a log-verossimilhança categórica equivale a minimizar a entropia da folha, um corte que reduz a entropia de AMBAS as folhas filhas em relação à do pai necessariamente maximiza o ganho de informação entre todos os cortes candidatos disponíveis naquele nó.</p></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Entropia e Gini: forma e interpretação
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>□ À medida que o número de classes <span class="math inline">\(K\)</span> numa folha cresce, sempre mantendo a distribuição uniforme entre elas, tanto a entropia máxima <span class="math inline">\(H=\ln K\)</span> quanto o valor máximo do índice de Gini, <span class="math inline">\(G=1-1/K\)</span>, crescem sem limite.</p></li>
<li><p>□ Se, em vez do índice de Gini, usássemos <span class="math inline">\(G'(p)=\max_k p_k\)</span> (a proporção da classe majoritária) como critério de impureza, um corte que produz duas folhas com <span class="math inline">\(\max_k p_k\)</span> idêntico teria impureza ponderada igual, mesmo que as distribuições internas das duas folhas fossem completamente diferentes fora da classe majoritária.</p></li>
<li><p>□ Num problema de detecção de fraude com 99% de transações legítimas e 1% fraudulentas, uma folha que reproduz exatamente essa proporção tem entropia próxima do mínimo possível, mesmo antes de qualquer corte ser feito.</p></li>
<li><p>□ Como entropia e Gini se anulam numa folha pura e atingem o máximo em <span class="math inline">\(p=0{,}5\)</span> (caso binário), as duas medidas sempre concordam sobre qual, entre dois cortes candidatos, produz a maior redução de impureza.</p></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Por que não usar a taxa de erro bruta para crescer a árvore
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>□ Num nó com duas classes empatadas em número de pontos (proporção <span class="math inline">\(50/50\)</span>), a taxa de erro do classificador majoritário é <span class="math inline">\(0{,}5\)</span> — o valor máximo possível dessa métrica, coincidindo com o ponto de máxima entropia e máximo Gini.</p></li>
<li><p>□ Se a taxa de erro bruta fosse o único critério de crescimento, e dois cortes candidatos produzissem a mesma taxa de erro ponderada, o algoritmo não teria como preferir um corte ao outro, nem mesmo quando um deles produz uma folha perfeitamente pura.</p></li>
<li><p>□ Considere um nó com 3 classes e contagens <span class="math inline">\((50,49,1)\)</span>. O classificador que sempre prevê a classe majoritária nesse nó erra em <span class="math inline">\(50\%\)</span> dos casos, mesmo a folha estando longe de ser uniformemente distribuída entre as 3 classes.</p></li>
<li><p>□ Como a validação, na escolha de <span class="math inline">\(\lambda\)</span>, usa a acurácia (equivalente à taxa de erro), conclui-se que entropia e Gini deixam de ter qualquer papel na fase de poda por custo-complexidade.</p></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Custo vs.&nbsp;complexidade e a poda
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>□ No limite em que <span class="math inline">\(\lambda\to\infty\)</span>, o critério <span class="math inline">\(C(T) =
\sum_\tau Q_\tau(T) + \lambda|T|\)</span> é minimizado por uma árvore com uma única folha.</p></li>
<li><p>□ Se a penalidade de complexidade fosse proporcional à profundidade da árvore em vez de ao número de folhas, duas árvores com o mesmo número de folhas mas formatos diferentes (uma bem desbalanceada, outra balanceada) poderiam receber penalidades diferentes sob esse critério alternativo, ao contrário do critério <span class="math inline">\(C(T)\)</span> usado na aula.</p></li>
<li><p>□ Numa tarefa de regressão em que os alvos <span class="math inline">\(t\)</span> passam a ser medidos numa escala muito maior (ex.: milhões em vez de milhares de dólares), o mesmo valor de <span class="math inline">\(\lambda\)</span> usado na escala original não produz, em geral, a mesma árvore podada na nova escala.</p></li>
<li><p>□ Como <span class="math inline">\(\sum_\tau Q_\tau(T)\)</span> só pode diminuir (ou manter-se) conforme se adicionam folhas, e <span class="math inline">\(\lambda|T|\)</span> só pode aumentar, conclui-se que <span class="math inline">\(C(T)\)</span> é uma função estritamente convexa do número de folhas, com um único mínimo global bem definido.</p></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Treino vs.&nbsp;validação: por que separar os dados
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>□ Se o conjunto de validação tivesse exatamente <span class="math inline">\(0\%\)</span> dos dados (todo o conjunto fosse usado como treino), a acurácia medida no que sobrasse para “validação” seria, no limite, idêntica à acurácia de treino.</p></li>
<li><p>□ Se a escolha do melhor <span class="math inline">\(\lambda\)</span> fosse feita usando a acurácia de TREINO em vez da de validação, o <span class="math inline">\(\lambda\)</span> escolhido tenderia a ser sistematicamente menor (menos poda) do que o escolhido por validação.</p></li>
<li><p>□ Num cenário com apenas 40 pontos de treino disponíveis, reservar <span class="math inline">\(40\%\)</span> deles só para validação tem um custo prático mais sério do que reservar a mesma proporção de um conjunto de 40.000 pontos.</p></li>
<li><p>□ Como o conjunto de validação nunca é usado para ajustar os cortes da árvore, o desempenho medido nele é uma estimativa não-enviesada do erro de generalização, mesmo que o próprio valor de <span class="math inline">\(\lambda\)</span> tenha sido escolhido observando exatamente esse mesmo conjunto.</p></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Splits alinhados aos eixos
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>□ No limite em que a profundidade tende a infinito, o erro de aproximação de uma fronteira diagonal por cortes alinhados aos eixos tende a zero, mas o número de folhas necessário para um erro menor que <span class="math inline">\(\epsilon\)</span> cresce sem limite à medida que <span class="math inline">\(\epsilon\to0\)</span>.</p></li>
<li><p>□ Se a fronteira de decisão ótima entre duas classes fosse alinhada a um dos eixos originais (dependendo só de <span class="math inline">\(x_1\)</span>, por exemplo), uma árvore poderia representá-la exatamente com um único corte, ao contrário do caso diagonal.</p></li>
<li><p>□ Considere um problema em que a fronteira ótima é um círculo centrado na origem. Uma árvore com cortes alinhados aos eixos pode aproximar essa fronteira com uma sequência de retângulos, mas nunca a representa exatamente com um número finito de cortes.</p></li>
<li><p>□ Como uma árvore com profundidade suficiente aproxima arbitrariamente bem qualquer fronteira, o número de folhas necessário para uma boa aproximação não depende da complexidade geométrica da fronteira verdadeira, só da profundidade escolhida.</p></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Instabilidade estrutural
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>□ Se, em vez de escolher deterministicamente o corte de maior <span class="math inline">\(IG\)</span> (ou menor <span class="math inline">\(Q\)</span>), o algoritmo escolhesse aleatoriamente entre os <span class="math inline">\(k\)</span> melhores cortes candidatos a cada rodada, a instabilidade da estrutura de uma árvore individual a pequenas mudanças no treino tenderia a diminuir.</p></li>
<li><p>□ No limite em que o conjunto de treino tem um número muito grande de pontos amostrados da mesma distribuição geradora, o corte escolhido na raiz se aproxima de um valor estável, e pequenas remoções de pontos deixam de mudar esse corte de forma perceptível.</p></li>
<li><p>□ Num conjunto de dados em que várias variáveis são fortemente correlacionadas entre si (quase redundantes para prever a classe), a instabilidade estrutural de uma árvore tende a ser maior do que em variáveis pouco correlacionadas.</p></li>
<li><p>□ Como a estrutura de uma árvore pode mudar substancialmente com a remoção de poucos pontos de treino, as previsões dessa árvore para a maioria dos pontos de teste também mudam substancialmente sempre que a estrutura muda.</p></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Partição rígida e descontinuidades
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>□ À medida que o número de folhas de uma árvore de regressão cresce sem limite, o tamanho de cada descontinuidade entre folhas vizinhas tende a diminuir, mas a partição continua sendo, em qualquer profundidade finita, uma função em degraus.</p></li>
<li><p>□ Se, em vez de prever a média constante em cada folha, a árvore previsse uma reta local ajustada por mínimos quadrados dentro de cada folha, as descontinuidades entre folhas vizinhas desapareceriam automaticamente, sem qualquer restrição adicional.</p></li>
<li><p>□ Na aplicação de precificação de imóveis desta aula (California Housing), dois imóveis com <code>MedInc</code> quase idêntico, mas de lados opostos de um limiar de corte, podem receber previsões de preço bastante diferentes, mesmo sendo quase indistinguíveis em todo o resto.</p></li>
<li><p>□ Como a rigidez da partição é a mesma característica que permite à árvore modelar interações não-lineares sem exigir que sejam especificadas de antemão, conclui-se que a rigidez da partição não tem nenhuma desvantagem prática relevante.</p></li>
</ul>
</div>
</div>
</section>
<section id="aviso" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="aviso"><span class="header-section-number">8.3</span> Aviso</h2>
<p>As questões de Verdadeiro/Falso e discursivas ficam sem solução neste arquivo — são para resolução autônoma do aluno, fora do horário de aula.</p>


</section>
</section>

</main> <!-- /main -->
<!-- Parcial estático, igual em toda aula (não é mais gerado por script —
     ver histórico do teaching/generate_lesson_nav.py, removido). Só
     carrega o script que transforma o sumário nativo do Quarto (#TOC,
     "Nesta página") no painel de acordeão "Nesta aula". -->
<script src="../../toc-accordion.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© 2026 Marcos M. Raimundo</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>