{
  "hash": "777e5217da819dab3aea977822b939fd",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Aula 3: Topografia de Densidade e Grafos — Clustering Hierárquico e HDBSCAN\"\nsubtitle: \"Aprendizado Não Supervisionado\"\nauthor: \"Marcos M. Raimundo — Instituto de Computação, UNICAMP\"\ndate: \"2026-08-30\"\nlang: pt-BR\nformat:\n  html:\n    include-after-body: ../../lesson-toc-accordion.html\n    output-file: notas.html\n    theme: [flatly, ../../../custom.scss, ../../lesson-theme.scss]\n    toc: true\n    toc-depth: 3\n    number-sections: true\n    code-fold: false\n    fig-width: 6\n    fig-height: 3.8\n  revealjs:\n    transition: slide\n    width: 1280\n    height: 800\n    margin: 0.02\n    fig-responsive: true\n    fig-format: \"svg\"\n    footer: \"UNICAMP — Instituto de Computação\"\n    chalkboard:\n      boardmarker-width: 3\n      chalk-width: 3\n    include-in-header: ../../bootstrap-icons-header.html\n    include-after-body: ../../logos-footer.html\n    title-slide-attributes:\n      data-background-image: \"../../UNICAMP.png, ../../IC.png\"\n      data-background-size: \"140px, 140px\"\n      data-background-position: \"5% 8%, 95% 8%\"\n    output-file: slides.html\n    slide-number: true\n    smaller: true\n    scrollable: true\n    theme: [simple, ../../lesson-theme.scss]\n    fig-width: 6\n    fig-height: 3.8\njupyter: homepage\nexecute:\n  warning: false\n  message: false\n---\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n[Slides](slides.html){.see-all aria-label=\"Ver slides\" title=\"Ver slides\"}\n[Lista de aulas](../index.qmd){.see-all .lesson-list-link aria-label=\"Lista de aulas\" title=\"Lista de aulas\"}\n:::\n\n\n\n# Revisão e Introdução\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n\n## Revisão Rápida: Da Aula 1 à Aula 2, e a Limitação Que Ficou Pendente\n\nA Aula 1 assumiu uma forma paramétrica fixa para a densidade\n$p(\\mathbf{x})$ (uma gaussiana, por exemplo). A Aula 2 abandonou essa\nforma fixa: a partir do mesmo estimador geral $p(\\mathbf{x})=K/(NV)$,\nfixar $K$ e deixar $V$ crescer até capturar $K$ vizinhos dá o $k$-NN\n(com a distância ao $K$-ésimo vizinho, $d_K(\\mathbf{x})$, como\nsubproduto); fixar $V$ e contar quantos pontos caem dentro dá a Janela\nde Parzen, suavizada com kernel gaussiano na KDE. Nenhum dos dois\nmétodos escapou de duas limitações, porém: sem uma forma paramétrica para\n\"resumir\" os dados em poucos parâmetros, os dados **são** o modelo\n(toda consulta nova revisita o conjunto de treino inteiro), e ambos\nsofrem a **maldição da dimensionalidade** — em dimensão alta, o volume\nse concentra numa casca fina e as distâncias perdem poder de\ndiscriminação, um problema que volta a aparecer no bloco final desta\naula, quando os $30$ atributos originais do Breast Cancer Wisconsin\n(não só os $2$ usados nas figuras) entram em jogo.\n\nO resultado desses métodos, para qualquer conjunto de dados, é uma\n**paisagem** $p(\\mathbf{x})$ com picos (regiões densas) e vales\n(regiões raras) — essa paisagem, sozinha, já responde \"esse valor de\n$\\mathbf{x}$ é comum ou raro?\" ponto a ponto. A própria Aula 2 já\napontou para onde isso ia: fechou com uma \"Ponte para a Aula 3\"\navisando que $d_K(\\mathbf{x})$, ali uma ferramenta de estimação de\ndensidade, seria reaproveitada como uma **métrica de densidade local**\npara construir caminhos num grafo — é exatamente esse reaproveitamento\nque esta aula cumpre.\n\n## Ideia Central\n\nSó que \"comum ou raro\" não é a única pergunta que interessa. Dado um\nconjunto de pacientes, uma pergunta diferente — e ainda sem resposta —\né: **quais pacientes são parecidos o bastante entre si para merecer o\nmesmo rótulo?** Saber que um ponto está numa região densa não diz,\nsozinho, com quais outros pontos ele forma um grupo: duas regiões\ndensas separadas por um vale de baixa densidade são dois grupos\ndiferentes, mas dois pontos dentro da mesma região densa e contígua —\nmesmo geometricamente distantes um do outro — deveriam contar como um\núnico grupo. \"Comum ou raro\" é uma propriedade de um ponto isolado;\n\"parecido com quem\" é uma propriedade de *conjuntos* de pontos. Essa\nsegunda pergunta é **clustering** — o objeto desta aula: transformar a\nmesma paisagem de densidade que a Aula 2 já sabe estimar numa partição\nde grupos, sem que ninguém diga de antemão quantos grupos existem, nem\nque forma cada um tem.\n\n## Roteiro da Aula\n\nA pergunta que fecha o Organizador Prévio — transformar uma paisagem de\ndensidade numa partição de grupos — se desdobra em quatro perguntas\nmais específicas, cada uma resolvida em um bloco desta aula:\n\n1. Densidade sozinha não define grupo — **o que exatamente deveria\n   significar \"cluster\"**?\n2. Dada essa definição, **como construir um cluster\n   computacionalmente**, sem escolher quantos grupos existem de\n   antemão?\n3. Isso pode ser reduzido a um problema de **grafos** — e, se sim, qual\n   estrutura de grafo captura *toda* a hierarquia de clusters possível\n   de uma só vez?\n4. Uma vez com essa estrutura, **como decidir quais clusters\n   encontrados são estrutura real dos dados**, e quais são só\n   flutuação amostral?\n\n## Problema Motivador\n\nAntes de resolver nada, olhe a paisagem de densidade de frente: a\nfigura abaixo é a mesma ferramenta da Aula 2 — KDE — aplicada a um\nconjunto de pontos sintético e controlado, em forma de duas luas\nentrelaçadas, escolhido especificamente porque nenhuma suposição de\n\"bola em torno de um centro\" o respeitaria.\n\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## Revisão Rápida: Da Aula 1 à Aula 2\n\n::: {.fragment}\n- Aula 1: forma paramétrica fixa para $p(\\mathbf{x})$ (ex.: gaussiana).\n- Aula 2: abandona a forma fixa — $p(\\mathbf{x})=K/(NV)$, fixar $K$ dá $k$-NN (com $d_K(\\mathbf{x})$ como subproduto), fixar $V$ dá KDE.\n:::\n\n::: {.fragment}\nDuas limitações em ambos: sem forma paramétrica, os dados **são** o\nmodelo; e ambos sofrem a **maldição da dimensionalidade** — volta no\nbloco final desta aula, com os $30$ atributos do Breast Cancer\nWisconsin.\n:::\n\n::: {.fragment}\nA Aula 2 já mostrou que $d_K(\\mathbf{x})$ seria reaproveitada como\n**métrica de densidade local** para construir caminhos num grafo — é\nesse reaproveitamento que esta aula cumpre.\n:::\n\n::: {.fragment  .callout-note}\nA paisagem $p(\\mathbf{x})$ responde \"comum ou raro?\" ponto a ponto —\nmas não diz **com quais outros pontos** um ponto forma um grupo.\n:::\n\n## Ideia Central\n\n::: {.fragment}\nPergunta nova, ainda sem resposta: dado um conjunto de pacientes,\n**quais são parecidos o bastante entre si para merecer o mesmo\nrótulo?**\n:::\n\n::: {.fragment}\nSaber que um ponto está numa região densa não diz, sozinho, com quais\noutros pontos ele forma um grupo.\n:::\n\n::: {.fragment}\nDuas regiões densas separadas por um vale raso: **dois** grupos. Dois\npontos na mesma região densa e contígua, mesmo geometricamente\ndistantes: **um** grupo só.\n:::\n\n::: {.fragment}\n\"Comum ou raro\" é propriedade de um ponto isolado; \"parecido com quem\"\né propriedade de *conjuntos* de pontos. Essa segunda pergunta é\n**clustering** — o objeto desta aula.\n:::\n\n## Roteiro da Aula\n\n::: {.fragment}\nTransformar uma paisagem de densidade numa partição de grupos se\ndesdobra em quatro perguntas, uma por bloco:\n:::\n\n::: {.fragment}\n**1.** Densidade sozinha não define grupo — o que deveria significar\n\"cluster\"?\n:::\n\n::: {.fragment}\n**2.** Como construir isso computacionalmente, sem escolher quantos\ngrupos existem a priori?\n:::\n\n::: {.fragment}\n**3.** Isso é um problema de **grafos** — qual estrutura captura toda a\nhierarquia de clusters de uma vez?\n:::\n\n::: {.fragment}\n**4.** Como decidir quais clusters encontrados são reais, e quais são\nflutuação amostral?\n:::\n\n## Problema Motivador\n\n::: {.fragment}\nDuas luas entrelaçadas (sintético, controlado). Mesma ferramenta da\nAula 2 — KDE — aplicada aqui: qual é a paisagem de densidade?\n:::\n\n:::\n\n::: {.fig-resize style=\"width: 65%; margin: 0 auto;\"}\n\n::: {#1a7d728c .cell execution_count=2}\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-revealjs/cell-3-output-1.svg){fig-align='center'}\n:::\n:::\n\n\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n\nA paisagem mostra exatamente duas cristas conectadas, cada uma\nacompanhando o formato de uma lua, separadas por um vale visível de\nbaixa densidade — apesar de as duas luas se entrelaçarem\ngeometricamente (a ponta de uma passa perto do meio da outra). Isso já\né informação nova, que a Aula 2 sozinha nunca perguntou: a Aula 2\ncalculava $p(\\mathbf{x})$ para qualquer ponto individual do plano, mas\nnunca perguntava \"quantas cristas separadas existem nessa paisagem, e\nonde termina uma e começa a outra?\" — essa é uma pergunta sobre a\n**conectividade** do terreno alto, não sobre o valor da densidade em\nnenhum ponto isolado. Repare também que a resposta óbvia a olho nu\n(duas cristas) não tem nada a ver com \"estar perto de um centro\ngeométrico fixo\": as duas pontas de cada lua estão, em linha reta, tão\nlonge uma da outra quanto de pontos da lua vizinha — o que as une é a\ncrista de densidade alta que as conecta, não a proximidade a um ponto\ncentral.\n\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n::: {.fragment}\nA paisagem mostra **duas cristas conectadas**, cada uma acompanhando\numa lua, separadas por um vale visível — mesmo as duas luas se\nentrelaçando geometricamente. Pergunta nova, que a Aula 2 nunca fez:\nnão \"qual a densidade aqui\", mas \"onde termina uma crista e começa a\noutra\" — uma pergunta sobre **conectividade**, não sobre o valor da\ndensidade num ponto isolado.\n:::\n\n::: {.fragment}\nA resposta óbvia a olho nu (duas cristas) **não** tem nada a ver com\n\"perto de um centro fixo\": as duas pontas de cada lua estão, em linha\nreta, tão longe uma da outra quanto de pontos da lua vizinha — o que as\nune é a **crista de densidade alta** que as conecta, não a proximidade\na um ponto central.\n:::\n\n:::\n\n## Pergunta\n\n::: {.callout-tip}\n## A paisagem de densidade acima parece ter, a olho nu, duas cristas separadas por um vale. Isso já resolve sozinho o problema de encontrar os grupos, ou falta alguma coisa?\n\nDica: pense se \"ter uma paisagem de densidade\" é a mesma coisa que \"ter\numa lista de quais pontos pertencem a qual grupo\" — e o que teria que\nacontecer, algoritmicamente, para ir de um para o outro.\n\n- □ Basta calcular $p(\\mathbf{x})$ em cada ponto do dataset e aplicar\n  um limiar fixo $\\lambda$: os pontos acima do limiar já vêm\n  automaticamente rotulados por grupo, sem nenhum passo adicional.\n- □ Se toda a paisagem de densidade fosse uma única crista, sem nenhum\n  vale separando regiões, não existiria estrutura de cluster genuína a\n  recuperar — qualquer partição imposta sobre ela seria arbitrária.\n- □ Já que a Aula 2 responde \"esse ponto é comum ou raro?\" para cada\n  ponto isolado, basta ordenar os pacientes por densidade estimada e\n  cortar a lista ao meio para obter os dois grupos verdadeiros, em\n  qualquer dataset com exatamente dois grupos.\n- □ Numa aplicação de detecção de fraude com dois golpes bem distintos,\n  cada um formando sua própria concentração no espaço de atributos, a\n  mesma lógica de \"componente conectada de uma região de alta\n  densidade\" se aplicaria para separar os dois tipos de fraude entre\n  si, mesmo sem nunca ter visto o rótulo do tipo de golpe.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## Resposta\n\n::: {.callout-tip}\n## Resposta — densidade x grupo\n\n- ✗ Um limiar sozinho diz quais pontos estão \"acima\" — não diz quais\n  desses pontos formam a mesma componente conectada; isso exige um\n  passo algorítmico a mais (o resto desta aula).\n- ✔ Sem vale nenhum separando regiões, não há estrutura de cluster\n  genuína — qualquer corte imposto seria arbitrário.\n- ✗ Ordenar por densidade e cortar ao meio ignora conectividade\n  espacial — nada garante que os pontos mais densos formem um único\n  grupo geometricamente coerente.\n- ✔ A lógica de componente conectada de alta densidade transfere para\n  qualquer domínio com concentrações bem separadas, não só para os\n  exemplos vistos aqui.\n:::\n\n::: {.fragment}\n**Voltando à pergunta:** densidade ponto a ponto (Aula 2) é\nmatéria-prima, não o produto final — falta o passo de transformar essa\npaisagem numa partição de grupos, exatamente o que o resto da aula\nconstrói.\n:::\n\n:::\n\n# Intuição — Vales e Montanhas\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n\nAntes de qualquer formalismo, veja o resultado inteiro primeiro — só\nvai faltar nomear os passos. Pense na densidade $p(\\mathbf{x})$ dos\ndados como uma **paisagem**: regiões densas são montanhas, regiões\nraras são vales. A aposta desta aula é que **um cluster é uma montanha\ninteira** — não importa o formato do contorno da montanha na base, só\nimporta que ela seja um bloco conectado de terreno alto, separado das\noutras montanhas por um vale (uma região de baixa densidade).\n\nUm algoritmo que respeita essa definição não precisa de centróide\nnenhum: em vez de \"para qual centro fixo eu estou mais perto\", ele\npergunta \"caminhando sempre por terreno alto, até onde eu consigo\nchegar sem descer a um vale?\". Cada lua inteira, mesmo curva, é\nterreno alto conectado de ponta a ponta — não importa que as duas\npontas da lua estejam geometricamente longe uma da outra em linha\nreta, porque a trilha entre elas nunca desce a um vale.\n\nEssa escolha não é só estética. Qualquer regra que particione o espaço\natribuindo cada ponto ao centro fixo mais próximo, dentre um pequeno\nconjunto de protótipos, sempre corta o espaço em regiões **convexas**\n— a região de cada protótipo é a interseção dos semiespaços \"mais\nperto deste protótipo do que de qualquer outro\", e toda interseção de\nsemiespaços é convexa. Isso significa que nenhuma escolha de\nprotótipos, por mais que se aumente a quantidade deles, recupera uma\nlua ou um anel como um cluster único: a fronteira entre dois protótipos\nvizinhos é sempre reta (ou, em mais dimensões, um hiperplano), e uma\nreta não acompanha uma curva fechada. A definição por conectividade de\nterreno alto não tem essa restrição de forma nenhuma.\n\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## A Aposta Desta Aula\n\n::: {.fragment}\nPense em $p(\\mathbf{x})$ como uma **paisagem**: montanhas = regiões\ndensas, vales = regiões raras.\n:::\n\n::: {.fragment}\n**Um cluster é uma montanha inteira** — não importa o formato do\ncontorno, só que seja um bloco conectado de terreno alto, separado dos\noutros por um vale.\n:::\n\n::: {.fragment}\nAlgoritmo: não \"que centro fixo está mais perto?\", mas **\"caminhando\npor terreno alto, até onde eu chego sem descer a um vale?\"**\n:::\n\n::: {.fragment}\nUma lua inteira, mesmo curva, é uma trilha alta conectada de ponta a\nponta — mesmo que as duas pontas estejam geometricamente longe em\nlinha reta.\n:::\n\n:::\n::: {.fig-resize style=\"width: 62%; margin: 0 auto;\"}\n\n::: {#f312659e .cell execution_count=3}\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-revealjs/cell-4-output-1.svg){fig-align='center'}\n:::\n:::\n\n\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n\nOs dois painéis usam exatamente o algoritmo que esta aula vai\nconstruir — HDBSCAN, cujo nome ainda não foi justificado — e acertam\npor completo: acurácia $100\\%$ contra o rótulo verdadeiro (nunca visto\npelo algoritmo), tanto nas duas luas quanto nos dois anéis\nconcêntricos — uma forma ainda mais hostil à ideia de \"bola em torno de\num centro\", já que o anel externo *envolve* o interno por todos os\nlados. Nenhum dos dois resultados depende de qualquer suposição sobre a\nforma do cluster: o algoritmo nunca precisou saber, de antemão, que a\nforma certa era uma lua ou um anel.\n\nFalta nomear os passos: como, exatamente, \"caminhar por terreno alto\"\nse transforma em um algoritmo executável? A resposta atravessa três\nideias, uma por bloco: (i) formalizar \"montanha\" como um conjunto de\nnível de densidade (Bloco 3); (ii) transformar isso em um grafo, usando\numa distância que \"sabe\" onde é vale e onde é montanha (Bloco 4); (iii)\nextrair, desse grafo, uma única estrutura que contém toda a hierarquia\nde clusters possível ao mesmo tempo (Bloco 5).\n\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## Os Números Por Trás da Figura\n\n::: {.fragment}\n**Duas luas:** HDBSCAN (o algoritmo desta aula) $=100\\%$ de acurácia\ncontra o rótulo verdadeiro.\n:::\n\n::: {.fragment}\n**Dois anéis concêntricos** (forma ainda mais hostil à ideia de \"bola\nem torno de um centro\" — o anel externo envolve o interno por todos os\nlados): HDBSCAN também $=100\\%$.\n:::\n\n::: {.fragment}\nNenhum dos dois resultados depende de saber, de antemão, a forma certa\ndo cluster.\n:::\n\n## O Que Falta Nomear\n\n::: {.fragment}\n**(i)** Formalizar \"montanha\" como conjunto de nível de densidade\n(Bloco 3).\n:::\n\n::: {.fragment}\n**(ii)** Transformar isso num grafo, com uma distância que \"sabe\" onde\né vale e onde é montanha (Bloco 4).\n:::\n\n::: {.fragment}\n**(iii)** Extrair desse grafo uma única estrutura com toda a hierarquia\nde clusters possível, de uma vez (Bloco 5).\n:::\n\n:::\n\n## Pergunta\n\n::: {.callout-tip}\n## Duas montanhas separadas por um vale raso (densidade baixa, mas não zero) — \"andar por terreno alto\" as trata como um cluster só, ou dois?\n\nDica: pense no que muda se o vale for rebaixado ainda mais, até chegar\na densidade zero, comparado ao vale raso original.\n\n- □ Se o vale entre as duas montanhas nunca é totalmente seco (densidade\n  sempre estritamente positiva em todo o caminho), então, para\n  qualquer limiar de altura $\\lambda$ suficientemente baixo, existe um\n  caminho de terreno \"alto o bastante\" ligando as duas montanhas —\n  então, nesse limiar, elas formam um cluster só.\n- □ A pergunta \"cluster só ou dois clusters\" tem uma resposta fixa,\n  independente de qual altura $\\lambda$ se usa para definir \"terreno\n  alto\".\n- □ Se o vale for rebaixado até ter densidade exatamente zero em algum\n  ponto do caminho, nenhum limiar $\\lambda>0$ jamais conecta as duas\n  montanhas por cima desse ponto.\n- □ Um vale raso entre duas montanhas altas é evidência de que, na\n  verdade, os dados vieram de uma única população, e a divisão em duas\n  montanhas é sempre um artefato de estimação.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## Resposta\n\n::: {.callout-tip}\n## Resposta — cluster só ou dois clusters?\n\n- ✔ Vale nunca seco → para $\\lambda$ baixo o bastante, existe caminho\n  alto conectando — um cluster só nesse limiar.\n- ✗ A resposta depende de $\\lambda$ — é exatamente por isso que\n  \"cluster\" vira uma hierarquia indexada por $\\lambda$, não uma\n  resposta única (Bloco 3).\n- ✔ Vale com densidade exatamente zero em algum ponto: nenhum\n  $\\lambda>0$ conecta por cima desse ponto — barreira genuína.\n- ✗ Vale raso não é evidência de \"sempre um artefato\" — pode ser\n  estrutura real (duas subpopulações genuinamente distintas, ainda que\n  próximas).\n:::\n\n::: {.fragment}\n**Voltando à pergunta:** a resposta depende de $\\lambda$ — e é\nexatamente essa dependência que o Bloco 3 transforma em definição\nformal.\n:::\n\n:::\n\n# Conjuntos de Nível de Densidade\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n\nAntes do formalismo, veja o esqueleto abstrato da metáfora da paisagem\n(Bloco 2) num corte transversal simples: um eixo $\\mathbf{x}$ (aqui em\n1D, só para poder desenhar) e a densidade $p(\\mathbf{x})$ no eixo\nvertical, com duas \"montanhas\" separadas por um \"vale\".\n\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## O Esqueleto Abstrato da Metáfora\n\n::: {.fragment}\nCorte transversal 1D: eixo $\\mathbf{x}$, densidade $p(\\mathbf{x})$ no\neixo vertical — duas \"montanhas\" separadas por um \"vale\".\n:::\n\n:::\n\n::: {.fig-resize style=\"width: 62%; margin: 0 auto;\"}\n```{.tikz}\n\\definecolor{curvecolor}{RGB}{93,109,126}\n\\definecolor{highlight}{RGB}{0,133,202}\n\\definecolor{threshold}{RGB}{224,60,49}\n\n\\begin{tikzpicture}\n% eixos\n\\draw[->, thick, black!70] (-0.3,0) -- (9.6,0) node[right, font=\\small] {$\\mathbf{x}$};\n\\draw[->, thick, black!70] (0,-0.2) -- (0,4.4) node[above, font=\\small] {$p(\\mathbf{x})$};\n\n% curva de densidade: duas montanhas, um vale\n\\draw[smooth, thick, color=curvecolor]\n  plot coordinates {\n    (0,0.3) (0.7,0.4) (1.3,0.9) (1.8,2.0) (2.2,3.4) (2.6,3.9) (3.0,3.4)\n    (3.4,2.0) (3.9,0.9) (4.5,0.6) (5.1,0.9) (5.6,2.0) (6.0,3.4) (6.4,3.9)\n    (6.8,3.4) (7.3,2.0) (7.8,0.9) (8.3,0.4) (9.0,0.3)\n  };\n\n% linha de corte lambda\n\\draw[dashed, thick, color=threshold] (-0.1,2.6) -- (9.3,2.6);\n\\node[left, font=\\small, color=threshold] at (-0.15,2.6) {$\\lambda$};\n\n% duas componentes de L_lambda (trechos da curva acima de lambda)\n\\draw[very thick, color=highlight]\n  plot[smooth] coordinates { (2.0,2.6) (2.2,3.4) (2.6,3.9) (3.0,3.4) (3.2,2.6) };\n\\draw[very thick, color=highlight]\n  plot[smooth] coordinates { (5.8,2.6) (6.0,3.4) (6.4,3.9) (6.8,3.4) (7.0,2.6) };\n\n% vale\n\\draw[dotted, color=threshold] (4.5,0) -- (4.5,0.6);\n\\node[below, font=\\scriptsize, color=threshold] at (4.5,-0.35) {vale};\n\n% rotulos das componentes\n\\node[below, font=\\scriptsize, color=highlight] at (2.6,-0.35) {componente 1};\n\\node[below, font=\\scriptsize, color=highlight] at (6.4,-0.35) {componente 2};\n\n\\node[font=\\small, color=highlight] at (4.7,5.1) {$L_\\lambda=\\{\\mathbf{x}:p(\\mathbf{x})\\ge\\lambda\\}$};\n\\draw[->, color=highlight] (4.3,3.85) -- (3.0,3.55);\n\\draw[->, color=highlight] (5.5,3.85) -- (6.4,3.65);\n\n\\node[font=\\small, color=curvecolor] at (2.6,4.15) {montanha};\n\\node[font=\\small, color=curvecolor] at (6.4,4.15) {montanha};\n\n\\end{tikzpicture}\n```\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n\nFixando um limiar $\\lambda$ (linha vermelha tracejada), o conjunto de\nnível $L_\\lambda=\\{\\mathbf{x}:p(\\mathbf{x})\\ge\\lambda\\}$ é exatamente o\ntrecho do eixo $\\mathbf{x}$ em que a curva azul-acinzentada está acima\nda linha — aqui, **duas componentes conexas disjuntas** (destacadas em\nazul), uma por montanha, porque o vale entre elas fica abaixo de\n$\\lambda$. Baixando $\\lambda$ até abaixo da altura do vale, as duas\ncomponentes se tocariam e passariam a contar como uma componente só —\nexatamente o mecanismo que a figura seguinte (com densidade estimada\nde verdade, via KDE, sobre os dados reais de duas luas) verifica\nnumericamente, variando $\\lambda$ de fato.\n\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n\n::: {.fragment}\nLimiar $\\lambda$ (linha vermelha): $L_\\lambda$ = trecho do eixo onde a curva está acima da linha — aqui, **2 componentes**, uma por montanha\n(o vale fica abaixo de $\\lambda$).\n:::\n\n::: {.fragment}\nBaixar $\\lambda$ até abaixo da altura do vale funde as duas\ncomponentes numa só — verificado a seguir com densidade real (KDE,\nduas luas).\n:::\n\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n\nFormalize a metáfora da paisagem. Para um limiar $\\lambda \\ge 0$,\ndefina o **conjunto de nível** de densidade\n\n$$L_\\lambda = \\{\\mathbf{x} : p(\\mathbf{x}) \\ge \\lambda\\}.$$\n\n$L_\\lambda$ é o \"terreno acima da altura $\\lambda$\" — o conjunto de\ntodos os pontos do espaço onde a densidade é pelo menos $\\lambda$. A\ntese central desta aula, anunciada na Abertura, agora tem uma fórmula:\n\n> **Um cluster, num nível $\\lambda$ fixo, é uma componente conexa de\n> $L_\\lambda$.**\n\nEssa definição já responde ao Bloco 2: uma componente conexa não\nprecisa ser convexa, nem ter contorno regular — só precisa ser um\nbloco de terreno alto que se pode percorrer inteiro sem descer abaixo\nde $\\lambda$. Hastie, Tibshirani & Friedman (ESL, 2009, p. 507)\ndescrevem essa família de método como um dos três paradigmas\nfundamentais de clustering, ao lado do combinatório (baseado em\nprotótipos fixos, como o discutido no Bloco 2 — não o foco desta\ndisciplina) e da modelagem por mistura (que a Aula 4 vai cobrir) —\ntradução livre:\n\n> \"Buscadores de moda ('caçadores de irregularidades') adotam uma\n> perspectiva não-paramétrica, tentando estimar diretamente as modas\n> distintas da função de densidade de probabilidade. As observações\n> 'mais próximas' de cada respectiva moda definem então os clusters\n> individuais.\"\n\n**Os três paradigmas, lado a lado, nos mesmos dados.** Para ver a\ndiferença na prática, não só na definição, rode os três sobre as\nmesmas duas luas:\n\n::: {#c0ae4990 .cell execution_count=4}\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-revealjs/cell-5-output-1.svg){fig-align='center'}\n:::\n:::\n\n\nNos mesmos dados, os dois primeiros paradigmas erram de formas\ndiferentes: o combinatório (KMeans, à esquerda) só sabe traçar\nfronteiras retas entre protótipos — cada lua fica cortada ao meio,\nmetade indo para o cluster errado. A mistura de duas gaussianas (centro)\njá é paramétrica o bastante para inclinar a fronteira, mas continua\nelíptica — ainda erra pontos nas pontas de cada lua. Só o terceiro\n(direita), sem nenhuma suposição de forma, acompanha exatamente o\ncontorno de cada lua — é essa liberdade de forma que motiva usar\nconjuntos de nível de densidade nesta aula.\n\n**O que acontece variando $\\lambda$.** Para $\\lambda$ muito alto, só os\npicos mais extremos de densidade sobrevivem — poucas regiões, pequenas,\nbem separadas (cada montanha isolada pelo próprio topo). Conforme\n$\\lambda$ cai, cada região de $L_\\lambda$ cresce (o \"terreno acima de\n$\\lambda$\" se expande encosta abaixo) e, em algum ponto crítico, duas\nregiões que eram separadas se tocam e se fundem numa só — exatamente o\nfenômeno da Pergunta do Bloco 2. Em $\\lambda=0$, $L_0$ é o suporte\ninteiro da densidade: uma única componente (supondo suporte conexo).\n\nIsso já é, em germe, uma **hierarquia de clusters indexada por\n$\\lambda$**: decrescer $\\lambda$ de $\\infty$ até $0$ nunca separa\ncomponentes que já estavam unidas (só pode fundir, nunca dividir) — a\nmesma estrutura de árvore, de baixo para cima, que o dendrograma da\nAula de hierárquico clássico (Bloco 5) vai produzir. A figura abaixo\nmostra $L_\\lambda$ estimado por KDE nos dados de duas luas, para\nlimiares decrescentes: repare como as duas luas — cada uma uma\ncomponente sozinha nos limiares mais altos — permanecem separadas até\n$\\lambda$ ficar baixo o bastante para o \"vale\" entre elas ser\nabsorvido.\n\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## Formalizando \"Montanha\"\n\n::: {.fragment}\nConjunto de nível de densidade, limiar $\\lambda\\ge 0$:\n$$L_\\lambda = \\{\\mathbf{x} : p(\\mathbf{x}) \\ge \\lambda\\}$$\n:::\n\n::: {.fragment}\n**Definição central da aula:** um cluster, num nível $\\lambda$ fixo, é\numa **componente conexa de $L_\\lambda$** — não precisa ser convexa, só\nprecisa ser percorrível inteira sem descer abaixo de $\\lambda$.\n:::\n\n## Três Paradigmas de Clustering (ESL, p. 507)\n\n::: {.fragment}\n**Combinatório** (Bloco 2): sem modelo de densidade — parte o espaço\npor proximidade a um conjunto fixo de protótipos. Sempre gera regiões\n**convexas** (tesselação de Voronoi); não captura luas nem anéis.\n:::\n\n::: {.fragment}\n**Modelagem por mistura** (Aula 4): assume densidade paramétrica com\n$K$ componentes (ex.: $K$ gaussianas) — cluster = \"de qual componente\neste ponto veio?\", estimado por EM.\n:::\n\n::: {.fragment}\n**\"Mode seeking\"** (esta aula): não assume forma nenhuma — estima as\nmodas da densidade diretamente. Tradução livre (p. 507): *\"observações\nmais próximas de cada moda definem os clusters.\"*\n:::\n\n::: {.fragment}\nOs três respondem à mesma pergunta (\"quem vai com quem?\"), com\nsuposições bem diferentes sobre a forma dos dados — só o terceiro não\nassume nenhuma.\n:::\n\n## Os Três, Lado a Lado\n\n::: {#50af7cbd .cell execution_count=5}\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-revealjs/cell-6-output-1.svg){fig-align='center'}\n:::\n:::\n\n\n::: {.fragment}\nCombinatório e mistura só sabem traçar fronteiras retas/elípticas —\ncada lua fica cortada ao meio. Só o mode seeking (direita), sem\nsuposição de forma, acompanha o contorno real de cada lua.\n:::\n\n## O Que Acontece Variando $\\lambda$\n\n::: {.fragment}\n$\\lambda$ alto: só os picos mais extremos sobrevivem — poucas regiões\npequenas, bem separadas.\n:::\n\n::: {.fragment}\n$\\lambda$ caindo: cada região cresce; em algum ponto, duas regiões\nantes separadas se tocam e se fundem.\n:::\n\n::: {.fragment}\n$\\lambda=0$: $L_0$ é o suporte inteiro — uma componente só (supondo\nsuporte conexo).\n:::\n\n::: {.fragment}\n**Hierarquia indexada por $\\lambda$:** decrescer $\\lambda$ só funde\ncomponentes, nunca separa — mesma lógica do dendrograma (Bloco 5).\n:::\n\n:::\n\n::: {.fig-resize style=\"width: 90%; margin: 0 auto;\"}\n\n::: {#53e37c1e .cell execution_count=6}\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-revealjs/cell-7-output-1.svg){fig-align='center'}\n:::\n:::\n\n\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n\nDa esquerda para a direita, $\\lambda$ cai de $0{,}20$ para $0{,}04$: no\npainel esquerdo, as duas luas ainda são regiões nitidamente separadas\nde $L_\\lambda$ (a área azul); no painel direito, $\\lambda$ já é baixo\no bastante para que o vale entre as luas seja absorvido em $L_\\lambda$\n— as duas regiões se tocam e, para esse $\\lambda$, seriam contadas\ncomo uma componente conexa só. Nenhum $\\lambda$ único é \"o certo\" — é\nexatamente esse problema (qual $\\lambda$ escolher?) que o Bloco 6 vai\nresolver, não escolhendo um único $\\lambda$, mas medindo quanto tempo\ncada cluster \"sobrevive\" ao longo de toda a faixa de $\\lambda$.\n\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## Nenhum $\\lambda$ é \"o Certo\"\n\n::: {.fragment}\n$\\lambda=0{,}20$: as duas luas são regiões separadas de $L_\\lambda$.\n:::\n\n::: {.fragment}\n$\\lambda=0{,}04$: o vale entre as luas já foi absorvido — uma\ncomponente conexa só.\n:::\n\n::: {.fragment}\n**Problema aberto:** qual $\\lambda$ escolher? Resposta no Bloco 6 — não\nescolher um único $\\lambda$, medir *persistência* ao longo de toda a\nfaixa.\n:::\n\n:::\n\n## Pergunta\n\n::: {.callout-tip}\n## No limite $\\lambda \\to \\infty$, quantas componentes conexas tem $L_\\lambda$, em geral?\n\nDica: pense no que sobra de \"terreno acima de $\\lambda$\" quando\n$\\lambda$ é maior que a densidade máxima de qualquer região dos dados.\n\n- □ No limite $\\lambda\\to\\infty$, $L_\\lambda$ é, em geral, o conjunto\n  vazio — nenhum ponto do espaço tem densidade infinita, então nenhum\n  ponto sobrevive ao limiar.\n- □ O número de componentes conexas de $L_\\lambda$ é uma função\n  monótona não-crescente de $\\lambda$ — nunca aumenta conforme $\\lambda$\n  sobe (pode diminuir ou ficar igual, indo a zero no limite).\n- □ Existe sempre um $\\lambda$ finito tal que $L_\\lambda$ tem\n  exatamente uma componente conexa por moda (pico local) da densidade\n  — desde que os picos tenham alturas suficientemente diferentes entre\n  si e o $\\lambda$ seja escolhido logo abaixo do menor pico relevante.\n- □ Se a densidade $p(\\mathbf{x})$ é estritamente positiva em todo o\n  espaço $\\mathbb{R}^d$ (nunca toca zero, mesmo longe dos dados), então\n  $L_\\lambda$ para $\\lambda$ pequeno mas positivo pode ainda ter mais\n  de uma componente conexa, dependendo de como $p$ varia.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## Resposta\n\n::: {.callout-tip}\n## Resposta — o limite $\\lambda \\to \\infty$\n\n- ✔ $\\lambda\\to\\infty$: $L_\\lambda\\to\\emptyset$, em geral (nenhuma\n  densidade real é infinita).\n- ✔ Número de componentes é não-crescente em $\\lambda$ — só funde\n  subindo, nunca divide.\n- ✔ Existe $\\lambda$ que isola cada moda, se as alturas forem bem\n  diferentes e o limiar for escolhido com cuidado.\n- ✔ Mesmo com $p>0$ em todo lugar, $L_\\lambda$ pequeno-positivo pode\n  ter várias componentes — \"positivo\" não é \"uniformemente alto\"; pode\n  haver vales rasos acima de zero mas abaixo de $\\lambda$.\n:::\n\n::: {.fragment}\n**Voltando à pergunta:** o vale raso do Bloco 2 agora tem nome —\ndepende inteiramente de onde $\\lambda$ corta. Os Blocos 4 a 6 constroem,\nem etapas, uma ferramenta computável que termina não dependendo de\nescolher $\\lambda$ à mão.\n:::\n\n:::\n\n# DBSCAN\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n\n**Do conjunto de nível a uma regra mais direta.** O Bloco 3 definiu\ncluster via conjuntos de nível de densidade $L_\\lambda$ — mas isso\nexige estimar $p(\\mathbf{x})$ (KDE) e escolher um $\\lambda$. Existe uma\nvia mais direta e clássica para a mesma ideia (\"cluster = região densa\nconectada\"), baseada só em **contar vizinhos dentro de um raio**, sem\nestimar densidade nenhuma: o **DBSCAN** (*Density-Based Spatial\nClustering of Applications with Noise*, Ester, Kriegel, Sander & Xu,\n1996).\n\n**Os dois parâmetros.** DBSCAN precisa de um raio $\\varepsilon$ e uma\ncontagem mínima `minPts`. Defina a vizinhança\n$N_\\varepsilon(p)=\\{q : d(p,q)\\le\\varepsilon\\}$ — que, por convenção\n(Ester et al., 1996; a mesma que o `scikit-learn` usa), **conta o\npróprio $p$** (afinal $d(p,p)=0\\le\\varepsilon$ sempre). Um ponto $p$ é\n**núcleo** (*core point*) se $|N_\\varepsilon(p)|\\ge\\text{minPts}$ — se\ntem gente suficiente por perto, incluindo ele mesmo.\n\n**Conexão direta e cadeia.** Dois núcleos $p,q$ conectam\n**diretamente** se $d(p,q)\\le\\varepsilon$. Um cluster é formado\nseguindo **cadeias** dessas conexões diretas — o fecho transitivo de\n\"conectar direto\", uma definição **recursiva**, não um teste par a par:\n$p$ e um ponto distante $z$ podem acabar no mesmo cluster sem que\n$d(p,z)\\le\\varepsilon$, desde que exista uma cadeia de núcleos\n$p=x_0,x_1,\\dots,x_m=z$ com $d(x_i,x_{i-1})\\le\\varepsilon$ em cada\npasso. Um ponto não-núcleo que cai a $\\le\\varepsilon$ de algum núcleo\nentra no cluster como **borda** (mas não propaga a cadeia adiante);\nquem sobra — nem núcleo, nem a $\\le\\varepsilon$ de nenhum núcleo —\nvira **ruído**.\n\n**O algoritmo, por extenso.** Nada aqui exige nenhuma peça sofisticada\n— dá para descrever o DBSCAN clássico direto da definição, em poucos\npassos, usando só a matriz de distâncias $D$:\n\n1. Para cada ponto $p$, conte quantos pontos (incluindo o próprio $p$)\n   estão a distância $\\le\\varepsilon$; se houver pelo menos `minPts`,\n   marque $p$ como **núcleo**.\n2. Escolha um núcleo $p$ ainda não visitado e abra um cluster novo;\n   marque $p$ como visitado e ponha $p$ numa fila de busca.\n3. Tire um ponto $q$ da fila e examine todo vizinho $r$ a distância\n   $\\le\\varepsilon$ de $q$: coloque $r$ no cluster atual (núcleo ou\n   borda); se $r$ **também for núcleo** e ainda não tiver sido\n   visitado, marque-o como visitado e **acrescente-o à fila** — é essa\n   propagação, só por núcleos, que forma a cadeia (fecho transitivo).\n4. Repita o passo 3 até a fila esvaziar; volte ao passo 2 para o\n   próximo núcleo ainda não visitado, até cobrir todos os núcleos.\n5. Todo ponto que nunca entrou em cluster nenhum (não é núcleo, e não\n   está a $\\le\\varepsilon$ de nenhum núcleo) fica como **ruído**.\n\n\n\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## O Que é o DBSCAN\n\n::: {.fragment}\nBloco 3: cluster via $L_\\lambda$ — exige estimar $p(\\mathbf{x})$ (KDE)\ne escolher $\\lambda$. **DBSCAN** (Ester, Kriegel, Sander & Xu, 1996)\nataca a mesma ideia de um jeito mais direto — só **contar vizinhos num\nraio**, sem estimar densidade nenhuma.\n:::\n\n::: {.fragment}\nDois parâmetros: raio $\\varepsilon$ e contagem mínima `minPts`.\n$N_\\varepsilon(p)=\\{q:d(p,q)\\le\\varepsilon\\}$ conta o próprio $p$\n(convenção Ester et al. 1996 / `scikit-learn`).\n:::\n\n::: {.fragment .callout-important}\n## Ponto Núcleo\n\n$p$ é **núcleo** se $|N_\\varepsilon(p)|\\ge\\text{minPts}$ — tem gente\nsuficiente por perto, incluindo ele mesmo.\n:::\n\n## Conexão, Cadeia e Cluster\n\n::: {.fragment}\nDois núcleos $p,q$ conectam **diretamente** se $d(p,q)\\le\\varepsilon$.\nUm cluster é uma **cadeia** dessas conexões — fecho transitivo,\ndefinição **recursiva**: $p$ e um $z$ distante podem cair no mesmo\ncluster sem $d(p,z)\\le\\varepsilon$, desde que exista uma cadeia de\nnúcleos entre eles.\n:::\n\n::: {.fragment}\nPonto não-núcleo a $\\le\\varepsilon$ de algum núcleo = **borda** (entra\nno cluster, mas não propaga a cadeia adiante). Quem sobra = **ruído**.\n:::\n\n## O Algoritmo, por Extenso\n\n::: {.fragment}\n**1.** $p$ é **núcleo** se $\\ge$ `minPts` pontos (contando $p$) estão a\n$\\le\\varepsilon$ dele.\n:::\n\n::: {.fragment}\n**2.** Escolha um núcleo ainda não visitado, abra um cluster novo,\nponha-o numa fila.\n:::\n\n::: {.fragment}\n**3.** Tire $q$ da fila; todo vizinho $r$ a $\\le\\varepsilon$ entra no\ncluster; se $r$ **também é núcleo** e não visitado, marque-o e\n**acrescente-o à fila** — só núcleos propagam a busca (a cadeia).\n:::\n\n::: {.fragment}\n**4.** Repita até a fila esvaziar; volte ao passo 2 para o próximo\nnúcleo não visitado.\n:::\n\n::: {.fragment}\n**5.** Quem nunca entrou em nenhum cluster vira **ruído**.\n:::\n\n\n\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n\n**Um jeito mais fácil de checar \"esses dois estão juntos?\".** Decidir\nse dois pontos $p,q$ conectam, do jeito que acabamos de ver, exige\n**duas** verificações separadas: \"$p$ é núcleo?\", \"$q$ é núcleo?\", e só\nentão \"$d(p,q)\\le\\varepsilon$?\". Dá para colapsar tudo isso numa\n**única** comparação de distância — o que também é exatamente o que\nfalta para montar um grafo pesado e usar tudo que já se sabe sobre\ngrafos (Bloco 5). Para isso, é preciso primeiro medir \"o quão núcleo\"\num ponto é, sem fixar $\\varepsilon$ ainda.\n\nO Bloco 3 já definiu cluster em termos de $p(\\mathbf{x})$ — mas $p$\nnunca é conhecido de verdade, só estimado. A Aula 2 já resolveu\nexatamente esse problema com o estimador $k$-NN: fixar $K$ vizinhos e\nmedir o raio $d_K(\\mathbf{x})$ da bola que os captura dá\n$p(\\mathbf{x})\\approx K/(NV)$, com $V$ o volume dessa bola — e $V$\ncresce junto com $d_K(\\mathbf{x})$ (raio maior, volume maior). É por\nisso, e não por coincidência, que $d_K(\\mathbf{x})$ é **inversamente\nrelacionado à densidade local**: ele é literalmente o raio que aparece\nno denominador do estimador. $d_K(\\mathbf{x})$ pequeno significa que\nbastou uma bola pequena (volume pequeno) para juntar $K$ vizinhos —\nregião densa; $d_K(\\mathbf{x})$ grande significa que foi preciso um\nraio grande — região rara. Sem exigir nenhuma forma paramétrica para\n$p$, é essa mesma distância, sem nenhuma mudança na fórmula, que hoje\nrecebe um nome novo — **core distance**, ou distância ao núcleo,\n$\\mathrm{core}_K(\\mathbf{x}) = d_K(\\mathbf{x})$ — e um uso novo: virar\npeso de aresta num grafo.\n\n::: {.callout-note}\n## Premissas desta derivação\n\n1. $\\mathrm{core}_K(\\mathbf{x})$ pequeno $\\Leftrightarrow$ $\\mathbf{x}$\n   está numa região densa (herdado direto da Aula 2).\n2. A distância bruta $d(a,b)$ entre dois pontos, por si só, **não**\n   diz nada sobre a densidade da vizinhança de nenhum dos dois — dois\n   pontos podem estar geometricamente próximos mesmo que um deles more\n   numa região densa e o outro numa região quase vazia.\n3. Um cluster (Bloco 3) é definido por conectividade *dentro de\n   terreno alto* — então a \"distância\" usada para conectar dois pontos\n   no grafo precisa penalizar caminhos que passam por regiões raras,\n   não só medir o comprimento geométrico do caminho.\n:::\n\n**Por que a distância bruta não basta.** Imagine dois pacientes $a$ e\n$b$ com valores de atributos geometricamente próximos — $d(a,b)$\npequeno. Se $a$ mora no meio de uma região densa (muitos pacientes\nparecidos por perto, $\\mathrm{core}_K(a)$ pequeno) e $b$ mora sozinho,\nlonge de qualquer vizinho (região rara, $\\mathrm{core}_K(b)$ grande),\nconectar $a$ e $b$ diretamente pelo valor bruto $d(a,b)$ ignoraria que\n$b$ está, na prática, isolado — $b$ só \"parece\" perto de $a$ porque a\ndistância entre os dois é pequena, não porque existe uma trilha densa\nde pacientes ligando os dois.\n\n**A construção, passo a passo.** Defina a **distância de\nalcançabilidade mútua**\n\n$$d_{\\mathrm{mreach}}(a,b) = \\max\\bigl(\\mathrm{core}_K(a),\\ \\mathrm{core}_K(b),\\ d(a,b)\\bigr).$$\n\nEla \"acalma\" pontos em regiões raras: se $b$ está isolado\n($\\mathrm{core}_K(b)$ grande), então $d_{\\mathrm{mreach}}(a,b) \\ge\n\\mathrm{core}_K(b)$ para **qualquer** $a$ — $b$ nunca parece mais\npróximo de ninguém do que sua própria distância ao vale mais próximo\npermite. Ao mesmo tempo, se $a$ e $b$ moram na mesma região densa\n(ambos os *core distances* pequenos e $d(a,b)$ também pequeno),\n$d_{\\mathrm{mreach}}(a,b)$ continua pequeno — a distância bruta domina o\nmáximo, e a conexão é barata, exatamente o que se espera de dois\npontos dentro da mesma \"montanha\".\n\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## $d_K(\\mathbf{x})$, Um Uso Novo\n\n::: {.fragment}\nChecar \"$p,q$ conectam?\" exige **duas** verificações (núcleo? núcleo?\ndistância?). Dá pra colapsar numa **única** comparação — e é o que\nfalta pra montar um grafo pesado (Bloco 5).\n:::\n\n::: {.fragment}\nAula 2: $p(\\mathbf{x})\\approx K/(NV)$, $V$ = volume da bola de raio\n$d_K(\\mathbf{x})$ que captura $K$ vizinhos. $V$ cresce com $d_K$ — o\nraio está no denominador do estimador.\n:::\n\n::: {.fragment}\nNão é coincidência: $d_K(\\mathbf{x})$ pequeno $\\Rightarrow$ bola\npequena bastou $\\Rightarrow$ região densa; $d_K(\\mathbf{x})$ grande\n$\\Rightarrow$ precisou de raio grande $\\Rightarrow$ região rara.\n:::\n\n::: {.fragment}\nHoje: mesmo número, novo nome — **core distance** —\n$\\mathrm{core}_K(\\mathbf{x}) = d_K(\\mathbf{x})$ — e novo uso: peso de\naresta num grafo.\n:::\n\n## Premissas Desta Derivação\n\n::: {.callout-note icon=false}\n**1.** $\\mathrm{core}_K(x)$ pequeno $\\Leftrightarrow$ região densa.\n\n**2.** Distância bruta $d(a,b)$ não diz nada sobre densidade da\nvizinhança de $a$ ou $b$.\n\n**3.** Cluster = conectividade *dentro de terreno alto* — a distância\ndo grafo precisa penalizar caminhos por regiões raras.\n:::\n\n## Por Que a Distância Bruta Não Basta\n\n::: {.fragment}\n$a$ numa região densa (muita gente parecida por perto); $b$ sozinho,\nlonge de todo vizinho — mas $d(a,b)$ pequeno.\n:::\n\n::: {.fragment}\nConectar $a,b$ pela distância bruta ignora que $b$ está, na prática,\nisolado — $b$ só \"parece\" perto de $a$, sem trilha densa ligando os\ndois.\n:::\n\n:::\n\n::: {.fig-resize style=\"width: 55%; margin: 0 auto;\"}\n```{.tikz}\n\\definecolor{boxfill}{RGB}{224,242,241}\n\\definecolor{boxborder}{RGB}{17,122,101}\n\\definecolor{resfill}{RGB}{255,232,214}\n\\definecolor{resborder}{RGB}{255,94,0}\n\n\\begin{tikzpicture}[\n  inp/.style={rectangle, rounded corners, fill=boxfill, draw=boxborder, line width=1.2pt, text=black, minimum width=4.6cm, minimum height=1cm, align=center, font=\\small},\n  outbox/.style={rectangle, rounded corners, fill=resfill, draw=resborder, line width=1.2pt, text=black, minimum width=5.2cm, minimum height=1.2cm, align=center, font=\\small},\n  arr/.style={draw=black!60, thick, ->}\n]\n\n\\node[inp] (A) at (0,2.4) {$\\mathrm{core}_K(a)$};\n\\node[inp] (B) at (0,1.2) {$\\mathrm{core}_K(b)$};\n\\node[inp] (C) at (0,0) {$d(a,b)$ (distância bruta)};\n\\node[outbox] (M) at (5.4,1.2) {$d_{\\mathrm{mreach}}(a,b) = \\max(\\cdot,\\cdot,\\cdot)$};\n\n\\draw[arr] (A) -- (M);\n\\draw[arr] (B) -- (M);\n\\draw[arr] (C) -- (M);\n\n\\end{tikzpicture}\n```\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n\nO diagrama resume a construção: três quantidades entram, uma sai. Note\nque $d_{\\mathrm{mreach}}$ é sempre **maior ou igual** à distância bruta\n$d(a,b)$ — a alcançabilidade mútua nunca aproxima pontos, só os afasta\nquando algum dos dois mora numa região rara. Essa assimetria (só\nafastar, nunca aproximar) é o mecanismo exato de \"acalmar\" pontos\nisolados sem alterar em nada as distâncias dentro de uma região já\ndensa.\n\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## A Construção, Passo a Passo\n\n::: {.fragment}\n$$d_{\\mathrm{mreach}}(a,b) = \\max\\bigl(\\mathrm{core}_K(a), \\mathrm{core}_K(b), d(a,b)\\bigr)$$\n:::\n\n::: {.fragment}\nSe $b$ está isolado ($\\mathrm{core}_K(b)$ grande):\n$d_{\\mathrm{mreach}}(a,b) \\ge \\mathrm{core}_K(b)$ para **qualquer**\n$a$ — $b$ nunca parece mais perto de ninguém do que permite sua própria\ndistância ao vale mais próximo.\n:::\n\n::: {.fragment}\nSe $a,b$ moram na mesma região densa: $d_{\\mathrm{mreach}}(a,b)$\ncontinua pequeno — a distância bruta domina o máximo.\n:::\n\n::: {.fragment}\n**Nunca aproxima, só afasta:** $d_{\\mathrm{mreach}}(a,b)\\ge d(a,b)$\nsempre — acalma isolados sem alterar nada dentro de uma região já\ndensa.\n:::\n\n:::\n\n::: {#8527f532 .cell execution_count=9}\n``` {.python .cell-code}\n# Núcleo pequeno (K=5) sobre os dois atributos reais que vão sustentar\n# o Bloco 6 -- ilustra a \"calma\" da alcançabilidade mútua em 5 pacientes\n# escolhidos deliberadamente: 4 numa vizinhança densa, 1 isolado.\n_tree_2d = cKDTree(X_2d)\n_core_2d = core_distance(X_2d, K=5)\n_isolado = np.argmax(_core_2d)          # paciente com o maior core distance\n_denso = np.argsort(_core_2d)[:4]        # 4 pacientes na região mais densa\n\n_a, _b = _denso[0], _isolado\n_d_raw = np.linalg.norm(X_2d[_a] - X_2d[_b])\n_d_mreach = max(_core_2d[_a], _core_2d[_b], _d_raw)\nprint(f\"core({_a})={_core_2d[_a]:.3f}  core({_b})={_core_2d[_b]:.3f}  \"\n      f\"d_bruta={_d_raw:.3f}  d_mreach={_d_mreach:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncore(418)=0.033  core(461)=1.288  d_bruta=5.388  d_mreach=5.388\n```\n:::\n:::\n\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n\nNeste exemplo com os dados reais do Breast Cancer Wisconsin (usando\napenas os dois atributos de visualização deste bloco em diante,\n`radius_worst` e `concave points_worst`, padronizados), o paciente mais\nisolado tem $\\mathrm{core}_5$ visivelmente maior que a distância bruta\naté um paciente da região densa — então $d_{\\mathrm{mreach}}$ é\ndominado pelo *core distance* do isolado, não pela distância bruta:\nexatamente o comportamento \"acalmante\" descrito acima, agora visto num\nnúmero real, não só na fórmula.\n\n:::\n\n## Pergunta\n\n::: {.callout-tip}\n## Se $\\mathrm{core}_K(a) = \\mathrm{core}_K(b) = 0$ (dois pontos coincidentes com pelo menos $K$ outros pontos na mesma posição exata), o que $d_{\\mathrm{mreach}}(a,b)$ vale?\n\nDica: releia a fórmula — o que o $\\max$ faz quando dois dos três termos\nsão zero?\n\n- □ Se $\\mathrm{core}_K(a)=\\mathrm{core}_K(b)=0$, então\n  $d_{\\mathrm{mreach}}(a,b) = d(a,b)$ — a distância bruta passa a\n  decidir sozinha, porque os dois termos de núcleo não competem com\n  ela no máximo.\n- □ $d_{\\mathrm{mreach}}(a,b)$ sempre vale zero quando pelo menos um\n  dos dois *core distances* é zero, independente do valor de $d(a,b)$.\n- □ Num caso extremo em que $d(a,b)=0$ também (os próprios $a$ e $b$\n  coincidem exatamente), $d_{\\mathrm{mreach}}(a,b)=0$.\n- □ Esse caso extremo (core distance zero) é impossível de ocorrer na\n  prática com dados reais, então não precisa ser considerado ao\n  implementar a fórmula.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## Resposta\n\n::: {.callout-tip}\n## Resposta — o caso extremo $\\mathrm{core}_K=0$\n\n- ✔ Com os dois núcleos em zero, $d_{\\mathrm{mreach}}(a,b)=d(a,b)$ — a\n  distância bruta decide.\n- ✗ Não basta um dos dois ser zero — o outro ainda entra no $\\max$; só\n  se ambos forem zero (ou menores que $d(a,b)$) a bruta domina.\n- ✔ Com os três termos em zero, o máximo é zero.\n- ✗ Dados reais com valores repetidos/arredondados (ex.: medições\n  discretizadas) produzem core distance zero com frequência — o caso\n  precisa, sim, ser tratado.\n:::\n\n::: {.fragment}\n**Voltando à pergunta:** quando ambos os núcleos são pequenos (região\ndensa dos dois lados), a alcançabilidade mútua colapsa na distância\nbruta — exatamente o comportamento que o Bloco 5 vai usar para\nconstruir o grafo completo.\n:::\n\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n\n**A vantagem: uma distância só, em vez de duas verificações.** Com\n$d_{\\mathrm{mreach}}$ definida para todo par, dá para checar se $p$ e\n$q$ conectam com uma **única** comparação de distância — sem verificar\n\"núcleo?\" separadamente para cada um. Escolha um limiar $\\varepsilon$,\nconstrua o grafo cujos vértices são os $N$ pontos e cujas arestas ligam\n$u,v$ sempre que $d_{\\mathrm{mreach}}(u,v)\\le\\varepsilon$, e tome as\n**componentes conexas** desse grafo — cada componente é um cluster;\npontos sem nenhuma aresta (porque o $\\mathrm{core}_K$ deles já é maior\nque $\\varepsilon$) ficam isolados e viram ruído, sem nenhuma etapa\nextra.\n\n**Por que isso é exatamente o DBSCAN da seção anterior.** Lembrando:\nDBSCAN define $p$ como núcleo se $|N_\\varepsilon(p)|\\ge\\text{minPts}$ e\nconecta diretamente dois núcleos $p,q$ se $d(p,q)\\le\\varepsilon$.\n\n**Atenção a um detalhe de contagem que muda o resultado.**\n$N_\\varepsilon(p)$ conta o próprio $p$ (a distância de $p$ a si mesmo é\n$0\\le\\varepsilon$, sempre) — é a convenção original do DBSCAN (Ester et\nal., 1996) e a que o `scikit-learn` usa. Então \"pelo menos `minPts`\npontos em $N_\\varepsilon(p)$, contando $p$\" significa \"pelo menos\n$\\text{minPts}-1$ **outros** pontos a distância $\\le\\varepsilon$\" — e\n$\\mathrm{core}_K(p)$, por definição, é a distância ao $K$-ésimo vizinho\n**sem contar $p$**. O $K$ certo, portanto, é\n$$K = \\text{minPts} - 1,$$\nnão $K=\\text{minPts}$ (testei os dois numericamente contra o\n`DBSCAN` do `scikit-learn`: com $K=\\text{minPts}-1$ os conjuntos de\npontos-núcleo batem exatamente; com $K=\\text{minPts}$, não — sobra\nsistematicamente um ponto de vizinhança por causa dessa contagem).\n\nCom esse $K$, \"$p$ é núcleo a um limiar $\\varepsilon$\" é exatamente\n\"$\\mathrm{core}_K(p)\\le\\varepsilon$\", a própria definição de core\ndistance. Logo, os dois requisitos do DBSCAN para uma conexão direta —\n\"$p$ núcleo, $q$ núcleo, e $d(p,q)\\le\\varepsilon$\" — viram\n$$\n\\mathrm{core}_K(p)\\le\\varepsilon \\ \\text{e}\\ \\mathrm{core}_K(q)\\le\\varepsilon \\ \\text{e}\\ d(p,q)\\le\\varepsilon\n\\quad\\iff\\quad\n\\max\\bigl(\\mathrm{core}_K(p),\\mathrm{core}_K(q),d(p,q)\\bigr)\\le\\varepsilon\n\\quad\\iff\\quad\nd_{\\mathrm{mreach}}(p,q)\\le\\varepsilon.\n$$\nO grafo de $d_{\\mathrm{mreach}}$ cortado em $\\varepsilon$ e o grafo de\nnúcleos do DBSCAN nesses mesmos parâmetros\n($\\varepsilon,\\ \\text{minPts}=K+1$) têm exatamente as mesmas arestas —\nlogo, as mesmas componentes conexas, os mesmos clusters. Essa variante,\nque só liga núcleo a núcleo (sem a etapa extra de \"anexar ponto de\nborda ao cluster mais próximo\" do DBSCAN original), é chamada\n**DBSCAN\\*** no artigo do HDBSCAN (Campello, Moulavi & Sander, 2013).\n\n**O desafio que sobra: como escolher os parâmetros?** DBSCAN (ou sua\nversão $d_{\\mathrm{mreach}}$) funciona bem — mas exige fixar\n$\\varepsilon$ e `minPts`/$K$ *a priori*, sem nenhum critério óbvio para\nescolhê-los, e o resultado pode mudar bastante conforme esses valores\nmudam. Em vez de tentar adivinhar o $\\varepsilon$ \"certo\" de uma vez,\nexiste uma saída mais palpável: construir a hierarquia inteira,\nvariando $\\varepsilon$ de $0$ a $\\infty$, e decidir depois onde (e se)\ncortar. É essa ideia — clustering hierárquico — que resolve o problema\nde frente.\n\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## Como Isso Vira o DBSCAN da Seção Anterior\n\n::: {.fragment}\nEscolha um limiar $\\varepsilon$. Monte o grafo: aresta $(u,v)$ sempre\nque $d_{\\mathrm{mreach}}(u,v)\\le\\varepsilon$ — **uma única** comparação,\nem vez de núcleo + núcleo + distância separadamente.\n:::\n\n::: {.fragment}\n**Componentes conexas** = clusters. Pontos sem aresta nenhuma\n($\\mathrm{core}_K$ maior que $\\varepsilon$) ficam isolados = ruído.\n:::\n\n## Por Dentro da Equivalência\n\n::: {.fragment}\n**Detalhe que importa:** $N_\\varepsilon(p)$ conta o próprio $p$\n(convenção do DBSCAN original/`scikit-learn`), mas $\\mathrm{core}_K(p)$\nnão conta $p$. O $K$ certo é $K=\\text{minPts}-1$, não $\\text{minPts}$\n(verificado numericamente contra o `DBSCAN` do `scikit-learn`).\n:::\n\n::: {.fragment}\nCom $K=\\text{minPts}-1$: \"$p$ núcleo\" $\\iff$\n$\\mathrm{core}_K(p)\\le\\varepsilon$ — a própria definição de core\ndistance.\n:::\n\n::: {.fragment}\nLogo: \"$p,q$ núcleos e $d(p,q)\\le\\varepsilon$\" $\\iff$\n$\\max(\\mathrm{core}_K(p),\\mathrm{core}_K(q),d(p,q))\\le\\varepsilon$\n$\\iff$ $d_{\\mathrm{mreach}}(p,q)\\le\\varepsilon$ — mesma aresta, mesmo\ngrafo, mesmos clusters (**DBSCAN\\***, Campello, Moulavi & Sander 2013).\n:::\n\n## O Desafio que Sobra\n\n::: {.fragment}\nDBSCAN/$d_{\\mathrm{mreach}}$ funcionam, mas exigem fixar $\\varepsilon$\ne `minPts`/$K$ *a priori*, sem critério óbvio — o resultado muda\nbastante conforme esses valores mudam.\n:::\n\n::: {.fragment}\nSaída mais palpável: construir a hierarquia **inteira**, variando\n$\\varepsilon$ de $0$ a $\\infty$, e decidir depois onde cortar —\n**clustering hierárquico**.\n:::\n\n:::\n\n# Clustering Hierárquico\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n\n**Motivação: sentir o número de clusters sem fixar um único corte.** O\nBloco 4 terminou num desafio: DBSCAN (com ou sem $d_{\\mathrm{mreach}}$)\nexige fixar $\\varepsilon$ e `minPts`/$K$ de antemão, sem critério óbvio\npara escolhê-los. Clustering hierárquico ataca o problema de outro\njeito: em vez de escolher um corte e ver o que sai, constrói a\n**sequência inteira** de partições aninhadas, de $N$ clusters (um por\nponto) até $1$ cluster (todo mundo junto), e só depois — ou nunca,\ndeixando a árvore inteira como resposta — decide onde cortar. É\nexatamente essa ideia, aplicada à hierarquia de $d_{\\mathrm{mreach}}$\nem vez da distância bruta, que o Bloco 6 (HDBSCAN) vai usar para\nextrair clusters sem escolher nenhum $\\lambda$ à mão.\n\n**Como funciona: aglomerativo, de baixo para cima.** Um algoritmo\nhierárquico aglomerativo começa com $N$ clusters — um por ponto — e, a\ncada passo, funde os **dois clusters mais próximos** num só, sempre num\nnível de dissimilaridade maior que o passo anterior, até sobrar um\núnico cluster com todo mundo dentro. Essa sequência de $N-1$ fusões é a\n**hierarquia** propriamente dita — o **dendrograma**. O que falta\nespecificar é uma única coisa: o que significa \"distância entre dois\n*clusters*\" (não entre dois pontos) — existem várias regras possíveis\npara isso, e a Aula usa uma específica.\n\n**Ligação simples (single linkage).** Hastie, Tibshirani & Friedman\n(ESL, 2009, §14.3.12) descrevem a regra desta aula, tradução livre —\n\n> \"*Ligação simples* (SL) toma a dissimilaridade intergrupo como a do\n> par mais próximo (menos dissimilar): $d_{SL}(G,H) = \\min_{i\\in G,\n> i'\\in H} d_{ii'}$. Isso também é chamado, com frequência, de técnica\n> do *vizinho mais próximo*.\" (p. 523)\n\nO algoritmo hierárquico aglomerativo por ligação simples começa com $N$\nclusters (um por ponto) e, a cada passo, funde os dois clusters cuja\nmenor distância entre um par de membros é a menor de todas — produzindo\numa sequência de $N-1$ fusões, cada uma em um nível de dissimilaridade\nmaior que a anterior (ESL, p. 520-521, tradução livre): *\"cada nível\nda hierarquia representa um agrupamento particular [...] a árvore\nbinária [...] tem $N-1$ níveis\"*.\n\n**O custo de fazer isso ingenuamente.** Construir essa hierarquia do\nzero — recalculando, a cada uma das $N-1$ fusões, qual par de clusters\nestá mais próximo — parece exigir refazer o trabalho inteiro para cada\n$k$ diferente que se queira testar. Existe um atalho: uma única\nestrutura, com apenas $N-1$ arestas, que já contém a hierarquia inteira\nde ligação simples de uma vez — a **Árvore Geradora Mínima** (MST).\n\nCom uma matriz de distâncias definida para todo par de pontos (aqui,\n$d_{\\mathrm{mreach}}$, mas o argumento a seguir vale para qualquer\ndistância), construa o **grafo completo** cujos vértices são os $N$\npontos e cujo peso de aresta $(i,j)$ é a distância entre eles. Esse\ngrafo tem $N(N-1)/2$ arestas — muitas delas redundantes, no sentido de\nque existem vários caminhos possíveis entre o mesmo par de vértices.\nUma **árvore geradora** (*spanning tree*) é um subgrafo que conecta\ntodos os $N$ vértices usando exatamente $N-1$ arestas e nenhum ciclo —\no mínimo de arestas que ainda mantém tudo ligado. Entre todas as\nárvores geradoras possíveis desse grafo (e existem muitas), a que\nminimiza a soma dos pesos das suas $N-1$ arestas é a **Árvore Geradora\nMínima** (*Minimum Spanning Tree*, MST).\n\n**Teorema (equivalência MST–ligação simples; Gower & Ross, 1969).** Seja\n$G$ o grafo completo de pesos $d(i,j)$ e, para um limiar $\\tau\\ge0$,\nseja $G_\\tau$ o subgrafo de $G$ restrito às arestas de peso $\\le\\tau$.\nSeja $T$ a MST de $G$ e $T_\\tau$ o subgrafo de $T$ restrito às arestas\nde peso $\\le\\tau$. Então, **para todo $\\tau$, $G_\\tau$ e $T_\\tau$ têm\nexatamente as mesmas componentes conexas** — ou seja, os clusters de\nligação simples no nível $\\tau$ (componentes de $G_\\tau$, por\ndefinição) são idênticos às componentes obtidas cortando de $T$ só as\narestas de peso $>\\tau$.\n\n*Prova.* Como $T\\subseteq G$ (toda aresta da MST é uma aresta de $G$),\n$T_\\tau\\subseteq G_\\tau$: qualquer caminho dentro de $T_\\tau$ também é\num caminho dentro de $G_\\tau$, logo toda componente de $T_\\tau$ está\ncontida numa componente de $G_\\tau$. Falta a direção que não é óbvia:\nse $p$ e $q$ estão na mesma componente de $G_\\tau$ (existe *algum*\ncaminho entre eles em $G$ usando só arestas $\\le\\tau$), eles também\nprecisam estar na mesma componente de $T_\\tau$. Chame de **custo** de\num caminho o **maior** peso de aresta ao longo dele — o \"elo mais fraco\nda corrente\". A MST tem a propriedade do **caminho de gargalo mínimo**\n(resultado clássico de teoria de grafos): o caminho entre $p$ e $q$\n*dentro da MST* — único, já que é uma árvore — tem sempre o menor custo\npossível entre **todos** os caminhos de $p$ a $q$ em $G$; nenhuma rota\nalternativa consegue um elo mais fraco mais barato. Por hipótese existe\num caminho em $G$ de custo $\\le\\tau$ (o que exibe $p,q$ na mesma\ncomponente de $G_\\tau$); logo o custo mínimo entre $p$ e $q$ é\n$\\le\\tau$; logo o caminho da MST entre eles também tem custo $\\le\\tau$\n— ou seja, esse caminho inteiro sobrevive em $T_\\tau$, colocando $p$ e\n$q$ na mesma componente de $T_\\tau$. $\\blacksquare$\n\n**Consequência prática.** Cortar as $k-1$ arestas mais pesadas da MST é\nsó escolher $\\tau$ logo abaixo do peso da $(k-1)$-ésima aresta mais\npesada — pelo teorema, isso produz exatamente as $k$ componentes do\nclustering por ligação simples com $k$ clusters, para qualquer $k$, sem\nrecalcular nada.\n\n**Verificando num exemplo pequeno.** O teorema já garante a igualdade;\nmesmo assim vale conferir com números antes de seguir em frente, um\n*worked example* no espírito da técnica de \"exemplo resolvido antes do\nresultado geral\".\n\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## Sentir o Número de Clusters, sem Fixar um Corte\n\n::: {.fragment}\nBloco 4 terminou num desafio: DBSCAN exige fixar $\\varepsilon$ e\n`minPts`/$K$ sem critério óbvio. Clustering hierárquico ataca isso\ndiferente: constrói a **sequência inteira** de partições, de $N$\nclusters a $1$, e só depois decide onde cortar.\n:::\n\n::: {.fragment}\nEssa ideia, sobre a hierarquia de $d_{\\mathrm{mreach}}$, é o que o\nBloco 6 (HDBSCAN) usa pra extrair clusters sem escolher $\\lambda$ à\nmão.\n:::\n\n## O Algoritmo: Aglomerativo por Ligação Simples\n\n::: {.fragment}\nComeça com $N$ clusters, um por ponto; a cada passo funde os **dois\nclusters mais próximos** num só — $N-1$ fusões até sobrar um cluster\ncom todo mundo, cada fusão num nível de dissimilaridade **maior** que a\nanterior. Essa sequência é a **hierarquia** (o dendrograma).\n:::\n\n::: {.fragment}\nFalta definir \"distância entre dois *clusters*\" (não entre dois\npontos). A regra desta aula, **ligação simples**: distância entre\nclusters = distância do **par mais próximo**, um de cada lado. ESL\n(p. 523), tradução livre: *\"a dissimilaridade intergrupo [é] a do par\nmais próximo: $d_{SL}(G,H)=\\min_{i\\in G,i'\\in H} d_{ii'}$\"* — o\n\"vizinho mais próximo\".\n:::\n\n::: {.fragment}\n**O custo de fazer isso ingenuamente:** recalcular, a cada uma das\n$N-1$ fusões, qual par de clusters está mais próximo parece exigir\nrefazer tudo pra cada $k$ diferente. Atalho: uma única estrutura,\n$N-1$ arestas, contém a hierarquia inteira de uma vez — a **Árvore\nGeradora Mínima** (MST).\n:::\n\n## O Que é uma Árvore Geradora\n\n::: {.fragment}\nGrafo completo, pesos $d(i,j)$: $N$ vértices, $N(N-1)/2$ arestas —\nconectado, mas redundante (vários caminhos possíveis entre o mesmo\npar).\n:::\n\n::: {.fragment}\n**Árvore geradora** (*spanning tree*): subgrafo que conecta todos os\n$N$ vértices com só $N-1$ arestas, sem ciclo — o mínimo de arestas que\nainda mantém tudo ligado.\n:::\n\n::: {.fragment .callout-important}\n## A Árvore Geradora *Mínima* (MST)\n\nEntre todas as árvores geradoras possíveis, a **MST** é a que minimiza\na soma dos pesos das suas $N-1$ arestas.\n:::\n\n## Teorema (Gower & Ross, 1969)\n\n::: {.fragment .callout-important}\n## Equivalência MST–Ligação Simples\n\nPara todo limiar $\\tau$: as componentes conexas do grafo completo\nrestrito a arestas $\\le\\tau$ **são idênticas** às componentes obtidas\ncortando da MST só as arestas $>\\tau$.\n:::\n\n::: {.fragment}\n($\\subseteq$) MST $\\subseteq$ grafo completo — todo caminho na MST\ncortada já é um caminho no grafo completo cortado. Direção fácil.\n:::\n\n::: {.fragment}\n($\\supseteq$, a direção que importa) Se $p,q$ conectam no grafo\ncompleto em $\\tau$, existe *algum* caminho de custo $\\le\\tau$ (custo =\nmaior aresta do caminho, o \"elo mais fraco\").\n:::\n\n::: {.fragment .callout-important}\n## Propriedade do Caminho de Gargalo Mínimo\n\nO caminho entre $p$ e $q$ **dentro da MST** (único) sempre tem o\n**menor custo possível** entre todos os caminhos de $p$ a $q$ no grafo\ncompleto — resultado clássico de teoria de grafos.\n:::\n\n::: {.fragment}\nLogo o caminho da MST entre $p,q$ também tem custo $\\le\\tau$ — sobrevive\ninteiro em $T_\\tau$. $\\blacksquare$\n:::\n\n::: {.fragment}\n**Consequência prática:** cortar as $k-1$ arestas mais pesadas da MST =\nescolher $\\tau$ logo abaixo da $(k-1)$-ésima aresta mais pesada. Pelo\nteorema, isso dá exatamente os $k$ clusters de ligação simples, **para\nqualquer $k$**, sem recalcular nada.\n:::\n\n:::\n\n## Verificando com um Exemplo Pequeno\n\n\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n\n::: {#fa1f4e9e .cell execution_count=11}\n``` {.python .cell-code}\nprint(\"Arestas da MST (i, j, peso), ordem crescente:\")\nfor i, j, w in edges_pts:\n    print(f\"  ({i},{j}) peso={w:.3f}\")\n\nfor k, (labels_mst, labels_sl, iguais) in _resultado_k.items():\n    print(f\"k={k}:  MST-corte = {labels_mst}   ligação-simples = {labels_sl}   partições idênticas? {iguais}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nArestas da MST (i, j, peso), ordem crescente:\n  (3,5) peso=0.412\n  (3,4) peso=0.500\n  (0,1) peso=0.583\n  (1,2) peso=0.671\n  (2,5) peso=6.140\n  (5,6) peso=6.223\nk=2:  MST-corte = [0 0 0 0 0 0 1]   ligação-simples = [1 1 1 1 1 1 2]   partições idênticas? True\nk=3:  MST-corte = [0 0 0 1 1 1 2]   ligação-simples = [2 2 2 1 1 1 3]   partições idênticas? True\n```\n:::\n:::\n\n\n:::\n\n::: {.fig-resize style=\"width: 55%; margin: 0 auto;\"}\n\n::: {#873e56a3 .cell execution_count=12}\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-revealjs/cell-13-output-1.svg){fig-align='center'}\n:::\n:::\n\n\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n\nOs 7 pontos formam visualmente três grupos: A ($0,1,2$, perto da\norigem), B ($3,4,5$, perto de $(5,5)$) e o ponto isolado $6$ ($(9{,}5,\n0{,}2)$). A MST tem, como esperado, $6$ arestas ($N-1=6$): quatro\narestas curtas dentro de A e B (pesos entre $0{,}41$ e $0{,}67$) e duas\narestas longas ligando os grupos entre si e ao ponto isolado (pesos\n$6{,}14$ e $6{,}22$) — exatamente as duas arestas mais pesadas.\n\nCortando a aresta mais pesada ($k=2$): sobra $\\{0,1,2,3,4,5\\}$ de um\nlado e $\\{6\\}$ isolado do outro — e o clustering por ligação simples\ncom $k=2$ produz **exatamente a mesma partição** (o código acima\nconfirma: partições idênticas). Cortando também a segunda mais pesada\n($k=3$): sobra $\\{0,1,2\\}$, $\\{3,4,5\\}$ e $\\{6\\}$ — os três grupos\nvisuais, de novo idênticos à ligação simples. Note que\nem $k=2$ os grupos A e B se fundem antes de $6$ se juntar a qualquer um\ndeles — porque a menor distância entre A e B ($6{,}14$) é, por pouco,\nmenor que a menor distância de $6$ a qualquer dos dois grupos\n($6{,}22$); um exemplo de que \"vizinho mais próximo\" pode produzir\nfusões que não são as mais \"intuitivas\" à primeira vista, mas são as\nmatematicamente corretas pela definição de ligação simples.\n\n**A vantagem desta construção.** A MST, uma única estrutura com $N-1$ arestas,\ncontém a hierarquia completa: para obter o clustering de ligação\nsimples em **qualquer** número de clusters $k$, basta ordenar as\narestas da MST por peso e cortar as $k-1$ mais pesadas — sem refazer\nnenhum cálculo de distância. É a compressão exata da paisagem inteira\nde $\\lambda$s do Bloco 3 numa única árvore.\n\nUm aviso honesto, também do ESL (p. 524, tradução livre), sobre a\nligação simples especificamente: *\"Como a ligação simples exige apenas\nque uma única dissimilaridade seja pequena para que dois grupos sejam\nconsiderados próximos, [...] ela terá tendência a combinar, em\nlimiares relativamente baixos, observações ligadas por uma série de\nobservações intermediárias próximas. Esse fenômeno, chamado de\n*encadeamento* (*chaining*), é frequentemente considerado um defeito do\nmétodo.\"* — uma fileira de pontos, cada um perto do próximo, pode\nencadear dois grupos que \"deveriam\" ser distintos. É esse defeito,\nmais o problema de \"que $k$/$\\lambda$ escolher\" do Bloco 3, que o\nBloco 6 ataca.\n\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n::: {.fragment}\nNa figura acima: 7 pontos, 3 grupos visuais — A ($0,1,2$), B\n($3,4,5$), ponto isolado $6$. MST tem $N-1=6$ arestas; as duas\ntracejadas em vermelho são as **duas mais pesadas**.\n:::\n\n::: {.fragment}\n$k=2$ (corta 1 aresta mais pesada): MST dá $\\{0..5\\},\\{6\\}$ — ligação\nsimples dá **o mesmo** (partições idênticas, conferido no código).\n:::\n\n::: {.fragment}\n$k=3$ (corta 2 mais pesadas): MST dá $\\{0,1,2\\},\\{3,4,5\\},\\{6\\}$ —\nligação simples de novo **idêntico**.\n:::\n\n::: {.fragment}\nCurioso: A e B se fundem antes de $6$ ($6{,}14 < 6{,}22$) — \"vizinho\nmais próximo\" nem sempre é o mais intuitivo à primeira vista, mas é\ncorreto pela definição.\n:::\n\n## A Vantagem da MST\n\n::: {.fragment}\nUma única árvore de $N-1$ arestas contém a hierarquia inteira — para\nqualquer $k$, corte as $k-1$ arestas mais pesadas, sem recálculo.\n:::\n\n::: {.fragment}\nESL (p. 524), tradução livre, sobre o defeito da ligação simples:\n*\"tendência a combinar [...] observações ligadas por uma série de\nobservações intermediárias próximas [...] chamado de *encadeamento*\"*.\n:::\n\n::: {.fragment}\nEncadeamento + \"que $k$/$\\lambda$ escolher?\" (Bloco 3) → o Bloco 6\nataca os dois.\n:::\n\n:::\n\n## Pergunta\n\n::: {.callout-tip}\n## Se um único ponto de ruído for inserido exatamente no meio do \"vale\" entre dois clusters genuinamente distintos, o que acontece com a MST e com o clustering por ligação simples resultante?\n\nDica: pense no \"encadeamento\" citado do ESL — o que uma única\nobservação intermediária bem posicionada consegue fazer.\n\n- □ Esse único ponto de ruído pode, por si só, criar uma aresta curta\n  ligando os dois clusters através dele, fazendo a ligação simples\n  fundir os dois clusters num nível de dissimilaridade bem mais baixo\n  do que fundiria sem esse ponto.\n- □ Um único ponto no meio do vale nunca afeta a MST global, porque a\n  MST é definida pela soma total de pesos, e um único ponto tem peso\n  desprezível relativo ao total.\n- □ Esse cenário é exatamente o que o ESL chama de *chaining*\n  (encadeamento) — um defeito citado explicitamente do método de\n  ligação simples.\n- □ O problema desapareceria completamente ao usar $d_{\\mathrm{mreach}}$\n  em vez da distância bruta, porque a alcançabilidade mútua nunca\n  permite encadeamento em nenhuma circunstância.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## Resposta\n\n::: {.callout-tip}\n## Resposta — um ponto de ruído no vale\n\n- ✔ Um único ponto bem posicionado cria uma aresta curta ligando os\n  dois clusters — funde-os num nível bem mais baixo.\n- ✗ A MST é sensível a arestas individuais — inserir um vértice pode\n  mudar radicalmente a topologia local da árvore, não só uma média\n  global.\n- ✔ Isso é exatamente o *chaining* citado do ESL.\n- ✗ $d_{\\mathrm{mreach}}$ reduz o problema (o core distance do ponto de\n  ruído tende a ser grande, penalizando a aresta), mas não elimina\n  encadeamento em toda circunstância — daí a necessidade adicional de\n  `min_cluster_size`/persistência no Bloco 6.\n:::\n\n::: {.fragment}\n**Voltando à pergunta:** encadeamento não é resolvido só pela\nalcançabilidade mútua — o Bloco 6 ataca o problema de frente, exigindo\nque um cluster \"sobreviva\" por um tamanho mínimo, não só por uma\ncadeia fina de pontos.\n:::\n\n:::\n\n# HDBSCAN\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n\nO nome já entrega a receita: **H**ierarchical **DBSCAN** — a ideia do\nBloco 4 (núcleo, alcançabilidade mútua, grafo por limiar) rodando por\n**toda** a hierarquia do Bloco 5 de uma vez, em vez de um único\n$\\varepsilon$. Mas o Bloco 5 deixou dois problemas em aberto: (i) um\núnico $k$ (ou $\\lambda$) fixo não serve para um dataset com clusters de\ndensidades muito diferentes entre si — um $\\lambda$ que revela um\ncluster raro e denso pode já ter apagado outro, mais espalhado; (ii)\nencadeamento pode ligar, por um fio fino de pontos, dois grupos que\n\"deveriam\" ser distintos. O HDBSCAN ataca os dois de uma vez, com uma\nideia que não está em nenhum dos livros-texto desta disciplina\n(Campello, Moulavi & Sander, 2013) — **persistência**.\n\n::: {.callout-tip}\n## Ponte conceitual\n\nPense na hierarquia inteira (a MST cortada em toda altura possível,\nnão só um $k$) como um filme: em cada quadro (cada valor de\n$d_{\\mathrm{mreach}}$ de corte), alguns clusters existem, outros não.\nUm cluster que aparece por muitos quadros seguidos, sobrevivendo como\ncomponente distinta por uma longa faixa de cortes, é mais \"real\" do que\num que aparece e desaparece rapidamente.\n:::\n\n**Vendo o filme nos 7 pontos do Bloco 5.** A figura abaixo é o mesmo\ndendrograma de ligação simples dos 7 pontos usado ali para verificar a\nconexão com a MST, agora cortado em três alturas diferentes — três\n\"quadros\" do filme:\n\n::: {#56a6002f .cell execution_count=13}\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-revealjs/cell-14-output-1.svg){fig-align='center'}\n:::\n:::\n\n\nLendo de baixo para cima: no quadro 1 (corte raso, $\\lambda$ alto),\nnenhuma fusão ainda aconteceu — 7 clusters, um por ponto. No quadro 2\n($\\lambda$ médio), os pontos de cada grupo visual já se fundiram entre\nsi (grupo A $=\\{0,1,2\\}$, grupo B $=\\{3,4,5\\}$), mas A e B ainda não se\ntocaram, e o ponto isolado $6$ segue sozinho — 3 clusters. No quadro 3\n($\\lambda$ baixo, corte fundo), A e B já se fundiram num só cluster; só\no ponto isolado resiste separado — 2 clusters. O cluster A (e o B)\nsobrevive como componente distinta do quadro 1 ao quadro 3 inteiro —\numa faixa longa —, exatamente o tipo de \"sobrevivência prolongada\" que\nos Passos 1-3 a seguir chamam de alta persistência.\n\n**Passo 1 — árvore condensada.** Construa a hierarquia completa (o\ndendrograma de ligação simples equivalente à MST, Bloco 5) e\n**condense-a**: sempre que um ramo se divide em dois, mas um dos dois\nlados tem menos que `min_cluster_size` pontos, trate esse lado como\n\"pontos que se perderam do cluster pai\" (não como um novo cluster) em\nvez de um novo ramo — só ramos com pelo menos `min_cluster_size`\npontos contam como clusters candidatos. Isso já elimina boa parte do\nencadeamento do Bloco 5: uma cadeia fina de pontos raramente atinge o\ntamanho mínimo para ser um ramo próprio.\n\n**Passo 2 — persistência por excesso de massa.** Para cada ramo\n(cluster candidato) da árvore condensada, meça por quanto tempo ele\n\"sobrevive\" como componente distinta ao longo da faixa de valores de\n$\\lambda$ (equivalentemente, de $1/d_{\\mathrm{mreach}}$) — a soma, para\ncada ponto do ramo, do intervalo de $\\lambda$ em que aquele ponto\npertenceu a esse cluster específico antes de ser absorvido por um\ncluster-pai ou virar ruído. Essa soma é a **persistência** (excesso de\nmassa) do cluster. Clusters de alta persistência sobreviveram como\nblocos coerentes por uma faixa longa de limiares — evidência de\nestrutura real, não um artefato de onde exatamente $\\lambda$ foi\ncortado.\n\n**Os Passos 1 e 2, num desenho.** A figura a seguir é **esquemática**\n(números ilustrativos, não computados de um dataset real — o\n`scikit-learn` não expõe a árvore condensada, só o resultado final;\nver nota mais abaixo) para mostrar a forma que a árvore condensada\nassume:\n\n::: {#480b2553 .cell execution_count=14}\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-revealjs/cell-15-output-1.svg){fig-align='center'}\n:::\n:::\n\n\nLendo de baixo para cima: a **raiz** (cinza) começa com todos os $20$\npontos em $\\lambda=0$ e vai afinando — cada linha fina que sai de\nlado é um ponto (ou um grupinho pequeno demais para virar ramo próprio,\nPasso 1) que \"vazou\" e virou ruído a partir daquele $\\lambda$. Em\n$\\lambda=2{,}0$ a raiz genuinamente **se divide** em dois — ambos os\nlados, $6$ e $5$ pontos, já batem `min_cluster_size`, então os dois\nviram ramos de verdade (não \"vazamento\"): o ramo A (azul) e o ramo B\n(laranja) — esse é o momento em que a raiz vira **cluster-pai** dos\ndois **ramos-filhos**. Dali em diante, A sobrevive por uma faixa de\n$\\lambda$ bem mais longa ($2{,}0$ a $5{,}0$), perdendo pontos aos poucos,\nenquanto B se esvazia quase todo de uma vez, logo em $\\lambda=2{,}3$.\n\n**A fórmula por trás da área.** Persistência de um ramo $C$, nascido em\n$\\lambda_{\\text{nasc}}(C)$: para cada ponto $p$ que já pertenceu a $C$,\nsome $\\lambda_p - \\lambda_{\\text{nasc}}(C)$, onde $\\lambda_p$ é o\n$\\lambda$ em que $p$ **deixou** $C$ especificamente (virou ruído, ou foi\npara um ramo-filho quando $C$ se dividiu) —\n\n$$\\text{persistência}(C) = \\sum_{p\\,\\in\\,C} \\bigl(\\lambda_p - \\lambda_{\\text{nasc}}(C)\\bigr).$$\n\nEssa soma é exatamente a área da barra: cada ponto contribui um\n\"retângulo\" de altura igual ao tempo (em $\\lambda$) que ficou dentro do\nramo antes de sair.\n\n**Calculando para o ramo A** (nasce em $\\lambda=2{,}0$): $2$ pontos\nvazam em $\\lambda=3{,}0$, cada um contribuindo $3{,}0-2{,}0=1{,}0$ (soma\nparcial $2\\times1{,}0=2{,}0$); mais $2$ vazam em $\\lambda=4{,}2$, cada um\ncontribuindo $2{,}2$ (soma parcial $4{,}4$); os últimos $2$ vazam em\n$\\lambda=5{,}0$ (fim do ramo), cada um contribuindo $3{,}0$ (soma parcial\n$6{,}0$): $\\text{persistência(A)}=2{,}0+4{,}4+6{,}0=12{,}4$.\n\n**Ramo B** (nasce em $\\lambda=2{,}0$, todos os $5$ pontos vazam juntos em\n$\\lambda=2{,}3$): $\\text{persistência(B)}=5\\times(2{,}3-2{,}0)=5\\times\n0{,}3=1{,}5$.\n\nQuase $10\\times$ menor — é por isso que o Passo 3 escolheria A como\ncluster final e descartaria B: a diferença de persistência não é sutil,\né a diferença entre \"sobreviveu como bloco coerente por uma faixa\nlonga\" e \"quase não sobreviveu\".\n\n**Passo 3 — extração.** Percorrendo a árvore condensada de baixo para\ncima, escolha, em cada ramificação, o cluster de maior persistência\ntotal entre \"manter o cluster-pai inteiro\" ou \"dividir nos dois\nfilhos\" — o algoritmo original (Campello, Moulavi & Sander, 2013,\ndescrito também na documentação do scikit-learn, fonte não-livro,\nsinalizada como tal) resolve essa escolha por programação dinâmica,\nmaximizando a persistência total da partição final. O resultado: uma\npartição em clusters que **não** precisa vir de um único corte\nhorizontal em $\\lambda$ — clusters diferentes podem ser extraídos de\nalturas diferentes da árvore, cada um no seu próprio \"melhor\"\n$\\lambda$.\n\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## HDBSCAN: Hierarchical DBSCAN\n\n::: {.fragment}\nO nome entrega a receita: ideia do Bloco 4 (núcleo, alcançabilidade\nmútua, grafo por limiar) rodando por **toda** a hierarquia do Bloco 5,\nnão um só $\\varepsilon$. Mas o Bloco 5 deixou dois problemas em aberto:\n:::\n\n::: {.fragment}\n**(i)** Um $\\lambda$ fixo não serve para clusters de densidades muito\ndiferentes entre si.\n:::\n\n::: {.fragment}\n**(ii)** Encadeamento pode ligar, por um fio fino, dois grupos que\n\"deveriam\" ser distintos.\n:::\n\n::: {.fragment}\nHDBSCAN (Campello, Moulavi & Sander, 2013) ataca os dois com uma ideia\nnova: **persistência**.\n:::\n\n## Pense num Filme\n\n::: {.fragment}\nHierarquia completa = um filme: em cada quadro ($\\lambda$ de corte),\nalguns clusters existem, outros não.\n:::\n\n::: {.fragment}\nUm cluster que sobrevive por muitos quadros seguidos é mais \"real\" do\nque um que aparece e desaparece rápido.\n:::\n\n## O Filme, Visualmente\n\n::: {.fig-resize style=\"width: 50%; margin: 0 auto;\"}\n\n::: {#b82d7d85 .cell execution_count=15}\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-revealjs/cell-16-output-1.svg){fig-align='center'}\n:::\n:::\n\n\n:::\n\n::: {.fragment}\nDo quadro 1 ao 3, o cluster A ($\\{0,1,2\\}$) e o B ($\\{3,4,5\\}$)\nsobrevivem inteiros por uma faixa longa — cada divisão nova cria um\n**ramo** (o quadro seguinte da árvore); onde dois ramos se fundem, o\nnó resultante é o **cluster-pai** dos dois.\n:::\n\n## Vocabulário da Árvore\n\n::: {.fragment}\n**Ramo** (ou nó): um cluster candidato em algum nível da hierarquia —\num pedaço do dendrograma que ainda não se dividiu. Quando um ramo se\ndivide em dois, ele vira o **cluster-pai** dos dois **ramos-filhos**.\n:::\n\n::: {.fragment}\n$\\lambda$ aqui é a mesma ideia do Bloco 3 (nível de corte), agora sobre\na árvore de $d_{\\mathrm{mreach}}$ em vez da densidade $p(\\mathbf{x})$\ndireto: $\\lambda = 1/d_{\\mathrm{mreach}}$, então $\\lambda$ **alto** =\ncorte raso, ainda separado; $\\lambda$ **baixo** = corte fundo, já\nfundido.\n:::\n\n:::\n\n::: {.fig-resize style=\"width: 35%; margin: 0 auto;\"}\n```{.tikz}\n\\definecolor{boxfill}{RGB}{224,242,241}\n\\definecolor{boxborder}{RGB}{17,122,101}\n\\definecolor{midfill}{RGB}{219,234,254}\n\\definecolor{midborder}{RGB}{0,133,202}\n\\definecolor{resfill}{RGB}{255,232,214}\n\\definecolor{resborder}{RGB}{255,94,0}\n\n\\begin{tikzpicture}[\n  pipeA/.style={rectangle, rounded corners, fill=boxfill, draw=boxborder, line width=1.2pt, text=black, minimum width=3.6cm, minimum height=1.1cm, align=center, font=\\small},\n  pipeB/.style={rectangle, rounded corners, fill=midfill, draw=midborder, line width=1.2pt, text=black, minimum width=3.6cm, minimum height=1.1cm, align=center, font=\\small},\n  pipeC/.style={rectangle, rounded corners, fill=resfill, draw=resborder, line width=1.2pt, text=black, minimum width=3.6cm, minimum height=1.1cm, align=center, font=\\small},\n  arr/.style={draw=black!60, thick, ->}\n]\n\n\\node[pipeA]  (A) at (0,3)   {MST\\\\(Bloco 5)};\n\\node[pipeA]  (B) at (0,1.5) {Hierarquia completa\\\\(dendrograma de $d_{\\mathrm{mreach}}$)};\n\\node[pipeB] (C) at (0,0)   {Árvore condensada\\\\(funde ramos $<$ min\\_cluster\\_size)};\n\\node[pipeC] (D) at (0,-1.5) {Extrai clusters de\\\\maior persistência};\n\n\\draw[arr] (A) -- (B);\n\\draw[arr] (B) -- (C);\n\\draw[arr] (C) -- (D);\n\n\\end{tikzpicture}\n```\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n\nO pipeline resume os três passos: da MST (já construída no Bloco 5)\npara a hierarquia completa (o dendrograma equivalente), dessa para a\nárvore condensada (Passo 1) e, por fim, a extração por persistência\n(Passos 2-3). Cada seta é um passo computável, sem nenhum $\\lambda$\nescolhido à mão — só o parâmetro de escala `min_cluster_size` (e,\ntipicamente, `min_samples`, o análogo de $K$ do *core distance*).\n\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## Os Três Passos\n\n::: {.fragment}\n**1. Árvore condensada** — percorra a hierarquia de baixo para cima; a\ncada divisão, se um dos dois ramos-filhos tem menos que\n`min_cluster_size` pontos, ele **não** vira ramo novo — os pontos dele\nsomam como \"perda\" do cluster-pai. Só sobram como ramos as divisões em\nque os dois lados são grandes o bastante.\n:::\n\n::: {.fragment}\n**2. Persistência (excesso de massa)** — para cada ramo, some, ponto a\nponto, a faixa de $\\lambda$ em que aquele ponto pertenceu a *esse* ramo\nespecífico, antes de sair dele (virar ruído ou passar a um\nramo-filho). Ramos com persistência alta sobreviveram por uma faixa\nlonga de $\\lambda$ — evidência de estrutura real, não artefato de onde\no corte caiu.\n:::\n\n## Os Passos 1 e 2, num Desenho\n\n::: {.fragment}\nEsquemático (números ilustrativos — `scikit-learn` não expõe a árvore\ncondensada, só o resultado final):\n:::\n\n::: {#570cc6ad .cell execution_count=16}\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-revealjs/cell-17-output-1.svg){fig-align='center'}\n:::\n:::\n\n\n::: {.fragment}\nRaiz (cinza) afina conforme pontos \"vazam\" (linhas finas); em\n$\\lambda=2{,}0$ ela **divide de verdade** (os dois lados batem\n`min_cluster_size`) em ramo A e ramo B — a raiz vira **cluster-pai**\ndos dois **ramos-filhos**.\n:::\n\n::: {.fragment}\nÁrea de cada ramo = persistência: A sobrevive bem mais tempo\n($2{,}0$–$5{,}0$) que B ($2{,}0$–$2{,}3$) — quase $10\\times$ mais\npersistente.\n:::\n\n## Calculando a Persistência\n\n::: {.fragment}\n$$\\text{persistência}(C) = \\sum_{p\\,\\in\\,C} \\bigl(\\lambda_p - \\lambda_{\\text{nasc}}(C)\\bigr)$$\nPara cada ponto $p$ de $C$: quanto $\\lambda$ ele durou dentro de $C$\nantes de sair (virar ruído ou ir a um ramo-filho).\n:::\n\n::: {.fragment}\n**Ramo A** (nasce em $\\lambda=2{,}0$): $2$ pontos saem em $\\lambda=3{,}0$\n($2\\times1{,}0=2{,}0$); $2$ em $\\lambda=4{,}2$ ($2\\times2{,}2=4{,}4$); os\núltimos $2$ em $\\lambda=5{,}0$ ($2\\times3{,}0=6{,}0$).\n$\\text{persistência(A)}=2{,}0+4{,}4+6{,}0=12{,}4$.\n:::\n\n::: {.fragment}\n**Ramo B** (nasce em $\\lambda=2{,}0$, todos os $5$ saem juntos em\n$\\lambda=2{,}3$): $\\text{persistência(B)}=5\\times0{,}3=1{,}5$.\n:::\n\n## 3. Extração, no Mesmo Exemplo\n\n::: {.fragment}\nEm cada divisão da árvore condensada, escolha entre \"manter o\ncluster-pai inteiro\" ou \"dividir nos dois ramos-filhos\", pela opção de\n**maior persistência total** (programação dinâmica, de baixo para cima\nna árvore).\n:::\n\n::: {.fragment}\nNa figura anterior: $\\text{persistência(A)}\\approx12{,}4 \\gg\n\\text{persistência(B)}\\approx1{,}5$ — a divisão vale a pena por causa\nde A. **A** sobrevive como cluster final; **B**, por ter durado tão\npouco, não vira cluster — seus pontos ficam como ruído.\n:::\n\n::: {.fragment}\nResultado geral: clusters extraídos de **alturas diferentes** da\nárvore — não vem de um único corte horizontal em $\\lambda$.\n:::\n\n:::\n\n## Aplicando ao Breast Cancer Wisconsin, Sem Rótulos\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n\nHora de aplicar tudo isso ao problema-fio real, ainda sem usar o\ndiagnóstico. Usando os dois atributos reais de visualização já\napresentados (`radius_worst`, padronizado, e `concave points_worst`,\npadronizado) e `min_cluster_size=15`, o HDBSCAN (via\n`sklearn.cluster.HDBSCAN`, confirmado disponível na versão 1.8.0 do\nscikit-learn instalada no kernel desta disciplina — não o pacote\n`hdbscan` externo, que não está instalado) encontra a seguinte\npartição:\n\n:::\n\n::: {#8f376b2c .cell execution_count=17}\n``` {.python .cell-code}\nhdb_bc = HDBSCAN(min_cluster_size=15).fit(X_2d)\nlabels_bc = hdb_bc.labels_\nuniq, counts = np.unique(labels_bc, return_counts=True)\nprint(\"Clusters encontrados (rótulo: nº de pacientes):\", dict(zip(uniq, counts)))\nprint(f\"Fração marcada como ruído (-1): {(labels_bc == -1).mean():.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nClusters encontrados (rótulo: nº de pacientes): {np.int64(-1): np.int64(168), np.int64(0): np.int64(54), np.int64(1): np.int64(347)}\nFração marcada como ruído (-1): 0.295\n```\n:::\n:::\n\n\n::: {.fig-resize style=\"width: 100%; margin: 0 auto;\"}\n\n::: {#f561ab9a .cell execution_count=18}\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-revealjs/cell-19-output-1.svg){fig-align='center'}\n:::\n:::\n\n\n:::\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n\n**Só agora, olhando o painel direito, o diagnóstico entra na\nconversa** — nenhum passo anterior usou a coluna `diagnosis`. A\ncorrespondência:\n\n::: {#5377c8b4 .cell execution_count=19}\n``` {.python .cell-code}\nimport pandas as pd\nprint(pd.crosstab(labels_bc, diagnosis, margins=True))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncol_0    B    M  All\nrow_0               \n-1      42  126  168\n0        0   54   54\n1      315   32  347\nAll    357  212  569\n```\n:::\n:::\n\n\nO HDBSCAN encontrou dois clusters e marcou $168$ dos $569$ pacientes\n($\\approx 29{,}5\\%$) como ruído. O **Cluster 0** ($54$ pacientes) é\n**puro**: os $54$ são malignos, zero benignos — uma \"montanha\" densa e\nhomogênea de tumores malignos, exatamente o tipo de estrutura que a\ndefinição do Bloco 3 promete encontrar sem nunca ter visto o rótulo. O\n**Cluster 1** ($347$ pacientes) é majoritariamente benigno ($315$\nbenignos, $32$ malignos — $\\approx 90{,}8\\%$ de pureza benigna), mas\ncom contaminação real. Dos $212$ pacientes malignos no total, a maioria\n($126$, $\\approx 59{,}4\\%$) cai no ruído — não em nenhum dos dois\nclusters — o que é, honestamente, o resultado esperado: tumores\nmalignos variam muito mais em apresentação do que tumores benignos (a\ndoença tem múltiplos subtipos e estágios), então só uma fração forma\numa \"montanha\" densa o bastante para sobreviver como cluster de alta\npersistência nesses dois atributos; boa parte fica dispersa no \"vale\"\nentre o núcleo maligno denso e a grande massa benigna.\n\nNenhum dos dois clusters é $100\\%$ puro nos dois sentidos ao mesmo\ntempo, e boa parte dos malignos cai em ruído: o HDBSCAN não é um\nclassificador, e não teve acesso ao rótulo. O fato de encontrar\n*qualquer* estrutura — um cluster inteiramente maligno, outro\nmajoritariamente benigno — que se alinha tão bem ao diagnóstico real,\ncomeçando de dois atributos e nenhuma supervisão, é o resultado central\ndeste bloco.\n\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n::: {.fragment}\n$569$ pacientes, `radius_worst` + `concave points_worst`,\n`min_cluster_size=15`: **2 clusters** + $168$ pacientes como ruído\n($\\approx 29{,}5\\%$).\n:::\n\n::: {.fragment}\n**Cluster 0** ($54$ pacientes): **100% malignos** — uma montanha densa\ne pura, encontrada sem nunca ver o rótulo.\n:::\n\n::: {.fragment}\n**Cluster 1** ($347$ pacientes): $315$ benignos + $32$ malignos\n($\\approx 90{,}8\\%$ de pureza benigna).\n:::\n\n## Só Agora o Rótulo Entra na Conversa\n\n::: {.fragment}\nDos $212$ pacientes malignos: $54$ no cluster puro, $32$ no cluster\nmisto, $126$ ($\\approx 59{,}4\\%$) em ruído.\n:::\n\n::: {.fragment}\nMaligno varia mais em apresentação (múltiplos subtipos/estágios) — só\numa fração forma montanha densa o bastante para sobreviver como\ncluster de alta persistência nesses 2 atributos.\n:::\n\n::: {.fragment}\nHDBSCAN não é classificador, não viu o rótulo. Encontrar um cluster\ninteiramente maligno e outro majoritariamente benigno, sem supervisão,\né o resultado.\n:::\n\n:::\n\n## Pergunta\n\n::: {.callout-tip}\n## Se `min_cluster_size` fosse reduzido de 15 para 2 no exemplo do Breast Cancer Wisconsin, o que aconteceria com a fração de pacientes marcados como ruído, e por quê?\n\nDica: pense no que `min_cluster_size` está, na prática, impedindo de\nvirar cluster.\n\n- □ Reduzir `min_cluster_size` para 2 tende a diminuir a fração de\n  ruído, porque ramos muito pequenos da árvore condensada (antes\n  descartados como \"perda\" do cluster-pai) passam a contar como\n  clusters válidos por si mesmos.\n- □ `min_cluster_size=2` reintroduz, na prática, uma versão do\n  problema de encadeamento (*chaining*) da ligação simples pura — uma\n  cadeia fina de 2-3 pontos já basta para ser aceita como cluster\n  próprio.\n- □ O valor de `min_cluster_size` não afeta a fração de ruído — ele só\n  afeta quantos clusters distintos são extraídos, mantendo o total de\n  pontos \"ruidosos\" constante.\n- □ Escolher `min_cluster_size` continua sendo, mesmo no HDBSCAN, uma\n  decisão de escala imposta pelo usuário — a persistência decide\n  *quais* ramos sobrevivem, mas não decide, por si só, o tamanho mínimo\n  que conta como ramo.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## Resposta\n\n::: {.callout-tip}\n## Resposta — reduzindo `min_cluster_size` para 2\n\n- ✔ Ramos pequenos, antes descartados, passam a valer como clusters —\n  ruído tende a cair.\n- ✔ Reintroduz uma versão do encadeamento — cadeias finas voltam a\n  contar como cluster.\n- ✗ Afeta, sim, a fração de ruído — não só a contagem de clusters.\n- ✔ `min_cluster_size` continua sendo escolha de escala do usuário —\n  persistência decide quais ramos sobrevivem, não o tamanho mínimo de\n  ramo.\n:::\n\n::: {.fragment}\n**Voltando à pergunta:** o HDBSCAN troca \"escolher $\\lambda$\" por\n\"escolher `min_cluster_size`\" — não elimina a decisão de escala, só a\nmove para um parâmetro mais estável e mais fácil de interpretar (Bloco\n7).\n:::\n\n:::\n\n# Síntese: Vantagens e Limitações do HDBSCAN\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n\nRecapitulando de ponta a ponta: (1) $\\mathrm{core}_K(\\mathbf{x})$, o\nmesmo $d_K(\\mathbf{x})$ da Aula 2, mede densidade local sem forma\nparamétrica; (2) $d_{\\mathrm{mreach}}$ transforma isso numa distância\nde grafo que \"acalma\" pontos isolados; (3) a MST desse grafo comprime\ntoda a hierarquia de clustering por ligação simples numa única árvore;\n(4) condensar essa árvore e medir persistência por excesso de massa\nextrai os clusters mais estáveis, em alturas possivelmente diferentes,\nsem exigir um único corte global.\n\n**As vantagens**, em relação a uma partição por protótipos fixos\n(Bloco 2): nenhuma suposição de convexidade (as duas luas, os dois\nanéis, resolvidos de ponta a ponta); nenhuma escolha obrigatória do\n**número de clusters** (não confundir com o $K$ do *core distance*,\n`min_samples` — esse continua sendo escolhido, controla escala de\ndensidade, não quantidade de clusters); pontos genuinamente atípicos\npodem ser marcados como ruído em vez de forçados a pertencer a algum\ncluster.\n\n**As limitações.** Duas, nenhuma anunciada como\n\"gratuita\" antes: primeiro, `min_cluster_size` (e, em geral,\n`min_samples`, que desempenha o papel de $K$ no *core distance*) ainda\né uma escolha de escala — o Bloco 6 mostrou, na Pergunta, que reduzir\nesse parâmetro reintroduz uma versão do encadeamento. Segundo — e este\né o fio que conecta diretamente de volta à Aula 2 — o HDBSCAN herda a\nmesma maldição da dimensionalidade que $d_K(\\mathbf{x})$ já sofria\ncomo estimador de densidade, porque $\\mathrm{core}_K$ é literalmente o\nmesmo número. Um teste direto, nos $30$ atributos originais (todos\npadronizados) do Breast Cancer Wisconsin, torna isso concreto:\n\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## Recapitulando de Ponta a Ponta\n\n::: {.fragment}\n**(1)** $\\mathrm{core}_K(\\mathbf{x})=d_K(\\mathbf{x})$ (Aula 2): mede\ndensidade local, sem forma paramétrica.\n:::\n\n::: {.fragment}\n**(2)** $d_{\\mathrm{mreach}}$: transforma em distância de grafo que\nacalma pontos isolados.\n:::\n\n::: {.fragment}\n**(3)** MST: comprime toda a hierarquia de ligação simples numa única\nárvore.\n:::\n\n::: {.fragment}\n**(4)** Árvore condensada + persistência: extrai os clusters mais\nestáveis, sem corte global único.\n:::\n\n## As Vantagens\n\n::: {.fragment}\nNenhuma suposição de convexidade — luas e anéis resolvidos de ponta a\nponta.\n:::\n\n::: {.fragment}\nNenhuma escolha obrigatória do **número de clusters** (diferente do\n$K$ do *core distance*, `min_samples` — esse continua sendo escolhido).\n:::\n\n::: {.fragment}\nPontos atípicos podem ser ruído — não forçados a um cluster.\n:::\n\n## As Limitações\n\n::: {.fragment}\n**1.** `min_cluster_size`/`min_samples` ainda é escolha de escala —\nreduzir demais reintroduz encadeamento (Bloco 6).\n:::\n\n::: {.fragment}\n**2.** Herda a maldição da dimensionalidade de $d_K(\\mathbf{x})$ — é\nliteralmente o mesmo número.\n:::\n\n:::\n\n::: {#09f4aa26 .cell execution_count=20}\n``` {.python .cell-code}\nfor mcs in [5, 10, 15, 20, 30]:\n    hdb_full = HDBSCAN(min_cluster_size=mcs).fit(X_std)\n    frac_ruido = (hdb_full.labels_ == -1).mean()\n    n_clusters = len(set(hdb_full.labels_) - {-1})\n    print(f\"min_cluster_size={mcs:3d}  →  {n_clusters} cluster(s), \"\n          f\"{frac_ruido:.1%} dos pacientes como ruído\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmin_cluster_size=  5  →  2 cluster(s), 59.2% dos pacientes como ruído\nmin_cluster_size= 10  →  0 cluster(s), 100.0% dos pacientes como ruído\nmin_cluster_size= 15  →  0 cluster(s), 100.0% dos pacientes como ruído\nmin_cluster_size= 20  →  0 cluster(s), 100.0% dos pacientes como ruído\nmin_cluster_size= 30  →  0 cluster(s), 100.0% dos pacientes como ruído\n```\n:::\n:::\n\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n\nNos $30$ atributos originais, padronizados, sem nenhuma redução de\ndimensionalidade: com `min_cluster_size=5` (já um valor agressivo,\npequeno), $\\approx 59{,}2\\%$ dos pacientes já viram ruído; a partir de\n`min_cluster_size=10`, **$100\\%$** dos $569$ pacientes são marcados\ncomo ruído — nenhum cluster sobrevive. Comparado aos dois atributos do\nBloco 6, onde $70{,}5\\%$ dos pacientes ficaram em algum cluster, essa é\numa queda drástica de estrutura encontrada, só por aumentar de $2$ para\n$30$ dimensões (mesmos pacientes, mesmos dados). O mecanismo é\nexatamente o da Aula 2: em alta dimensão, distâncias perdem poder de\ndiscriminação, $d_K(\\mathbf{x})$ deixa de refletir bem \"densidade\nlocal\" no sentido intuitivo, $d_{\\mathrm{mreach}}$ (que depende de\n$d_K$ e de $d$ bruta) herda o problema, e a árvore condensada não\nencontra ramo nenhum estável o bastante para sobreviver como cluster —\ntudo vira \"ruído\" porque, em alta dimensão, quase tudo parece\nigualmente distante de quase tudo.\n\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## Maldição da Dimensionalidade, Concretamente\n\n::: {.fragment}\n$2$ atributos (Bloco 6): $70{,}5\\%$ dos pacientes em algum cluster.\n:::\n\n::: {.fragment}\n$30$ atributos, `min_cluster_size=5`: $\\approx 59{,}2\\%$ já é ruído.\n:::\n\n::: {.fragment}\n$30$ atributos, `min_cluster_size\\ge 10`: **$100\\%$** ruído — nenhum\ncluster sobrevive.\n:::\n\n::: {.fragment}\nMesmo mecanismo da Aula 2: distâncias perdem poder discriminativo,\n$d_K$ some, $d_{\\mathrm{mreach}}$ herda, árvore condensada não encontra\nramo estável.\n:::\n\n:::\n\n## Pergunta\n\n::: {.callout-tip}\n## Um colega sugere \"resolver\" a queda de estrutura em 30 dimensões aumentando `min_cluster_size` até encontrar pelo menos um cluster de novo. Isso resolveria o problema de fundo?\n\nDica: pense se `min_cluster_size` grande está atacando a causa\n(distâncias perdendo poder discriminativo) ou só mudando o limiar de\nquantos pontos \"contam\".\n\n- □ Aumentar `min_cluster_size` pode, sim, eventualmente produzir\n  algum cluster de novo — mas isso resolve o sintoma (nenhum cluster\n  aparecia) sem resolver a causa (as distâncias em 30D perderam poder\n  discriminativo).\n- □ Se um cluster aparecer com `min_cluster_size` bem alto em 30D, ele\n  é necessariamente tão confiável estatisticamente quanto o cluster\n  puro de $54$ pacientes encontrado com $2$ atributos no Bloco 6.\n- □ A solução mais direta para a maldição, sugerida já na Aula 2 e\n  reaproveitável aqui, é reduzir a dimensionalidade (ex.: escolher um\n  subconjunto de atributos informativos, ou usar componentes\n  principais) antes de rodar HDBSCAN, não só ajustar\n  `min_cluster_size`.\n- □ Esse problema é exclusivo de métodos baseados em densidade como o\n  HDBSCAN — qualquer método de clustering baseado em distância entre\n  pontos escaparia dessa maldição.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## Resposta\n\n::: {.callout-tip}\n## Resposta — \"resolver\" aumentando `min_cluster_size`\n\n- ✔ Ataca o sintoma, não a causa — distâncias continuam sem poder\n  discriminativo.\n- ✗ Um cluster que só aparece forçando `min_cluster_size` alto não é\n  automaticamente tão confiável quanto o cluster puro do Bloco 6 —\n  pode ser um artefato do limiar, não estrutura real.\n- ✔ Reduzir dimensionalidade primeiro é a rota mais direta — a mesma\n  lição da Aula 2.\n- ✗ Nenhum método baseado em distância escapa por completo — distâncias\n  em geral perdem significado geométrico em alta dimensão, não só as\n  baseadas em densidade.\n:::\n\n::: {.fragment}\n**Voltando à pergunta:** a maldição não tem solução mágica dentro do\npróprio algoritmo — reduzir dimensionalidade, ou usar conhecimento de\ndomínio para escolher poucos atributos relevantes (como o Bloco 6 fez\n\"na mão\"), é o caminho, não um parâmetro a mais.\n:::\n\n:::\n\n# Fechamento e Ponte para a Aula 4\n\n::: {.content-visible when-format=\"html\" unless-format=\"revealjs\"}\n\nRetomando as quatro perguntas da Abertura, uma frase cada:\n\n1. **O que deveria significar \"cluster\"?** Uma componente conexa de uma\n   região de alta densidade — não uma bola em torno de um centróide.\n2. **Como construir isso sem escolher o número de clusters a priori?**\n   Via $d_{\\mathrm{mreach}}$ e a MST, sem nenhum parâmetro de forma —\n   só uma escala local de densidade, o $K$ do *core distance*\n   (`min_samples`), que é uma coisa diferente de \"número de clusters\":\n   controla o quão local é a estimativa de densidade, não quantos\n   clusters existem.\n3. **Que estrutura de grafo captura toda a hierarquia de uma vez?** A\n   MST — cortar suas $k-1$ arestas mais pesadas reproduz ligação\n   simples para qualquer $k$, verificado no exemplo do Bloco 5.\n4. **Como decidir quais clusters são reais?** Persistência por excesso\n   de massa na árvore condensada, não um único $\\lambda$ escolhido à\n   mão.\n\n**O que fica em aberto.** O HDBSCAN entrega uma partição **rígida**:\ncada paciente pertence a exatamente um cluster, ou é ruído — uma\ndecisão binária, sem meio-termo. Isso é honesto quando os clusters são\ngenuinamente bem separados (como as duas luas), mas força uma escolha\nartificial quando dois clusters genuinamente se sobrepõem — um paciente\nna fronteira entre o núcleo maligno denso e a massa benigna do Bloco 6\nnão é \"um pouco maligno, um pouco benigno\": ele é forçado a ruído ou a\num dos dois lados.\n\n::: {.callout-tip}\n## Ponte para a Aula 4\n\nA Aula 4 introduz **Modelos de Mistura Gaussiana** (*Gaussian Mixture\nModels*) e o algoritmo **EM** (*Expectation-Maximization*) — a mesma\npergunta de agrupar pontos, mas relaxando a atribuição rígida para uma\natribuição **probabilística**: cada paciente recebe uma probabilidade\nde pertencer a cada cluster, não um rótulo único. Útil exatamente onde\no HDBSCAN força uma escolha: fronteiras genuinamente ambíguas entre\npopulações que se sobrepõem.\n:::\n\nO ESL (p. 507) já havia citado essa rota como um dos três paradigmas —\n\"modelagem por mistura\" — ao lado do combinatório (protótipos fixos,\nBloco 2) e do \"mode seeking\" (esta aula inteira). A Aula 4 fecha o\ntrio.\n\n[Exercícios](exercicios.qmd){.see-all .exercicios-link aria-label=\"Ver exercícios\" title=\"Ver exercícios\"}\n[Soluções](soluções.qmd){.see-all .solucoes-link aria-label=\"Ver soluções\" title=\"Ver soluções\"}\n\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## Retomando as Quatro Perguntas\n\n::: {.fragment}\n**1.** O que é \"cluster\"? Componente conexa de região de alta\ndensidade — não bola em torno de centróide.\n:::\n\n::: {.fragment}\n**2.** Como construir sem escolher o **número de clusters**?\n$d_{\\mathrm{mreach}}$ + MST, sem parâmetro de forma — só uma escala\nlocal de densidade, o $K$ do núcleo (`min_samples`; não é \"número de\nclusters\", é \"o quão local\").\n:::\n\n::: {.fragment}\n**3.** Que grafo captura toda a hierarquia? A MST — cortar as $k-1$\narestas mais pesadas reproduz ligação simples para qualquer $k$.\n:::\n\n::: {.fragment}\n**4.** Como decidir quais clusters são reais? Persistência por excesso\nde massa na árvore condensada.\n:::\n\n## O Que Fica em Aberto\n\n::: {.fragment}\nHDBSCAN entrega partição **rígida**: cada ponto é de um cluster, ou é\nruído — decisão binária.\n:::\n\n::: {.fragment}\nHonesto quando clusters são bem separados; força escolha artificial\nquando dois clusters genuinamente se sobrepõem.\n:::\n\n::: {.callout-tip}\n## Ponte para a Aula 4\n\nModelos de Mistura Gaussiana + EM: mesma pergunta de agrupar, mas\natribuição **probabilística** — cada ponto com uma probabilidade por\ncluster, não um rótulo único. Útil onde o HDBSCAN força escolha.\n:::\n\n::: {.fragment}\nESL (p. 507): \"modelagem por mistura\" era o terceiro paradigma citado\ndesde a Abertura — a Aula 4 fecha o trio (combinatório, mistura, modo).\n:::\n\n[Exercícios](exercicios.qmd){.see-all .exercicios-link aria-label=\"Ver exercícios\" title=\"Ver exercícios\"}\n[Soluções](soluções.qmd){.see-all .solucoes-link aria-label=\"Ver soluções\" title=\"Ver soluções\"}\n\n:::\n\n## Pergunta\n\n::: {.callout-tip}\n## Um hospital precisa decidir se atribuição rígida (HDBSCAN) ou probabilística (GMM/EM, Aula 4) se ajusta melhor a uma triagem entre dois subtipos de tumor cujos biomarcadores parecem se sobrepor. O que deveria pesar mais nessa escolha?\n\nDica: pense se a \"ambiguidade\" observada nos dados é evidência de um\nvale de densidade genuíno entre os subtipos, ou de uma sobreposição\nreal e contínua entre eles.\n\n- □ Se os dois subtipos realmente se sobrepõem numa faixa contínua de\n  biomarcadores, sem um vale de densidade genuíno entre eles, uma\n  atribuição probabilística tende a refletir melhor essa ambiguidade do\n  que forçar cada paciente a um rótulo único.\n- □ Como o HDBSCAN já produz uma força de pertencimento por ponto\n  dentro do cluster ao qual foi atribuído, ele já é, na prática,\n  equivalente a uma atribuição probabilística completa como a do\n  GMM/EM, que distribui probabilidade entre *todos* os clusters.\n- □ No limite em que os dois subtipos verdadeiros são separados por um\n  vale de densidade exatamente zero, a atribuição probabilística do\n  GMM/EM converge para probabilidades próximas de $0$ ou $1$ —\n  coincidindo, na prática, com a atribuição rígida do HDBSCAN.\n- □ Se a escolha entre partição rígida e probabilística fosse só uma\n  questão de conveniência computacional, sem nenhuma relação com a\n  estrutura real dos dados, então HDBSCAN e GMM deveriam sempre\n  produzir partições idênticas quando aplicados ao mesmo dataset.\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n\n## Resposta\n\n::: {.callout-tip}\n## Resposta — partição rígida ou probabilística?\n\n- ✔ Sobreposição contínua e genuína → probabilística reflete melhor a\n  ambiguidade real.\n- ✗ A força de pertencimento do HDBSCAN é interna ao cluster atribuído\n  — não é o mesmo que distribuir probabilidade entre todos os\n  clusters, como o GMM/EM faz.\n- ✔ Vale de densidade zero → GMM/EM converge para probabilidades\n  extremas, coincidindo com HDBSCAN nesse limite.\n- ✗ Não é só conveniência — reflete uma hipótese diferente sobre a\n  estrutura dos dados; os métodos coincidem só no caso limite acima.\n:::\n\n::: {.fragment}\n**Voltando à pergunta:** a escolha depende de crer (ou não) que existe\num vale de densidade genuíno separando os subtipos — exatamente a\npergunta que a Aula 4 equipa o aluno para responder com uma ferramenta\nnova.\n:::\n\n:::\n\n",
    "supporting": [
      "index_files/figure-revealjs"
    ],
    "filters": [],
    "includes": {}
  }
}